import { BlogGLP1BreastfeedingSafety } from "../../../components/blog-glp1-breastfeeding-safety-2026.jsx";
export const metadata = {
  alternates: { canonical: 'https://telehealthfx.com/blog/glp1-breastfeeding-safety-2026/' },
  title: "GLP-1 and Breastfeeding: Can You Take Semaglutide While Nursing? Complete Safety Analysis",
  description: "GLP-1 medications are not recommended during breastfeeding due to insufficient safety data. Safe alternatives and when to start after weaning.",
  openGraph: { title: "GLP-1 and Breastfeeding: Can You Take Semaglutide While Nursing? Complete Safety Analysis", description: "GLP-1 medications are not recommended during breastfeeding due to insufficient safety data. Safe alternatives and when to start after weaning.", images: [{ url: "https://telehealthfx.com/assets/glp1-breastfeeding-safety-featured.png", width: 1200, height: 630, alt: "GLP-1 Breastfeeding Safety" }] },
};
export default function Page() {
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "MedicalWebPage", "@id": "https://telehealthfx.com/blog/glp1-breastfeeding-safety-2026/#article", "headline": "GLP-1 and Breastfeeding: Can You Take Semaglutide While Nursing? Complete Safety Analysis", "description": "GLP-1 medications are not recommended during breastfeeding due to insufficient safety data. Safe alternatives and when to start after weaning.", "image": "https://telehealthfx.com/assets/glp1-breastfeeding-safety-featured.png", "datePublished": "2026-05-12", "dateModified": "2026-05-12", "wordCount": 3200, "author": { "@type": "Person", "name": "Julian Mercer, M.S.", "url": "https://telehealthfx.com/about", "jobTitle": "Lead Bio-Systems Analyst" }, "publisher": { "@id": "https://telehealthfx.com/#organization" }, "mainEntityOfPage": { "@type": "WebPage", "@id": "https://telehealthfx.com/blog/glp1-breastfeeding-safety-2026/" } },
    { "@type": "Article", "@id": "https://telehealthfx.com/blog/glp1-breastfeeding-safety-2026/#newsarticle", "headline": "GLP-1 and Breastfeeding: Can You Take Semaglutide While Nursing? Complete Safety Analysis", "image": "https://telehealthfx.com/assets/glp1-breastfeeding-safety-featured.png", "datePublished": "2026-05-12", "dateModified": "2026-05-12", "author": { "@type": "Person", "name": "Julian Mercer, M.S." }, "publisher": { "@id": "https://telehealthfx.com/#organization" } },
    { "@type": "FAQPage", "@id": "https://telehealthfx.com/blog/glp1-breastfeeding-safety-2026/#faq", "mainEntity": [
      { "@type": "Question", "name": "Can I pump and dump while on GLP-1?", "acceptedAnswer": { "@type": "Answer", "text": "Unlike alcohol semaglutide has a 7-day half-life. It would take 5+ weeks to fully clear making pump-and-dump impractical." } },
      { "@type": "Question", "name": "What if I accidentally took GLP-1 while breastfeeding?", "acceptedAnswer": { "@type": "Answer", "text": "A single dose exposure is unlikely to cause harm. Peptides are generally poorly absorbed through infant GI tract. Contact your clinician and pediatrician." } },
      { "@type": "Question", "name": "Is any weight loss medication safe while breastfeeding?", "acceptedAnswer": { "@type": "Answer", "text": "No weight loss medication is officially approved during breastfeeding. The safest approach is dietary optimization and exercise." } }
    ]},
    { "@type": "Product", "name": "TelehealthFX GLP-1 Weight Loss Program", "description": "Clinician-guided GLP-1 weight loss protocol including compounded semaglutide.", "brand": { "@type": "Brand", "name": "TelehealthFX" }, "url": "https://go.telehealthfx.com/start", "image": "https://telehealthfx.com/assets/Site%20Icon-modified.png", "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.9", "reviewCount": "2847", "bestRating": "5", "worstRating": "1" }, "review": [{ "@type": "Review", "reviewRating": { "@type": "Rating", "ratingValue": "5", "bestRating": "5" }, "author": { "@type": "Person", "name": "Stephanie R." }, "reviewBody": "They helped me plan my timeline perfectly. Started GLP-1 two weeks after weaning and already down 25 lbs." }], "offers": { "@type": "Offer", "price": "199", "priceCurrency": "USD", "priceValidUntil": "2026-12-31", "availability": "https://schema.org/InStock", "url": "https://go.telehealthfx.com/start" } },
    { "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://telehealthfx.com/" }, { "@type": "ListItem", "position": 2, "name": "Blog", "item": "https://telehealthfx.com/blog/" }, { "@type": "ListItem", "position": 3, "name": "GLP-1 Breastfeeding Safety", "item": "https://telehealthfx.com/blog/glp1-breastfeeding-safety-2026/" }] },
    { "@type": "MedicalOrganization", "@id": "https://telehealthfx.com/#organization", "name": "Telehealth FX", "url": "https://telehealthfx.com", "logo": { "@type": "ImageObject", "url": "https://telehealthfx.com/assets/Site%20Icon-modified.png" }, "sameAs": ["https://www.youtube.com/@TelehealthFX"], "contactPoint": { "@type": "ContactPoint", "contactType": "customer service", "url": "https://go.telehealthfx.com/start" }, "medicalSpecialty": "Endocrine" }
  ]};
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><BlogGLP1BreastfeedingSafety /></>);
}
