import { BlogGLP1BingeEatingDisorder } from "../../../components/blog-glp1-binge-eating-disorder-2026.jsx";
export const metadata = {
  alternates: { canonical: 'https://telehealthfx.com/blog/glp1-binge-eating-disorder-2026/' },
  title: "GLP-1 for Binge Eating Disorder: How Semaglutide Quiets the Compulsion to Eat",
  description: "Semaglutide reduced binge episodes by 74%. The complete neuroscience of GLP-1 for binge eating disorder.",
  openGraph: { title: "GLP-1 for Binge Eating Disorder: How Semaglutide Quiets the Compulsion to Eat", description: "Semaglutide reduced binge episodes by 74%. The complete neuroscience of GLP-1 for binge eating disorder.", images: [{ url: "https://telehealthfx.com/assets/glp1-binge-eating-disorder-featured.png", width: 1200, height: 630, alt: "GLP-1 Binge Eating Disorder" }] },
};
export default function Page() {
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "MedicalWebPage", "@id": "https://telehealthfx.com/blog/glp1-binge-eating-disorder-2026/#article", "headline": "GLP-1 for Binge Eating Disorder: How Semaglutide Quiets the Compulsion to Eat", "description": "Semaglutide reduced binge episodes by 74%. The complete neuroscience of GLP-1 for binge eating disorder.", "image": "https://telehealthfx.com/assets/glp1-binge-eating-disorder-featured.png", "datePublished": "2026-05-12", "dateModified": "2026-05-12", "wordCount": 3200, "author": { "@type": "Person", "name": "Julian Mercer, M.S.", "url": "https://telehealthfx.com/about", "jobTitle": "Lead Bio-Systems Analyst" }, "publisher": { "@id": "https://telehealthfx.com/#organization" }, "mainEntityOfPage": { "@type": "WebPage", "@id": "https://telehealthfx.com/blog/glp1-binge-eating-disorder-2026/" } },
    { "@type": "Article", "@id": "https://telehealthfx.com/blog/glp1-binge-eating-disorder-2026/#newsarticle", "headline": "GLP-1 for Binge Eating Disorder: How Semaglutide Quiets the Compulsion to Eat", "image": "https://telehealthfx.com/assets/glp1-binge-eating-disorder-featured.png", "datePublished": "2026-05-12", "dateModified": "2026-05-12", "author": { "@type": "Person", "name": "Julian Mercer, M.S." }, "publisher": { "@id": "https://telehealthfx.com/#organization" } },
    { "@type": "FAQPage", "@id": "https://telehealthfx.com/blog/glp1-binge-eating-disorder-2026/#faq", "mainEntity": [
      { "@type": "Question", "name": "Can I take GLP-1 and Vyvanse together for BED?", "acceptedAnswer": { "@type": "Answer", "text": "There is no pharmacological interaction. Some psychiatrists prescribe both for severe BED. Close monitoring of nutritional intake is essential." } },
      { "@type": "Question", "name": "Will binge eating return if I stop GLP-1?", "acceptedAnswer": { "@type": "Answer", "text": "Binge frequency increases after discontinuation in most patients. Patients who completed CBT during therapy are better equipped to maintain changes." } },
      { "@type": "Question", "name": "Is GLP-1 appropriate for all eating disorders?", "acceptedAnswer": { "@type": "Answer", "text": "No. GLP-1 is contraindicated in anorexia nervosa and should be used cautiously in bulimia. It is appropriate for BED and emotional overeating in patients with obesity." } }
    ]},
    { "@type": "Product", "name": "TelehealthFX GLP-1 Weight Loss Program", "description": "Clinician-guided GLP-1 weight loss protocol including compounded semaglutide.", "brand": { "@type": "Brand", "name": "TelehealthFX" }, "url": "https://go.telehealthfx.com/start", "image": "https://telehealthfx.com/assets/Site%20Icon-modified.png", "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.9", "reviewCount": "2847", "bestRating": "5", "worstRating": "1" }, "review": [{ "@type": "Review", "reviewRating": { "@type": "Rating", "ratingValue": "5", "bestRating": "5" }, "author": { "@type": "Person", "name": "Jessica L." }, "reviewBody": "The food noise is completely gone. I havent had a binge episode in 3 months." }], "offers": { "@type": "Offer", "price": "199", "priceCurrency": "USD", "priceValidUntil": "2026-12-31", "availability": "https://schema.org/InStock", "url": "https://go.telehealthfx.com/start" } },
    { "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://telehealthfx.com/" }, { "@type": "ListItem", "position": 2, "name": "Blog", "item": "https://telehealthfx.com/blog/" }, { "@type": "ListItem", "position": 3, "name": "GLP-1 Binge Eating Disorder", "item": "https://telehealthfx.com/blog/glp1-binge-eating-disorder-2026/" }] },
    { "@type": "MedicalOrganization", "@id": "https://telehealthfx.com/#organization", "name": "Telehealth FX", "url": "https://telehealthfx.com", "logo": { "@type": "ImageObject", "url": "https://telehealthfx.com/assets/Site%20Icon-modified.png" }, "sameAs": ["https://www.youtube.com/@TelehealthFX"], "contactPoint": { "@type": "ContactPoint", "contactType": "customer service", "url": "https://go.telehealthfx.com/start" }, "medicalSpecialty": "Endocrine" }
  ]};
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><BlogGLP1BingeEatingDisorder /></>);
}
