"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationDurham() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="North Carolina" cityName="Durham" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Durham</span>" subheadline="Durham is home to Duke University Medical Center—one of the top 10 hospitals in America—and Research Triangle Park, the largest research park in the country. The irony: the city with arguably the best healthcare institution in the Southeast still has specialist waits that exceed 12 weeks for its own residents." dataPoint1="Durham County's adult obesity rate exceeds 29%. The Research Triangle's tech and pharma workforce is overwhelmingly sedentary. Duke's national reputation draws patients from across the Southeast, crowding out local access." dataPoint2="Telehealth FX serves the RTP workforce without competing for Duke's specialist appointments." />
      <PatientArchetype archetype="The GSK Research Triangle Park Pharmacologist" quote="I develop drug formulations at the GSK campus in RTP. I understand GLP-1 receptor agonism at the molecular level—I've read every Phase III trial. My Blue Cross NC plan requires 6 months of behavioral modification before GLP-1 authorization. I literally develop medications for a living and I can't access them through my own insurance." details="<strong>Patient Profile:</strong> Dr. Patel, 39, Senior Pharmacologist at GlaxoSmithKline, RTP.<br/><br/><strong>The Challenge:</strong> Develops drug formulations professionally. Understands GLP-1 pharmacology at the molecular level. His own BCBS NC plan requires 6 months behavioral therapy before authorization.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Chapel Hill. NC-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Top-10 Hospital, 12-Week Wait" paragraphs={["Duke University Medical Center consistently ranks in the US News top 10. Durham has world-class healthcare within its borders. But Duke's national reputation means patients fly in from across the Southeast for complex care—crowding the specialist schedule for Durham residents who need routine endocrinology.","Research Triangle Park—the 7,000-acre campus between Durham, Raleigh, and Chapel Hill—houses IBM, GSK, Cisco, Fidelity, and dozens of biotech startups. The workforce is overwhelmingly sedentary: lab scientists, software engineers, and corporate analysts who sit 10+ hours per day.","The food culture reflects Durham's transformation: the old tobacco-city BBQ tradition (Picnic, The Pit) alongside the farm-to-table boom (Mateo, Mothers & Sons) and the international food scene driven by the university community. The caloric density is high across all price points.","GLP-1 medications serve RTP's pharma scientists, Duke's own staff, and the Triangle workforce—delivering metabolic care without the 12-week Duke specialist wait."]} citations={["Durham County Department of Public Health. (2025). <em>Community Health Assessment</em>.","Duke Global Health Institute. (2024). <em>Sedentary Workforce and Metabolic Health in the Research Triangle</em>."]} />
      <InsuranceBreakdown title="Duke, RTP, and the Triangle Paradox" text="Durham's economy centers on healthcare, pharma, and tech." employers={[{name:"GlaxoSmithKline / Fidelity / IBM (RTP)",detail:"Pharma and tech plans require behavioral modification before GLP-1 authorization."},{name:"Duke Health System",detail:"Duke employees face the same specialist waits they create."},{name:"BCBS NC (State Plan)",detail:"NC's dominant insurer requires standard Step Therapy."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Durham" localCompetitors={[{name:"Hope Valley / Southpoint Concierge",cost:"$700-$1,200/mo",consult:"In-Person",access:"Branded Only"},{name:"9th St MedSpas",cost:"$400-$700/mo",consult:"Monthly",access:"Variable"},{name:"Duke Endocrinology",cost:"$125 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass 147/40 & Duke Waitlists" transitText="Durham connects to Raleigh (30 min) via I-40 and RTP via 147. Rush hour on 40 and 147 is severe." hospitalText="<strong>Duke University Medical Center</strong> and <strong>Duke Regional</strong> serve Durham." />
      <InteractiveFAQ faqs={[{q:"I work in pharma. I know these drugs. Why can't I get them?",a:"Your insurance's PBM restrictions exist regardless of your expertise. Telehealth FX bypasses the formulary."},{q:"Do you deliver to Chapel Hill and Cary?",a:"Yes. All Durham, Orange, and Wake County addresses."}]} />
      <StateLegalFramework stateName="North Carolina" boardName="North Carolina Medical Board" text="Telehealth FX operates in compliance with the <strong>NC Medical Board</strong> and NCGS § 90." />
      <DeliveryGridMap cityName="Durham" mapQuery="Durham, NC" coordinates="35.9940° N, 78.8986° W" counties="Durham County, Orange County, Wake County" neighborhoods={['Hope Valley','Southpoint','Chapel Hill','Cary','RTP','Hillsborough','Morrisville']} />
      <FinalCTA stateName="North Carolina" />
    </div>
  );
}
