"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationShreveport() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Louisiana" cityName="Shreveport" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Shreveport</span>" subheadline="Shreveport anchors Northwest Louisiana—a region isolated from the state's major medical centers in New Orleans and Baton Rouge. Barksdale Air Force Base adds a military population competing for the same limited specialist pool. Louisiana has the third-highest adult obesity rate in America." ctaText="Check Louisiana Eligibility" />
      <PatientArchetype archetype="The Barksdale AFB B-52 Maintenance Crew Chief" quote="I maintain B-52 bombers—aircraft older than my parents. Twelve-hour shifts on the flight line in Louisiana heat and humidity. The DFAC food is military institutional. TRICARE specialist referral at the base clinic is 18 weeks. The nearest civilian alternative is Ochsner LSU Health, and they're booked too. Shreveport has bombers. It doesn't have enough doctors." details="<strong>Patient Profile:</strong> MSgt Jackson, 36, B-52 Crew Chief at Barksdale AFB.<br/><br/><strong>The Challenge:</strong> Flight line maintenance in extreme heat/humidity. TRICARE specialist wait 18 weeks. Civilian options equally overwhelmed. New Orleans is 5 hours away.<br/><br/><strong>The Intervention:</strong> Completed intake from Bossier City apartment. LA-licensed physician prescribed compounded Tirzepatide within 20 hours." />
      <ClinicalDeepDive title="Bombers, Casinos, and the NW Louisiana Isolation" paragraphs={["Shreveport-Bossier City sits in the corner of Louisiana closest to Texas and Arkansas—and farthest from the state's medical infrastructure. New Orleans is 5 hours southeast. Dallas (3 hours west) is actually closer for specialist care. Barksdale AFB's Global Strike Command mission adds 8,000+ airmen and families to the healthcare demand.","The casino economy (Horseshoe, Margaritaville, Sam's Town) creates a 24/7 shift workforce with the same off-hours eating patterns seen in Reno and Las Vegas. Combined with Louisiana's legendary food culture (even in the north: boudin, crawfish, gumbo, fried catfish), the caloric environment is relentless.","Ochsner LSU Health Shreveport is the academic anchor, supplemented by Willis-Knighton Health System. Together they serve all of NW Louisiana, SW Arkansas, and East Texas—a vast catchment area that stretches specialist capacity thin.","GLP-1 medications serve the Barksdale military community, casino workers, and the broader NW Louisiana population without the 5-hour drive to New Orleans."]} citations={["Caddo Parish Health Unit. (2025). <em>Community Health Assessment</em>.","LSU Health Shreveport. (2024). <em>Healthcare Access in Northwest Louisiana</em>."]} />
      <InsuranceBreakdown title="Barksdale, Casinos, and the Regional Burden" text="Shreveport's employer mix spans military, gaming, and healthcare." employers={[{name:"Barksdale AFB (TRICARE)",detail:"Military population faces 18+ week specialist waits at base clinic."},{name:"Casino Industry (Horseshoe/Margaritaville)",detail:"24/7 gaming workforce has plans with limited local networks."},{name:"Ochsner LSU Health / Willis-Knighton",detail:"Regional health systems face overwhelming demand from multi-state catchment."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Shreveport" localCompetitors={[{name:"South Highlands Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Youree Dr MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Ochsner LSU Endocrinology",cost:"$100 Copay+Rx",consult:"14-20 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-20 & the 5-Hour Drive to New Orleans" transitText="Shreveport sits on I-20, connecting to Dallas (3hr W) and Jackson MS (4hr E). New Orleans is 5 hours southeast on I-49/I-10." hospitalText="<strong>Ochsner LSU Health Shreveport</strong> and <strong>Willis-Knighton</strong> serve NW Louisiana." />
      <InteractiveFAQ faqs={[{q:"I'm at Barksdale. Will this affect my readiness?",a:"No. GLP-1 medications are not controlled substances."},{q:"Do you deliver to Bossier City and Minden?",a:"Yes. All Caddo, Bossier, and Webster Parish addresses."}]} />
      <StateLegalFramework stateName="Louisiana" boardName="Louisiana State Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>LSBME</strong> and Louisiana telehealth statutes." />
      <DeliveryGridMap cityName="Shreveport" mapQuery="Shreveport, LA" coordinates="32.5252° N, 93.7502° W" counties="Caddo Parish, Bossier Parish" neighborhoods={['South Highlands','Broadmoor','Bossier City','Haughton','Minden','Blanchard','Greenwood']} />
      <FinalCTA stateName="Louisiana" />
    </div>
  );
}
