"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationChattanooga() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Tennessee" cityName="Chattanooga" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Chattanooga</span>" subheadline="Chattanooga reinvented itself as the Gig City—the first US city with citywide 10-gigabit internet. But the city that gave America one of its most iconic foods—the MoonPie—still lives with the metabolic consequences of its industrial heritage and Southern comfort food traditions." dataPoint1="Hamilton County's adult obesity rate exceeds 32%. Chattanooga's post-industrial economy has shifted to tech, logistics (Volkswagen), and tourism (Ruby Falls, Rock City), but the food culture remains rooted in Southern tradition." dataPoint2="Telehealth FX delivers 21st-century metabolic care over the Gig City's gigabit internet—without the Erlanger waitlist." />
      <PatientArchetype archetype="The Volkswagen Assembly Plant Worker" quote="I work on the Atlas line at the VW plant. Ten-hour shifts, rotating days and nights. The plant cafeteria is German-meets-Southern—schnitzel and sweet tea. My BlueCross plan has a 12-week wait for endocrinology. Chattanooga has the fastest internet in America but the slowest specialist access I've ever experienced." details="<strong>Patient Profile:</strong> Craig, 39, Assembly Technician at Volkswagen Chattanooga.<br/><br/><strong>The Challenge:</strong> Rotating shifts at VW's only US assembly plant. German-Southern hybrid cafeteria culture. BlueCross TN specialist waits 12 weeks in a city that prides itself on speed and connectivity.<br/><br/><strong>The Intervention:</strong> Completed intake from home in East Brainerd. TN-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="MoonPies, Gigabit, and the Assembly Line" paragraphs={["Chattanooga has the distinction of being both the birthplace of the MoonPie (a 300-calorie marshmallow-graham-chocolate snack sold by the millions) and the first US city with citywide 10-gigabit fiber internet. This tension between industrial food heritage and tech-forward aspiration defines the city's health landscape.","Volkswagen's only US assembly plant employs thousands in shift-oriented manufacturing. The VW plant joins Amazon's fulfillment center, Unum (insurance HQ), and the logistics companies along I-75 in creating a workforce that is predominantly shift-based or desk-bound.","The food culture is Tennessee Southern with a tourist-economy overlay: pulled pork BBQ, fried catfish, biscuits, and the MoonPie/RC Cola combination that locals still consume unironically. The Scenic City's outdoor recreation opportunities (Rock City, Lookout Mountain, Chickamauga trails) are real but seasonally limited by humidity and largely utilized by tourists, not shift workers.","GLP-1 medications leverage the Gig City's connectivity to deliver metabolic care at the speed Chattanooga promises in everything else."]} citations={["Hamilton County Health Department. (2025). <em>Community Health Assessment</em>.","UT College of Medicine Chattanooga. (2024). <em>Post-Industrial Health Transition in the Scenic City</em>."]} />
      <InsuranceBreakdown title="Volkswagen, MoonPies, and the Scenic City" text="Chattanooga's economy spans automotive, insurance, and tourism." employers={[{name:"Volkswagen Chattanooga",detail:"VW offers German corporate benefits adapted for the US—standard PBM restrictions still apply."},{name:"Unum (HQ) / BlueCross TN",detail:"Insurance company HQs—employees face the same restrictions they administer."},{name:"Erlanger / CHI Memorial",detail:"Health systems serve the region with 10-14 week specialist waits."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Chattanooga" localCompetitors={[{name:"Signal Mountain / Lookout Mtn Concierge",cost:"$600-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Gunbarrel Rd MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"Erlanger Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-75/I-24 & Erlanger Waitlists" transitText="Chattanooga sits at the junction of I-75 and I-24 in the Tennessee River valley. Atlanta is 2 hours south, Nashville is 2 hours north." hospitalText="<strong>Erlanger Health System</strong> and <strong>CHI Memorial</strong> serve the Scenic City region." />
      <InteractiveFAQ faqs={[{q:"I work at VW. Rotating shifts. When?",a:"Anytime. Fully asynchronous."},{q:"Do you deliver to Signal Mountain and Cleveland?",a:"Yes. All Hamilton, Bradley, and Catoosa (GA) County addresses."}]} />
      <StateLegalFramework stateName="Tennessee" boardName="Tennessee Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>TN Board of Medical Examiners</strong> and TCA § 63-1-155." />
      <DeliveryGridMap cityName="Chattanooga" mapQuery="Chattanooga, TN" coordinates="35.0456° N, 85.3097° W" counties="Hamilton County, Bradley County, Catoosa County (GA)" neighborhoods={['East Brainerd','Signal Mountain','Hixson','Ooltewah','Cleveland','Red Bank','Lookout Mountain']} />
      <FinalCTA stateName="Tennessee" />
    </div>
  );
}
