"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationMobile() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Alabama" cityName="Mobile" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Mobile</span>" subheadline="Mobile is Alabama's port city—where Airbus builds A320 jets, the shipyards service naval vessels, and the Gulf Coast seafood tradition meets the Deep South. Alabama has the second-highest obesity rate in America, and Mobile's combination of industrial shift work, Gulf humidity, and fried seafood creates a metabolic environment the healthcare system can't keep up with." ctaText="Check Alabama Eligibility" />
      <PatientArchetype archetype="The Airbus Mobile Assembly Line Worker" quote="I assemble A320 fuselage sections at the Airbus factory at Brookley Aeroplex. Ten-hour shifts, standing on concrete, using pneumatic tools. The cafeteria is fine but I'm exhausted after work. Mobile's food is incredible—fried oyster po'boys, seafood gumbo, Bienville sauce—and it's everywhere. My USA Health plan has a 16-week wait for endocrinology." details="<strong>Patient Profile:</strong> Terrence, 35, Assembly Technician at Airbus Mobile.<br/><br/><strong>The Challenge:</strong> 10-hour shifts on the A320 line. Physical exhaustion without metabolic benefit. Mobile's legendary Gulf seafood (fried) and Mardi Gras food traditions. USA Health specialist waits 14-18 weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from home in West Mobile. AL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Port City's Deep South Metabolic Challenge" paragraphs={["Mobile is Alabama's oldest city and its connection to the Gulf of Mexico. The port, Airbus's A320 final assembly line (the only Airbus factory in the US), and Austal USA's shipyard create an industrial workforce that mirrors other manufacturing hubs—shift work, cafeteria food, physical exhaustion that doesn't translate to cardiovascular health.","The food culture is arguably the richest in Alabama. Mobile's culinary traditions predate New Orleans'—the city claims to have invented Mardi Gras, and its food reflects French, Spanish, Creole, and Southern influences: fried oysters, shrimp and grits, West Indies salad, seafood gumbo, and the Mardi Gras king cake tradition. This is not tourist food—it is daily food.","Gulf Coast humidity from May through October makes outdoor exercise oppressive. Combined with Alabama's #2 national obesity ranking and limited specialist capacity at USA Health and Providence Hospital, Mobile faces a metabolic crisis amplified by geography, culture, and healthcare access.","GLP-1 medications serve Mobile's aerospace and shipyard workers, healthcare professionals, and the broader Gulf Coast community—without requiring them to drive 3 hours to Birmingham for a UAB specialist."]} citations={["Mobile County Health Department. (2025). <em>Community Health Assessment</em>.","USA College of Medicine. (2024). <em>Gulf Coast Food Culture and Metabolic Disease in Southwest Alabama</em>."]} />
      <InsuranceBreakdown title="Airbus, Shipyards, and the Gulf Coast" text="Mobile's economy spans aerospace, maritime, and healthcare." employers={[{name:"Airbus (Brookley) / Austal USA (Shipyard)",detail:"Aerospace and maritime plans apply standard PBM restrictions."},{name:"USA Health / Providence Hospital",detail:"Mobile's health systems face overwhelming demand as the only specialist sources for SW Alabama."},{name:"AM/NS Calvert (Steel) / Chevron (Pascagoula)",detail:"Industrial corridor employers add shift-work populations."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Mobile" localCompetitors={[{name:"West Mobile / Spring Hill Concierge",cost:"$500-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Airport Blvd MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"USA Health Endocrinology",cost:"$100 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-65/I-10 & USA Health Waitlists" transitText="Mobile sprawls along I-65 and I-10, with the Bayway and tunnels creating bottlenecks. Birmingham is 3+ hours north." hospitalText="<strong>USA Health</strong> and <strong>Providence Hospital</strong> serve SW Alabama. UAB in Birmingham is 3+ hours away." />
      <InteractiveFAQ faqs={[{q:"I work at Airbus. When do I do the intake?",a:"Anytime. Fully asynchronous."},{q:"Do you deliver to Daphne, Fairhope, and Saraland?",a:"Yes. All Mobile and Baldwin County addresses."}]} />
      <StateLegalFramework stateName="Alabama" boardName="Alabama Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>Alabama Board of Medical Examiners</strong> and Ala. Code § 34-24." />
      <DeliveryGridMap cityName="Mobile" mapQuery="Mobile, AL" coordinates="30.6954° N, 88.0399° W" counties="Mobile County, Baldwin County" neighborhoods={['West Mobile','Spring Hill','Daphne','Fairhope','Saraland','Tillmans Corner','Theodore','Semmes']} />
      <FinalCTA stateName="Alabama" />
    </div>
  );
}
