"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationLawton() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Oklahoma" cityName="Lawton" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Lawton</span>" subheadline="Lawton is home to Fort Sill—the US Army's Fires Center of Excellence and the place where every Army artillery officer and enlisted soldier trains. The 'King of Battle' installation dominates Lawton's economy. The city exists because the Army exists here." dataPoint1="Comanche County's adult obesity rate exceeds 36%. Fort Sill adds 12,000+ soldiers and families to a civilian healthcare system designed for a much smaller population. OKC is 90 min north—the only alternative." dataPoint2="Telehealth FX serves the artillery community and Lawton's workforce without the I-44 drive to Oklahoma City." />
      <PatientArchetype archetype="The Fort Sill Drill Sergeant (Basic Combat Training)" quote="Fort Sill runs Basic Combat Training alongside artillery school. I train recruits and fire artillery. The physical demands are extreme—but the DFAC food is designed for 18-year-old privates burning 5,000 calories a day. I'm 36 and burning half that. My TRICARE specialist referral from Reynolds Army Health Clinic is 20 weeks. OKC is 90 minutes on I-44. I don't have 90 minutes." details="<strong>Patient Profile:</strong> SSG Davis, 36, BCT Drill Sergeant, Fort Sill.<br/><br/><strong>The Challenge:</strong> DFAC food designed for teen recruits. DS metabolism doesn't match 18-year-old caloric intake. Reynolds AHC specialist wait 20 weeks. OKC is 90 min north.<br/><br/><strong>The Intervention:</strong> Completed intake from off-post in Lawton. OK-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="The King of Battle's Ground-Level Problem" paragraphs={["Fort Sill is where every artillery soldier in the US Army learns their craft—from 2LT Forward Observers to M109 Paladin crewmen. It also runs Basic Combat Training, adding drill sergeants and recruits to the population. Reynolds Army Health Clinic serves the military, but its specialist capacity reflects a community clinic, not a major medical center.","Lawton's food environment is military-town standard: Gate 3 fast food strip, Gore Blvd chain restaurants, and the DFAC. The DFAC food is calorie-dense by design—fueling 18-year-old trainees in physically demanding programs. The cadre (NCOs and officers) eat the same food without the same caloric expenditure.","Comanche County Memorial Hospital is the primary civilian system. The nearest alternative is Oklahoma City (90 min north on I-44). For Lawton residents, specialist care means either the 20-week Reynolds wait or a half-day OKC commitment.","GLP-1 medications serve Fort Sill's drill sergeants, artillery instructors, and families—delivering metabolic care to the community that trains America's artillerymen."]} citations={["Comanche County Health Department. (2025). <em>Community Health Assessment</em>.","Cameron University. (2024). <em>Military Community Health Outcomes at Fort Sill</em>."]} />
      <InsuranceBreakdown title="Fort Sill Dominance" text="Lawton's economy is overwhelmingly military." employers={[{name:"Fort Sill / Fires Center (TRICARE)",detail:"12,000+ soldiers. Reynolds AHC specialist waits 18-22 weeks."},{name:"Comanche County Memorial Hospital",detail:"Civilian system absorbs military overflow."},{name:"Goodyear (Lawton) / Cameron University",detail:"Manufacturing and education add plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Lawton" localCompetitors={[{name:"NW Lawton Clinics",cost:"$400-$600/mo",consult:"In-Person",access:"Limited"},{name:"Gore Blvd MedSpas",cost:"$200-$400/mo",consult:"Monthly",access:"Variable"},{name:"Reynolds / CCMH Endocrinology",cost:"$0-100 Copay",consult:"18-22 Week Wait",access:"Referral Chain"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-44 & Reynolds Waitlists" transitText="Lawton sits on I-44. OKC is 90 min north. Dallas is 3 hours south. Wichita Falls is 60 min SE." hospitalText="<strong>Reynolds AHC</strong> serves the military. <strong>CCMH</strong> serves civilians." />
      <InteractiveFAQ faqs={[{q:"I'm a drill sergeant. Can I do this between cycles?",a:"Yes. Fully asynchronous—complete on your schedule."},{q:"Do you deliver on post and to Elgin?",a:"Yes. All Fort Sill, Lawton, and Comanche County addresses."}]} />
      <StateLegalFramework stateName="Oklahoma" boardName="Oklahoma Board of Medical Licensure" text="Telehealth FX operates in compliance with the <strong>OK Board of Medical Licensure</strong>." />
      <DeliveryGridMap cityName="Lawton" mapQuery="Lawton, OK" coordinates="34.6036° N, 98.3959° W" counties="Comanche County" neighborhoods={['NW Lawton','Elgin','Cache','Fletcher','Medicine Park','Fort Sill']} />
      <FinalCTA stateName="Oklahoma" />
    </div>
  );
}
