"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationDayton() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Ohio" cityName="Dayton" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Dayton</span>" subheadline="Dayton is the Birthplace of Aviation—the Wright Brothers built and flew the first airplane here. Wright-Patterson Air Force Base remains the city's economic anchor, but the aerospace workforce that designs the future of flight is grounded by the same specialist shortage facing every mid-size Rust Belt city." dataPoint1="Montgomery County's adult obesity rate exceeds 34%. Dayton's post-industrial transition has been among the most challenging in Ohio—GM's Moraine Assembly closure in 2008 was a defining economic blow." dataPoint2="Telehealth FX serves the Wright-Patt workforce, the remaining manufacturing community, and the healthcare workers who anchor Dayton's economy." />
      <PatientArchetype archetype="The Wright-Patterson AFRL Research Physicist" quote="I conduct directed energy weapons research at the Air Force Research Laboratory. My clearance restricts where I can eat—the AFRL cafeteria is my only option during shifts. The work is intellectually demanding and completely sedentary. TRICARE has a 16-week specialist referral, and the civilian options at Premier Health aren't much faster. The Wright Brothers' city can't fly me to a doctor any faster." details="<strong>Patient Profile:</strong> Dr. Foster, 40, Research Physicist at AFRL, Wright-Patterson AFB.<br/><br/><strong>The Challenge:</strong> Classified directed energy research. SCIF cafeteria-only diet. TRICARE specialist wait 16 weeks. Civilian alternatives similarly overwhelmed.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Beavercreek. OH-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Birthplace of Aviation, Grounded by Access" paragraphs={["Wright-Patterson Air Force Base is Dayton's economic engine—the Air Force Research Laboratory (AFRL), the National Air and Space Intelligence Center (NASIC), and the Air Force Life Cycle Management Center employ over 30,000 military, civilian, and contractor personnel. The work is classified, sedentary, and cafeteria-dependent.","Dayton's post-industrial transition has been painful. The closure of GM's Moraine Assembly plant, NCR's departure, and the hollowing out of the manufacturing base left the city dependent on Wright-Patt and healthcare (Premier Health, Kettering Health). The food culture is classic Ohio comfort: skyline chili (Cincinnati-style, adopted by Dayton), Cassano's pizza, and the meat-and-potatoes tradition of the Rust Belt.","Premier Health and Kettering Health Network serve the Dayton metro, but specialist capacity for a region of 800,000 that includes a massive military population is constrained. Endocrinology waits average 12-18 weeks.","GLP-1 medications serve the Wright-Patt research community and the broader Dayton population—bridging the specialist gap in the city that invented human flight."]} citations={["Public Health Dayton & Montgomery County. (2025). <em>Community Health Assessment</em>.","Wright State University School of Medicine. (2024). <em>Military Population, Post-Industrial Transition, and Healthcare Access in the Greater Dayton Region</em>."]} />
      <InsuranceBreakdown title="Wright-Patt and the Post-GM Economy" text="Dayton's economy centers on the military and healthcare." employers={[{name:"Wright-Patterson AFB (TRICARE/FEHB)",detail:"30,000+ military and civilian workers face 16+ week specialist waits."},{name:"Premier Health / Kettering Health",detail:"Health systems serve military and civilian populations with constrained capacity."},{name:"CareSource (HQ) / LexisNexis",detail:"Corporate employers add standard PBM plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Dayton" localCompetitors={[{name:"Beavercreek / Oakwood Concierge",cost:"$500-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Far Hills MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"Premier Endocrinology",cost:"$100 Copay+Rx",consult:"12-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-75/I-70 & Premier Waitlists" transitText="Dayton sits at I-75 and I-70. Cincinnati is 1 hour south. Columbus is 1 hour east." hospitalText="<strong>Premier Health (Miami Valley)</strong> and <strong>Kettering Health</strong> serve the Greater Dayton region." />
      <InteractiveFAQ faqs={[{q:"I work at AFRL. Security clearance concerns?",a:"None. GLP-1 medications are not controlled substances. Telehealth FX is independent of TRICARE and your military/civilian record."},{q:"Do you deliver to Beavercreek, Centerville, and Xenia?",a:"Yes. All Montgomery, Greene, and Clark County addresses."}]} />
      <StateLegalFramework stateName="Ohio" boardName="State Medical Board of Ohio" text="Telehealth FX operates in compliance with the <strong>State Medical Board of Ohio</strong>." />
      <DeliveryGridMap cityName="Dayton" mapQuery="Dayton, OH" coordinates="39.7589° N, 84.1916° W" counties="Montgomery County, Greene County, Clark County" neighborhoods={['Beavercreek','Oakwood','Centerville','Kettering','Xenia','Fairborn','Huber Heights','Troy']} />
      <FinalCTA stateName="Ohio" />
    </div>
  );
}
