"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationKilleen() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="Killeen" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Killeen</span>" subheadline="Killeen is home to Fort Cavazos (formerly Fort Hood)—the largest active-duty armored post in the US military. Over 45,000 soldiers, plus families and civilian workers, depend on a TRICARE system and a civilian healthcare network that were never designed for a population this large in Central Texas." dataPoint1="Bell County's adult obesity rate exceeds 35%. Fort Cavazos dominates the economy. Carl R. Darnall Army Medical Center serves the military but overflows into a civilian system with limited specialist depth." dataPoint2="Telehealth FX serves the armored corps families, DoD civilians, and the broader Central Texas community without the Darnall waitlist." />
      <PatientArchetype archetype="The Fort Cavazos 1st Cavalry Division Spouse" quote="My husband is deployed with 1st Cav. Third deployment in 5 years. I've gained 50 pounds across three deployments—stress eating, solo parenting three kids, zero time for myself. Darnall has a 22-week wait for endocrinology. Twenty-two weeks. My husband will be home before I get an appointment." details="<strong>Patient Profile:</strong> Jessica, 30, Military Spouse, Fort Cavazos.<br/><br/><strong>The Challenge:</strong> Three deployments, 50 lbs gained, solo parenting, 22-week Darnall wait. Deployment returns before specialist appointment arrives.<br/><br/><strong>The Intervention:</strong> Completed intake from on-post housing at 11 PM. TX-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="The Armored Post's 22-Week Wait" paragraphs={["Fort Cavazos is the largest active-duty armored post in the world. 1st Cavalry Division, III Corps, 1st Medical Brigade—the post houses more tanks, soldiers, and families than most American cities. Darnall Army Medical Center is the primary medical facility, but its specialist capacity cannot serve a population of this size.","The deployment cycle at Fort Cavazos is relentless. Combat deployments, rotational deployments to Europe and Korea, and NTC rotations at Fort Irwin mean soldiers are frequently gone for 9-12 months. The spouse health crisis is well-documented in military family research: cortisol elevation, stress eating, weight gain, and a complete inability to prioritize personal health during solo parenting.","Killeen's food environment outside the gates is classic military-town sprawl: Rancier Avenue fast food, strip mall restaurants, and the limited options that characterize most military communities. The combination of deployment stress, food environment, and 22-week specialist waits creates a metabolic crisis.","GLP-1 medications serve the Fort Cavazos community—the armored corps families who sacrifice the most and wait the longest for care."]} citations={["Bell County Health District. (2025). <em>Community Health Assessment</em>.","Carl R. Darnall Army Medical Center. (2024). <em>Specialist Referral Patterns and Wait Times</em>."]} />
      <InsuranceBreakdown title="Fort Cavazos Dominance" text="Killeen's economy is almost entirely military." employers={[{name:"Fort Cavazos / III Corps (TRICARE)",detail:"45,000+ soldiers. Darnall specialist referrals exceed 20 weeks."},{name:"Seton Medical Center / AdventHealth",detail:"Civilian systems absorb TRICARE overflow."},{name:"DoD Civilian / Contractor",detail:"DoD and contractor plans face the same limited network."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Killeen" localCompetitors={[{name:"Harker Heights Clinics",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"Rancier Ave MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Darnall Endocrinology",cost:"$0 (TRICARE)",consult:"22+ Week Wait",access:"Referral Chain"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Darnall's 22-Week Wait" transitText="Killeen sits on US-190. Austin is 70 min south. Temple (BSW) is 30 min east." hospitalText="<strong>Darnall AMC</strong> serves the military. <strong>AdventHealth</strong> and <strong>BSW Temple</strong> serve civilians." />
      <InteractiveFAQ faqs={[{q:"My spouse is deployed. Can I start?",a:"Yes. Military spouses use Telehealth FX independently."},{q:"Do you deliver on post?",a:"Yes. All Fort Cavazos and Killeen addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong>." />
      <DeliveryGridMap cityName="Killeen" mapQuery="Killeen, TX" coordinates="31.1171° N, 97.7278° W" counties="Bell County, Coryell County" neighborhoods={['Harker Heights','Copperas Cove','Nolanville','Temple','Belton','Gatesville']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
