"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationTyler() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="Tyler" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Tyler</span>" subheadline="Tyler is the Rose Capital of the World—and the regional medical hub for East Texas. UT Health East Texas and Christus Mother Frances serve a territory larger than some New England states. But the healthcare workforce that staffs these hospitals faces the same specialist access challenge as their patients." dataPoint1="Smith County's adult obesity rate exceeds 34%. Tyler's medical corridor employs thousands of healthcare workers who understand metabolic health professionally but face the same insurance barriers personally." dataPoint2="Telehealth FX serves East Texas' healthcare professionals and the rose country community." />
      <PatientArchetype archetype="The UT Health East Texas ICU Nurse" quote="I work the ICU at UT Health Tyler—12-hour night shifts. I know exactly what metabolic syndrome does to the body. I see it kill people. I chart A1C values and calculate insulin drips. Then I go home at 7 AM and eat breakfast tacos because I'm exhausted and nothing healthy is open. My BCBS plan through the hospital requires 6 months of behavioral modification before GLP-1 authorization. I literally staff the endocrinology ward. I can't get an appointment on it." details="<strong>Patient Profile:</strong> Jessica, 34, RN/ICU, UT Health East Texas.<br/><br/><strong>The Challenge:</strong> Night shift ICU nurse. Understands metabolic syndrome clinically. Her own hospital's BCBS plan requires 6 months behavioral mod before GLP-1 auth. Staffs the endo ward she can't access as a patient.<br/><br/><strong>The Intervention:</strong> Completed intake from home in South Tyler. TX-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="The Rose Capital's Healthcare Worker Paradox" paragraphs={["Tyler is unusual among our target cities: it has strong healthcare infrastructure. UT Health East Texas and Christus Mother Frances are legitimate regional systems that serve as the referral hub for all of East Texas. The irony is that the workers who staff these hospitals face the same insurance PBM restrictions as everyone else.","The food culture is East Texas: BBQ (the Tyler leg of the Texas BBQ belt includes Stanley's Famous Pit BBQ and Bodacious Bar-B-Q), Southern comfort food, breakfast tacos, and the rose festival food culture. The 12-hour shift nurse diet is a national problem, but Tyler's food environment makes it worse.","Tyler's medical corridor (Broadway Ave medical district) employs thousands. The specialist capacity exists—but it's designed for the broader East Texas population, not prioritized for the hospital's own employees. Insurance Step Therapy requirements mean healthcare workers face the same 6-month behavioral modification gates as everyone else.","GLP-1 medications serve Tyler's healthcare workers, the UT Tyler academic community, and East Texas—delivering the metabolic care that ICU nurses understand clinically but can't access personally."]} citations={["Northeast Texas Public Health District. (2025). <em>Smith County Community Health Assessment</em>.","UT Health Science Center at Tyler. (2024). <em>Healthcare Worker Metabolic Health in Regional Medical Centers</em>."]} />
      <InsuranceBreakdown title="Rose Country and the Healthcare Worker Paradox" text="Tyler's economy centers on healthcare, education, and energy." employers={[{name:"UT Health East Texas / Christus Mother Frances",detail:"Healthcare workers face the same Step Therapy their patients do. BCBS requires 6-month behavioral mod."},{name:"Brookshire Grocery Co. (HQ)",detail:"Corporate plans with standard PBM restrictions."},{name:"UT Tyler / TJC",detail:"Education plans with Step Therapy."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Tyler" localCompetitors={[{name:"South Tyler / Hollytree Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"S. Broadway MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"UT Health Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"6-Month Behavioral Mod"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="East Texas Medical Hub, Worker Access Gap" transitText="Tyler sits on I-20 and US-69. Dallas is 90 min west. Shreveport is 90 min east. Longview is 35 min east." hospitalText="<strong>UT Health East Texas</strong> and <strong>Christus Mother Frances</strong> serve the region." />
      <InteractiveFAQ faqs={[{q:"I work at the hospital. Can I really get this faster than through my own employer?",a:"Yes. Our process bypasses your hospital's PBM Step Therapy entirely."},{q:"Do you deliver to Longview, Jacksonville, and Whitehouse?",a:"Yes. All Smith, Gregg, and Cherokee County addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong>." />
      <DeliveryGridMap cityName="Tyler" mapQuery="Tyler, TX" coordinates="32.3513° N, 95.3011° W" counties="Smith County, Gregg County" neighborhoods={['South Tyler','Hollytree','Whitehouse','Lindale','Longview','Bullard','Flint','Troup']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
