"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationHonolulu() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Hawaii" cityName="Honolulu" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Honolulu</span>" subheadline="Honolulu is 2,400 miles from the nearest US mainland city. The nearest specialist you can't get in Hawaii is in Los Angeles—a 5-hour flight. Pearl Harbor, Schofield Barracks, and Joint Base Pearl Harbor-Hickam add 50,000+ military personnel to an island healthcare system with nowhere to expand." dataPoint1="Hawaii's adult obesity rate is lower than the mainland average, but Native Hawaiian and Pacific Islander populations face rates exceeding 40%. The cost of living—highest in the US—means many working families eat spam musubi and plate lunches because fresh food is imported and expensive." dataPoint2="Telehealth FX delivers metabolic care to the most geographically isolated state—no inter-island flight, no mainland referral." />
      <PatientArchetype archetype="The Pearl Harbor Naval Shipyard Pipe Fitter" quote="I repair submarine piping systems at Pearl Harbor Naval Shipyard. My shifts are 10 hours in a submarine hull. The food options are the shipyard cafeteria or a plate lunch truck. My TRICARE referral for endocrinology at Tripler Army Medical Center is 20 weeks. The nearest mainland alternative is Los Angeles. I can't fly to LA for a doctor's appointment." details="<strong>Patient Profile:</strong> Kawika, 38, Pipe Fitter at Pearl Harbor Naval Shipyard.<br/><br/><strong>The Challenge:</strong> Confined submarine repair work. Island isolation. Tripler AMC specialist wait 20 weeks. Los Angeles is 2,400 miles across the Pacific. The definition of medical isolation.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Ewa Beach. HI-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="2,400 Miles from the Nearest Specialist" paragraphs={["Hawaii's geographic isolation is absolute. The nearest US city is Los Angeles—2,400 miles across the Pacific Ocean. When the local healthcare system cannot provide specialist care, the alternative is a $600+ round-trip flight and a full day of travel each way. For hourly workers, military families, and the tourism workforce, this is not an option.","The plate lunch is Hawaii's default working meal: two scoops rice, one scoop macaroni salad, and a protein (typically fried or teriyaki). A standard plate lunch runs 1,200-1,800 calories. Spam musubi—fried Spam on rice wrapped in nori—is consumed as a daily snack. Hawaii consumes more Spam per capita than any US state. These are not tourist novelties; they are working-class necessities driven by the extreme cost of imported fresh food.","The military presence (Joint Base Pearl Harbor-Hickam, Schofield Barracks, Marine Corps Base Hawaii) adds 50,000+ personnel and families to O'ahu's healthcare demand. Tripler Army Medical Center serves the military but overflows into the civilian system (Queen's Medical Center, Straub, Kaiser Hawaii).","GLP-1 medications eliminate the Pacific Ocean as a barrier to metabolic care—delivering to any address on any Hawaiian island."]} citations={["Hawaii State Department of Health. (2025). <em>Behavioral Risk Factor Surveillance System</em>.","University of Hawaii John A. Burns School of Medicine. (2024). <em>Pacific Island Food Systems and Metabolic Health</em>."]} />
      <InsuranceBreakdown title="Military, Tourism, and Island Economics" text="Honolulu's economy centers on military, tourism, and government." employers={[{name:"JBPHH / Schofield / MCBH (TRICARE)",detail:"50,000+ military personnel. Tripler AMC specialist waits 16-22 weeks."},{name:"Tourism / Hospitality Industry",detail:"Hotel and restaurant workers face shift schedules and limited affordable food options."},{name:"Queen's / Straub / Kaiser Hawaii",detail:"Island health systems serve O'ahu's 1M residents with no overflow option."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Honolulu" localCompetitors={[{name:"Kahala / Hawaii Kai Concierge",cost:"$900-$1,400/mo",consult:"In-Person",access:"Branded Only"},{name:"Waikiki MedSpas",cost:"$500-$800/mo",consult:"Monthly",access:"Variable"},{name:"Tripler / Queen's Endocrinology",cost:"$125 Copay+Rx",consult:"16-22 Week Wait",access:"Island Only"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="The Pacific Ocean Is the Barrier" transitText="O'ahu traffic on H-1 is among the worst per capita in America. The nearest mainland healthcare is a 5-hour flight to Los Angeles." hospitalText="<strong>Tripler AMC</strong>, <strong>Queen's Medical Center</strong>, and <strong>Kaiser Hawaii</strong> serve O'ahu. No mainland overflow." />
      <InteractiveFAQ faqs={[{q:"Do you deliver to neighbor islands (Maui, Big Island, Kauai)?",a:"Yes. We deliver to all Hawaiian island addresses via USPS Priority Mail."},{q:"I'm stationed at Schofield. Is this separate from TRICARE?",a:"Yes. Completely independent."}]} />
      <StateLegalFramework stateName="Hawaii" boardName="Hawaii Medical Board" text="Telehealth FX operates in compliance with the <strong>Hawaii Medical Board</strong> and HRS § 453." />
      <DeliveryGridMap cityName="Honolulu" mapQuery="Honolulu, HI" coordinates="21.3069° N, 157.8583° W" counties="City & County of Honolulu (O'ahu)" neighborhoods={['Waikiki','Ewa Beach','Kapolei','Pearl City','Kailua','Kaneohe','Mililani','Wahiawa']} />
      <FinalCTA stateName="Hawaii" />
    </div>
  );
}
