"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSanAngelo() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Texas" cityName="San Angelo" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>San Angelo</span>" subheadline="San Angelo is home to Goodfellow Air Force Base—the Joint Cryptologic and Intelligence Training Center. Every military intelligence analyst, every linguist, and every fire protection specialist in the Department of Defense trains here. The city sits in the heart of West Texas ranch country, 3+ hours from any major metro." ctaText="Check Texas Eligibility" />
      <PatientArchetype archetype="The Goodfellow AFB Intelligence Analyst Instructor" quote="I teach intelligence analysts at the 316th Training Squadron—people who will analyze satellite imagery and intercept communications. I sit in a SCIF for 10 hours teaching classification protocols. The DFAC food hasn't changed in a decade. San Angelo is beautiful ranch country but there's no specialist for 200 miles. Shannon has a 20-week wait. I train people to find hidden threats. I can't find an endocrinologist." details="<strong>Patient Profile:</strong> MSgt Howard, 37, Intelligence Analyst Instructor, 316th TRS, Goodfellow AFB.<br/><br/><strong>The Challenge:</strong> SCIF-based sedentary instruction. DFAC food. San Angelo 200+ miles from any specialist alternative. Shannon specialist wait 20 weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from off-base in San Angelo. TX-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Intelligence Training in Ranch Country" paragraphs={["Goodfellow AFB is a joint DOD intelligence training facility—processing students from the Air Force, Army, Navy, and Marines through cryptologic linguist, intelligence analyst, and fire protection courses. The permanent party population includes some of the most highly-clearanced instructors in the military, all living in a small West Texas city.","San Angelo's food culture is West Texas ranching: mesquite BBQ, chicken-fried steak, Tex-Mex, and the goat (cabrito) tradition from the Concho Valley's goat ranching heritage. Zentner's Daughter and Peasant Village define the local dining.","Shannon Medical Center is the sole major hospital, serving the Concho Valley—a geographic area spanning 20+ counties. The nearest alternative specialist care is in Lubbock (3 hours NW), Midland (2 hours NW), or San Antonio (3+ hours SE).","GLP-1 medications serve the intelligence community, Angelo State University, and the ranching workforce—delivering metabolic care to one of the most isolated training installations in the military."]} citations={["Tom Green County Health Department. (2025). <em>Community Health Assessment</em>.","Angelo State University. (2024). <em>Healthcare Access in the Concho Valley</em>."]} />
      <InsuranceBreakdown title="Intelligence Training and Goat Country" text="San Angelo's economy centers on military, ranching, and education." employers={[{name:"Goodfellow AFB (TRICARE)",detail:"Intelligence training base. TRICARE specialist waits 18-22 weeks."},{name:"Shannon Medical Center",detail:"Sole major hospital for 20+ county Concho Valley territory."},{name:"Angelo State University / Ethicon",detail:"Education and medical device manufacturing add plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in San Angelo" localCompetitors={[{name:"Southwest / Bluffs Concierge",cost:"$400-$600/mo",consult:"In-Person",access:"Branded Only"},{name:"Sherwood Way MedSpas",cost:"$250-$400/mo",consult:"Monthly",access:"Variable"},{name:"Shannon Endocrinology",cost:"$100 Copay+Rx",consult:"18-22 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="200 Miles from a Major Metro" transitText="San Angelo sits on US-87/US-67. Midland is 2 hours NW. San Antonio is 3+ hours SE. Lubbock is 3 hours NW." hospitalText="<strong>Shannon Medical Center</strong> serves the 20+ county Concho Valley." />
      <InteractiveFAQ faqs={[{q:"I work in a SCIF. Is this confidential?",a:"Yes. Completely independent of your military/intelligence employer."},{q:"Do you deliver to Goodfellow and Christoval?",a:"Yes. All Tom Green County addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong>." />
      <DeliveryGridMap cityName="San Angelo" mapQuery="San Angelo, TX" coordinates="31.4638° N, 100.4370° W" counties="Tom Green County" neighborhoods={['Southwest','Lake Nasworthy','Christoval','Wall','Grape Creek','Carlsbad','Goodfellow AFB']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
