"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationHuntsville() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Alabama" cityName="Huntsville" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Huntsville</span>" subheadline="Huntsville is where America builds rockets. NASA's Marshall Space Flight Center, Redstone Arsenal, and the defense contractors that surround them employ the most technically brilliant workforce in Alabama—in SCIF environments that are uniformly sedentary, windowless, and cafeteria-dependent." dataPoint1="Huntsville is the fastest-growing city in Alabama, driven by aerospace and defense. Healthcare infrastructure has not kept pace with population growth—a familiar pattern." dataPoint2="Telehealth FX serves Rocket City's SCIF-bound engineers and defense workers without the Huntsville Hospital waitlist." />
      <PatientArchetype archetype="The Marshall Space Flight Center SLS Engineer" quote="I design propulsion systems for the Space Launch System. My office is inside a secured facility. No natural light, no outdoor breaks, vending machine lunches. I can calculate the delta-v needed to reach lunar orbit but I can't get a doctor's appointment in my own city in less than 4 months." details="<strong>Patient Profile:</strong> Dr. Patel, 37, Propulsion Engineer at NASA MSFC.<br/><br/><strong>The Challenge:</strong> SCIF work at Marshall—sedentary, windowless, cafeteria food. FEHB coverage is strong on paper but Huntsville's specialist network can't serve a booming population. 14-week endocrinology wait.<br/><br/><strong>The Intervention:</strong> Completed intake from his home in Hampton Cove. AL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Rocket City's Ground-Level Problem" paragraphs={["Huntsville's economy is built on aerospace and defense. NASA Marshall Space Flight Center, Redstone Arsenal (home of US Army Space and Missile Defense Command), and the ring of defense contractors—Boeing, Lockheed Martin, Northrop Grumman, Raytheon—create one of the most technically sophisticated workforces in America. The work is intellectually demanding and physically sedentary.","The SCIF-worker metabolic profile seen in Tucson (Raytheon), Colorado Springs (NORAD), and Tampa (CENTCOM) is amplified in Huntsville by concentration. Cummings Research Park—the second-largest research park in the US—houses thousands of engineers in office parks that are entirely car-dependent with limited food options beyond fast food chains.","Huntsville's rapid growth has strained Huntsville Hospital and Crestwood Medical Center. Specialist recruitment in North Alabama cannot keep pace with a population adding 5,000+ residents per year.","GLP-1 medications serve Rocket City's defense and aerospace workforce—bypassing the specialist bottleneck created by rapid growth."]} citations={["Madison County Health Department. (2025). <em>Community Health Assessment</em>.","UAH College of Engineering. (2024). <em>SCIF Work Environments and Occupational Health in the Defense Sector</em>."]} />
      <InsuranceBreakdown title="NASA, Army, and the Contractor Ring" text="Huntsville's employers are overwhelmingly defense and aerospace." employers={[{name:"NASA MSFC / Redstone Arsenal (FEHB/TRICARE)",detail:"Federal employees have FEHB; military have TRICARE. Both face limited local specialist networks."},{name:"Boeing / Lockheed / Northrop (Contractors)",detail:"Defense contractors offer corporate plans with standard PBM restrictions."},{name:"Huntsville Hospital / Crestwood",detail:"Regional hospitals face overwhelming demand from rapid growth."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Huntsville" localCompetitors={[{name:"Hampton Cove / SE Huntsville Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"University Dr MedSpas",cost:"$300-$600/mo",consult:"Monthly",access:"Variable"},{name:"Huntsville Hospital Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Memorial Parkway & Hospital Waitlists" transitText="Huntsville's growth has overwhelmed Memorial Parkway (US-231) and I-565. Cummings Research Park traffic alone creates daily congestion." hospitalText="<strong>Huntsville Hospital</strong> and <strong>Crestwood Medical Center</strong> serve North Alabama. Specialist waits average 12-16 weeks." />
      <InteractiveFAQ faqs={[{q:"Will this affect my security clearance?",a:"No. GLP-1 medications are not controlled substances and have no security clearance implications."},{q:"Do you deliver to Madison and Decatur?",a:"Yes. All Madison, Limestone, and Morgan County addresses."}]} />
      <StateLegalFramework stateName="Alabama" boardName="Alabama Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>Alabama Board of Medical Examiners</strong> and Ala. Code § 34-24." />
      <DeliveryGridMap cityName="Huntsville" mapQuery="Huntsville, AL" coordinates="34.7304° N, 86.5861° W" counties="Madison County, Limestone County, Morgan County" neighborhoods={['Hampton Cove','Jones Valley','Madison','Decatur','Athens','Meridianville','Harvest']} />
      <FinalCTA stateName="Alabama" />
    </div>
  );
}
