"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationTallahassee() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Florida" cityName="Tallahassee" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Tallahassee</span>" subheadline="Tallahassee is Florida's capital and home to two major universities—FSU and FAMU. The state government workforce that writes Florida's health policies and the university community that studies them both face the same specialist access barriers as everyone else in the Big Bend region." ctaText="Check Florida Eligibility" />
      <PatientArchetype archetype="The Florida AHCA Health Policy Analyst" quote="I work at the Agency for Health Care Administration—I analyze Medicaid data, hospital outcomes, and access metrics for the state of Florida. I know exactly where the specialist gaps are because I map them. My state employee plan requires a referral chain that takes 4 months in a capital city with limited endocrinology. I regulate healthcare access. I just can't access it myself." details="<strong>Patient Profile:</strong> Lisa, 42, Health Policy Analyst at Florida AHCA.<br/><br/><strong>The Challenge:</strong> She maps healthcare access gaps for the state—and lives inside one. State employee plan requires standard Step Therapy in a city with limited specialist capacity.<br/><br/><strong>The Intervention:</strong> Completed intake from her home in Killearn. FL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Capital's Own Access Gap" paragraphs={["Tallahassee is geographically isolated from Florida's major medical centers. Jacksonville is 2.5 hours east, Orlando is 4 hours south, and Gainesville (UF Health) is 2.5 hours southeast. The capital city of the third-largest state depends on Tallahassee Memorial and Capital Regional for specialist care—adequate community hospitals, but not the depth of an academic medical center.","The state government workforce fills the Capitol complex and the surrounding office buildings. FSU and FAMU add 70,000+ students and thousands of faculty/staff. The combined population is predominantly sedentary—desk-bound policy work, academic research, and classroom instruction.","The food culture is a blend of Southern comfort (fried catfish, BBQ) and the college-town dining that serves FSU and FAMU (pizza, wings, late-night food trucks). The combination creates a caloric environment familiar to any college town, amplified by the state worker desk-job population.","GLP-1 medications serve Tallahassee's policy analysts, university researchers, and the broader Big Bend community—the people who study, regulate, and debate healthcare access but face the same specialist barriers they document."]} citations={["Leon County Health Department. (2025). <em>Community Health Assessment</em>.","FSU College of Medicine. (2024). <em>Healthcare Access in Florida's Big Bend Region</em>."]} />
      <InsuranceBreakdown title="State Workers, Students, and the Big Bend" text="Tallahassee's economy is dominated by state government and higher education." employers={[{name:"State of Florida (Capitol Workforce)",detail:"State plans require Step Therapy that takes months in a city with limited specialist availability."},{name:"FSU / FAMU / TCC",detail:"University plans apply standard PBM restrictions."},{name:"TMH / Capital Regional",detail:"Local hospitals serve the Big Bend but lack academic medical center specialist depth."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Tallahassee" localCompetitors={[{name:"Killearn / Betton Hills Concierge",cost:"$600-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Thomasville Rd MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"TMH Endocrinology",cost:"$100 Copay+Rx",consult:"10-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Thomasville Rd & TMH Waitlists" transitText="Tallahassee sprawls along I-10, Thomasville Road, and Apalachee Parkway. The city is car-dependent with no rail transit." hospitalText="<strong>Tallahassee Memorial</strong> and <strong>Capital Regional</strong> serve the Big Bend. The nearest academic medical center is UF Health in Gainesville, 2.5 hours away." />
      <InteractiveFAQ faqs={[{q:"I'm a state employee. Can I use this?",a:"Yes. Telehealth FX is private, self-pay, completely independent of the State of Florida employee plan."},{q:"Do you deliver to Crawfordville and Quincy?",a:"Yes. All Leon, Wakulla, and Gadsden County addresses."}]} />
      <StateLegalFramework stateName="Florida" boardName="Florida Board of Medicine" text="Telehealth FX operates in compliance with the <strong>Florida Board of Medicine</strong> and F.S. § 456.47." />
      <DeliveryGridMap cityName="Tallahassee" mapQuery="Tallahassee, FL" coordinates="30.4383° N, 84.2807° W" counties="Leon County, Wakulla County, Gadsden County" neighborhoods={['Killearn','Betton Hills','Southwood','Bradfordville','Crawfordville','Quincy','Havana']} />
      <FinalCTA stateName="Florida" />
    </div>
  );
}
