"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationWorcester() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Massachusetts" cityName="Worcester" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Worcester</span>" subheadline="Worcester is the second-largest city in New England—40 miles from Boston's world-class medical infrastructure but a world away from its specialist access. UMass Memorial anchors local care, but the city's working-class population faces barriers that proximity to Boston cannot solve." ctaText="Check Massachusetts Eligibility" />
      <PatientArchetype archetype="The UMass Memorial Medical Center CNA" quote="I'm a CNA on a med-surg floor at UMass Memorial. I lift patients, change beds, and run for 12 hours straight. I know exactly what metabolic syndrome looks like because I care for patients living with it every shift. My own UMass employee plan requires a referral to an endocrinologist who's booked 14 weeks out. I work in the hospital. I still can't get seen." details="<strong>Patient Profile:</strong> Danielle, 29, CNA at UMass Memorial Medical Center.<br/><br/><strong>The Challenge:</strong> She provides direct patient care for metabolic disease patients but faces the same specialist waitlists as a community member. Her UMass employee plan requires standard referral and prior authorization chains.<br/><br>Completed intake from her apartment in Main South. MA-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Boston's Shadow, Worcester's Reality" paragraphs={["Worcester is 40 miles from Boston—close enough that residents theoretically have access to the best medical infrastructure in the world. In practice, the working-class population that defines Worcester (healthcare workers, manufacturing, education) cannot take a full day off to drive to Boston, park at a hospital, and see a specialist. Worcester's healthcare reality is local.","UMass Memorial is a strong academic medical center, but it serves as the regional referral hub for all of Central Massachusetts. Specialist capacity reflects this burden. Saint Vincent Hospital adds capacity but was acquired by Tenet Healthcare, introducing corporate healthcare dynamics.","Worcester's food culture is old New England working class: diners, pizza shops, and the comfort food traditions of the city's large Irish, Italian, and Puerto Rican communities. The city's restaurant scene has evolved, but the dietary default for shift workers remains high-calorie convenience.","GLP-1 medications serve Worcester's healthcare workers, students, and manufacturing employees—delivering specialist-grade metabolic care within the city rather than requiring the I-90 drive to Boston."]} citations={["Worcester Division of Public Health. (2025). <em>Community Health Assessment</em>.","UMass Chan Medical School. (2024). <em>Healthcare Access in Central Massachusetts</em>."]} />
      <InsuranceBreakdown title="Healthcare Workers, Students, and the Boston Shadow" text="Worcester's economy centers on healthcare and education." employers={[{name:"UMass Memorial Health",detail:"Worcester's largest employer. Plans require standard referral chains in a system with 12-16 week specialist waits."},{name:"College of the Holy Cross / WPI / Clark",detail:"Education employers offer plans with standard PBM restrictions."},{name:"Saint Gobain / National Grid",detail:"Industrial and utility employers add corporate plans with specialty-tier barriers."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Worcester" localCompetitors={[{name:"Shrewsbury / Holden Concierge",cost:"$700-$1,100/mo",consult:"In-Person",access:"Branded Only"},{name:"Route 9 MedSpas",cost:"$400-$650/mo",consult:"Monthly",access:"Variable"},{name:"UMass Endocrinology",cost:"$125 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-90 to Boston & UMass Waitlists" transitText="Worcester connects to Boston via I-90 (Mass Pike)—a 50-minute drive in ideal conditions, 90+ minutes during rush hour." hospitalText="<strong>UMass Memorial</strong> and <strong>Saint Vincent Hospital</strong> serve Central MA. Specialist waits average 12-16 weeks." />
      <InteractiveFAQ faqs={[{q:"Should I just go to a Boston specialist?",a:"Boston specialists have their own 10-16 week waits, plus the commute. Telehealth FX provides the same clinical evaluation from your home in Worcester."},{q:"Do you deliver to Shrewsbury, Holden, and Grafton?",a:"Yes. All Worcester County addresses."}]} />
      <StateLegalFramework stateName="Massachusetts" boardName="Massachusetts Board of Registration in Medicine" text="Telehealth FX operates in compliance with the <strong>MA Board of Registration in Medicine</strong> and MGL c.111 § 53A." />
      <DeliveryGridMap cityName="Worcester" mapQuery="Worcester, MA" coordinates="42.2626° N, 71.8023° W" counties="Worcester County" neighborhoods={['Main South','Shrewsbury','Holden','Grafton','Auburn','Millbury','Leicester','Northborough']} />
      <FinalCTA stateName="Massachusetts" />
    </div>
  );
}
