"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationRockford() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Illinois" cityName="Rockford" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Rockford</span>" subheadline="Rockford is Illinois' third-largest city—a Rust Belt manufacturing hub 90 minutes from Chicago that has faced decades of economic challenge. The aerospace fastener and machining industry keeps the economy alive, but the post-industrial food culture and specialist shortage mirror every mid-size Midwest manufacturing city." ctaText="Check Illinois Eligibility" />
      <PatientArchetype archetype="The Collins Aerospace Fastener Machinist" quote="I machine precision aerospace fasteners at Collins Aerospace—the parts that hold aircraft together at 30,000 feet. My work requires absolute precision, which means absolute stillness. I sit at a CNC machine for 10 hours. Rockford used to be the Screw Capital of the World—we made all the fasteners. Now there's fewer of us and the food hasn't changed. SwedishAmerican has a 12-week specialist wait." details="<strong>Patient Profile:</strong> Tom, 46, CNC Machinist at Collins Aerospace, Rockford.<br/><br/><strong>The Challenge:</strong> Precision machining requires sedentary stillness. Post-industrial Rockford. Swedish-Italian food traditions. SwedishAmerican specialist wait 12 weeks. Chicago is 90 min but inaccessible for shift workers.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Machesney Park. IL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Screw Capital's Metabolic Problem" paragraphs={["Rockford was once the 'Screw Capital of the World'—the fastener and machine tool industry built the city. Collins Aerospace (formerly Sundstrand), Woodward, and the remaining precision manufacturing companies keep the industrial heritage alive, but the workforce is a fraction of its peak. The economic transition left Rockford with elevated poverty, food desert neighborhoods, and health outcomes below the state average.","The food culture is Swedish-Italian immigrant heritage: Swedish pancakes at Stockholm Inn, Italian beef at multiple local shops, and the Midwest comfort canon. The combination reflects the immigrant communities that built the fastener industry.","SwedishAmerican (now part of UW Health) and Mercyhealth serve the Stateline region. As community systems, they provide solid care but lack the specialist depth of Chicago's academic medical centers, 90 minutes southeast.","GLP-1 medications serve Rockford's aerospace machinists, healthcare workers, and the broader Stateline community—delivering metabolic care without the I-90 drive to Chicago."]} citations={["Winnebago County Health Department. (2025). <em>Community Health Assessment</em>.","University of Illinois College of Medicine Rockford. (2024). <em>Post-Industrial Health Outcomes in the Stateline Region</em>."]} />
      <InsuranceBreakdown title="Aerospace Fasteners and the Stateline" text="Rockford's economy centers on precision manufacturing and healthcare." employers={[{name:"Collins Aerospace / Woodward",detail:"Aerospace manufacturers offer union/corporate plans with standard PBM restrictions."},{name:"SwedishAmerican / Mercyhealth",detail:"Regional health systems with 10-14 week specialist waits."},{name:"Fiat Chrysler (Belvidere) / Amazon",detail:"Assembly and logistics add shift-work populations."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Rockford" localCompetitors={[{name:"East Side / Perryville Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"E. State St MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"SwedishAmerican Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-90 to Chicago & Local Waitlists" transitText="Rockford sits on I-90. Chicago is 90 min SE. Madison WI is 60 min NW." hospitalText="<strong>SwedishAmerican</strong> and <strong>Mercyhealth</strong> serve the Stateline." />
      <InteractiveFAQ faqs={[{q:"I work rotating shifts at Collins. When?",a:"Anytime. Fully asynchronous."},{q:"Do you deliver to Belvidere, Loves Park, and Machesney Park?",a:"Yes. All Winnebago, Boone, and Ogle County addresses."}]} />
      <StateLegalFramework stateName="Illinois" boardName="Illinois Division of Professional Regulation" text="Telehealth FX operates in compliance with <strong>IDFPR</strong> and 225 ILCS 60." />
      <DeliveryGridMap cityName="Rockford" mapQuery="Rockford, IL" coordinates="42.2711° N, 89.0940° W" counties="Winnebago County, Boone County" neighborhoods={['East Side','Machesney Park','Loves Park','Belvidere','Roscoe','Rockton','Cherry Valley']} />
      <FinalCTA stateName="Illinois" />
    </div>
  );
}
