"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationBiloxi() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Mississippi" cityName="Biloxi" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Biloxi</span>" subheadline="Biloxi is home to Keesler Air Force Base—the Air Force's Electronics and Cyber Operations training center. Every Air Force combat communications, weather, and cyber operator trains here. The Gulf Coast casinos add a 24/7 hospitality workforce. Both populations share the same specialist shortage." ctaText="Check Mississippi Eligibility" />
      <PatientArchetype archetype="The Keesler AFB Cyber Operations Instructor" quote="I train the Air Force's cyber warfare operators—sitting in a SCIF teaching network exploitation for 10 hours. The base food court is Burger King and Charley's. After work, Biloxi's casino buffets are literally designed to keep people eating. My TRICARE specialist referral is 18 weeks. The nearest academic medical center is UMMC in Jackson—3 hours north. I teach people to hack networks. I can't hack through a specialist waitlist." details="<strong>Patient Profile:</strong> TSgt Chen, 33, Cyber Operations Instructor, Keesler AFB.<br/><br/><strong>The Challenge:</strong> SCIF-based sedentary cyber instruction. Base fast food + casino buffet culture. TRICARE specialist wait 18 weeks. UMMC Jackson 3 hours north.<br/><br/><strong>The Intervention:</strong> Completed intake from off-base apartment in Ocean Springs. MS-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Cyber Warriors and Casino Buffets" paragraphs={["Keesler AFB processes thousands of airmen annually through electronics, communications, weather, and cyber operations training. The permanent party (instructors and support staff) live on the Mississippi Gulf Coast alongside the casino industry workforce. Both populations face the same paradox: sedentary indoor work in a location surrounded by calorie-dense food options.","The Gulf Coast casino industry (Beau Rivage, Hard Rock, IP, Golden Nugget) employs thousands in 24/7 hospitality. The casinos' all-you-can-eat buffet culture is the defining food environment of Biloxi—designed by food psychologists to maximize consumption.","The non-casino food culture is Gulf Coast seafood at its finest: po'boys, fried shrimp, gumbo, and the Vietnamese-Gulf Coast fusion that Biloxi's significant Vietnamese fishing community created. Mary Mahoney's Old French House is a landmark.","Merit Health Biloxi and the Biloxi VA serve the coast. UMMC (Jackson, 3 hours north) is the nearest academic center. Gulf Coast specialist capacity is thin relative to the combined military and casino workforce."]} citations={["Harrison County Health Department. (2025). <em>Community Health Assessment</em>.","University of Southern Mississippi Gulf Park. (2024). <em>Military, Casino, and Seafood Industry Health on the MS Gulf Coast</em>."]} />
      <InsuranceBreakdown title="Keesler, Casinos, and the Gulf" text="Biloxi's economy centers on military, casino gaming, and seafood." employers={[{name:"Keesler AFB (TRICARE)",detail:"Cyber/electronic warfare training base. TRICARE specialist waits 16-20 weeks."},{name:"Casino Industry (MGM/Hard Rock)",detail:"24/7 hospitality plans with minimal specialist networks."},{name:"Merit Health / Biloxi VA",detail:"Gulf Coast health systems with limited specialist depth."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Biloxi" localCompetitors={[{name:"Ocean Springs / D'Iberville Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Pass Rd MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Merit Health Endocrinology",cost:"$100 Copay+Rx",consult:"14-20 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-10 & the Jackson Drive" transitText="Biloxi sits on I-10 and US-90. Mobile AL is 60 min west. New Orleans is 90 min west. Jackson/UMMC is 3 hours north." hospitalText="<strong>Merit Health Biloxi</strong> and <strong>Biloxi VA</strong> serve the Gulf Coast." />
      <InteractiveFAQ faqs={[{q:"I work in a SCIF. Is this secure?",a:"Telehealth FX is completely separate from your military or security clearance records."},{q:"Do you deliver to Ocean Springs, Gulfport, and D'Iberville?",a:"Yes. All Harrison and Jackson County addresses."}]} />
      <StateLegalFramework stateName="Mississippi" boardName="Mississippi State Board of Medical Licensure" text="Telehealth FX operates in compliance with the <strong>MS Board of Medical Licensure</strong>." />
      <DeliveryGridMap cityName="Biloxi" mapQuery="Biloxi, MS" coordinates="30.3960° N, 88.8853° W" counties="Harrison County, Jackson County" neighborhoods={['Ocean Springs','Gulfport','D Iberville','Long Beach','Pass Christian','Gautier','Moss Point']} />
      <FinalCTA stateName="Mississippi" />
    </div>
  );
}
