"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationRapidCity() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="South Dakota" cityName="Rapid City" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Rapid City</span>" subheadline="Rapid City is the gateway to the Black Hills, Mount Rushmore, and Ellsworth Air Force Base—home of the B-1B Lancer. The city serves as the medical hub for western South Dakota, the Pine Ridge Reservation, and a geographic area larger than many eastern states." ctaText="Check South Dakota Eligibility" />
      <PatientArchetype archetype="The Ellsworth AFB B-1B Crew Chief" quote="I maintain the B-1B Lancer on the Ellsworth flight line. South Dakota winters mean I'm working on bombers at -20°F with wind chill. After shift, I eat at the BX food court or drive into Rapid City for something hot. My TRICARE specialist referral is 20 weeks. The nearest alternative medical center is Sioux Falls—5 hours east across nothing but grassland." details="<strong>Patient Profile:</strong> TSgt Miller, 34, B-1B Crew Chief, Ellsworth AFB.<br/><br/><strong>The Challenge:</strong> Flight line maintenance in -20°F. BX food court diet. TRICARE specialist wait 20 weeks. Sioux Falls (nearest alternative) is 5 hours east.<br/><br/><strong>The Intervention:</strong> Completed intake from base housing at Box Elder. SD-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Mount Rushmore's Medical Desert" paragraphs={["Rapid City serves as the medical capital of western South Dakota—a geographic territory of approximately 40,000 square miles. Monument Health (formerly Regional Health) is the only hospital system, serving Rapid City alongside Pine Ridge, Sturgis, Deadwood, and everything west of the Missouri River.","Ellsworth AFB adds the B-1B maintenance and operations community. The flight line culture involves extreme cold exposure (Black Hills winters), high-calorie recovery eating, and the same military food environment challenges seen at Dyess AFB.","The food culture is Black Hills frontier: buffalo burgers, Indian tacos (fry bread with toppings—a Pine Ridge cultural staple), steak from ranching heritage, and the Sturgis Rally week that brings 500,000 motorcyclists and their appetites annually.","GLP-1 medications serve Ellsworth's maintenance crews, Monument Health's own staff, and the western South Dakota community—delivering metabolic care across a territory where the next hospital is 5 hours away."]} citations={["Rapid City Health Department. (2025). <em>Community Health Assessment</em>.","South Dakota State University. (2024). <em>Healthcare Access in Western South Dakota</em>."]} />
      <InsuranceBreakdown title="Ellsworth, the Black Hills, and Pine Ridge" text="Rapid City's economy centers on military, tourism, and healthcare." employers={[{name:"Ellsworth AFB (TRICARE)",detail:"B-1B base. TRICARE specialist waits 18-22 weeks."},{name:"Monument Health",detail:"The only hospital system for 40,000 square miles of western SD."},{name:"Tourism / Sturgis Rally",detail:"Seasonal workforce with limited plan coverage."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Rapid City" localCompetitors={[{name:"West Rapid / Black Hawk Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Mt Rushmore Rd MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Monument Health Endocrinology",cost:"$100 Copay+Rx",consult:"16-22 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="One Hospital for 40,000 Square Miles" transitText="Rapid City sits on I-90. Sioux Falls is 5 hours east. Denver is 6 hours south. Billings is 5 hours NW." hospitalText="<strong>Monument Health</strong> is the sole system for western South Dakota." />
      <InteractiveFAQ faqs={[{q:"I'm at Ellsworth. Will this affect my flight line duties?",a:"GLP-1 medications do not affect duty status. Telehealth FX is independent of military records."},{q:"Do you deliver to Box Elder, Sturgis, and Spearfish?",a:"Yes. All Pennington, Meade, and Lawrence County addresses."}]} />
      <StateLegalFramework stateName="South Dakota" boardName="South Dakota Board of Medical and Osteopathic Examiners" text="Telehealth FX operates in compliance with the <strong>SD Board of Medical and Osteopathic Examiners</strong>." />
      <DeliveryGridMap cityName="Rapid City" mapQuery="Rapid City, SD" coordinates="44.0805° N, 103.2310° W" counties="Pennington County, Meade County, Lawrence County" neighborhoods={['West Rapid','Box Elder','Black Hawk','Sturgis','Spearfish','Deadwood','Custer','Hot Springs']} />
      <FinalCTA stateName="South Dakota" />
    </div>
  );
}
