"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationTopeka() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Kansas" cityName="Topeka" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Topeka</span>" subheadline="Topeka is the Kansas capital and home to the Colmery-O'Neil VA Medical Center—the largest VA in the state. State government, the VA workforce, and the Goodyear tire plant define a city where the food culture is Kansas comfort and the specialist system was built for a smaller population." ctaText="Check Kansas Eligibility" />
      <PatientArchetype archetype="The Colmery-O'Neil VA Psychiatric Nurse" quote="I treat veterans with PTSD, TBI, and substance abuse at the Topeka VA. My patients are fighting demons. I absorb their trauma daily. The antidepressants my own doctor prescribed added 40 pounds. My state employee plan has a 14-week wait for endocrinology at Stormont Vail. I care for veterans who gave everything. I can't get care for myself." details="<strong>Patient Profile:</strong> Karen, 42, RN at Colmery-O'Neil VA Medical Center.<br/><br/><strong>The Challenge:</strong> Secondary trauma from psychiatric nursing. Antidepressant-induced weight gain. State plan specialist wait 14 weeks at Stormont Vail.<br/><br/><strong>The Intervention:</strong> Completed intake from home in SW Topeka. KS-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Capital, the VA, and Kansas Comfort" paragraphs={["Topeka's identity centers on state government and veterans' care. The Kansas State Capitol, combined with dozens of state agencies, creates the largest employer class. Colmery-O'Neil VA—Kansas' largest VA facility—adds a federal healthcare workforce that faces the same specialist access challenges as their patients.","The food culture is Kansas heartland: BBQ (Topeka sits in the KC BBQ spillover zone), chicken-fried steak, Porubsky's chili (a North Topeka institution), and the meat-and-potato default that defines Midwestern state capital dining.","Stormont Vail Health is the primary system, supplemented by The University of Kansas Health System St. Francis. Together they serve NE Kansas with solid community care but limited specialist depth compared to KU Medical Center in Kansas City (60 min east).","GLP-1 medications serve Topeka's VA nurses, state workers, and Goodyear plant employees—delivering metabolic care without the I-70 drive to Kansas City."]} citations={["Shawnee County Health Department. (2025). <em>Community Health Assessment</em>.","KU School of Medicine-Wichita. (2024). <em>Healthcare Access in Northeast Kansas</em>."]} />
      <InsuranceBreakdown title="State Government, VA, and Goodyear" text="Topeka's economy centers on government, veterans' healthcare, and manufacturing." employers={[{name:"State of Kansas",detail:"State employee plans require Step Therapy and behavioral modification."},{name:"Colmery-O'Neil VA (FEHB)",detail:"Federal employee plans face the same limited local specialist network."},{name:"Goodyear / Mars (Topeka)",detail:"Manufacturing plans with standard PBM restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Topeka" localCompetitors={[{name:"SW Topeka / Washburn Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Wanamaker Rd MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Stormont Vail Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-70 & Stormont Vail Waitlists" transitText="Topeka sits on I-70. Kansas City is 60 min east. Wichita is 2.5 hours SW. Manhattan/K-State is 60 min west." hospitalText="<strong>Stormont Vail</strong> and <strong>KU Health St. Francis</strong> serve NE Kansas." />
      <InteractiveFAQ faqs={[{q:"I work at the VA. Is this separate from FEHB?",a:"Yes. Completely independent of your federal benefits."},{q:"Do you deliver to Lawrence and Manhattan?",a:"Yes. All Shawnee, Douglas, and Riley County addresses."}]} />
      <StateLegalFramework stateName="Kansas" boardName="Kansas Board of Healing Arts" text="Telehealth FX operates in compliance with the <strong>Kansas Board of Healing Arts</strong> and K.S.A. § 65-28." />
      <DeliveryGridMap cityName="Topeka" mapQuery="Topeka, KS" coordinates="39.0473° N, 95.6752° W" counties="Shawnee County, Douglas County" neighborhoods={['SW Topeka','North Topeka','Silver Lake','Lawrence','Manhattan','Auburn','Tecumseh']} />
      <FinalCTA stateName="Kansas" />
    </div>
  );
}
