"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSyracuse() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="New York" cityName="Syracuse" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Syracuse</span>" subheadline="Syracuse receives more snow than any major city in America—an average of 127 inches per year. The lake-effect machine from Lake Ontario buries the city from November through April, eliminating outdoor activity for half the year. Add the salt potato tradition, the Dinosaur Bar-B-Que, and the Micron chip fab coming to Clay—Syracuse is at a metabolic inflection point." ctaText="Check New York Eligibility" />
      <PatientArchetype archetype="The Lockheed Martin Syracuse Radar Systems Engineer" quote="I design radar systems for the F-35 at Lockheed Martin's Syracuse campus. My work is classified, desk-bound, and intense. Syracuse gets 127 inches of snow a year. I haven't been outside for exercise since October. My Excellus plan has a 12-week wait for endocrinology at Upstate Medical. Micron is about to add 50,000 jobs. The wait is only going to get longer." details="<strong>Patient Profile:</strong> Scott, 42, Radar Systems Engineer at Lockheed Martin, Syracuse.<br/><br/><strong>The Challenge:</strong> Classified desk work at Lockheed. 127 inches of annual snow eliminates outdoor exercise. Specialist waits at Upstate Medical 12 weeks—and about to worsen as Micron's fab brings 50,000 jobs.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Manlius. NY-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="127 Inches of Snow and 50,000 New Jobs" paragraphs={["Syracuse's snowfall is legendary—127 inches annually, the most of any major US city. Lake-effect bands from Lake Ontario can dump 3 feet in a single event. The practical effect is that outdoor exercise is eliminated for approximately 6 months of the year, and the SAD/carbohydrate craving cycle is among the most severe in the country.","Micron Technology's planned $100 billion chip fabrication complex in Clay (north of Syracuse) will be the largest private investment in New York State history. It will bring an estimated 50,000 jobs—and their families—to a metro whose healthcare infrastructure was designed for a population that has been declining for 50 years. The specialist shortage that already exists is about to become a crisis.","Syracuse's food traditions are distinctive: salt potatoes (boiled in heavily salted water, served with melted butter—a Central NY original), Dinosaur Bar-B-Que, the Utica greens and chicken riggies from nearby Utica, and the garbage plate variant that migrated from Rochester.","GLP-1 medications serve Syracuse's defense workforce, university community, and the coming Micron population—delivering metabolic care before the specialist shortage reaches critical levels."]} citations={["Onondaga County Health Department. (2025). <em>Community Health Assessment</em>.","SUNY Upstate Medical University. (2024). <em>Micron Investment, Population Growth, and Healthcare Capacity Planning for Central New York</em>."]} />
      <InsuranceBreakdown title="Defense, Micron, and the Snow Belt" text="Syracuse's economy is transforming with Micron's arrival." employers={[{name:"Lockheed Martin Syracuse",detail:"Defense plans with standard PBM restrictions. Classified work environments are sedentary."},{name:"Micron (Coming 2025-2030)",detail:"50,000 new jobs will overwhelm current specialist capacity."},{name:"Upstate Medical / Crouse / St. Joseph's",detail:"Health systems face growing demand they cannot scale fast enough."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Syracuse" localCompetitors={[{name:"DeWitt / Fayetteville Concierge",cost:"$600-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Erie Blvd MedSpas",cost:"$350-$550/mo",consult:"Monthly",access:"Variable"},{name:"Upstate Endocrinology",cost:"$125 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-81/I-90 & Upstate Waitlists" transitText="Syracuse sits at I-81 and I-90 (NYS Thruway). Lake-effect snow events can close roads entirely." hospitalText="<strong>Upstate University Hospital</strong>, <strong>Crouse</strong>, and <strong>St. Joseph's</strong> serve CNY." />
      <InteractiveFAQ faqs={[{q:"Will Micron's arrival make the specialist shortage worse?",a:"Yes. Telehealth FX provides access now—before 50,000 new residents compete for the same specialist appointments."},{q:"Do you deliver to Manlius, Baldwinsville, and Utica?",a:"Yes. All Onondaga, Madison, and Oneida County addresses."}]} />
      <StateLegalFramework stateName="New York" boardName="New York State Education Department" text="Telehealth FX operates in compliance with <strong>NYSED Office of the Professions</strong> and NY Education Law § 6524-a." />
      <DeliveryGridMap cityName="Syracuse" mapQuery="Syracuse, NY" coordinates="43.0481° N, 76.1474° W" counties="Onondaga County, Madison County, Oneida County" neighborhoods={['DeWitt','Manlius','Liverpool','Baldwinsville','Clay','Camillus','Fayetteville','Utica']} />
      <FinalCTA stateName="New York" />
    </div>
  );
}
