"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationRochester() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="New York" cityName="Rochester" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Rochester</span>" subheadline="Rochester built Kodak, Xerox, and Bausch + Lomb. The companies that invented photography, modern printing, and contact lenses created a middle-class workforce that no longer exists—but the food culture and healthcare patterns it left behind persist. The Garbage Plate is not a joke. It's a 2,000-calorie Rochester institution." ctaText="Check New York Eligibility" />
      <PatientArchetype archetype="The Rochester Regional Health Night Shift RN" quote="I work nights in the ER at Rochester General. I treat metabolic emergencies—DKA, hyperglycemic crises, heart failure exacerbations—all night. My own metabolic health has deteriorated over 8 years of night shifts. My employer plan requires a daytime wellness program. I sleep during the day. That's not a scheduling conflict—it's a structural impossibility." details="<strong>Patient Profile:</strong> Tanya, 34, ER Night Shift RN at Rochester General Hospital.<br/><br/><strong>The Challenge:</strong> Night shift ER nursing + daytime wellness program requirement = structural impossibility. She treats the metabolic consequences of Rochester's food culture professionally while experiencing them personally.<br/><br/><strong>The Intervention:</strong> Completed intake at 8 AM after a shift. NY-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Garbage Plates, Kodak Ghosts, and Lake-Effect Snow" paragraphs={["Rochester's signature dish is the Garbage Plate—a combination of hamburger patties (or hot dogs), macaroni salad, home fries, baked beans, onions, and hot sauce, all piled on a single plate. It averages 2,000 calories per serving. Nick Tahou's invented it, and dozens of restaurants serve their own versions. It is consumed not as an occasional indulgence but as a weekly default for a significant portion of the population.","The Rust Belt economic transition has left deep marks. Kodak employed 60,000+ Rochesterians at its peak. Today that number is under 5,000. Xerox has similarly contracted. The middle-class food culture these companies supported—hearty, calorie-dense, built for manufacturing workers—persists in a city that is now predominantly service-economy and healthcare.","Lake-effect snow from Lake Ontario (100+ inches annually in the eastern suburbs) eliminates outdoor activity for 5-6 months. The SAD-carbohydrate craving cycle mirrors Buffalo and Cleveland.","GLP-1 medications serve Rochester's post-industrial workforce—healthcare workers, university staff, and the remaining manufacturing employees—without requiring them to navigate weather, waitlists, or wellness program scheduling conflicts."]} citations={["Monroe County Department of Public Health. (2025). <em>Community Health Assessment</em>.","University of Rochester Medical Center. (2024). <em>Shift Work, Food Culture, and Metabolic Health in Western New York</em>."]} />
      <InsuranceBreakdown title="Post-Kodak Economy" text="Rochester's economy has shifted from manufacturing to healthcare and education." employers={[{name:"Rochester Regional / URMC",detail:"Healthcare systems are Rochester's largest employers. Plans require wellness programs that conflict with clinical shift schedules."},{name:"University of Rochester / RIT",detail:"Education employers offer standard PBM restrictions."},{name:"Kodak / Xerox (Remaining)",detail:"Legacy employer plans apply standard formulary management."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in Rochester" localCompetitors={[{name:"Park Ave / Pittsford Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Monroe Ave MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"URMC Endocrinology",cost:"$125 Copay+Rx",consult:"10-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass the Lake-Effect & URMC Waitlists" transitText="Rochester's geography along Lake Ontario and the Genesee River creates a compact but weather-challenged metro. Lake-effect events can shut down east-side suburbs entirely." hospitalText="<strong>URMC (Strong Memorial)</strong> and <strong>Rochester Regional Health</strong> serve the region. Specialist waits average 10-16 weeks." />
      <InteractiveFAQ faqs={[{q:"I work night shifts. When do I do the intake?",a:"Anytime. Fully asynchronous—complete it after your shift, before sleep, or on a day off."},{q:"Do you deliver to Pittsford, Victor, and Greece?",a:"Yes. All Monroe, Ontario, and Wayne County addresses."}]} />
      <StateLegalFramework stateName="New York" boardName="New York State Education Department" text="Telehealth FX operates in compliance with <strong>NYSED Office of the Professions</strong> and NY Education Law § 6524-a." />
      <DeliveryGridMap cityName="Rochester" mapQuery="Rochester, NY" coordinates="43.1566° N, 77.6088° W" counties="Monroe County, Ontario County, Wayne County" neighborhoods={['Park Avenue','South Wedge','Pittsford','Victor','Greece','Webster','Fairport','Henrietta']} />
      <FinalCTA stateName="New York" />
    </div>
  );
}
