"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationColumbia() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="South Carolina" cityName="Columbia" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Columbia</span>" subheadline="Columbia is South Carolina's capital and home to Fort Jackson—the US Army's largest basic training installation. Every year, 50,000 soldiers pass through Fort Jackson. The permanent party, their families, and the state government workforce all compete for specialist appointments in a mid-size Southern capital." ctaText="Check South Carolina Eligibility" />
      <PatientArchetype archetype="The Fort Jackson Drill Sergeant" quote="I train 50,000 recruits a year to Army physical standards. The irony is that my own metabolic health has declined over 6 years of drill sergeant duty—the stress, the 4 AM wake-ups, the DFAC meals, and zero time for my own fitness outside of PT formations. My TRICARE specialist referral is 16 weeks. I get soldiers fit for a living. I can't get myself fit." details="<strong>Patient Profile:</strong> SFC Martinez, 35, Senior Drill Sergeant at Fort Jackson.<br/><br/><strong>The Challenge:</strong> Extreme cortisol from training 50,000 recruits annually. DFAC diet. No personal fitness time. TRICARE specialist wait 16 weeks. He gets soldiers combat-ready but can't access metabolic care himself.<br/><br/><strong>The Intervention:</strong> Completed intake from on-post housing. SC-licensed physician prescribed compounded Tirzepatide within 20 hours." />
      <ClinicalDeepDive title="Basic Training Capital and the State Capitol" paragraphs={["Fort Jackson processes more initial entry trainees than any Army installation in the country—50,000+ soldiers per year. The permanent party (drill sergeants, cadre, support staff) and their families live in Columbia alongside the state government workforce and USC students. The combined healthcare demand overwhelms Moncrief Army Health Clinic and overflows into the civilian system.","The food culture is South Carolina comfort: BBQ (mustard-based, the Midlands tradition), fried chicken, shrimp and grits (in the Lowcountry migration), and the meat-and-three tradition that dominates lunch for state workers. Lizard's Thicket—a local chain—serves the prototypical Columbia lunch: fried pork chops, mac and cheese, and sweet tea.","Prisma Health (formerly Palmetto Health) is the dominant system, supplemented by Lexington Medical Center. Together they serve the Midlands alongside the Fort Jackson overflow. Specialist capacity is strained but adequate for a population not facing rapid growth like Charleston.","GLP-1 medications serve Columbia's drill sergeants, state workers, and USC community—the people who train America's soldiers and govern South Carolina but can't access metabolic care themselves."]} citations={["Richland County Health Department. (2025). <em>Community Health Assessment</em>.","USC School of Medicine. (2024). <em>Military Population, State Government, and Healthcare Access in the SC Midlands</em>."]} />
      <InsuranceBreakdown title="Fort Jackson, State Capitol, and USC" text="Columbia's economy centers on military, state government, and education." employers={[{name:"Fort Jackson (TRICARE)",detail:"Army's largest training installation. TRICARE specialist referrals 14-18 weeks."},{name:"State of South Carolina",detail:"State plans require Step Therapy and behavioral modification."},{name:"Prisma Health / Lexington Medical",detail:"Midlands health systems serve military, state, and civilian populations."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Columbia" localCompetitors={[{name:"Forest Acres / Irmo Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Two Notch Rd MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Prisma Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-26/I-77 & Prisma Waitlists" transitText="Columbia sits at I-26, I-77, and I-20. Fort Jackson's gates create additional traffic bottlenecks." hospitalText="<strong>Prisma Health Richland</strong> and <strong>Lexington Medical Center</strong> serve the Midlands." />
      <InteractiveFAQ faqs={[{q:"I'm active duty at Fort Jackson. Will this show up?",a:"Telehealth FX is independent of TRICARE and your military records."},{q:"Do you deliver to Lexington, Irmo, and Elgin?",a:"Yes. All Richland and Lexington County addresses."}]} />
      <StateLegalFramework stateName="South Carolina" boardName="South Carolina Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>SC Board of Medical Examiners</strong> and SC Code § 40-47." />
      <DeliveryGridMap cityName="Columbia" mapQuery="Columbia, SC" coordinates="34.0007° N, 81.0348° W" counties="Richland County, Lexington County" neighborhoods={['Forest Acres','Shandon','Irmo','Lexington','Elgin','Blythewood','Cayce','West Columbia']} />
      <FinalCTA stateName="South Carolina" />
    </div>
  );
}
