"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationFlint() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Michigan" cityName="Flint" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Flint</span>" subheadline="Flint made international headlines for the water crisis. What didn't make headlines: Genesee County's adult obesity rate exceeds 38%. The city that General Motors built—and largely abandoned—faces a healthcare infrastructure deficit that mirrors the infrastructure failure the world already saw." ctaText="Check Michigan Eligibility" />
      <PatientArchetype archetype="The Flint Water Crisis Community Health Worker" quote="I've been doing lead-level testing and health assessments for Flint residents since 2016. I counsel families about nutrition while they're still afraid to drink the water. I visit homes where the only grocery option is a corner store with zero fresh produce. My Hurley plan has a 16-week wait for endocrinology. I advocate for health equity. I can't access equitable healthcare myself." details="<strong>Patient Profile:</strong> Denise, 39, Community Health Worker, Genesee County Health Dept.<br/><br/><strong>The Challenge:</strong> Decade of water crisis response work. Counsels families on nutrition in food deserts. Her own Hurley plan has 16-week specialist wait. Advocates for health equity she can't access.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Burton. MI-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="After the Water Crisis, the Metabolic Crisis" paragraphs={["Flint's water crisis (2014-2019) exposed what residents already knew: the infrastructure serving Flint was failing long before the lead contamination. The healthcare infrastructure follows the same pattern. GM's departure hollowed out the tax base, population declined from 200,000 to under 100,000, and the health systems that remain serve a community with elevated poverty, food desert geography, and chronic disease rates far above state averages.","The food culture reflects post-industrial Michigan: coney dogs (Flint-style with dry coney sauce—distinct from Detroit-style), pasties (Upper Peninsula heritage), and the fast food dependency that food deserts create. Angelo's Coney Island is a Flint institution, but the reality for most residents is corner store food.","Hurley Medical Center and McLaren Flint are the primary hospitals. Both serve Genesee County with community-level care, but specialist capacity reflects the population decline—designed for a larger city that no longer exists. U of M (Ann Arbor) is 60 minutes south for complex cases.","GLP-1 medications serve Flint's healthcare workers, remaining manufacturing workforce, and a community that has been failed by infrastructure at every level—delivering metabolic care without another systemic barrier."]} citations={["Genesee County Health Department. (2025). <em>Community Health Assessment</em>.","Michigan State University College of Human Medicine-Flint. (2024). <em>Post-Crisis Health Outcomes in Genesee County</em>."]} />
      <InsuranceBreakdown title="Post-Industrial, Post-Crisis" text="Flint's economy centers on healthcare, education, and remaining manufacturing." employers={[{name:"Hurley Medical / McLaren Flint",detail:"Health systems are both employer and specialist source. 14-18 week waits."},{name:"General Motors (Flint Assembly)",detail:"Remaining GM workers have UAW plans with Step Therapy requirements."},{name:"Kettering University / Mott CC",detail:"Education employers add standard plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Flint" localCompetitors={[{name:"Grand Blanc / Fenton Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Miller Rd MedSpas",cost:"$250-$400/mo",consult:"Monthly",access:"Variable"},{name:"Hurley Endocrinology",cost:"$80 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-69/I-75 & Hurley Waitlists" transitText="Flint sits on I-69 and I-75. Detroit is 70 min south. Ann Arbor/U of M is 60 min SW." hospitalText="<strong>Hurley Medical</strong> and <strong>McLaren Flint</strong> serve Genesee County." />
      <InteractiveFAQ faqs={[{q:"Is the water safe for mixing medication?",a:"GLP-1 medications are injectable, not mixed with water. No water interaction."},{q:"Do you deliver to Grand Blanc, Burton, and Fenton?",a:"Yes. All Genesee County addresses."}]} />
      <StateLegalFramework stateName="Michigan" boardName="Michigan Board of Medicine" text="Telehealth FX operates in compliance with the <strong>MI Board of Medicine</strong> and MCL § 333.16284." />
      <DeliveryGridMap cityName="Flint" mapQuery="Flint, MI" coordinates="43.0125° N, 83.6875° W" counties="Genesee County" neighborhoods={['Grand Blanc','Burton','Fenton','Davison','Flushing','Swartz Creek','Mt. Morris','Clio']} />
      <FinalCTA stateName="Michigan" />
    </div>
  );
}
