"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationPueblo() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Colorado" cityName="Pueblo" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Pueblo</span>" subheadline="Pueblo is Colorado's Steel City—a Southern Colorado industrial hub that shares more with the Rust Belt than with Denver or Boulder. The EVRAZ Rocky Mountain Steel mill still operates, but the workforce has shrunk. The city's food culture is defined by the Pueblo chile—and the specialist gap is defined by the 110-mile drive to Denver." ctaText="Check Colorado Eligibility" />
      <PatientArchetype archetype="The EVRAZ Steel Mill Roll Operator" quote="I run the rolling mill at EVRAZ—we make railroad rail. Twelve-hour shifts in 130-degree heat near the rollers, then I go home and eat Pueblo green chile smothered everything. My steel mill plan has a 16-week specialist wait at Parkview. Denver is 2 hours north on I-25 but I'm working 60-hour weeks. Pueblo isn't Denver. We don't have Denver's options." details="<strong>Patient Profile:</strong> Carlos, 44, Roll Operator, EVRAZ Rocky Mountain Steel.<br/><br/><strong>The Challenge:</strong> 12-hour shifts in extreme industrial heat. Pueblo chile cuisine. Steel mill plan specialist wait 16 weeks. Denver 2 hours north but inaccessible during 60-hour work weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Belmont. CO-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Steel City South of Denver" paragraphs={["Pueblo is Colorado's industrial exception. While Denver and Boulder became tech and outdoor-lifestyle hubs, Pueblo retained its steel heritage. EVRAZ Rocky Mountain Steel (formerly CF&I) still produces railroad rail and structural steel. The Bessemer neighborhood was literally built around the mill.","The food culture centers on the Pueblo chile—a Mirasol variety roasted at hundreds of stands every September during the Chile & Frijoles Festival. The chile appears on everything: smothered burritos, chile rellenos, green chile cheeseburgers, and the slopper (an open-faced burger drowned in green chile). This is not health food.","Parkview Medical Center is the primary hospital, supplemented by St. Mary-Corwin. Together they serve Pueblo County and the upper Arkansas Valley, but specialist capacity is thin compared to Denver's UCHealth and National Jewish systems 110 miles north.","GLP-1 medications serve Pueblo's steel workers, the Colorado State University-Pueblo community, and Southern Colorado—delivering metabolic care without the I-25 drive to Denver."]} citations={["Pueblo City-County Health Department. (2025). <em>Community Health Assessment</em>.","CSU-Pueblo. (2024). <em>Industrial Workforce Health in Southern Colorado</em>."]} />
      <InsuranceBreakdown title="Steel, Chiles, and the Denver Gap" text="Pueblo's economy centers on steel, healthcare, and agriculture." employers={[{name:"EVRAZ Rocky Mountain Steel",detail:"Steel mill plans with union Step Therapy. 14-18 week specialist waits."},{name:"Parkview Medical / St. Mary-Corwin",detail:"Regional systems serve Southern Colorado with limited specialist depth."},{name:"CSU-Pueblo / School District 60",detail:"Education and public sector plans add volume."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Pueblo" localCompetitors={[{name:"Northside / Pueblo West Concierge",cost:"$500-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"N. Elizabeth St MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Parkview Endocrinology",cost:"$100 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-25 & the Denver Drive" transitText="Pueblo sits on I-25. Denver is 2 hours north. Colorado Springs is 45 min north. Trinidad is 80 min south." hospitalText="<strong>Parkview Medical</strong> and <strong>St. Mary-Corwin</strong> serve Southern Colorado." />
      <InteractiveFAQ faqs={[{q:"I work rotating shifts at the mill. When?",a:"Anytime. Fully asynchronous—complete between shifts."},{q:"Do you deliver to Pueblo West and Cañon City?",a:"Yes. All Pueblo and Fremont County addresses."}]} />
      <StateLegalFramework stateName="Colorado" boardName="Colorado Medical Board" text="Telehealth FX operates in compliance with the <strong>Colorado Medical Board</strong>." />
      <DeliveryGridMap cityName="Pueblo" mapQuery="Pueblo, CO" coordinates="38.2544° N, 104.6091° W" counties="Pueblo County, Fremont County" neighborhoods={['Northside','Belmont','Pueblo West','Cañon City','Bessemer','South Side','Mesa Junction']} />
      <FinalCTA stateName="Colorado" />
    </div>
  );
}
