"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationAbilene() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Texas" cityName="Abilene" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Abilene</span>" subheadline="Abilene is home to Dyess Air Force Base—the sole stateside wing of the B-1B Lancer strategic bomber. The aircrews who carry out America's long-range strike missions and their families depend on a healthcare system 150 miles from the nearest major city in any direction." ctaText="Check Texas Eligibility" />
      <PatientArchetype archetype="The Dyess AFB B-1B Weapons Systems Officer" quote="I'm a WSO on the B-1B Lancer—we carry out strategic bomber missions. The flight profile is high-stress, high-G, and the post-mission debrief culture involves food. The base DFAC is standard. Abilene's restaurant scene is Texas BBQ and chicken-fried steak. My TRICARE specialist referral is 18 weeks. Dallas is 2.5 hours east. Lubbock is 2 hours north. There's nothing closer." details="<strong>Patient Profile:</strong> Capt. Morrison, 31, B-1B Weapons Systems Officer, Dyess AFB.<br/><br/><strong>The Challenge:</strong> High-stress strategic bomber missions. Post-mission eating culture. Abilene is 150 mi from any major city. TRICARE specialist wait 18 weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from off-base housing. TX-licensed physician prescribed compounded Tirzepatide within 24 hours." />
      <ClinicalDeepDive title="The Bone and the West Texas Desert" paragraphs={["Dyess AFB is the sole stateside B-1B Lancer base—making Abilene the home of America's variable-sweep wing strategic bomber capability. The 7th Bomb Wing and its support infrastructure employ thousands. The aircrews train for long-duration missions, the maintenance crews work flight-line shifts in West Texas heat, and both populations face the same healthcare access challenge: Abilene is isolated.","The food culture is West Texas: chicken-fried steak (the regional signature), BBQ (mesquite-smoked brisket), Tex-Mex, and the meat-heavy ranching heritage. Joe Allen's BBQ and Perini Ranch Steakhouse (Buffalo Gap, 15 min south) define the culinary environment.","Hendrick Health and Abilene Regional Medical Center serve the Big Country region. As the referral hub for a vast West Texas territory, specialist capacity is stretched thin—especially endocrinology, which must serve Abilene, the military, and a multi-county rural catchment.","GLP-1 medications serve the B-1B community, Abilene's three universities (ACU, HSU, McMurry), and the Big Country workforce—eliminating the 150-mile drive to Dallas or Lubbock for metabolic care."]} citations={["Taylor County Health Department. (2025). <em>Community Health Assessment</em>.","Abilene Christian University. (2024). <em>Healthcare Access in the Big Country</em>."]} />
      <InsuranceBreakdown title="Dyess AFB and the Big Country" text="Abilene's economy centers on military, education, and ranching." employers={[{name:"Dyess AFB / 7th Bomb Wing (TRICARE)",detail:"B-1B crews and families. TRICARE specialist waits 16-20 weeks."},{name:"Hendrick Health / Abilene Regional",detail:"Regional systems serve a vast West Texas catchment."},{name:"ACU / HSU / McMurry",detail:"Three university employers add standard plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Abilene" localCompetitors={[{name:"SW Abilene / Buffalo Gap Concierge",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"S. 14th St MedSpas",cost:"$250-$400/mo",consult:"Monthly",access:"Variable"},{name:"Hendrick Endocrinology",cost:"$100 Copay+Rx",consult:"14-20 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="150 Miles from Anywhere" transitText="Abilene sits on I-20. Dallas is 2.5 hours east. Lubbock is 2 hours north. San Angelo is 90 min south." hospitalText="<strong>Hendrick Health</strong> and <strong>Abilene Regional</strong> serve the Big Country." />
      <InteractiveFAQ faqs={[{q:"Will this affect my flight status?",a:"Consult your flight surgeon. Telehealth FX is independent of military medical records."},{q:"Do you deliver to Dyess AFB and Buffalo Gap?",a:"Yes. All Taylor and Jones County addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong>." />
      <DeliveryGridMap cityName="Abilene" mapQuery="Abilene, TX" coordinates="32.4487° N, 99.7331° W" counties="Taylor County, Jones County" neighborhoods={['SW Abilene','Wylie','Buffalo Gap','Tye','Merkel','Clyde','Tuscola']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
