"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationMidland() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Texas" cityName="Midland" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Midland</span>" subheadline="Midland is the headquarters of the Permian Basin—the most productive oil field in the world. The city's economy has boomed and busted with crude for a century. During boom cycles, the population surges but the healthcare system doesn't expand. During busts, nobody invests in medical infrastructure. The result: a wealthy city with a healthcare access deficit." ctaText="Check Texas Eligibility" />
      <PatientArchetype archetype="The Pioneer Natural Resources Completions Engineer" quote="I design hydraulic fracturing treatments for Pioneer—optimizing proppant placement in horizontal laterals. I sit at a desk with reservoir simulation software for 12 hours, then eat at Rosa's Cafe or Whataburger because nothing else is open. Midland has the highest per-capita income in Texas and one of the lowest specialist-per-capita ratios. My Pioneer plan has an 18-week specialist wait at Midland Memorial. Lubbock is 2 hours NE. I earn six figures and can't get an endocrinology appointment." details="<strong>Patient Profile:</strong> Blake, 32, Completions Engineer, Pioneer Natural Resources.<br/><br/><strong>The Challenge:</strong> Sedentary desk work designing frac jobs. Fast food culture in a boom town. Highest income in TX, lowest specialist access. 18-week wait. Lubbock 2 hours away.<br/><br/><strong>The Intervention:</strong> Completed intake from apartment in NW Midland. TX-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="The Richest City with the Worst Wait" paragraphs={["The Permian Basin produces more oil than most OPEC nations. Midland-Odessa is the command center—housing the corporate offices of Diamondback Energy, Pioneer (now ExxonMobil), Concho (now ConocoPhillips), and dozens of operators. The white-collar oil workforce (engineers, geologists, landmen) earns six figures but lives in a city where the nearest major medical center is 2+ hours away.","The food culture is West Texas boom-town: Rosa's Cafe (tortillas), Whataburger, BBQ, and the steak-and-potato culture that defines Midland's corporate dining. Fast-casual chains dominate because the population surges too fast for independent restaurants to keep up.","Midland Memorial Hospital and Medical Center Hospital (Odessa) serve the Permian Basin. Neither has the specialist depth of a comparably-wealthy metro. The boom-bust cycle means hospitals can't plan long-term infrastructure investment.","GLP-1 medications serve the Permian Basin's engineers, rig workers, and support community—delivering metabolic care to the wealthiest metro in Texas that can't attract enough specialists."]} citations={["Midland County Health Department. (2025). <em>Community Health Assessment</em>.","UTPB. (2024). <em>Healthcare Access and Economic Boom Cycles in the Permian Basin</em>."]} />
      <InsuranceBreakdown title="The Permian Basin Paradox" text="Midland's economy is overwhelmingly oil and gas." employers={[{name:"Pioneer / Diamondback / ExxonMobil",detail:"Operator plans are generous but the local specialist network is nonexistent."},{name:"Midland Memorial / Medical Center (Odessa)",detail:"Two hospitals for a boom-bust metro with surging population."},{name:"Halliburton / Schlumberger (Service Cos)",detail:"Oilfield service companies with standard PBM restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Midland" localCompetitors={[{name:"NW Midland / Grassland Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Wadley / Loop 250 MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"Midland Memorial Endocrinology",cost:"$100 Copay+Rx",consult:"16-22 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="The Permian Basin's Medical Desert" transitText="Midland sits on I-20. Lubbock is 2 hours NE. San Angelo is 2 hours SE. Dallas is 5 hours east." hospitalText="<strong>Midland Memorial</strong> and <strong>Medical Center Hospital (Odessa)</strong> serve the Permian Basin." />
      <InteractiveFAQ faqs={[{q:"I earn six figures. Why can't I get a specialist?",a:"Income ≠ access. Midland's specialist-per-capita ratio is among the lowest in Texas. We bypass the local shortage entirely."},{q:"Do you deliver to Odessa, Andrews, and Big Spring?",a:"Yes. All Midland, Ector, Andrews, and Howard County addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong>." />
      <DeliveryGridMap cityName="Midland" mapQuery="Midland, TX" coordinates="31.9973° N, 102.0779° W" counties="Midland County, Ector County, Andrews County" neighborhoods={['NW Midland','Odessa','Andrews','Big Spring','Stanton','Greenwood','Gardendale']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
