"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSpringfield() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Missouri" cityName="Springfield" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Springfield, MO</span>" subheadline="Springfield is the birthplace of Route 66 and the headquarters of Bass Pro Shops—the outdoor recreation retailer whose flagship store is literally a wilderness lodge inside a building. The employees who sell hiking boots and fishing gear face the same desk-bound and warehouse realities as any retail workforce." ctaText="Check Missouri Eligibility" />
      <PatientArchetype archetype="The Bass Pro Shops Distribution Center Worker" quote="I work in the Bass Pro distribution center—picking and packing camping gear, hunting equipment, and outdoor clothing for 10 hours a day. The irony is I'm surrounded by products designed for active lifestyles while I walk on concrete in a warehouse. My CoxHealth plan has a 14-week wait for endocrinology. Springfield is the outdoor capital. I just can't get outdoors." details="<strong>Patient Profile:</strong> Tyler, 32, Distribution Associate at Bass Pro Shops, Springfield.<br/><br/><strong>The Challenge:</strong> Warehouse work at the outdoor recreation HQ. Physical exhaustion without metabolic benefit. Surrounded by outdoor lifestyle products he doesn't have energy to use. CoxHealth specialist waits 12-16 weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Nixa. MO-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Outdoor Capital That Sits Indoors" paragraphs={["Bass Pro Shops' headquarters and flagship Wonders of Wildlife museum make Springfield the symbolic capital of American outdoor recreation. But the corporate and distribution workforce that makes Bass Pro run is overwhelmingly warehouse-and-office-based. The 'outdoor lifestyle' brand does not translate to the daily metabolic reality of the employees who sell it.","Springfield's food culture is Ozark comfort: cashew chicken (a Springfield original—deep-fried chicken with cashews and white rice, invented by a Chinese-American restaurateur in 1963), BBQ, biscuits and gravy, and the fast food that lines Glenstone Avenue and Sunshine Street.","CoxHealth and Mercy Springfield are strong community systems, but they serve as the referral hub for the entire SW Missouri and NW Arkansas Ozark region. Specialist capacity reflects this broad catchment. Endocrinology waits average 12-16 weeks.","GLP-1 medications serve Springfield's retail, healthcare, and university workforce—delivering metabolic care that the outdoor lifestyle brand promises but the daily reality doesn't provide."]} citations={["Springfield-Greene County Health Department. (2025). <em>Community Health Assessment</em>.","Missouri State University. (2024). <em>Ozark Region Food Culture and Healthcare Access</em>."]} />
      <InsuranceBreakdown title="Bass Pro, Healthcare, and the Ozarks" text="Springfield's economy centers on retail HQs, healthcare, and education." employers={[{name:"Bass Pro Shops (HQ) / O'Reilly Auto Parts (HQ)",detail:"Retail HQs offer corporate plans with standard PBM restrictions."},{name:"CoxHealth / Mercy Springfield",detail:"Health systems serve the Ozark region with stretched specialist capacity."},{name:"Missouri State / Drury / Evangel",detail:"Education employers add standard plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Springfield" localCompetitors={[{name:"South Springfield Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Glenstone MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"CoxHealth Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass US-65/I-44 & CoxHealth Waitlists" transitText="Springfield sits at I-44 and US-65. Kansas City is 3 hours north. St. Louis is 3.5 hours east." hospitalText="<strong>CoxHealth</strong> and <strong>Mercy Springfield</strong> serve SW Missouri and the Ozarks." />
      <InteractiveFAQ faqs={[{q:"I work at Bass Pro. Warehouse shifts. When?",a:"Anytime. Fully asynchronous."},{q:"Do you deliver to Nixa, Ozark, and Branson?",a:"Yes. All Greene, Christian, and Taney County addresses."}]} />
      <StateLegalFramework stateName="Missouri" boardName="Missouri State Board of Registration for the Healing Arts" text="Telehealth FX operates in compliance with the <strong>Missouri Board of Healing Arts</strong> and RSMo § 334." />
      <DeliveryGridMap cityName="Springfield" mapQuery="Springfield, MO" coordinates="37.2090° N, 93.2923° W" counties="Greene County, Christian County, Taney County" neighborhoods={['South Springfield','Nixa','Ozark','Republic','Branson','Willard','Strafford']} />
      <FinalCTA stateName="Missouri" />
    </div>
  );
}
