"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationAmarillo() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="Amarillo" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Amarillo</span>" subheadline="Amarillo sits on the Llano Estacado—the Texas Panhandle flatlands where cattle outnumber people 10 to 1. The Big Texan Steak Ranch offers a free 72-ounce steak to anyone who can finish it. That's not a tourist gimmick—it's a symbol of a food culture where steak is a daily staple and the nearest major medical center is 5 hours away in Dallas." dataPoint1="The Texas Panhandle has among the highest per-capita beef consumption in America. Amarillo is the center of the US cattle feeding industry, surrounded by feedlots that process millions of head annually." dataPoint2="Telehealth FX bridges the 5-hour gap between Amarillo and Dallas, delivering metabolic care to the Panhandle." />
      <PatientArchetype archetype="The Pantex Nuclear Weapons Facility Technician" quote="I work at Pantex—the nation's only nuclear weapons assembly plant. Security clearance, 12-hour shifts, a cafeteria inside a secured perimeter. I can't leave for lunch. The food is institutional. Amarillo has two hospitals and not enough specialists for a city handling nuclear weapons, cattle, and the whole Panhandle's healthcare." details="<strong>Patient Profile:</strong> Derek, 40, Weapons Assembly Technician at Pantex Plant, Amarillo.<br/><br/><strong>The Challenge:</strong> Secured facility, can't leave for meals, 12-hour shifts. Amarillo has limited specialist capacity serving the entire Panhandle region. Dallas is 5 hours away.<br/><br/><strong>The Intervention:</strong> Completed intake from home in West Amarillo. TX-licensed physician prescribed compounded Tirzepatide within 20 hours." />
      <ClinicalDeepDive title="Cattle, Nuclear Weapons, and the Panhandle" paragraphs={["Amarillo sits at the center of the Texas Panhandle cattle feeding industry. The feedlots surrounding the city process millions of cattle annually, and beef is not a dinner option—it is a cultural identity. The Big Texan's 72-ounce steak challenge is famous, but the everyday reality is more relevant: a standard Amarillo dinner plate features 12-16 ounces of beef as a default portion.","Pantex—the nation's only nuclear weapons assembly and disassembly facility—is located 17 miles northeast of Amarillo. The facility employs thousands in highly secured, shift-oriented work where leaving the facility for meals is not an option. The cafeteria is the only food source during a 12-hour shift.","The geographic isolation mirrors Lubbock: Dallas is 5 hours southeast, Albuquerque is 4.5 hours west, and Oklahoma City is 4 hours northeast. BSA (Baptist St. Anthony's) and Northwest Texas Healthcare System serve the Panhandle, but specialist capacity for a region this vast is critically limited.","GLP-1 medications serve the Panhandle's nuclear workforce, ranching community, and healthcare workers without the 5-hour drive to Dallas."]} citations={["Potter-Randall County Health Department. (2025). <em>Community Health Assessment</em>.","Texas Tech University Health Sciences Center-Amarillo. (2024). <em>Healthcare Access in the Texas Panhandle</em>."]} />
      <InsuranceBreakdown title="Pantex, Cattle, and the Panhandle Void" text="Amarillo's economy centers on nuclear weapons, cattle, and regional healthcare." employers={[{name:"Pantex (CNS/DOE)",detail:"Nuclear facility workers have FEHB or contractor plans. Secured facility prevents external food access."},{name:"Ranching / Feedlot Industry",detail:"Agricultural employers offer plans with limited specialist networks in an extremely isolated region."},{name:"BSA / Northwest Texas Healthcare",detail:"The Panhandle's hospitals serve a vast region with limited specialist depth."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Amarillo" localCompetitors={[{name:"Southwest Amarillo Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"I-40 Corridor MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"BSA Endocrinology",cost:"$100 Copay+Rx",consult:"14-20 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="There's Nothing for 300 Miles" transitText="Amarillo sits at the junction of I-40 and I-27. Dallas is 5 hours SE. Albuquerque is 4.5 hours W. Lubbock is 2 hours S. The Panhandle is functionally isolated." hospitalText="<strong>BSA</strong> and <strong>Northwest Texas Healthcare</strong> are the only hospitals serving the entire Panhandle." />
      <InteractiveFAQ faqs={[{q:"I work at Pantex. Is this confidential?",a:"Yes. Completely independent of your employer and DOE clearance."},{q:"Do you deliver to Canyon, Dumas, and Borger?",a:"Yes. All Panhandle addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong> and Texas Occupations Code § 111." />
      <DeliveryGridMap cityName="Amarillo" mapQuery="Amarillo, TX" coordinates="35.2220° N, 101.8313° W" counties="Potter County, Randall County" neighborhoods={['Southwest Amarillo','Canyon','Dumas','Borger','Pampa','Hereford','Bushland']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
