"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationValdosta() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Georgia" cityName="Valdosta" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Valdosta</span>" subheadline="Valdosta is home to Moody Air Force Base—the 23rd Wing and its A-29 Super Tucano/HC-130J Combat King fleet. South Georgia's heat, the military population, and the distance from any major medical center create a healthcare gap that the base clinic cannot close alone." ctaText="Check Georgia Eligibility" />
      <PatientArchetype archetype="The Moody AFB HC-130J Combat Rescue Loadmaster" quote="I'm a loadmaster on the HC-130J—we fly combat search and rescue. Long-duration flights, sitting in a cargo bay for 8+ hours monitoring refueling operations. Post-mission is the Moody BX food court or driving into Valdosta for Southern comfort food. My TRICARE specialist referral is 20 weeks. Jacksonville FL is 2 hours south. Atlanta is 4 hours north. I rescue downed pilots. I can't rescue myself from a 20-week wait." details="<strong>Patient Profile:</strong> SSgt Reeves, 30, HC-130J Loadmaster, 71st Rescue Squadron, Moody AFB.<br/><br/><strong>The Challenge:</strong> Long-duration CSAR flights, sedentary cargo bay hours. BX fast food + South GA comfort food. TRICARE specialist wait 20 weeks. Jacksonville 2 hours, Atlanta 4 hours.<br/><br/><strong>The Intervention:</strong> Completed intake from off-base apartment in Valdosta. GA-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Combat Rescue and Southern Comfort" paragraphs={["Moody AFB is home to the 23rd Wing—the Air Force's combat rescue and close air support wing. The HC-130J Combat King II and HH-60W Jolly Green II crews perform the most dangerous rescue missions in the DOD. The permanent party lives in Valdosta, a small South Georgia city near the Florida border.","The food culture is South Georgia: fried everything, BBQ, boiled peanuts at every roadside stand, and the meat-and-three tradition. Austin's Cattle Company and Mom & Dad's Italian are Valdosta institutions. The Moody BX food court defaults to standard fast food.","South Georgia Medical Center (SGMC) is the primary hospital. The Lowndes County specialist capacity is thin—complex cases route to Jacksonville (2 hours south on I-75), Gainesville UF (3 hours south), or Emory Atlanta (4 hours north).","GLP-1 medications serve the combat rescue community, Valdosta State University, and South Georgia—delivering metabolic care to aircrews who rescue others but can't access timely specialist care."]} citations={["Lowndes County Health Department. (2025). <em>Community Health Assessment</em>.","Valdosta State University. (2024). <em>Military-Community Healthcare in South Georgia</em>."]} />
      <InsuranceBreakdown title="Combat Rescue and South Georgia" text="Valdosta's economy centers on Moody AFB, education, and agriculture." employers={[{name:"Moody AFB / 23rd Wing (TRICARE)",detail:"Combat rescue crews. TRICARE specialist waits 18-22 weeks."},{name:"South Georgia Medical Center",detail:"Primary hospital. Limited specialist depth."},{name:"Valdosta State University / Lowndes County Schools",detail:"Education plans with standard Step Therapy."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Valdosta" localCompetitors={[{name:"North Valdosta / Lake Park Concierge",cost:"$400-$600/mo",consult:"In-Person",access:"Branded Only"},{name:"Baytree Rd MedSpas",cost:"$200-$400/mo",consult:"Monthly",access:"Variable"},{name:"SGMC Endocrinology",cost:"$80 Copay+Rx",consult:"16-22 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="South Georgia's I-75 Corridor" transitText="Valdosta sits on I-75. Jacksonville FL is 2 hours south. Macon is 2.5 hours north. Atlanta is 4 hours north." hospitalText="<strong>South Georgia Medical Center</strong> serves the Valdosta metro." />
      <InteractiveFAQ faqs={[{q:"I fly CSAR missions. Will this affect my flight status?",a:"Consult your flight surgeon. Telehealth FX is independent of military medical records."},{q:"Do you deliver to Moody AFB and Lake Park?",a:"Yes. All Lowndes and Lanier County addresses."}]} />
      <StateLegalFramework stateName="Georgia" boardName="Georgia Composite Medical Board" text="Telehealth FX operates in compliance with the <strong>Georgia Composite Medical Board</strong>." />
      <DeliveryGridMap cityName="Valdosta" mapQuery="Valdosta, GA" coordinates="30.8327° N, 83.2785° W" counties="Lowndes County, Lanier County" neighborhoods={['North Valdosta','Lake Park','Hahira','Moody AFB','Remerton','Dasher','Lakeland']} />
      <FinalCTA stateName="Georgia" />
    </div>
  );
}
