"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationStPetersburg() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Florida" cityName="St. Petersburg" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>St. Petersburg</span>" subheadline="St. Pete averages 361 days of sunshine per year—the Guinness World Record. But the workforce that serves the tourism economy, the retiree healthcare system, and the growing tech scene spends those sunny days indoors. The city that sells sunshine has a metabolic crisis hiding behind the beach postcards." ctaText="Check Florida Eligibility" />
      <PatientArchetype archetype="The Johns Hopkins All Children's Hospital Pediatric Nurse" quote="I'm a pediatric ICU nurse at Johns Hopkins All Children's. I care for critically ill kids for 12 hours straight—emotionally devastating, physically exhausting work. I stress-eat after every shift. My BayCare plan has a 12-week wait for endocrinology. I keep children alive for a living. I can't keep my own metabolism healthy." details="<strong>Patient Profile:</strong> Brittany, 33, PICU RN at Johns Hopkins All Children's Hospital, St. Pete.<br/><br/><strong>The Challenge:</strong> Emotionally devastating pediatric ICU work. 12-hour night shifts. Stress eating as coping mechanism. BayCare specialist waits 10-14 weeks. 361 days of sunshine she never sees.<br/><br/><strong>The Intervention:</strong> Completed intake from apartment in Old Northeast at 7 AM after a night shift. FL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="361 Days of Sunshine, Zero Time Outside" paragraphs={["St. Petersburg holds the Guinness record for most consecutive days of sunshine—768 days without a fully overcast day. The weather is objectively ideal for outdoor activity year-round. But for the healthcare workers, hospitality staff, and office employees who make up the working population, those sunny days pass behind hospital walls, hotel lobbies, and office windows.","The food culture blends Florida seafood (grouper sandwiches, stone crab, smoked fish spread) with the retiree-driven early bird special tradition and the craft brewery explosion along Central Avenue. The brewery scene (Green Bench, Cycle, 3 Daughters) adds significant weekly caloric contributions in a city that increasingly centers social life around taprooms.","BayCare Health System and Bayfront Health (Orlando Health) serve Pinellas County. Johns Hopkins All Children's is a world-class pediatric facility that draws families from across the Southeast. Specialist capacity for the adult population is adequate but stretched during snowbird season (November-April) when the population swells.","GLP-1 medications serve St. Pete's healthcare workers, hospitality workforce, and year-round residents—delivering metabolic care that the sunshine alone cannot provide."]} citations={["Pinellas County Health Department. (2025). <em>Community Health Assessment</em>.","USF Health. (2024). <em>Tourism Economy, Healthcare Workforce, and Metabolic Health in Pinellas County</em>."]} />
      <InsuranceBreakdown title="Sunshine, Healthcare, and the Snowbird Surge" text="St. Pete's economy blends healthcare, tourism, and a growing tech sector." employers={[{name:"Johns Hopkins All Children's / BayCare",detail:"Healthcare workers face the same specialist waitlists they create. Plans require standard referral chains."},{name:"Tourism / Hospitality Industry",detail:"Hotel, restaurant, and beach service workers have limited plans with seasonal demand spikes."},{name:"Jabil (HQ) / Raymond James",detail:"Tech manufacturing and financial services add corporate plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in St. Pete" localCompetitors={[{name:"Old Northeast / Snell Isle Concierge",cost:"$700-$1,100/mo",consult:"In-Person",access:"Branded Only"},{name:"Central Ave MedSpas",cost:"$400-$650/mo",consult:"Monthly",access:"Variable"},{name:"BayCare Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass the Howard Frankland & BayCare Waitlists" transitText="The Howard Frankland and Gandy bridges connect St. Pete to Tampa—bottlenecks during rush hour and snowbird season." hospitalText="<strong>BayCare St. Anthony's</strong>, <strong>Bayfront Health</strong>, and <strong>Johns Hopkins All Children's</strong> serve Pinellas County." />
      <InteractiveFAQ faqs={[{q:"I work night shifts at All Children's. When?",a:"Anytime. Fully asynchronous—complete after your shift."},{q:"Do you deliver to Clearwater, Largo, and Pinellas Park?",a:"Yes. All Pinellas County addresses."}]} />
      <StateLegalFramework stateName="Florida" boardName="Florida Board of Medicine" text="Telehealth FX operates in compliance with the <strong>Florida Board of Medicine</strong> and F.S. § 456.47." />
      <DeliveryGridMap cityName="St. Petersburg" mapQuery="St. Petersburg, FL" coordinates="27.7676° N, 82.6403° W" counties="Pinellas County" neighborhoods={['Old Northeast','Downtown','Clearwater','Largo','Pinellas Park','Dunedin','Safety Harbor','Gulfport']} />
      <FinalCTA stateName="Florida" />
    </div>
  );
}
