"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationModesto() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="California" cityName="Modesto" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Modesto</span>" subheadline="Modesto sits in the heart of California's Central Valley—surrounded by the richest farmland in America but ranked among the state's most medically underserved cities. The 'Water, Wealth, Contentment, Health' arch downtown was aspirational in 1912. It's ironic in 2026." dataPoint1="Stanislaus County's adult obesity rate exceeds 34%. The combination of extreme heat, agricultural economy, food desert dynamics, and critical specialist shortage mirrors the broader Central Valley crisis." dataPoint2="Telehealth FX bypasses the Valley's specialist desert—no drive to Sacramento, no drive to the Bay Area." />
      <PatientArchetype archetype="The E. & J. Gallo Winery Production Supervisor" quote="I manage bottling operations at Gallo—the largest winery in the world. My shifts rotate, the production floor is hot, and the cafeteria options are industrial grade. Modesto doesn't have enough specialists for a city this size. My Kaiser plan redirected me to Sacramento. That's an hour each way on 99." details="<strong>Patient Profile:</strong> Carlos, 43, Production Supervisor at E. & J. Gallo Winery, Modesto.<br/><br/><strong>The Challenge:</strong> Rotating shifts at the world's largest winery. Kaiser Modesto has minimal endocrinology—patients redirected to Sacramento (60 min) or Bay Area (90 min). Central Valley heat eliminates outdoor activity for months.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Ceres. CA-licensed physician prescribed compounded Tirzepatide within 24 hours." />
      <ClinicalDeepDive title="Water, Wealth, Contentment, Health—Minus the Health" paragraphs={["Modesto's iconic arch proclaims 'Water, Wealth, Contentment, Health'—a 1912 aspiration that the city's current health metrics have not achieved. Stanislaus County faces the same Central Valley challenges as Fresno, Stockton, and Bakersfield: extreme summer heat, food desert neighborhoods, agricultural economics, and a specialist shortage that forces patients to drive to Sacramento or the Bay Area.","E. & J. Gallo Winery—the world's largest—anchors Modesto's economy alongside agriculture and food processing (Del Monte, Foster Farms). The food industry workforce is surrounded by agricultural abundance but eats from cafeterias and fast food—the same paradox seen across the Valley.","The specialist shortage is acute. Kaiser Modesto redirects endocrinology patients to Sacramento (60 miles north) or the Bay Area (90 miles west). For hourly workers, this is a full day of lost wages.","GLP-1 medications deliver clinical metabolic care to the heart of the Central Valley without the Highway 99 drive."]} citations={["Stanislaus County Health Services Agency. (2025). <em>Community Health Assessment</em>.","UCSF Fresno. (2024). <em>Specialist Access in the Northern San Joaquin Valley</em>."]} />
      <InsuranceBreakdown title="Winery Workers, Ag Economy, Kaiser Redirects" text="Modesto's economy centers on wine, agriculture, and food processing." employers={[{name:"E. & J. Gallo Winery (HQ)",detail:"The world's largest winery offers plans with standard PBM restrictions in a specialist-scarce region."},{name:"Del Monte / Foster Farms / Agriculture",detail:"Food industry and ag plans face the same limited local networks."},{name:"Kaiser Modesto / Memorial Medical",detail:"Kaiser redirects to Sacramento. Memorial serves the community with limited specialist depth."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Modesto" localCompetitors={[{name:"Village One Clinics",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"McHenry Ave MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Kaiser Endocrinology (Sacramento)",cost:"$100 Copay+Rx",consult:"14-18wk+60mi",access:"Redirected"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Highway 99 & Kaiser Sacramento" transitText="Modesto connects to Sacramento via Highway 99 (60 miles) and to the Bay Area via 132/580 (90 miles). Both routes are congested." hospitalText="<strong>Memorial Medical Center</strong> and <strong>Kaiser Modesto</strong> serve the area. Kaiser redirects specialist cases to Sacramento." />
      <InteractiveFAQ faqs={[{q:"Kaiser told me to go to Sacramento. Is there a local option?",a:"Yes. Telehealth FX is fully remote. Your medication ships directly to your Modesto address."},{q:"Do you deliver to Ceres, Turlock, and Patterson?",a:"Yes. All Stanislaus County addresses."}]} />
      <StateLegalFramework stateName="California" boardName="Medical Board of California" text="Telehealth FX operates in compliance with the <strong>Medical Board of California</strong> and Cal. B&P Code § 2290.5." />
      <DeliveryGridMap cityName="Modesto" mapQuery="Modesto, CA" coordinates="37.6391° N, 120.9969° W" counties="Stanislaus County" neighborhoods={['Village One','Ceres','Turlock','Patterson','Oakdale','Riverbank','Hughson']} />
      <FinalCTA stateName="California" />
    </div>
  );
}
