"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationTacoma() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Washington" cityName="Tacoma" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Tacoma</span>" subheadline="Tacoma lives in Seattle's shadow—30 miles south, a fraction of the tech wealth, and a completely different healthcare reality. Joint Base Lewis-McChord (JBLM) is the largest military installation on the West Coast, adding 40,000+ military personnel and families to a healthcare system already stretched by Seattle's overflow." dataPoint1="Pierce County's obesity rate exceeds 31%. Tacoma's economy blends military (JBLM), port operations, and blue-collar manufacturing that Seattle's tech boom has priced out." dataPoint2="Telehealth FX serves the JBLM community, port workers, and Tacoma's working-class population without the I-5 crawl to Seattle." />
      <PatientArchetype archetype="The JBLM Stryker Brigade Combat Team Spouse" quote="My husband is deployed with 2nd Stryker Brigade. I'm managing two kids, a house in Lakewood, and my own part-time job. I gained 35 pounds during this deployment. Madigan Army Medical Center has a 20-week specialist wait. Seattle is 45 minutes on a good I-5 day, which doesn't exist. I need help now, not in 5 months." details="<strong>Patient Profile:</strong> Rachel, 31, Military Spouse, JBLM.<br/><br/><strong>The Challenge:</strong> Deployment stress, solo parenting, part-time work. Madigan AMC specialist wait 20 weeks. Seattle healthcare is 45 min minimum via the most congested freeway in the Pacific NW.<br/><br/><strong>The Intervention:</strong> Completed intake from Lakewood at 9 PM after kids were asleep. WA-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Seattle's Shadow, JBLM's Burden" paragraphs={["Tacoma is not Seattle. The tech wealth, the Amazon-Microsoft-Google physician demand, and the specialist capacity that the Eastside and Capitol Hill enjoy do not extend 30 miles south on I-5. Tacoma's healthcare reality is MultiCare and CHI Franciscan serving Pierce County alongside the military overflow from JBLM.","Joint Base Lewis-McChord is the largest military installation on the West Coast—I Corps headquarters, 2nd Stryker Brigade, Special Forces, Rangers. Madigan Army Medical Center serves the military population but overflows into the civilian system. The deployment cycle creates the same spouse stress-eating pattern seen in Fayetteville and Killeen.","The Port of Tacoma adds a logistics and industrial workforce. The food culture is Pacific Northwest working class: fish and chips, teriyaki (Tacoma's teriyaki shop density rivals Seattle's), and the comfort food that gray, rainy winters demand.","GLP-1 medications bridge the I-5 gap between Tacoma's healthcare reality and Seattle's specialist capacity—serving the military community and working-class population without the freeway crawl."]} citations={["Tacoma-Pierce County Health Department. (2025). <em>Community Health Assessment</em>.","Madigan Army Medical Center. (2024). <em>Military Family Health and Specialist Referral Patterns at JBLM</em>."]} />
      <InsuranceBreakdown title="JBLM, Port, and Seattle's Shadow" text="Tacoma's economy blends military, port, and blue-collar sectors priced out of Seattle." employers={[{name:"JBLM (TRICARE)",detail:"40,000+ military. Madigan AMC specialist waits 18-22 weeks."},{name:"Port of Tacoma / Logistics",detail:"Port workers have union/employer plans with limited local specialist networks."},{name:"MultiCare / CHI Franciscan",detail:"Tacoma's health systems absorb military overflow alongside civilian demand."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Tacoma" localCompetitors={[{name:"North End / University Place Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"6th Ave MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"Madigan / MultiCare Endocrinology",cost:"$100 Copay+Rx",consult:"16-22 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-5 & Madigan Waitlists" transitText="I-5 between Tacoma and Seattle is the most congested corridor in the Pacific Northwest. A 30-mile drive can take 90+ minutes." hospitalText="<strong>Madigan AMC</strong>, <strong>MultiCare Tacoma General</strong>, and <strong>CHI Franciscan</strong> serve Pierce County." />
      <InteractiveFAQ faqs={[{q:"My spouse is deployed. Can I start without them?",a:"Yes. Military spouses can use Telehealth FX independently."},{q:"Do you deliver to Lakewood, Puyallup, and Olympia?",a:"Yes. All Pierce and Thurston County addresses."}]} />
      <StateLegalFramework stateName="Washington" boardName="Washington Medical Commission" text="Telehealth FX operates in compliance with the <strong>Washington Medical Commission</strong> and RCW 18.71." />
      <DeliveryGridMap cityName="Tacoma" mapQuery="Tacoma, WA" coordinates="47.2529° N, 122.4443° W" counties="Pierce County, Thurston County" neighborhoods={['North End','University Place','Lakewood','Puyallup','Spanaway','Bonney Lake','Olympia','DuPont']} />
      <FinalCTA stateName="Washington" />
    </div>
  );
}
