"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSavannah() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Georgia" cityName="Savannah" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Savannah</span>" subheadline="Savannah is one of America's most beautiful cities—the historic squares, the Spanish moss, the Lowcountry cuisine. It is also home to the busiest port on the East Coast and Hunter Army Airfield. The tourism economy, the port workforce, and the military all compete for the same limited specialist pool." dataPoint1="Chatham County's adult obesity rate exceeds 33%. The Lowcountry food tradition—shrimp and grits, fried green tomatoes, she-crab soup, pralines—is cultural heritage with significant caloric density." dataPoint2="Telehealth FX serves the port workers, military families, and SCAD students without competing for Memorial Health's specialist slots." />
      <PatientArchetype archetype="The Georgia Ports Authority Crane Operator" quote="I operate ship-to-shore cranes at the Port of Savannah—the busiest container port on the East Coast. Twelve-hour shifts, 150 feet in the air, no bathroom breaks for hours. I eat whatever I packed or whatever's at the port cafeteria. My Memorial Health plan has a 14-week wait for endocrinology. I move $100 billion in cargo a year. I can't move a doctor's appointment closer." details="<strong>Patient Profile:</strong> Andre, 41, Crane Operator at Georgia Ports Authority.<br/><br/><strong>The Challenge:</strong> 12-hour crane shifts at the busiest East Coast port. Packed lunches or port cafeteria. Memorial Health specialist capacity strained by tourism-driven population growth.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Pooler. GA-licensed physician prescribed compounded Tirzepatide within 20 hours." />
      <ClinicalDeepDive title="Spanish Moss, Shrimp and Grits, and the Busiest Port" paragraphs={["Savannah's port processes more container volume than any other port on the US East Coast. The Georgia Ports Authority employs thousands directly, with logistics, trucking, and warehouse operations extending into Pooler, Garden City, and along I-16. This industrial workforce operates alongside the tourism economy that draws 15 million visitors annually.","The Lowcountry food tradition is among the most celebrated in American cuisine—and among the most calorie-dense. Shrimp and grits (butter, cheese, cream), fried green tomatoes, she-crab soup, Savannah red rice, and the praline candy tradition create a food culture that tourists celebrate and locals eat daily.","Hunter Army Airfield adds a military population to the specialist demand. Memorial Health (HCA) is the dominant system, supplemented by St. Joseph's/Candler. Together they serve Savannah's growing population plus tourists requiring emergency care—a combination that stretches specialist capacity.","GLP-1 medications serve Savannah's port workers, military families, and hospitality workforce—the people who make this beautiful city function while the tourists eat the shrimp and grits."]} citations={["Chatham County Health Department. (2025). <em>Community Health Assessment</em>.","Mercer University School of Medicine-Savannah. (2024). <em>Tourism Economy, Port Operations, and Healthcare Access in Coastal Georgia</em>."]} />
      <InsuranceBreakdown title="Port, Military, and Tourism" text="Savannah's economy spans port operations, military, and hospitality." employers={[{name:"Georgia Ports Authority / Logistics",detail:"Port and logistics employers offer plans with standard PBM restrictions."},{name:"Hunter AAF / Fort Stewart (TRICARE)",detail:"Military population competes for limited civilian specialist slots."},{name:"Memorial Health / St. Joseph's-Candler",detail:"Health systems serve locals, military, and tourist emergencies."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Savannah" localCompetitors={[{name:"Historic District / Ardsley Park Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Abercorn St MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"Memorial Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-16/I-95 & Memorial Waitlists" transitText="Savannah's growth has pushed development west along I-16 toward Pooler and Statesboro. I-95 runs through the metro." hospitalText="<strong>Memorial Health</strong> and <strong>St. Joseph's/Candler</strong> serve the Coastal Empire." />
      <InteractiveFAQ faqs={[{q:"I work 12-hour crane shifts. When?",a:"Anytime. Fully asynchronous."},{q:"Do you deliver to Pooler, Richmond Hill, and Hinesville?",a:"Yes. All Chatham, Bryan, Effingham, and Liberty County addresses."}]} />
      <StateLegalFramework stateName="Georgia" boardName="Georgia Composite Medical Board" text="Telehealth FX operates in compliance with the <strong>Georgia Composite Medical Board</strong> and OCGA § 43-34." />
      <DeliveryGridMap cityName="Savannah" mapQuery="Savannah, GA" coordinates="32.0809° N, 81.0912° W" counties="Chatham County, Bryan County, Effingham County" neighborhoods={['Ardsley Park','Pooler','Richmond Hill','Garden City','Hinesville','Statesboro','Tybee Island']} />
      <FinalCTA stateName="Georgia" />
    </div>
  );
}
