"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationCharleston() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="South Carolina" cityName="Charleston" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Charleston</span>" subheadline="Charleston is America's most celebrated food city—the James Beard Award capital of the South. The shrimp and grits, she-crab soup, and Lowcountry boil traditions that win national accolades create a caloric environment that the city's growing population cannot metabolically sustain. Boeing's 787 Dreamliner plant adds an aerospace workforce to the demand." ctaText="Check South Carolina Eligibility" />
      <PatientArchetype archetype="The Boeing Charleston 787 Fuselage Assembler" quote="I assemble aft fuselage sections for the 787 Dreamliner at Boeing North Charleston. Ten-hour shifts, standing, using overhead tools. The plant cafeteria is standard industrial. After work, Charleston's food scene is impossible to resist—Rodney Scott's BBQ, Husk, and the shrimp and grits at every corner. My MUSC plan has a 14-week wait for endocrinology." details="<strong>Patient Profile:</strong> Devon, 36, Assembly Mechanic at Boeing Charleston.<br/><br/><strong>The Challenge:</strong> 10-hour shifts building Dreamliners. Charleston's world-class food scene is an after-work caloric minefield. MUSC specialist waits 12-16 weeks in a rapidly growing city.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Summerville. SC-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="James Beard Awards and the Dreamliner" paragraphs={["Charleston has won more James Beard Awards than cities ten times its size. The food is not just good—it is nationally significant. Husk, FIG, The Ordinary, and Rodney Scott's Whole Hog BBQ represent a culinary tradition rooted in Lowcountry Gullah-Geechee foodways: shrimp and grits, okra soup, Hoppin' John, she-crab soup. This is not restaurant food consumed on special occasions—it is cultural heritage eaten weekly.","Boeing's 787 assembly facility in North Charleston employs thousands in aerospace manufacturing. The Charleston Naval Weapons Station (now Joint Base Charleston) adds military demand. The combination of defense, aerospace, tourism/hospitality, and Volvo's assembly plant in Ridgeville creates a diverse but healthcare-stressing workforce.","MUSC (Medical University of South Carolina) is an excellent academic medical center, but Charleston has been one of the fastest-growing metros in the Southeast. Specialist capacity has not scaled proportionally. Endocrinology waits average 12-16 weeks.","GLP-1 medications serve Charleston's Boeing workers, military families, and hospitality workforce—delivering metabolic care without requiring them to resist the best food in the South."]} citations={["Charleston County Health Department. (2025). <em>Community Health Assessment</em>.","MUSC College of Medicine. (2024). <em>Rapid Growth, Food Culture, and Healthcare Access in the Lowcountry</em>."]} />
      <InsuranceBreakdown title="Boeing, Military, and the Food Capital" text="Charleston's economy spans aerospace, military, and culinary tourism." employers={[{name:"Boeing Charleston / Volvo (Ridgeville)",detail:"Aerospace and automotive plans with standard PBM restrictions."},{name:"Joint Base Charleston (TRICARE)",detail:"Military population adds to specialist demand."},{name:"MUSC / Roper St. Francis / Trident",detail:"Health systems face growth-driven specialist shortages."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Charleston" localCompetitors={[{name:"South of Broad / Mt Pleasant Concierge",cost:"$700-$1,100/mo",consult:"In-Person",access:"Branded Only"},{name:"Coleman Blvd MedSpas",cost:"$400-$650/mo",consult:"Monthly",access:"Variable"},{name:"MUSC Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass the Ravenel Bridge & MUSC Waitlists" transitText="Charleston traffic bottlenecks at the Ravenel Bridge (Mt. Pleasant), I-26, and US-17. Summerville commuters face 45-60 minute drives." hospitalText="<strong>MUSC</strong>, <strong>Roper St. Francis</strong>, and <strong>Trident Medical</strong> serve the Lowcountry." />
      <InteractiveFAQ faqs={[{q:"I work at Boeing. Shift schedule. When?",a:"Anytime. Fully asynchronous."},{q:"Do you deliver to Mt Pleasant, Summerville, and Goose Creek?",a:"Yes. All Charleston, Berkeley, and Dorchester County addresses."}]} />
      <StateLegalFramework stateName="South Carolina" boardName="South Carolina Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>SC Board of Medical Examiners</strong> and SC Code § 40-47." />
      <DeliveryGridMap cityName="Charleston" mapQuery="Charleston, SC" coordinates="32.7765° N, 79.9311° W" counties="Charleston County, Berkeley County, Dorchester County" neighborhoods={['Mt Pleasant','Summerville','Goose Creek','North Charleston','James Island','West Ashley','Johns Island','Kiawah']} />
      <FinalCTA stateName="South Carolina" />
    </div>
  );
}
