"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationFargo() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="North Dakota" cityName="Fargo" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Fargo</span>" subheadline="Fargo averages -3°F in January. The wind chill regularly hits -40°F. Outdoor exercise is impossible for 5 months of the year. The city that anchors the Northern Plains' agricultural economy and hosts North Dakota State University has a metabolic environment shaped by extreme cold, Scandinavian comfort food traditions, and the most severe seasonal affective disorder in the country." dataPoint1="Cass County's adult obesity rate exceeds 32%. Fargo's extreme cold creates a 5-month indoor confinement period. Scandinavian and German food traditions—hotdish, knoephla soup, lutefisk—are calorie-dense survival foods in a modern setting." dataPoint2="Telehealth FX delivers metabolic care through North Dakota's coldest months without the Sanford or Essentia waitlist." />
      <PatientArchetype archetype="The NDSU Agricultural Research Scientist" quote="I research crop genetics at NDSU—sitting in a lab analyzing wheat and soybean data. Fargo is -40 wind chill from November to March. I haven't been outside for exercise since October. The SAD is real—I crave carbs and hotdish constantly. Sanford has a 14-week wait for endocrinology. I study food production. I just can't manage my own food consumption." details="<strong>Patient Profile:</strong> Dr. Olson, 43, Crop Genetics Researcher at NDSU.<br/><br/><strong>The Challenge:</strong> Lab-based sedentary work. 5-month extreme cold confinement. Severe SAD carb cravings. Sanford specialist wait 14 weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from home in South Fargo. ND-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="-40 Wind Chill and the Hotdish Belt" paragraphs={["Fargo's winters are among the most extreme in the continental US. January average temperatures hover at -3°F, with wind chills regularly reaching -40°F. The Red River Valley's flat terrain offers zero wind protection. Outdoor exercise from November through March is not inadvisable—it is dangerous.","The food culture is Scandinavian-German Upper Midwest: hotdish (tater tot hotdish is the regional signature), knoephla soup (cream-based dumpling soup), lefse, kuchen, and the beer culture that NDSU's Bison football tailgating tradition celebrates. Fargo also sits in the upper Midwest bar food corridor—cheese curds, wings, and pizza are standard Thursday-through-Sunday fare.","Sanford Health (headquartered in Sioux Falls but with a major Fargo campus) and Essentia Health serve the region. As the referral center for all of eastern North Dakota, western Minnesota, and parts of South Dakota, specialist capacity is stretched across a vast geographic area.","GLP-1 medications serve Fargo's agricultural researchers, university community, and Northern Plains workforce—delivering metabolic care through the months when the cold makes everything else impossible."]} citations={["Fargo Cass Public Health. (2025). <em>Community Health Assessment</em>.","NDSU School of Public Health. (2024). <em>Extreme Cold, Seasonal Affective Disorder, and Metabolic Health in the Northern Plains</em>."]} />
      <InsuranceBreakdown title="Agriculture, University, and the Northern Plains" text="Fargo's economy spans agriculture, education, healthcare, and tech." employers={[{name:"NDSU / Concordia / MSUM",detail:"University plans with standard PBM restrictions."},{name:"Sanford Fargo / Essentia Health",detail:"Health systems serve a vast multi-state region."},{name:"Microsoft (Fargo) / Bobcat / BNSF",detail:"Tech, manufacturing, and rail add corporate plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Fargo" localCompetitors={[{name:"South Fargo / West Fargo Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"13th Ave MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Sanford Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-94 & Sanford Waitlists" transitText="Fargo sits on I-94 and I-29. Minneapolis is 3.5 hours SE. Bismarck is 3 hours west." hospitalText="<strong>Sanford Fargo</strong> and <strong>Essentia Health</strong> serve the region." />
      <InteractiveFAQ faqs={[{q:"It's January. How fast is delivery?",a:"USPS Priority Mail. Winter weather may add 1-2 days during severe events."},{q:"Do you deliver to Moorhead MN and West Fargo?",a:"Yes. All Cass County ND and Clay County MN addresses."}]} />
      <StateLegalFramework stateName="North Dakota" boardName="North Dakota Board of Medicine" text="Telehealth FX operates in compliance with the <strong>ND Board of Medicine</strong> and NDCC § 43-17." />
      <DeliveryGridMap cityName="Fargo" mapQuery="Fargo, ND" coordinates="46.8772° N, 96.7898° W" counties="Cass County ND, Clay County MN" neighborhoods={['South Fargo','West Fargo','Moorhead MN','Dilworth','Horace','Wahpeton','Grand Forks']} />
      <FinalCTA stateName="North Dakota" />
    </div>
  );
}
