"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationDesMoines() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Iowa" cityName="Des Moines" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Des Moines</span>" subheadline="Des Moines is the insurance capital of the Midwest—Principal Financial, EMC, Nationwide, and Wells Fargo call it home. The professionals who underwrite and manage America's health risk face the same PBM barriers as every other American." dataPoint1="Iowa's adult obesity rate exceeds 36%. Des Moines's corporate workforce is predominantly sedentary, and the comfort food culture (pork tenderloins, loose meat sandwiches, and the State Fair's deep-fried-everything tradition) creates significant weekly caloric contributions." dataPoint2="Telehealth FX bypasses the insurance industry's own barriers—serving the people who design the systems that restrict GLP-1 access." />
      <PatientArchetype archetype="The Principal Financial Actuary" quote="I model mortality risk for Principal Financial. I can tell you exactly how much insulin resistance costs the healthcare system per patient per year. My own Principal employee plan requires a 6-month behavioral program before GLP-1 authorization. I price the cost of obesity professionally and I can't access the solution personally." details="<strong>Patient Profile:</strong> Nathan, 38, Actuary at Principal Financial Group.<br/><br/><strong>The Challenge:</strong> Nathan understands metabolic risk at a professional level. His Principal employee plan requires behavioral modification before GLP-1 authorization—standard insurance industry practice designed by actuaries like himself.<br/><br/><strong>The Intervention:</strong> Completed intake from his home in Ankeny. An Iowa-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Insurance Capital's Own Barriers" paragraphs={["Des Moines hosts more insurance company headquarters per capita than any other US city. Principal Financial, EMC Insurance, Nationwide's operations center, and dozens of carriers and reinsurers employ tens of thousands of professionals who design, price, and administer the very health insurance products that restrict GLP-1 access. The irony rivals Hartford and Minneapolis.","The Iowa State Fair—held annually in Des Moines—is legendary for its deep-fried innovation (fried butter, fried Oreos, fried cheese curds on a stick). But the State Fair is one week. The year-round food culture is classic Midwest: the breaded pork tenderloin sandwich (a statewide obsession), Maid-Rite loose meat sandwiches, and the Casey's General Store pizza that is—improbably—among the most consumed pizza in the Midwest.","Iowa winters drive the familiar SAD/carbohydrate cycle. From November through March, the combination of cold, darkness, and comfort food creates metabolic momentum that spring doesn't reverse.","GLP-1 medications serve Des Moines's insurance professionals, state workers, and the broader Iowa workforce—restoring metabolic signaling in a community that understands health risk professionally but can't access the pharmaceutical solution personally."]} citations={["Polk County Health Department. (2025). <em>Community Health Assessment</em>.","University of Iowa College of Public Health. (2024). <em>Insurance Industry Employment, Sedentary Work, and Metabolic Health</em>."]} />
      <InsuranceBreakdown title="Insurance HQ Capital" text="Des Moines's economy IS the insurance industry." employers={[{name:"Principal Financial / EMC / Nationwide",detail:"Insurance employers offer their own plans—which still apply PBM Step Therapy for GLP-1s."},{name:"Wells Fargo / Hy-Vee (HQ)",detail:"Financial and retail HQs offer self-funded plans with standard restrictions."},{name:"UnityPoint / MercyOne",detail:"Health systems serve as both employer and specialist source."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in Des Moines" localCompetitors={[{name:"West Des Moines Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Jordan Creek MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"UnityPoint Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-80/I-35 & UnityPoint Waitlists" transitText="Des Moines sprawls along I-80 and I-35 with suburban growth in Ankeny, West Des Moines, and Waukee." hospitalText="<strong>UnityPoint Health</strong> and <strong>MercyOne</strong> serve the metro. Specialist waits average 10-14 weeks." />
      <InteractiveFAQ faqs={[{q:"I work in insurance. Is this a conflict?",a:"No. Telehealth FX is independent. Your use is a private healthcare decision."},{q:"Do you deliver to Ankeny and Waukee?",a:"Yes. All Polk, Dallas, and Warren County addresses."}]} />
      <StateLegalFramework stateName="Iowa" boardName="Iowa Board of Medicine" text="Telehealth FX operates in compliance with the <strong>Iowa Board of Medicine</strong> and Iowa Code Ch. 148." />
      <DeliveryGridMap cityName="Des Moines" mapQuery="Des Moines, IA" coordinates="41.5868° N, 93.6250° W" counties="Polk County, Dallas County, Warren County" neighborhoods={['West Des Moines','Ankeny','Waukee','Johnston','Urbandale','Clive','Altoona']} />
      <FinalCTA stateName="Iowa" />
    </div>
  );
}
