"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationMontgomery() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Alabama" cityName="Montgomery" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Montgomery</span>" subheadline="Montgomery is Alabama's capital and the birthplace of the Civil Rights Movement. Maxwell Air Force Base trains the Air Force's senior officers. The city that changed American history faces an adult obesity rate exceeding 38%—and a specialist shortage that its state capitol cannot legislate away." ctaText="Check Alabama Eligibility" />
      <PatientArchetype archetype="The Maxwell AFB Air War College Student" quote="I'm a Lieutenant Colonel attending Air War College—the military's senior professional education. It's a year of intense academic study, sedentary desk work, and Pentagon-prep stress. The O-Club food is decent, the Montgomery restaurant scene is surprisingly good, and I've gained 25 pounds since arriving. TRICARE at Maxwell has a 16-week specialist wait. I'm here for one year. That wait is a quarter of my assignment." details="<strong>Patient Profile:</strong> Lt Col Barnes, 42, Air War College Student, Maxwell AFB.<br/><br/><strong>The Challenge:</strong> Senior officers gain weight during war college year—intense academics, social dining, zero PT accountability. TRICARE specialist wait consumes 25% of their assignment.<br/><br/><strong>The Intervention:</strong> Completed intake from base housing. AL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Civil Rights Capital, Health Rights Crisis" paragraphs={["Montgomery's historical significance is profound—the Rosa Parks bus boycott, the Selma-to-Montgomery marches, and Dr. King's Dexter Avenue Baptist Church are foundational American moments. But the health disparities that the Civil Rights Movement sought to address persist in different form: Alabama's #2 national obesity ranking falls disproportionately on Montgomery's communities.","Maxwell AFB adds Air University's student population—senior officers from all branches attending Air War College, Air Command and Staff College, and Squadron Officer School. These are America's future generals, spending a year in academic environments that are uniformly sedentary.","The food culture is Deep South: fried catfish, BBQ, soul food (Chris' Hot Dogs has been open since 1917), and the Southern comfort traditions that define Montgomery dining. The combination of state government desk workers, military academics, and a food environment built for manual labor creates the metabolic gap.","GLP-1 medications serve Montgomery's military academics, state workers, and the broader community—delivering metabolic care in a city where historical health disparities and modern specialist shortages intersect."]} citations={["Montgomery County Health Department. (2025). <em>Community Health Assessment</em>.","Alabama State University. (2024). <em>Health Disparities and Healthcare Access in the River Region</em>."]} />
      <InsuranceBreakdown title="Maxwell, State Capitol, and the River Region" text="Montgomery's economy centers on military, state government, and automotive." employers={[{name:"Maxwell AFB / Air University (TRICARE)",detail:"Military academic population. TRICARE specialist waits 14-18 weeks."},{name:"State of Alabama (Capitol)",detail:"State plans require Step Therapy."},{name:"Baptist Health / Jackson Hospital",detail:"Regional systems serve central Alabama."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Montgomery" localCompetitors={[{name:"Cloverdale / Pike Rd Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Eastern Blvd MedSpas",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"Baptist Endocrinology",cost:"$100 Copay+Rx",consult:"12-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-65/I-85 & Baptist Waitlists" transitText="Montgomery sits at I-65 and I-85. Birmingham is 90 min north." hospitalText="<strong>Baptist Health</strong> and <strong>Jackson Hospital</strong> serve the River Region." />
      <InteractiveFAQ faqs={[{q:"I'm TDY at Maxwell for a year. Which state?",a:"Alabama. You'll be evaluated by an AL-licensed physician."},{q:"Do you deliver to Prattville and Pike Road?",a:"Yes. All Montgomery, Autauga, and Elmore County addresses."}]} />
      <StateLegalFramework stateName="Alabama" boardName="Alabama Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>Alabama Board of Medical Examiners</strong>." />
      <DeliveryGridMap cityName="Montgomery" mapQuery="Montgomery, AL" coordinates="32.3792° N, 86.3077° W" counties="Montgomery County, Autauga County, Elmore County" neighborhoods={['Cloverdale','Pike Road','Prattville','Wetumpka','Millbrook','Tallassee']} />
      <FinalCTA stateName="Alabama" />
    </div>
  );
}
