"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationFortWayne() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Indiana" cityName="Fort Wayne" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Fort Wayne</span>" subheadline="Fort Wayne is Indiana's second-largest city and a manufacturing powerhouse—General Motors, BAE Systems, and BF Goodrich keep the assembly lines running. But the factory workforce that builds America's trucks and defense systems faces a healthcare access gap that a city of 265,000 shouldn't have." ctaText="Check Indiana Eligibility" />
      <PatientArchetype archetype="The GM Fort Wayne Assembly Plant Worker" quote="I build full-size trucks on the GM line—12 hours a day, rotating between days and nights. The cafeteria serves what you'd expect: pizza, burgers, chicken tenders. After a 12-hour shift, I don't have the energy to cook. My Parkview plan has a 14-week wait for endocrinology. Fort Wayne has plenty of factories. Not enough doctors." details="<strong>Patient Profile:</strong> Kevin, 41, Assembly Technician at GM Fort Wayne Assembly.<br/><br/><strong>The Challenge:</strong> 12-hour rotating shifts on the truck line. Factory cafeteria diet. Parkview Health's specialist capacity cannot keep pace with Allen County's demand.<br/><br/><strong>The Intervention:</strong> Completed intake from home in New Haven after a shift. IN-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Truck Capital's Health Gap" paragraphs={["Fort Wayne's economy is anchored by manufacturing—GM's full-size truck plant, BAE Systems (military vehicles), and BF Goodrich (aerospace). These factories employ thousands in physically demanding, shift-oriented roles where the caloric expenditure is repetitive-motion exhaustion, not cardiovascular health.","The Midwest food culture is standard comfort: tenderloin sandwiches (Indiana's state obsession), Coney dogs from Fort Wayne's Famous Coney Island, and the ubiquitous fast food along Coliseum Boulevard and Lima Road. The weekly caloric landscape is relentless.","Fort Wayne's healthcare is anchored by Parkview Health and Lutheran Health, both strong community systems. But for a city of 265,000 serving a broader Northeast Indiana catchment, specialist capacity is limited. Endocrinology waits average 12-16 weeks.","GLP-1 medications serve Fort Wayne's manufacturing workforce without requiring them to find time between 12-hour shifts and sleep for a specialist appointment that's 14 weeks away."]} citations={["Allen County Department of Health. (2025). <em>Community Health Assessment</em>.","Indiana University School of Medicine-Fort Wayne. (2024). <em>Healthcare Access in Northeast Indiana</em>."]} />
      <InsuranceBreakdown title="Manufacturing Plans and the Specialist Gap" text="Fort Wayne's manufacturers dominate the employer landscape." employers={[{name:"GM / BAE Systems / BF Goodrich",detail:"Manufacturing plans require standard PBM Step Therapy for GLP-1s."},{name:"Parkview Health / Lutheran Health",detail:"Health systems serve as both employer and specialist source."},{name:"Lincoln Financial (Fort Wayne)",detail:"The financial sector adds corporate plans with standard restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Fort Wayne" localCompetitors={[{name:"Aboite / Southwest Concierge",cost:"$500-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Lima Rd MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"Parkview Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Coliseum Blvd & Parkview Waitlists" transitText="Fort Wayne sprawls along I-69 and US-30 with Coliseum Boulevard as the commercial spine." hospitalText="<strong>Parkview Regional</strong> and <strong>Lutheran Hospital</strong> serve NE Indiana. Specialist waits average 12-16 weeks." />
      <InteractiveFAQ faqs={[{q:"I work rotating shifts at GM. When do I do the intake?",a:"Anytime. Fully asynchronous."},{q:"Do you deliver to New Haven and Huntington?",a:"Yes. All Allen, Whitley, and Huntington County addresses."}]} />
      <StateLegalFramework stateName="Indiana" boardName="Indiana Medical Licensing Board" text="Telehealth FX operates in compliance with the <strong>Indiana Medical Licensing Board</strong> and IC § 25-1-9.5." />
      <DeliveryGridMap cityName="Fort Wayne" mapQuery="Fort Wayne, IN" coordinates="41.0793° N, 85.1394° W" counties="Allen County, Whitley County, DeKalb County" neighborhoods={['Aboite','New Haven','Huntertown','Leo-Cedarville','Decatur','Huntington','Auburn']} />
      <FinalCTA stateName="Indiana" />
    </div>
  );
}
