"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationWilmington() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="North Carolina" cityName="Wilmington" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Wilmington</span>" subheadline="Wilmington is North Carolina's port city—where the Cape Fear River meets the Atlantic. Camp Lejeune and MCAS New River (45 minutes north in Jacksonville) send Marines and families into Wilmington for specialist care the base can't provide. The Wrightsville Beach lifestyle sells wellness. The healthcare system can't deliver it fast enough." ctaText="Check North Carolina Eligibility" />
      <PatientArchetype archetype="The Camp Lejeune Marine Spouse (Wilmington Overflow)" quote="We live in Wilmington because the schools are better than Jacksonville. My husband commutes to Camp Lejeune. When I need a specialist, Naval Hospital Camp Lejeune sends me to Wilmington—which is 45 minutes from base. TRICARE's civilian referral network here has a 16-week wait. I moved to Wilmington for quality of life. I'm still waiting for quality of healthcare." details="<strong>Patient Profile:</strong> Lauren, 32, Marine Spouse living in Wilmington.<br/><br/><strong>The Challenge:</strong> Lives in Wilmington for schools, husband at Camp Lejeune. TRICARE civilian referral to NHRMC 16 weeks. Wilmington's beach culture emphasizes fitness she can't access through the system.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Porters Neck. NC-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Port, Beach, and the Marine Overflow" paragraphs={["Wilmington sits between the Cape Fear River and the Atlantic Ocean—a coastal city with a film industry (EUE/Screen Gems Studios), a growing tech sector, and a retirement community drawn by the beach lifestyle. Camp Lejeune (45 min north) sends military families into Wilmington for schools, housing, and civilian specialist care.","The food culture is coastal Carolina: shrimp and grits (Wilmington's version), fried seafood, oyster roasts, and the Southern comfort traditions of Eastern NC. The Wrightsville Beach and Carolina Beach scenes add a health-conscious overlay, but the working population eats at the restaurants on Market Street and College Road.","NHRMC (New Hanover Regional Medical Center, now Novant Health) is the dominant system. It serves both the Wilmington population and the Camp Lejeune overflow—a dual burden that stretches specialist capacity.","GLP-1 medications serve Wilmington's Marine families, retirees, and coastal workforce—delivering metabolic care without the NHRMC waitlist or the drive back to Camp Lejeune."]} citations={["New Hanover County Health Department. (2025). <em>Community Health Assessment</em>.","UNCW College of Health and Human Services. (2024). <em>Military Family Healthcare Access in Southeastern North Carolina</em>."]} />
      <InsuranceBreakdown title="Port, Marines, and the Beach Economy" text="Wilmington's economy blends port, military overflow, film, and retirement." employers={[{name:"Camp Lejeune Overflow (TRICARE)",detail:"Marine families using civilian network. 14-18 week specialist waits."},{name:"Novant Health NHRMC",detail:"Dominant system serves both civilian and military populations."},{name:"GE Hitachi / Corning / Film Industry",detail:"Manufacturing and entertainment plans with standard restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Wilmington" localCompetitors={[{name:"Porters Neck / Landfall Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Market St MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"NHRMC Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Market St Traffic & NHRMC Waitlists" transitText="Wilmington's Market Street corridor is perpetually gridlocked. Raleigh is 2.5 hours NW. Camp Lejeune/Jacksonville is 45 min north." hospitalText="<strong>Novant Health NHRMC</strong> serves the Cape Fear region." />
      <InteractiveFAQ faqs={[{q:"My husband is at Camp Lejeune. I live in Wilmington. Which state?",a:"North Carolina. Both are NC."},{q:"Do you deliver to Wrightsville Beach and Leland?",a:"Yes. All New Hanover, Brunswick, and Pender County addresses."}]} />
      <StateLegalFramework stateName="North Carolina" boardName="North Carolina Medical Board" text="Telehealth FX operates in compliance with the <strong>NC Medical Board</strong> and NCGS § 90." />
      <DeliveryGridMap cityName="Wilmington" mapQuery="Wilmington, NC" coordinates="34.2257° N, 77.9447° W" counties="New Hanover County, Brunswick County, Pender County" neighborhoods={['Porters Neck','Monkey Junction','Leland','Wrightsville Beach','Carolina Beach','Hampstead','Ogden']} />
      <FinalCTA stateName="North Carolina" />
    </div>
  );
}
