"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationColumbusGA() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Georgia" cityName="Columbus" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Columbus, GA</span>" subheadline="Columbus is home to Fort Moore—formerly Fort Benning—the US Army's Maneuver Center of Excellence. Every infantry and armor officer, every Ranger, and every airborne soldier earns their tabs here. The installation adds 30,000+ soldiers and families to a city whose healthcare system was designed for a fraction of that population." dataPoint1="Muscogee County's adult obesity rate exceeds 35%. Fort Moore's 30,000+ military and family population overwhelms the civilian specialist capacity. Atlanta's Emory is 2 hours north." dataPoint2="Telehealth FX serves the infantry community and Columbus without the I-185 drive to Atlanta." />
      <PatientArchetype archetype="The Fort Moore Ranger Instructor" quote="I teach at the Ranger Training Brigade—leading students through 62 days of the most physically demanding course in the military. But I'm 38 now. The caloric demands of Ranger School don't match my metabolism anymore. I eat the same MREs and DFAC food as 22-year-old students. Martin Army Community Hospital's specialist referral is 20 weeks. I train Rangers. I can't get an endocrinology appointment." details="<strong>Patient Profile:</strong> SFC Torres, 38, Ranger Instructor (RI), RTB, Fort Moore.<br/><br/><strong>The Challenge:</strong> Ranger School caloric intake at age 38. MRE/DFAC food designed for 22-year-old students. Martin Army specialist wait 20 weeks. Atlanta 2 hours north.<br/><br/><strong>The Intervention:</strong> Completed intake from off-post in Columbus. GA-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="Where Every Infantry Soldier Begins" paragraphs={["Fort Moore is where the US Army makes its infantry officers, armor officers, Rangers, and airborne soldiers. The Maneuver Center of Excellence processes thousands of soldiers annually through IBOLC, ABOLC, Ranger School, and Airborne School. The permanent party—instructors, drill sergeants, and support staff—live in Columbus alongside one of the largest military training populations in the Army.","The food environment is military-town standard amplified: Victory Drive fast food strip, the DFAC at multiple training sites, and MREs during field problems. Ranger Instructors eat MREs for weeks during each Ranger class cycle.","The civilian food culture is Southern Georgia: BBQ (Country's Barbecue is a Columbus institution), fried everything, and the meat-and-three tradition.","Piedmont Columbus Regional (formerly Midtown Medical Center) and St. Francis-Emory Healthcare serve the civilian population. Martin Army Community Hospital serves the military. Atlanta's Emory is 2 hours north on I-185/I-85 for complex specialist care."]} citations={["Columbus Health Department. (2025). <em>Muscogee County Community Health Assessment</em>.","Columbus State University. (2024). <em>Military-Civilian Healthcare Access in the Chattahoochee Valley</em>."]} />
      <InsuranceBreakdown title="Fort Moore and the Infantry Capital" text="Columbus' economy is dominated by the military installation." employers={[{name:"Fort Moore / MCoE (TRICARE)",detail:"30,000+ soldiers and families. Martin Army specialist waits 18-22 weeks."},{name:"Piedmont Columbus / St. Francis-Emory",detail:"Civilian systems absorb military overflow."},{name:"AFLAC (HQ) / Synovus",detail:"Corporate HQs add plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Columbus GA" localCompetitors={[{name:"North Columbus / Midland Concierge",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"Manchester Expwy MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Martin Army / Piedmont Endocrinology",cost:"$0-100 Copay",consult:"18-22 Week Wait",access:"Referral Chain"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-185 & Martin Army Waitlists" transitText="Columbus sits on I-185. Atlanta/Emory is 2 hours north. Macon is 90 min NE. Auburn AL is 35 min west." hospitalText="<strong>Martin Army</strong> serves military. <strong>Piedmont Columbus</strong> serves civilians." />
      <InteractiveFAQ faqs={[{q:"I'm an RI. Will this affect my Ranger tab status?",a:"Consult your unit surgeon. Telehealth FX is independent of military medical records."},{q:"Do you deliver to Phenix City and Fort Moore?",a:"Yes. All Muscogee, Russell (AL), and Harris County addresses."}]} />
      <StateLegalFramework stateName="Georgia" boardName="Georgia Composite Medical Board" text="Telehealth FX operates in compliance with the <strong>Georgia Composite Medical Board</strong>." />
      <DeliveryGridMap cityName="Columbus" mapQuery="Columbus, GA" coordinates="32.4610° N, 84.9877° W" counties="Muscogee County, Harris County, Russell County AL" neighborhoods={['North Columbus','Midland','Phenix City AL','Fort Moore','Smiths Station','Hamilton','Cataula']} />
      <FinalCTA stateName="Georgia" />
    </div>
  );
}
