"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSpokane() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Washington" cityName="Spokane" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Spokane</span>" subheadline="Spokane is the largest city between Seattle and Minneapolis—280 miles from the coast's medical infrastructure. The Inland Northwest is medically isolated, with specialist capacity serving a catchment area from Idaho to the Cascades." ctaText="Check Washington Eligibility" />
      <PatientArchetype archetype="The Fairchild AFB KC-135 Crew Chief" quote="I maintain KC-135 tankers at Fairchild. 12-hour shifts on the flight line, 105 in summer, -10 in winter. TRICARE has a 16-week specialist wait. Seattle is 4.5 hours over two mountain passes." details="<strong>Patient Profile:</strong> TSgt Rivera, 34, Crew Chief at Fairchild AFB.<br/><br/><strong>The Challenge:</strong> TRICARE referrals feed into a civilian network already stretched thin. Seattle is 280 miles and two mountain passes away.<br/><br/><strong>The Intervention:</strong> Completed intake from Airway Heights. WA-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Inland Northwest's Medical Island" paragraphs={["Spokane serves as the medical hub for the entire Inland Northwest—eastern Washington, the Idaho panhandle, and parts of Montana. Providence Sacred Heart and MultiCare Deaconess treat not just Spokane's 230,000 residents but provide specialist referral services for over 1 million people across a vast geographic area.","The isolation is absolute. Seattle is 280 miles west across two mountain passes. Portland is 350 miles. Boise is 300 miles south. The nearest alternative specialist is not accessible for routine metabolic care.","Spokane's food culture is Pacific Northwest comfort—craft beer, steakhouses, and hearty meals that cold winters demand. The modern economy (healthcare, education, Fairchild AFB) is predominantly sedentary, but the food tradition was built for physical labor.","GLP-1 medications deliver specialist-grade metabolic care to a region where the nearest alternative requires crossing mountain passes."]} citations={["Spokane Regional Health District. (2025). <em>Community Health Assessment</em>.","WSU College of Medicine. (2024). <em>Healthcare Access in the Inland Northwest</em>."]} />
      <InsuranceBreakdown title="Fairchild, Healthcare, and the Inland Economy" text="Spokane's employers span military, healthcare, and education." employers={[{name:"Fairchild AFB (TRICARE)",detail:"Military population competes with civilians for limited specialist pool."},{name:"Providence / MultiCare",detail:"Health systems employ thousands facing the same formulary restrictions."},{name:"Gonzaga / WSU Spokane",detail:"Education employers offer standard PBM GLP-1 restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in Spokane" localCompetitors={[{name:"South Hill Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Division St MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"Providence Endocrinology",cost:"$125 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="No Mountain Pass Alternatives" transitText="Spokane connects to Seattle via I-90 (280 miles, two passes) and to Boise via US-95 (300 miles). There is no nearby alternative metro." hospitalText="<strong>Providence Sacred Heart</strong> and <strong>MultiCare Deaconess</strong> serve the Inland Northwest. Specialist waits average 14-18 weeks." />
      <InteractiveFAQ faqs={[{q:"I live in Coeur d'Alene (Idaho). Which state?",a:"Idaho. You'll be evaluated by an ID-licensed physician. We serve both WA and ID across the Inland Northwest."},{q:"Do you deliver to Spokane Valley?",a:"Yes. All Spokane County and Kootenai County (ID) addresses."}]} />
      <StateLegalFramework stateName="Washington" boardName="Washington Medical Commission" text="Telehealth FX operates in compliance with the <strong>Washington Medical Commission</strong> and RCW 18.71." />
      <DeliveryGridMap cityName="Spokane" mapQuery="Spokane, WA" coordinates="47.6588° N, 117.4260° W" counties="Spokane County (WA), Kootenai County (ID)" neighborhoods={['South Hill','Spokane Valley','Liberty Lake','Airway Heights',"Coeur d'Alene (ID)",'Post Falls (ID)']} />
      <FinalCTA stateName="Washington" />
    </div>
  );
}
