"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationErie() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Pennsylvania" cityName="Erie" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Erie</span>" subheadline="Erie is Pennsylvania's only Great Lakes city—isolated in the state's NW corner, closer to Cleveland and Buffalo than to any other Pennsylvania city. GE Transportation (now Wabtec) built locomotives here for over a century. The lake-effect snow averages 100+ inches annually, creating 5 months of forced indoor living." dataPoint1="Erie County's adult obesity rate exceeds 33%. Lake-effect snow creates a Fargo-like indoor confinement problem, but without Fargo's agricultural wealth. Post-industrial decline has left Erie with fewer specialists per capita than any metro in Pennsylvania." dataPoint2="Telehealth FX delivers metabolic care through Erie's lake-effect winters without the 2-hour drive to Pittsburgh or Cleveland." />
      <PatientArchetype archetype="The Wabtec Locomotive Assembly Worker" quote="I assemble diesel-electric locomotives at the Wabtec plant—what used to be GE Transportation. The plant went from 6,000 workers to under 2,000. The ones left work harder. I'm on my feet for the physical work but sitting for the control systems. Erie gets 100 inches of snow. I haven't been outside for exercise since November. UPMC Hamot has a 14-week specialist wait." details="<strong>Patient Profile:</strong> Mark, 48, Locomotive Assembly, Wabtec (formerly GE Transportation).<br/><br/><strong>The Challenge:</strong> Post-downsizing workload increase. 100+ inches lake-effect snow. UPMC Hamot specialist wait 14 weeks. Pittsburgh is 2 hours south.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Millcreek. PA-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Lake-Effect Snow and the Locomotive Legacy" paragraphs={["Erie's lake-effect snow belt is among the most severe in the eastern US. The lake-effect machine—cold air over warm Lake Erie water—dumps 100+ inches annually, primarily between November and March. Unlike Buffalo (which at least has a major metro's medical infrastructure), Erie's isolation in NW Pennsylvania means the snow traps residents in a city with limited specialist capacity.","GE Transportation built Erie's middle class for over a century. The transition to Wabtec reduced the workforce dramatically. The remaining manufacturing base (Wabtec, Erie Indemnity, Eriez Magnetics) sustains the economy but at a smaller scale.","The food culture is Rust Belt Great Lakes: pepperoni balls (Erie's signature—breaded, deep-fried dough balls stuffed with pepperoni), fish fry (walleye from Lake Erie), pierogies, and the Polish-Italian immigrant food traditions.","UPMC Hamot (Erie's primary hospital, part of the Pittsburgh UPMC system) and Saint Vincent Hospital (Allegheny Health Network) serve the county. Both are community-level facilities with specialist capacity appropriate for a shrinking city."]} citations={["Erie County Health Department. (2025). <em>Community Health Assessment</em>.","Gannon University. (2024). <em>Lake-Effect Climate, Post-Industrial Health, and Specialist Access in NW Pennsylvania</em>."]} />
      <InsuranceBreakdown title="Locomotives, Lake-Effect, and the Rust Belt" text="Erie's economy centers on remaining manufacturing and healthcare." employers={[{name:"Wabtec / Eriez Magnetics",detail:"Manufacturing plans with union/corporate Step Therapy."},{name:"UPMC Hamot / Saint Vincent",detail:"Health systems serve NW PA with 12-16 week specialist waits."},{name:"Erie Insurance (HQ)",detail:"Corporate HQ plan adds volume."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Erie" localCompetitors={[{name:"Millcreek / Harborcreek Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Peach St MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"UPMC Hamot Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="PA's Most Isolated Metro" transitText="Erie sits on I-90. Pittsburgh is 2 hours south. Cleveland is 90 min west. Buffalo is 90 min east." hospitalText="<strong>UPMC Hamot</strong> and <strong>Saint Vincent</strong> serve NW Pennsylvania." />
      <InteractiveFAQ faqs={[{q:"It's January. 100 inches of snow. How fast?",a:"USPS Priority Mail. Winter weather may add 1-2 days during lake-effect events."},{q:"Do you deliver to Millcreek and Harborcreek?",a:"Yes. All Erie County addresses."}]} />
      <StateLegalFramework stateName="Pennsylvania" boardName="Pennsylvania State Board of Medicine" text="Telehealth FX operates in compliance with the <strong>PA State Board of Medicine</strong>." />
      <DeliveryGridMap cityName="Erie" mapQuery="Erie, PA" coordinates="42.1292° N, 80.0851° W" counties="Erie County" neighborhoods={['Millcreek','Harborcreek','Fairview','Edinboro','Corry','Girard','North East','Wesleyville']} />
      <FinalCTA stateName="Pennsylvania" />
    </div>
  );
}
