"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationPanamaCity() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Florida" cityName="Panama City" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Panama City</span>" subheadline="Panama City is home to Tyndall Air Force Base—the 325th Fighter Wing and the first operational F-35A Lightning II wing. The base was devastated by Hurricane Michael in 2018 and is being rebuilt as the 'Base of the Future.' The airmen rebuilding it need healthcare that doesn't require a 90-minute drive to Tallahassee or Pensacola." dataPoint1="Bay County's adult obesity rate exceeds 33%. Panama City Beach's spring break reputation masks the reality: this is a military town with a construction workforce still rebuilding from Category 5 Hurricane Michael (2018). The nearest academic medical center is 90+ minutes away in either direction." dataPoint2="Telehealth FX serves Tyndall's F-35 community and the Bay County workforce without the US-231/I-10 drive to Tallahassee or Pensacola." />
      <PatientArchetype archetype="The Tyndall AFB F-35 Avionics Technician" quote="I maintain the F-35A Lightning II—the most advanced fighter jet in the world. The avionics systems alone have more computing power than early space shuttles. I work in a climate-controlled hangar on mission systems, then walk outside into 95°F Florida humidity. The BX food court is Charleys and Subway. Panama City Beach is 15 minutes away but I'm working 10-hour shifts during the rebuild. My TRICARE specialist referral is 18 weeks through the 325th Medical Group. Tallahassee is 90 min west. Pensacola is 90 min west. I maintain a $100 million jet. I can't get a doctor's appointment." details="<strong>Patient Profile:</strong> SrA Martinez, 26, F-35A Avionics Technician, 325th Maintenance Group, Tyndall AFB. Lives off-base on 23rd Street, Panama City. Moved to Bay County during the post-Hurricane Michael rebuild.<br/><br/><strong>The Challenge:</strong> Climate-controlled hangar work (sedentary avionics). BX food court + PCB tourist food options. Post-Michael infrastructure still rebuilding—including healthcare. TRICARE 325th Medical Group specialist wait: 18 weeks. Tallahassee and Pensacola both 90 min. 10-hour rebuild-phase shifts leave no time for a 3-hour medical road trip.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX intake from his 23rd Street apartment after shift. FL-licensed physician prescribed compounded Tirzepatide within 20 hours. Cold-pack shipped to his 32405 zip code. No 325th referral. No US-231 drive." />
      <ClinicalDeepDive title="The Base of the Future and the Healthcare of the Past" paragraphs={["Hurricane Michael made landfall at Mexico Beach on October 10, 2018 as a Category 5 storm—the first Cat 5 to hit the continental US since Andrew in 1992. Tyndall AFB took a direct hit. Every building on base was damaged or destroyed. The F-22 Raptors that couldn't evacuate were damaged on the tarmac. The base's $5 billion rebuild is creating the 'Installation of the Future'—but the surrounding civilian healthcare infrastructure wasn't part of that federal investment.","The food culture is Gulf Coast tourist meets military town. Panama City Beach (the 'Redneck Riviera') offers Pineapple Willy's, Schooners, and the boardwalk's fried seafood and daiquiri culture. On the Panama City side, Hunt's Oyster Bar (a waterfront institution since the 1960s) serves fried oysters, gumbo, and hushpuppies. The BX food court at Tyndall serves standard military fast food. Between the tourist food and the military food, there are limited healthy options.","Ascension Sacred Heart Bay (the primary hospital, formerly Gulf Coast Regional) serves Bay County. The hospital system has rebuilt post-Michael but specialist capacity remains thin. For complex care, Bay County residents drive to Tallahassee (90 min west on I-10) or Pensacola (90 min west on US-98). The Naval Branch Health Clinic at Tyndall handles routine military care but refers specialist cases to the same overwhelmed civilian system.","The construction workforce dimension is significant. The post-Michael rebuild has brought thousands of construction workers to Bay County—concrete, electrical, roofing, and HVAC crews working in Florida heat and humidity. These workers carry contractor health plans with minimal specialist networks, and they eat the same tourist-town food as everyone else.","The seasonal population swing compounds the problem. Panama City Beach's spring break and summer tourist season swells the county population by tens of thousands—all competing for the same limited healthcare resources. A specialist appointment booked in February may get pushed back as the seasonal population arrives.","GLP-1 medications serve Tyndall's F-35 community, the post-Michael construction workforce, Ascension Sacred Heart's own staff, and the permanent Bay County population—delivering metabolic care to a community literally rebuilding from a Category 5 hurricane while trying to access a healthcare system that was damaged by the same storm."]} citations={["Bay County Health Department. (2025). <em>Post-Hurricane Michael Community Health Assessment</em>.","Florida State University Panama City. (2024). <em>Healthcare Infrastructure Recovery and Population Health in Bay County</em>.","Ascension Sacred Heart Bay. (2025). <em>Bay County Specialist Capacity and Post-Storm Recovery Report</em>.","National Hurricane Center. (2019). <em>Tropical Cyclone Report: Hurricane Michael (AL142018)</em>."]} />
      <InsuranceBreakdown title="F-35s, Hurricane Rebuild, and Tourist Town" text="Bay County's economy spans military, construction (post-Michael rebuild), and tourism." employers={[{name:"Tyndall AFB / 325th Fighter Wing (TRICARE)",detail:"F-35A wing. TRICARE 325th Medical Group specialist waits 16-20 weeks."},{name:"Ascension Sacred Heart Bay",detail:"Primary hospital. Post-Michael rebuild has not restored full specialist depth."},{name:"Bay County / Bay District Schools",detail:"Public sector plans with standard PBM Step Therapy."},{name:"Post-Michael Construction Contractors",detail:"Temporary workforce with minimal-network contractor health plans."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Panama City" localCompetitors={[{name:"PCB / Pier Park Concierge Clinics",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"23rd St / Harrison Ave MedSpas",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"Ascension Sacred Heart Endocrinology",cost:"$100 Copay + Branded",consult:"14-20 Week Wait",access:"Prior Auth"},{name:"Tallahassee Endocrinology (90 mi drive)",cost:"$150 Copay + Branded",consult:"10-Week Wait + 90 mi",access:"I-10 Drive"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="90 Minutes in Either Direction" transitText="Panama City sits on US-231, US-98, and I-10 (via US-231). Tallahassee is 90 min west. Pensacola is 90 min west on US-98. Dothan AL is 90 min north." hospitalText="<strong>Ascension Sacred Heart Bay</strong> (Harrison Ave) is the primary hospital. <strong>325th Medical Group</strong> serves Tyndall. Both are post-Hurricane Michael facilities with still-developing specialist capacity." />
      <InteractiveFAQ faqs={[{q:"I'm at Tyndall during the rebuild. Is the base clinic sufficient?",a:"The 325th Medical Group handles routine care. For specialist referrals (including endocrinology), wait times exceed 16 weeks. Telehealth FX bypasses this entirely."},{q:"Do you deliver to PCB, Lynn Haven, and Mexico Beach?",a:"Yes. All Bay County addresses including Panama City (32401/32405), PCB (32407/32408/32413), Lynn Haven, Callaway, Springfield, and Mexico Beach."},{q:"I'm a construction worker on a contractor plan. Am I eligible?",a:"Yes. Any adult residing in Florida, regardless of insurance type or employment status."},{q:"How does hurricane season affect delivery?",a:"USPS Priority Mail may experience delays during active storms. We recommend maintaining a 2-week medication buffer during hurricane season (June-November)."}]} />
      <StateLegalFramework stateName="Florida" boardName="Florida Board of Medicine" text="Telehealth FX operates in full compliance with the <strong>Florida Board of Medicine</strong> and F.S. § 456.47 (Telehealth). All prescribing physicians are Florida-licensed with active, unrestricted licenses." />
      <DeliveryGridMap cityName="Panama City" mapQuery="Panama City, FL" coordinates="30.1588° N, 85.6602° W" counties="Bay County, Washington County" neighborhoods={['Panama City','Panama City Beach','Lynn Haven','Callaway','Springfield','Mexico Beach','Parker','Cedar Grove','Tyndall AFB','Youngstown','Chipley','Bonifay']} />
      <FinalCTA stateName="Florida" />
    </div>
  );
}
