"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationBillings() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Montana" cityName="Billings" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Billings</span>" subheadline="Billings is the largest city in Montana—and the regional medical hub for a geographic area larger than most Eastern states combined. The 'Magic City' serves all of eastern Montana, northern Wyoming, and western North Dakota. The nearest alternative medical center is 3+ hours away in any direction." ctaText="Check Montana Eligibility" />
      <PatientArchetype archetype="The Bakken Oil Field Rotational Worker" quote="I work two weeks on, two weeks off at the Bakken oil fields—driving pipe on a drilling rig near Sidney, 250 miles from Billings. My 'on' weeks are 14-hour shifts eating rig food. My 'off' weeks in Billings are recovery eating. My Billings Clinic plan has a 16-week wait for endocrinology. The nearest alternative is... there is no alternative." details="<strong>Patient Profile:</strong> Jake, 33, Roughneck/Rotational Worker, Bakken Formation.<br/><br/><strong>The Challenge:</strong> 2-weeks-on/2-weeks-off oil field rotation. Rig food + recovery binge cycle. Billings Clinic is the only specialist option for a geographic area spanning 3 states.<br/><br/><strong>The Intervention:</strong> Completed intake during off-rotation week in Billings. MT-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Magic City Serves a Territory" paragraphs={["Billings serves as the medical referral center for eastern Montana, northern Wyoming (Sheridan, Gillette, Cody), and western North Dakota (Williston, Sidney). This is a geographic catchment area of approximately 200,000 square miles—larger than California. The specialist capacity at Billings Clinic and St. Vincent Healthcare cannot proportionally serve a territory this vast.","The Bakken oil formation sends rotational workers into Billings for off-weeks. The drilling industry's 2-on/2-off schedule creates a binge-recovery eating cycle that is metabolically devastating: rig food (high-calorie, institutional) for 14 days, followed by restaurant and comfort food for 14 days.","Montana's food culture is ranching-heritage: beef at every meal, wild game (elk, deer, antelope), and the bar food that defines small-town Montana dining. Billings' restaurant scene has grown, but the caloric default remains meat-heavy.","GLP-1 medications serve Billings' oil field workers, ranching community, and healthcare workers—delivering metabolic care across the largest medical service area in the lower 48."]} citations={["RiverStone Health. (2025). <em>Yellowstone County Community Health Assessment</em>.","Montana State University Billings. (2024). <em>Healthcare Access in the Northern Rockies and Great Plains</em>."]} />
      <InsuranceBreakdown title="Oil, Ranching, and the Magic City" text="Billings' economy spans energy, ranching, healthcare, and refining." employers={[{name:"Bakken Oil Field Operators",detail:"Rotational workers have employer or union plans with limited Montana specialist networks."},{name:"Billings Clinic / St. Vincent Healthcare",detail:"The only two hospital systems for 200,000 square miles."},{name:"CHS Refinery / ExxonMobil (Billings)",detail:"Refinery plans with standard PBM restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Billings" localCompetitors={[{name:"West End / Shiloh Rd Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"24th St MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Billings Clinic Endocrinology",cost:"$100 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="200,000 Square Miles, Two Hospitals" transitText="Billings sits on I-90 and I-94. Denver is 9 hours south. Minneapolis is 12 hours east. There is no nearby alternative." hospitalText="<strong>Billings Clinic</strong> and <strong>St. Vincent Healthcare</strong> serve the Northern Rockies/Plains." />
      <InteractiveFAQ faqs={[{q:"I'm on a 2-on/2-off rotation. When?",a:"Anytime during your off-rotation. Fully asynchronous."},{q:"Do you deliver to Laurel, Bozeman, and Miles City?",a:"Yes. All Montana addresses."}]} />
      <StateLegalFramework stateName="Montana" boardName="Montana Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>MT Board of Medical Examiners</strong> and MCA § 37-3." />
      <DeliveryGridMap cityName="Billings" mapQuery="Billings, MT" coordinates="45.7833° N, 108.5007° W" counties="Yellowstone County" neighborhoods={['West End','Heights','Lockwood','Laurel','Shepherd','Worden','Bozeman','Miles City']} />
      <FinalCTA stateName="Montana" />
    </div>
  );
}
