"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationKnoxville() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Tennessee" cityName="Knoxville" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Knoxville</span>" subheadline="Knoxville is the gateway to the Great Smoky Mountains and home to the University of Tennessee. The Vols' tailgate tradition, the Appalachian food heritage, and a healthcare system anchored by UT Medical Center create a metabolic environment where Saturday football and Sunday church dinners define the caloric week." dataPoint1="Knox County's adult obesity rate exceeds 33%. The combination of Appalachian comfort food traditions, a university-centered social eating culture, and a healthcare system serving the broader East Tennessee region stretches specialist capacity thin." dataPoint2="Telehealth FX serves the Vol Nation workforce—UT employees, Oak Ridge scientists, and the East Tennessee community—without competing for UT Medical Center's limited specialist appointments." />
      <PatientArchetype archetype="The Oak Ridge National Lab Research Scientist" quote="I work at ORNL designing next-generation nuclear reactor simulations. My job is intellectually demanding and completely sedentary. I sit in front of computational models for 10 hours a day. The ORNL cafeteria is decent but I default to comfort food under deadline pressure. My UT Health plan has a 12-week wait for endocrinology. I can model the half-life of a nuclear isotope but I can't get a doctor's appointment in less than 3 months." details="<strong>Patient Profile:</strong> Dr. Chen, 44, Computational Physicist at Oak Ridge National Laboratory.<br/><br/><strong>The Challenge:</strong> Sedentary intellectual work, deadline-driven stress eating, and a healthcare system that serves all of East Tennessee create specialist access barriers. His UT-administered plan has standard formulary restrictions.<br/><br/><strong>The Intervention:</strong> Completed intake from his home in Farragut. A TN-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Vol Nation's Caloric Tradition" paragraphs={["Knoxville's metabolic environment is shaped by two forces: the University of Tennessee and Appalachian food heritage. UT football Saturdays at Neyland Stadium (capacity: 102,000) are accompanied by tailgate spreads that rival any in the SEC—smoked pork, Brunswick stew, pimento cheese, deviled eggs, and beer. This is a 7-game-season ritual that adds thousands of calories across fall weekends.","The Appalachian food tradition extends beyond football. Biscuits and gravy, country ham, soup beans and cornbread, and the church dinner tradition (fried chicken, casseroles, desserts) create a weekly caloric pattern that is deeply embedded in community and family identity.","Oak Ridge National Laboratory—30 minutes west of Knoxville—adds a high-skill scientific workforce to the metro. ORNL's 6,000+ employees include some of the most brilliant minds in American science, working in conditions (secure facilities, computational labs, reactor buildings) that are uniformly sedentary.","GLP-1 medications serve both the Vol Nation community and the ORNL scientific workforce—restoring metabolic signaling without requiring anyone to skip a tailgate or eat a sad desk salad in a computational physics lab."]} citations={["Knox County Health Department. (2025). <em>Community Health Assessment</em>.","UT College of Medicine. (2024). <em>Food Culture, University Communities, and Metabolic Health in East Tennessee</em>."]} />
      <InsuranceBreakdown title="UT System, ORNL, and the Smoky Mountain Catchment" text="Knoxville's economy is dominated by the University of Tennessee and the federal research complex at Oak Ridge." employers={[{name:"University of Tennessee / UT Medical Center",detail:"UT is Knoxville's largest employer. Plans impose standard formulary restrictions for GLP-1s."},{name:"Oak Ridge National Laboratory / Y-12 (DOE)",detail:"Federal research employees have FEHB or contractor plans with standard PBM restrictions."},{name:"Covenant Health / Tennova",detail:"Regional health systems serve East Tennessee with limited specialist capacity."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in Knoxville" localCompetitors={[{name:"Farragut / Sequoyah Hills Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Kingston Pike MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"UT Medical Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-40/I-75 & UT Medical Waitlists" transitText="Knoxville sits at the junction of I-40 and I-75. Commuting from Oak Ridge (via Pellissippi Parkway) or from Maryville/Sevierville takes 30-45 minutes." hospitalText="<strong>UT Medical Center</strong> and <strong>Covenant Health</strong> serve East Tennessee. Specialist waits average 10-14 weeks." />
      <InteractiveFAQ faqs={[{q:"I work at ORNL. Is this separate from my federal benefits?",a:"Yes. Telehealth FX is independent of FEHB and your DOE employment."},{q:"Do you deliver to Oak Ridge, Farragut, and Maryville?",a:"Yes. All Knox, Anderson, Blount, and Loudon County addresses."}]} />
      <StateLegalFramework stateName="Tennessee" boardName="Tennessee Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>Tennessee Board of Medical Examiners</strong> and TCA § 63-1-155." />
      <DeliveryGridMap cityName="Knoxville" mapQuery="Knoxville, TN" coordinates="35.9606° N, 83.9207° W" counties="Knox County, Anderson County, Blount County, Loudon County" neighborhoods={['Farragut','Bearden','Sequoyah Hills','Oak Ridge','Maryville','Powell','Lenoir City']} />
      <FinalCTA stateName="Tennessee" />
    </div>
  );
}
