"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationClarksville() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Tennessee" cityName="Clarksville" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Clarksville</span>" subheadline="Clarksville is home to Fort Campbell—the 101st Airborne Division (Air Assault). The 'Screaming Eagles' and their families depend on Blanchfield Army Community Hospital, which serves 30,000+ soldiers and families with specialist capacity designed for a fraction of that population." ctaText="Check Tennessee Eligibility" />
      <PatientArchetype archetype="The 101st Airborne Gold Star Wife" quote="My husband was killed in action. I stayed in Clarksville because this is where our community is—the other Gold Star families, the support groups, my kids' school. But the grief, the antidepressants, the emotional eating—I've gained 60 pounds in 3 years. Blanchfield's specialist wait is 18 weeks. I gave this country everything. I can't get a doctor's appointment." details="<strong>Patient Profile:</strong> Amanda, 34, Gold Star Spouse, Clarksville.<br/><br/><strong>The Challenge:</strong> KIA grief, antidepressant-induced weight gain, emotional eating. Stayed near Fort Campbell for community. Blanchfield specialist wait 18 weeks. TRICARE benefits continue but access doesn't.<br/><br/><strong>The Intervention:</strong> Completed intake from home in St. Bethlehem. TN-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Screaming Eagles' Longest Wait" paragraphs={["Fort Campbell straddles the Tennessee-Kentucky border, but Clarksville is the primary off-post community. The 101st Airborne is one of the most deployed divisions in the US Army—Iraq, Afghanistan, and now rotational deployments to Europe. The deployment cycle creates the same spouse stress-eating pattern documented at Fort Cavazos and JBLM.","Blanchfield Army Community Hospital serves the military population, but its specialist capacity reflects a community hospital, not a major medical center. The nearest academic center is Vanderbilt (Nashville, 50 minutes southeast)—close enough to be theoretically accessible but far enough to require a half-day commitment.","Clarksville's food environment is military-town standard: Gate 1-10 fast food corridors, Wilma Rudolph Boulevard chain restaurants, and the limited options that define military community dining. Nashville's food scene is 50 minutes away but inaccessible to a solo-parenting military spouse.","GLP-1 medications serve the 101st Airborne community—active duty, spouses, Gold Star families, and retirees—delivering metabolic care without the Blanchfield wait or the Nashville drive."]} citations={["Montgomery County Health Department. (2025). <em>Community Health Assessment—Clarksville-Montgomery County</em>.","Austin Peay State University. (2024). <em>Military Family Health Outcomes in the Fort Campbell Community</em>."]} />
      <InsuranceBreakdown title="Fort Campbell and the 101st" text="Clarksville's economy is overwhelmingly military." employers={[{name:"Fort Campbell / 101st ABN (TRICARE)",detail:"30,000+ soldiers. Blanchfield specialist waits 16-20 weeks."},{name:"Tennova Healthcare",detail:"Civilian system absorbs military overflow."},{name:"Hankook Tire / LG Electronics",detail:"Manufacturing employers add plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Clarksville" localCompetitors={[{name:"St. Bethlehem / Sango Clinics",cost:"$400-$700/mo",consult:"In-Person",access:"Limited"},{name:"Wilma Rudolph Blvd MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Blanchfield Endocrinology",cost:"$0 (TRICARE)",consult:"16-20 Week Wait",access:"Referral Chain"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Blanchfield & the Nashville Drive" transitText="Clarksville is 50 min NW of Nashville on I-24. Fort Campbell's gates add 15-20 min to any on-post appointment." hospitalText="<strong>Blanchfield ACMH</strong> serves the military. <strong>Tennova</strong> serves civilians." />
      <InteractiveFAQ faqs={[{q:"I'm a Gold Star spouse. Do I still have TRICARE?",a:"Yes. And Telehealth FX is completely independent of TRICARE."},{q:"Do you deliver to Fort Campbell and Oak Grove KY?",a:"Yes. All Montgomery County TN and Christian County KY addresses."}]} />
      <StateLegalFramework stateName="Tennessee" boardName="Tennessee Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>TN Board of Medical Examiners</strong>." />
      <DeliveryGridMap cityName="Clarksville" mapQuery="Clarksville, TN" coordinates="36.5298° N, 87.3595° W" counties="Montgomery County TN, Christian County KY" neighborhoods={['St. Bethlehem','Sango','Exit 4','Oak Grove KY','Hopkinsville KY','Pleasant View']} />
      <FinalCTA stateName="Tennessee" />
    </div>
  );
}
