"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationPensacola() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Florida" cityName="Pensacola" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Pensacola</span>" subheadline="Pensacola is the Cradle of Naval Aviation—NAS Pensacola trains every Navy and Marine Corps pilot. The Blue Angels are based here. But the military families, the retiree community, and the Gulf Coast working population all compete for specialist appointments in Florida's most geographically isolated metro." dataPoint1="Escambia County's adult obesity rate exceeds 34%. Pensacola is closer to Mobile, AL than to any other Florida city. The nearest major Florida medical center (Gainesville/UF Health) is 5 hours east." dataPoint2="Telehealth FX serves the NAS Pensacola community, the Blue Angels support families, and the Gulf Coast workforce—without the 5-hour drive to Gainesville." />
      <PatientArchetype archetype="The NAS Pensacola Flight Instructor" quote="I train student naval aviators at NAS Pensacola. The stress of teaching people to fly jets is significant. The Officers' Club food is decent but the base food court is Subway and Charley's. My TRICARE specialist referral is 16 weeks at Naval Hospital Pensacola. I teach pilots to break the sound barrier. I can't break through a specialist waitlist." details="<strong>Patient Profile:</strong> LCDR Williams, 38, Primary Flight Instructor at NAS Pensacola.<br/><br/><strong>The Challenge:</strong> High-stress flight instruction. Base food environment. TRICARE specialist wait 16 weeks. Nearest Florida medical center 5 hours east.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Gulf Breeze. FL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Cradle of Naval Aviation's Ground-Level Problem" paragraphs={["Every Navy and Marine Corps aviator in history trained at NAS Pensacola. The Blue Angels practice here. The National Naval Aviation Museum draws visitors from around the world. But the permanent military population, their families, and the civilian support workforce face the same healthcare access challenge as every other military community—amplified by geographic isolation.","Pensacola is Florida's most isolated metro. Mobile, AL (60 miles west) is the nearest alternative city. Tallahassee is 3 hours east. Jacksonville is 5 hours. Gainesville/UF Health is 5+ hours. When Naval Hospital Pensacola can't provide specialist care, there is no nearby civilian alternative.","The Gulf Coast food culture is exceptional: fresh Gulf seafood (fried, grilled, raw), Cajun influence from the Alabama/Louisiana border proximity, and the Southern comfort traditions of the Florida Panhandle. Joe Patti's Seafood Market is a Pensacola institution—and the fried baskets are as popular as the fresh catches.","GLP-1 medications eliminate the geographic isolation for metabolic care—serving the naval aviation community and Gulf Coast population without the 5-hour drive to a Florida academic medical center."]} citations={["Escambia County Health Department. (2025). <em>Community Health Assessment</em>.","Florida State University College of Medicine-Pensacola. (2024). <em>Healthcare Access in the Western Florida Panhandle</em>."]} />
      <InsuranceBreakdown title="Naval Aviation, Gulf Coast, and Panhandle Isolation" text="Pensacola's economy centers on military, tourism, and healthcare." employers={[{name:"NAS Pensacola / Naval Hospital (TRICARE)",detail:"Flight training base. TRICARE specialist waits 14-18 weeks."},{name:"Baptist Health Care / Ascension Sacred Heart",detail:"Civilian systems serve the Panhandle with limited specialist depth."},{name:"Gulf Power / Tourism / Hospitality",detail:"Utility and hospitality plans with standard PBM restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Pensacola" localCompetitors={[{name:"East Hill / Gulf Breeze Concierge",cost:"$500-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"9 Mile Rd MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Baptist / Sacred Heart Endocrinology",cost:"$100 Copay+Rx",consult:"12-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Florida's Most Isolated Metro" transitText="Pensacola connects east via I-10. Tallahassee is 3 hours. Jacksonville is 5. The Panhandle is functionally isolated from Florida's medical infrastructure." hospitalText="<strong>Naval Hospital Pensacola</strong>, <strong>Baptist</strong>, and <strong>Ascension Sacred Heart</strong> serve the region." />
      <InteractiveFAQ faqs={[{q:"I'm a flight student. Will this affect my flight status?",a:"GLP-1 medications are not disqualifying for flight status, but consult your flight surgeon. Telehealth FX is independent of military medical records."},{q:"Do you deliver to Gulf Breeze, Navarre, and Milton?",a:"Yes. All Escambia and Santa Rosa County addresses."}]} />
      <StateLegalFramework stateName="Florida" boardName="Florida Board of Medicine" text="Telehealth FX operates in compliance with the <strong>Florida Board of Medicine</strong> and F.S. § 456.47." />
      <DeliveryGridMap cityName="Pensacola" mapQuery="Pensacola, FL" coordinates="30.4213° N, 87.2169° W" counties="Escambia County, Santa Rosa County" neighborhoods={['East Hill','Gulf Breeze','Navarre','Milton','Pace','Cantonment','Perdido Key','Pensacola Beach']} />
      <FinalCTA stateName="Florida" />
    </div>
  );
}
