"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationDuluth() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Minnesota" cityName="Duluth" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Duluth</span>" subheadline="Duluth sits at the westernmost point of Lake Superior—the coldest major metro in the lower 48. The Iron Range mining heritage, lake-effect winter, and geographic isolation create a metabolic environment where outdoor exercise is impossible 5+ months per year." dataPoint1="St. Louis County's adult obesity rate exceeds 31%. Duluth averages 86 inches of snow and temperatures below -20°F multiple times per winter. The nearest alternative medical center is Minneapolis—2.5 hours south on I-35." dataPoint2="Telehealth FX delivers metabolic care through Duluth's Arctic winters without the I-35 drive to the Twin Cities." />
      <PatientArchetype archetype="The Iron Range Taconite Plant Operator" quote="I work at the Northshore Mining taconite processing plant in Silver Bay—45 minutes north of Duluth on the North Shore. I process iron ore into taconite pellets in a facility that runs 24/7. After a 12-hour shift, I drive back to Duluth and eat at a bar because nothing else is open at midnight. It's -30°F outside. I haven't been outdoors voluntarily since October. Essentia has a 14-week specialist wait." details="<strong>Patient Profile:</strong> Mike, 41, Taconite Plant Operator, Northshore Mining, Silver Bay.<br/><br/><strong>The Challenge:</strong> Iron Range shift work. -30°F winters. Midnight bar food after shifts. Essentia specialist wait 14 weeks. Minneapolis 2.5 hours south.<br/><br/><strong>The Intervention:</strong> Completed intake from apartment in West Duluth. MN-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Lake Superior, the Iron Range, and Arctic Isolation" paragraphs={["Duluth's climate is functionally subarctic. Lake Superior moderates extreme cold slightly, but the lake-effect snow and wind chill make Duluth one of the coldest cities in the lower 48. From November through March, outdoor exercise is not just uncomfortable—it's dangerous. The city's fitness culture (surprisingly strong for its size—Grandma's Marathon is nationally known) exists despite the climate, not because of it.","The Iron Range heritage defines the region's food: pasties (Cornish meat pies adopted by Finnish and Scandinavian miners), bar pizza (thin, cut in squares—a Duluth institution), walleye fish fry, and the hotdish tradition. The Northern Waters Smokehaus sandwich is Duluth's most famous food.","Essentia Health and St. Luke's (now SLHDULUTH) serve the region. Both are community systems with solid care but limited specialist depth. The University of Minnesota-Duluth medical school is building capacity, but complex specialist cases still route to Mayo Clinic (3 hours south) or the Twin Cities.","GLP-1 medications serve the Iron Range workforce, Duluth's healthcare community, and the North Shore—delivering metabolic care through winters that make every other city on this list look tropical."]} citations={["St. Louis County Public Health. (2025). <em>Community Health Assessment</em>.","University of Minnesota-Duluth. (2024). <em>Arctic Climate, Seasonal Isolation, and Metabolic Health on the Iron Range</em>."]} />
      <InsuranceBreakdown title="Iron Range, Lake Superior, and Arctic Winter" text="Duluth's economy centers on mining, healthcare, and tourism." employers={[{name:"Northshore Mining / Cleveland-Cliffs",detail:"Taconite mining plans with union Step Therapy."},{name:"Essentia Health / St. Luke's",detail:"Regional systems serve NE Minnesota with 12-16 week specialist waits."},{name:"UMD / Cirrus Aircraft",detail:"Education and manufacturing add plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Duluth" localCompetitors={[{name:"East Hillside / Hermantown Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"London Rd MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Essentia Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="2.5 Hours to Minneapolis in January" transitText="Duluth sits on I-35. Minneapolis is 2.5 hours south. The Iron Range towns (Virginia, Hibbing, Eveleth) are 60 min north." hospitalText="<strong>Essentia Health</strong> and <strong>St. Luke's</strong> serve NE Minnesota." />
      <InteractiveFAQ faqs={[{q:"I drive the North Shore for work. Can I do this remotely?",a:"Yes. 100% asynchronous. Complete from anywhere with cell service."},{q:"Do you deliver to Hermantown, Proctor, and Two Harbors?",a:"Yes. All St. Louis County addresses including the Iron Range."}]} />
      <StateLegalFramework stateName="Minnesota" boardName="Minnesota Board of Medical Practice" text="Telehealth FX operates in compliance with the <strong>MN Board of Medical Practice</strong>." />
      <DeliveryGridMap cityName="Duluth" mapQuery="Duluth, MN" coordinates="46.7867° N, 92.1005° W" counties="St. Louis County, Carlton County" neighborhoods={['West Duluth','East Hillside','Hermantown','Proctor','Two Harbors','Cloquet','Superior WI']} />
      <FinalCTA stateName="Minnesota" />
    </div>
  );
}
