"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSanBernardino() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="California" cityName="San Bernardino" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>the Inland Empire</span>" subheadline="The Inland Empire is California's logistics backbone—Amazon, FedEx, and UPS distribution centers stretch from Ontario to Riverside. The warehouse workforce powers America's e-commerce economy but faces some of the worst healthcare access in Southern California." dataPoint1="San Bernardino County is the largest county in America by area. Its adult obesity rate exceeds 35%, and the specialist-to-population ratio is among the lowest in California." dataPoint2="Telehealth FX serves the IE's warehouse workforce, military families (March ARB), and suburban commuters without the 1.5-hour drive to LA for specialist care." />
      <PatientArchetype archetype="The Amazon ONT Fulfillment Associate" quote="I pick and pack at the Ontario fulfillment center. Ten-hour shifts, four days a week, walking 15 miles a day on concrete floors. My body is destroyed by 6 PM. The cafeteria has pizza and chicken fingers. My Kaiser plan redirected me to the Fontana facility for endocrinology—a 10-week wait. The Inland Empire has a million warehouses and not enough doctors." details="<strong>Patient Profile:</strong> Maria, 31, Fulfillment Associate at Amazon ONT8, Ontario, CA.<br/><br/><strong>The Challenge:</strong> Maria walks 15+ miles per shift but the physical demands are repetitive and joint-destructive, not metabolically beneficial. Kaiser IE's specialist capacity is overwhelmed by a booming population.<br/><br/><strong>The Intervention:</strong> Completed intake from her apartment in Fontana. CA-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="America's Warehouse Floor" paragraphs={["The Inland Empire is the logistics capital of the Western United States. Over 4,000 warehouses and distribution centers stretch along the I-10 and I-15 corridors from Ontario to Moreno Valley. Amazon alone operates over a dozen facilities in the IE. This logistics economy employs hundreds of thousands of workers in physically demanding, shift-oriented roles with limited food options and high injury rates.","The healthcare system has not scaled with population growth. San Bernardino and Riverside counties have grown explosively as LA affordability refugees move east, but physician recruitment has not kept pace. The result: Kaiser IE, Loma Linda University Health, and Arrowhead Regional serve a population of 4.6 million with specialist capacity designed for a much smaller community.","The food environment is classic sprawl: fast food along every commercial corridor, limited walkable dining, and the heat (105°F+ in summer) that constrains outdoor activity. The commuter workforce—many IE residents still drive 1-2 hours to LA or Orange County for work—adds the sedentary commute to the metabolic burden.","GLP-1 medications serve the IE population that America's e-commerce economy depends on—delivering metabolic care without the drive to LA or the 10-week Kaiser wait."]} citations={["San Bernardino County Dept of Public Health. (2025). <em>Community Health Assessment</em>.","UCR School of Medicine. (2024). <em>Healthcare Access in the Inland Empire</em>."]} />
      <InsuranceBreakdown title="Warehouses, Commuters, and the Doctor Shortage" text="The IE's employer landscape is dominated by logistics companies with limited local specialist networks." employers={[{name:"Amazon / FedEx / UPS (Logistics)",detail:"Warehouse employers offer plans with standard PBM restrictions in a region where specialist appointments are scarce."},{name:"March ARB / TRICARE",detail:"Military families add to specialist demand."},{name:"Kaiser IE / Loma Linda / Arrowhead",detail:"Health systems face overwhelming demand with insufficient specialist capacity."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in the IE" localCompetitors={[{name:"Rancho Cucamonga Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Ontario / Riverside MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"Kaiser IE Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass the I-10/I-15 & Kaiser Waitlists" transitText="The IE's freeways—I-10, I-15, I-215, and the 60—are among the most congested in California. Commuting from Moreno Valley to a specialist in Fontana or Loma Linda can take over an hour." hospitalText="<strong>Kaiser IE</strong>, <strong>Loma Linda University Health</strong>, and <strong>Arrowhead Regional</strong> serve the region." />
      <InteractiveFAQ faqs={[{q:"I work warehouse shifts. When do I do the intake?",a:"Anytime. Fully asynchronous—no appointment needed."},{q:"Do you deliver to Riverside, Ontario, and Moreno Valley?",a:"Yes. All San Bernardino and Riverside County addresses."}]} />
      <StateLegalFramework stateName="California" boardName="Medical Board of California" text="Telehealth FX operates in compliance with the <strong>Medical Board of California</strong> and Cal. B&P Code § 2290.5." />
      <DeliveryGridMap cityName="San Bernardino" mapQuery="San Bernardino, CA" coordinates="34.1083° N, 117.2898° W" counties="San Bernardino County, Riverside County" neighborhoods={['Ontario','Rancho Cucamonga','Fontana','Riverside','Moreno Valley','Redlands','Upland','Corona']} />
      <FinalCTA stateName="California" />
    </div>
  );
}
