"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSpringfieldIL() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Illinois" cityName="Springfield" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Springfield, IL</span>" subheadline="Springfield is Lincoln's capital—the political and administrative center of Illinois. State government is the dominant employer. The horseshoe sandwich was invented here. The combination of desk-bound bureaucracy, Illinois' most iconic calorie bomb, and a specialist system built for a smaller population creates a metabolic gap the legislature can't close." dataPoint1="Sangamon County's adult obesity rate exceeds 34%. Springfield's food identity centers on the horseshoe—an open-faced sandwich with thick toast, meat, french fries, and cheese sauce. This is not a restaurant novelty—it is the default lunch for state workers." dataPoint2="Telehealth FX serves the state government workforce without the Memorial or HSHS specialist waitlist." />
      <PatientArchetype archetype="The Illinois State Capitol Legislative Aide" quote="I staff a state senator—12-hour days during session, constant committee hearings, and the Springfield lunch culture. Every meeting includes food. Every lunch is a horseshoe or Cozy Dog. I've gained 30 pounds in 3 legislative sessions. My state employee plan has a 14-week wait for endocrinology at Memorial. I help write healthcare legislation. I can't access the healthcare my boss votes on." details="<strong>Patient Profile:</strong> Michael, 29, Legislative Aide, Illinois General Assembly.<br/><br/><strong>The Challenge:</strong> Legislative session hours. Horseshoe sandwich culture. State plan specialist wait 14 weeks. He helps write healthcare policy he can't navigate himself.<br/><br>  <strong>The Intervention:</strong> Completed intake from apartment near Capitol Complex. IL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Lincoln's Capital, the Horseshoe, and the Healthcare Gap" paragraphs={["Springfield is Illinois' political capital—home to the Governor's Mansion, the Illinois General Assembly, and dozens of state agencies. During legislative session (January-May), the population effectively increases as lobbyists, staffers, and advocates descend on the city. The food culture during session is legendary: horseshoes, Cozy Dogs (corn dogs on a stick—invented in Springfield), and the political lunch that defines Capitol culture.","The horseshoe sandwich deserves special mention: thick-cut Texas toast, a protein (usually pork or burger), a pile of french fries, and an entire boat of cheese sauce. This is not a novelty item—it is on virtually every Springfield restaurant menu and is the default working lunch for state employees.","Memorial Health System and HSHS St. John's Hospital serve the region. Both are strong community systems, but as Springfield serves as the referral hub for central Illinois (overlapping with Peoria's territory), specialist capacity is stretched.","GLP-1 medications serve the state government workforce, the healthcare community, and central Illinois—delivering metabolic care to the people who write Illinois healthcare policy but can't access specialist care themselves."]} citations={["Sangamon County Health Department. (2025). <em>Community Health Assessment</em>.","SIU School of Medicine. (2024). <em>Government Workforce Health and Food Culture in the Illinois Capital Region</em>."]} />
      <InsuranceBreakdown title="State Capitol, Horseshoes, and Healthcare Policy" text="Springfield's economy is overwhelmingly government and healthcare." employers={[{name:"State of Illinois (Capitol Complex)",detail:"State plans require behavioral modification. 12-16 week specialist waits."},{name:"Memorial Health / HSHS St. John's",detail:"Regional health systems serve central Illinois."},{name:"SIU School of Medicine",detail:"Academic medicine adds physician training capacity."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Springfield" localCompetitors={[{name:"West Side / Chatham Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Wabash Ave MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Memorial Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-55/I-72 & Memorial Waitlists" transitText="Springfield sits on I-55 and I-72. St. Louis is 90 min SW. Chicago is 3.5 hours NE. Peoria is 75 min NW." hospitalText="<strong>Memorial Health</strong> and <strong>HSHS St. John's</strong> serve the capital region." />
      <InteractiveFAQ faqs={[{q:"I'm a state employee. Is this separate?",a:"Yes. Completely independent of your state employee benefits."},{q:"Do you deliver to Chatham, Rochester, and Jacksonville?",a:"Yes. All Sangamon and Morgan County addresses."}]} />
      <StateLegalFramework stateName="Illinois" boardName="Illinois Division of Professional Regulation" text="Telehealth FX operates in compliance with <strong>IDFPR</strong> and 225 ILCS 60." />
      <DeliveryGridMap cityName="Springfield" mapQuery="Springfield, IL" coordinates="39.7817° N, 89.6501° W" counties="Sangamon County, Morgan County" neighborhoods={['West Side','Chatham','Rochester','Sherman','Riverton','Jacksonville','Auburn','Williamsville']} />
      <FinalCTA stateName="Illinois" />
    </div>
  );
}
