"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationNorfolk() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Virginia" cityName="Norfolk" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Norfolk</span>" subheadline="Norfolk is home to the largest naval base in the world—Naval Station Norfolk. Over 80,000 military and civilian personnel depend on a TRICARE and civilian healthcare system that cannot serve a population this dense. The sailors who protect American waters cannot access the specialist care they need on American soil." ctaText="Check Virginia Eligibility" />
      <PatientArchetype archetype="The Naval Station Norfolk Ship Repair Welder" quote="I weld on aircraft carrier hull repairs at Norfolk Naval Shipyard. Twelve-hour shifts in confined spaces, full PPE, breathing fumes. The galley food is Navy institutional. TRICARE specialist referral from the base clinic is 18 weeks. I repair the most advanced warships on Earth but I can't get a doctor's appointment in my own city." details="<strong>Patient Profile:</strong> Petty Officer Reyes, 34, Hull Technician at Norfolk Naval Shipyard.<br/><br/><strong>The Challenge:</strong> Confined-space welding on carrier repairs. 12-hour shifts. Navy galley diet. TRICARE specialist referrals 18+ weeks. Sentara and Riverside civilian systems equally backlogged.<br/><br/><strong>The Intervention:</strong> Completed intake from apartment in Ghent. VA-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="The World's Largest Naval Base, the World's Longest Wait" paragraphs={["Naval Station Norfolk is the largest naval installation in the world. Combined with Norfolk Naval Shipyard (across the Elizabeth River in Portsmouth), Joint Expeditionary Base Little Creek, and NAS Oceana (Virginia Beach), Hampton Roads has the densest military population in America. The healthcare demand from active duty, families, retirees, and civilian DoD employees overwhelms both the military medical system and the civilian network.","The food environment is classic military town: fast food along Hampton Boulevard, the Navy Exchange food court, and ship galley meals designed for caloric sustenance, not metabolic health. The civilian food scene in Ghent and Downtown Norfolk has improved, but for shift workers and military personnel, convenience drives dietary decisions.","Sentara Healthcare dominates the civilian market, with Riverside Health System and Chesapeake Regional supplementing. Combined, they serve the entire Hampton Roads region (1.8 million people) alongside the military population—a burden that creates specialist waits comparable to cities twice the size.","GLP-1 medications serve the naval community—active duty, spouses, shipyard workers, and the broader Hampton Roads population—without competing for the 18-week TRICARE specialist slot."]} citations={["Norfolk Department of Public Health. (2025). <em>Community Health Assessment</em>.","Eastern Virginia Medical School. (2024). <em>Military Population Density and Healthcare Access in Hampton Roads</em>."]} />
      <InsuranceBreakdown title="Naval Station, Shipyard, and Hampton Roads" text="Norfolk's economy is overwhelmingly military and defense." employers={[{name:"Naval Station Norfolk / NNSY (TRICARE)",detail:"The world's largest naval base. TRICARE specialist referrals 18+ weeks."},{name:"Sentara Healthcare / Riverside Health",detail:"Civilian systems serve 1.8M Hampton Roads residents plus military overflow."},{name:"Huntington Ingalls / BAE Ship Repair",detail:"Defense contractors offer plans with limited local specialist networks."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Norfolk" localCompetitors={[{name:"Ghent / Colonial Place Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Granby St MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"Sentara Endocrinology",cost:"$100 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass the HRBT & TRICARE Waitlists" transitText="Hampton Roads traffic is defined by tunnels and bridges—HRBT, Monitor-Merrimac, Midtown Tunnel. A 10-mile specialist appointment can take 90 minutes." hospitalText="<strong>Sentara Norfolk General</strong> and the <strong>Naval Medical Center Portsmouth</strong> serve the region." />
      <InteractiveFAQ faqs={[{q:"I'm active duty. Will this affect my record?",a:"Telehealth FX is completely independent of TRICARE and your military medical record."},{q:"Do you deliver to Chesapeake, Portsmouth, and Hampton?",a:"Yes. All Hampton Roads addresses."}]} />
      <StateLegalFramework stateName="Virginia" boardName="Virginia Board of Medicine" text="Telehealth FX operates in compliance with the <strong>Virginia Board of Medicine</strong> and Virginia Code § 54.1-2900." />
      <DeliveryGridMap cityName="Norfolk" mapQuery="Norfolk, VA" coordinates="36.8508° N, 76.2859° W" counties="Norfolk, Chesapeake, Portsmouth, Hampton, Newport News" neighborhoods={['Ghent','Ocean View','Chesapeake','Portsmouth','Hampton','Newport News','Suffolk','Williamsburg']} />
      <FinalCTA stateName="Virginia" />
    </div>
  );
}
