"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationWaco() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="Waco" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Waco</span>" subheadline="Waco sits between Dallas and Austin on I-35—close enough to both that specialists rarely settle here, far enough that the drive is a half-day commitment. Baylor University, the Magnolia empire, and the Dr Pepper birthplace define a city where comfort and tradition are identity. The food matches." dataPoint1="McLennan County's adult obesity rate exceeds 35%. Waco's food culture centers on BBQ (Vitek's Gut Pak, Helberg's), kolaches (Czech heritage), and the Dr Pepper Float tradition at the Dr Pepper Museum." dataPoint2="Telehealth FX serves the Baylor community, the Fort Cavazos overflow, and the Central Texas workforce without the 90-minute drive to Dallas or Austin." />
      <PatientArchetype archetype="The Baylor University Athletic Department Nutritionist" quote="I design meal plans for Baylor athletes—D1 football, basketball, track. I calculate macros, monitor body composition, and build performance nutrition programs. My own metabolic health has declined over 6 years of desk-based nutrition planning, stress eating during game weeks, and the Waco food environment. My Baylor plan has a 12-week wait for endocrinology at Baylor Scott & White. I feed athletes for a living. I can't feed myself correctly." details="<strong>Patient Profile:</strong> Sarah, 34, Sports Nutritionist at Baylor University Athletics.<br/><br/><strong>The Challenge:</strong> Designs elite athletic nutrition programs but her own desk-based role and Waco's BBQ culture have created metabolic decline. BSW specialist waits 10-14 weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Woodway. TX-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Dr Pepper, Magnolia, and the I-35 Gap" paragraphs={["Waco sits at the midpoint of the Dallas-Austin I-35 corridor—equidistant from both cities' medical infrastructure but belonging to neither. This geographic purgatory means specialist physicians gravitate toward Dallas (higher volume, higher pay) or Austin (lifestyle, tech economy), leaving Waco with a specialist gap disproportionate to its population.","The food culture is distinctly Central Texas: BBQ (Vitek's Gut Pak—a pile of sausage, Fritos, pickles, onions, and cheese), kolaches from the region's Czech heritage, and Dr Pepper (invented in Waco in 1885). The Magnolia Table restaurant (Chip and Joanna Gaines) has become a national destination, but the working Waco eats at Vitek's, not Magnolia.","Baylor Scott & White Hillcrest is the primary medical center, supplemented by Ascension Providence. Both serve McLennan County and the broader Central Texas region, including Fort Cavazos (formerly Fort Hood) overflow from 45 minutes south.","GLP-1 medications close the I-35 specialist gap—serving Waco without the 90-minute drive to Dallas or Austin."]} citations={["Waco-McLennan County Public Health District. (2025). <em>Community Health Assessment</em>.","Baylor University. (2024). <em>Central Texas Food Culture and Metabolic Health</em>."]} />
      <InsuranceBreakdown title="Baylor, Magnolia, and the I-35 Corridor" text="Waco's economy centers on education, tourism, and military overflow." employers={[{name:"Baylor University",detail:"Baylor employee plans apply standard PBM restrictions with 10-14 week specialist waits."},{name:"L3Harris / SpaceX (McGregor test site)",detail:"Aerospace/defense plans with standard formulary management."},{name:"BSW Hillcrest / Ascension Providence",detail:"Regional health systems serve Central Texas with limited specialist depth."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Waco" localCompetitors={[{name:"Woodway / China Spring Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"Valley Mills Dr MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"BSW Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass the I-35 Gap" transitText="Waco sits on I-35. Dallas is 90 minutes north. Austin is 90 minutes south. Neither city's specialist network extends to McLennan County." hospitalText="<strong>BSW Hillcrest</strong> and <strong>Ascension Providence</strong> serve Central Texas." />
      <InteractiveFAQ faqs={[{q:"I'm near Fort Cavazos. Which city page applies?",a:"If you live in the Waco/McLennan County area, this page. Fort Cavazos/Killeen residents are also served."},{q:"Do you deliver to Woodway, Hewitt, and Temple?",a:"Yes. All McLennan and Bell County addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong> and Texas Occupations Code § 111." />
      <DeliveryGridMap cityName="Waco" mapQuery="Waco, TX" coordinates="31.5493° N, 97.1467° W" counties="McLennan County, Bell County" neighborhoods={['Woodway','Hewitt','Robinson','China Spring','McGregor','Temple','Killeen','Bellmead']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
