"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationLittleRock() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Arkansas" cityName="Little Rock" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Little Rock</span>" subheadline="Little Rock is the capital of Arkansas—a state where the adult obesity rate exceeds 40%. UAMS is an excellent academic medical center, but it serves a state of 3 million people from a single campus. Walmart's corporate influence reaches from Bentonville to every corner of Arkansas's food environment." ctaText="Check Arkansas Eligibility" />
      <PatientArchetype archetype="The Arkansas State Health Department Epidemiologist" quote="I track obesity data for the Arkansas Department of Health. I publish the reports showing we're the 5th most obese state. I present the numbers to legislators. And my own state employee plan requires a 6-month behavioral program before GLP-1 authorization. I am the data. I just can't access the solution." details="<strong>Patient Profile:</strong> Dr. Williams, 39, Epidemiologist at Arkansas Dept of Health.<br/><br/><strong>The Challenge:</strong> She produces the state's obesity surveillance data professionally. Her state employee plan imposes the same barriers she documents in her research.<br/><br/><strong>The Intervention:</strong> Completed intake from home in West Little Rock. AR-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Data State Can't Fix Itself" paragraphs={["Arkansas's obesity rate exceeds 40%—the 5th highest in the nation. Little Rock, as the state capital, houses both the policy apparatus tasked with addressing this crisis and the academic medical center (UAMS) responsible for clinical intervention. Neither can scale to meet the need.","The food culture is Deep South: fried catfish, chicken and dumplings, BBQ, and the cheese dip that Little Rock claims as its own invention. The weekly church potluck and the restaurant traditions along Cantrell Road create a caloric environment that is culturally essential and metabolically challenging.","UAMS is an excellent academic medical center serving a state of 3 million from one campus. Specialist waitlists reflect this burden—endocrinology waits average 14-20 weeks. Baptist Health and CHI St. Vincent supplement, but combined capacity still falls short.","GLP-1 medications deliver the clinical intervention that Arkansas's data demands but its healthcare infrastructure cannot provide at scale."]} citations={["Arkansas Department of Health. (2025). <em>Arkansas Obesity Report</em>.","UAMS College of Public Health. (2024). <em>Healthcare Access and Chronic Disease in Central Arkansas</em>."]} />
      <InsuranceBreakdown title="State Government, UAMS, and Walmart's Shadow" text="Little Rock's economy centers on state government, healthcare, and Walmart's supply chain influence." employers={[{name:"State of Arkansas (Capitol)",detail:"State plans require 6-month behavioral modification before GLP-1 authorization."},{name:"UAMS / Baptist Health / CHI St. Vincent",detail:"Health systems face overwhelming demand from statewide referrals."},{name:"Dillard's (HQ) / Stephens Inc / Windstream",detail:"Corporate plans apply standard PBM restrictions."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Little Rock" localCompetitors={[{name:"West LR / Pleasant Valley Concierge",cost:"$500-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Cantrell Rd MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"UAMS Endocrinology",cost:"$100 Copay+Rx",consult:"14-20 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-30/I-40 & UAMS Waitlists" transitText="Little Rock sprawls along I-30, I-40, and I-430. The Arkansas River divides the city from North Little Rock." hospitalText="<strong>UAMS</strong>, <strong>Baptist Health</strong>, and <strong>CHI St. Vincent</strong> serve the region. UAMS specialist waits average 14-20 weeks." />
      <InteractiveFAQ faqs={[{q:"I'm a state employee. Can I use this alongside my plan?",a:"Yes. Telehealth FX is private, self-pay, independent of state benefits."},{q:"Do you deliver to North Little Rock and Conway?",a:"Yes. All Pulaski, Faulkner, and Saline County addresses."}]} />
      <StateLegalFramework stateName="Arkansas" boardName="Arkansas State Medical Board" text="Telehealth FX operates in compliance with the <strong>Arkansas State Medical Board</strong> and ACA § 17-80-403." />
      <DeliveryGridMap cityName="Little Rock" mapQuery="Little Rock, AR" coordinates="34.7465° N, 92.2896° W" counties="Pulaski County, Saline County, Faulkner County" neighborhoods={['West Little Rock','Pleasant Valley','North Little Rock','Conway','Benton','Bryant','Maumelle','Sherwood']} />
      <FinalCTA stateName="Arkansas" />
    </div>
  );
}
