"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationFayetteville() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="North Carolina" cityName="Fayetteville" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Fayetteville</span>" subheadline="Fayetteville is home to Fort Liberty (formerly Fort Bragg)—the largest military installation in the world by population. Over 54,000 soldiers, plus their families and civilian DoD employees, depend on a TRICARE system that cannot scale specialist care to match the base's demand." dataPoint1="Fort Liberty is home to the 82nd Airborne, USASOC, and JSOC. The military population creates healthcare demand that overwhelms both the base clinic system and the civilian specialist network." dataPoint2="Telehealth FX serves the military families and DoD civilians who can't wait 20 weeks for a TRICARE specialist referral." />
      <PatientArchetype archetype="The Fort Liberty Military Spouse" quote="My husband deploys with the 82nd Airborne. When he's gone, I'm a single parent of three managing everything alone. I gained 40 pounds over two deployments from stress eating and zero time for myself. Womack Army Medical Center has a 20-week wait for endocrinology. I called the TRICARE nurse line and they suggested I 'try yoga.' I don't need yoga. I need my hormones to stop fighting me." details="<strong>Patient Profile:</strong> Ashley, 33, Military Spouse, Fort Liberty.<br/><br/><strong>The Challenge:</strong> Deployment cycles create extreme stress eating, solo parenting exhaustion, and zero time for self-care. Womack Army Medical Center's specialist capacity is overwhelmed by the largest military installation in the world. TRICARE referrals to civilian providers face the same congestion.<br/><br/><strong>The Intervention:</strong> Completed intake from her home on post at 10 PM after the kids were asleep. NC-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="The Largest Base, The Longest Wait" paragraphs={["Fort Liberty is the largest military installation in the world by population—over 54,000 soldiers plus 12,000 civilian employees. When you add military families (spouses and dependents), the Fort Liberty community exceeds 200,000 people. Womack Army Medical Center serves as the primary medical facility, but its specialist capacity cannot serve a population of this size.","The deployment cycle creates a unique metabolic challenge for military spouses. During a 9-month deployment, the non-deployed spouse manages children, household, finances, and emotional stress alone. The cortisol elevation and stress-driven eating patterns are well-documented in military family health research. Weight gain during deployments is so common it has its own informal term.","Fayetteville's food environment outside the base gates is classic military-town sprawl: fast food chains, pizza delivery, and the limited dining options that characterize most military communities. The combination of deployment stress, food environment, and 20-week specialist waits creates a metabolic crisis in the population that supports America's most elite military units.","GLP-1 medications serve the Fort Liberty community—soldiers, spouses, and DoD civilians—without requiring them to navigate the 20-week Womack waitlist or the TRICARE civilian referral chain."]} citations={["Cumberland County Health Department. (2025). <em>Community Health Assessment</em>.","Uniformed Services University. (2024). <em>Military Spouse Health, Deployment Cycles, and Metabolic Outcomes</em>."]} />
      <InsuranceBreakdown title="TRICARE Dominance" text="Fayetteville's economy is almost entirely military-driven." employers={[{name:"Fort Liberty / 82nd Airborne / USASOC (TRICARE)",detail:"TRICARE Prime and Select cover the vast majority. Womack Army Medical Center specialist referrals can exceed 20 weeks."},{name:"Cape Fear Valley Health",detail:"The civilian health system absorbs TRICARE referrals alongside community patients."},{name:"DoD Civilian / Contractor Workforce",detail:"Civilian DoD and contractor plans face the same limited local specialist network."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in Fayetteville" localCompetitors={[{name:"Off-Post Concierge Clinics",cost:"$500-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Skibo Rd MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"Womack Endocrinology",cost:"$0 (TRICARE)",consult:"20+ Week Wait",access:"Referral Chain"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Womack's 20-Week Wait" transitText="Fayetteville sprawls around Fort Liberty with All American Freeway and Bragg Boulevard handling most traffic. The base itself requires gate access." hospitalText="<strong>Womack Army Medical Center</strong> serves the military population. <strong>Cape Fear Valley Health</strong> serves the civilian community." />
      <InteractiveFAQ faqs={[{q:"My spouse is deployed. Can I use this?",a:"Yes. Military spouses can use Telehealth FX independently. It's a private service unrelated to TRICARE or your spouse's military status."},{q:"Will this affect my spouse's career or clearance?",a:"No. Telehealth FX is completely independent of the military medical system."},{q:"Do you deliver on post?",a:"Yes. We deliver to all addresses including Fort Liberty on-post housing."}]} />
      <StateLegalFramework stateName="North Carolina" boardName="North Carolina Medical Board" text="Telehealth FX operates in compliance with the <strong>NCMB</strong> and NCGS § 90-21.1." />
      <DeliveryGridMap cityName="Fayetteville" mapQuery="Fayetteville, NC" coordinates="35.0527° N, 78.8784° W" counties="Cumberland County, Harnett County, Hoke County" neighborhoods={['Fort Liberty','Hope Mills','Spring Lake','Raeford','Sanford','Southern Pines','Linden']} />
      <FinalCTA stateName="North Carolina" />
    </div>
  );
}
