"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationMacon() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Georgia" cityName="Macon" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Macon</span>" subheadline="Macon sits in the geographic center of Georgia—equidistant from Atlanta and Savannah, close to neither's medical infrastructure. Robins Air Force Base, the largest single-site industrial complex in Georgia, adds 25,000+ military and civilian jobs to a healthcare system designed for a much smaller population." dataPoint1="Bibb County's adult obesity rate exceeds 37%. Macon's combination of Robins AFB workforce, post-industrial decline, and Deep South food traditions creates one of the most severe metabolic environments in Georgia." dataPoint2="Telehealth FX serves the Robins workforce, Mercer University community, and the broader Middle Georgia population." />
      <PatientArchetype archetype="The Robins AFB C-130 Depot Maintenance Worker" quote="I overhaul C-130 engines at the Warner Robins Air Logistics Complex—the largest single-site employer in Georgia. Ten-hour shifts, engine fumes, industrial cafeteria. My FEHB plan through the base has a 14-week specialist referral. Atlanta's Emory is 90 minutes north. But I can't take a day off depot maintenance to drive to Atlanta." details="<strong>Patient Profile:</strong> Marcus, 40, Aircraft Engine Mechanic, WR-ALC, Robins AFB.<br/><br/><strong>The Challenge:</strong> Depot-level maintenance on C-130 engines. Industrial shift work. FEHB specialist wait 14 weeks. Emory (Atlanta) is 90 min but requires full-day commitment.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Warner Robins. GA-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Air Logistics Complex in Georgia's Heart" paragraphs={["Robins Air Force Base is the Warner Robins Air Logistics Complex—the facility that overhauls, repairs, and maintains the Air Force's C-130, C-5, and F-15 fleets. It is the largest single-site industrial complex in Georgia, employing 25,000+ military, civilian, and contractor personnel. The workforce is overwhelmingly blue-collar maintenance: engine overhaul, avionics repair, and structural maintenance.","Macon's food culture is traditional Georgia: fried chicken (Nu-Way Weiners and H&H Soul Food are Macon landmarks), BBQ, biscuits, and the soul food tradition that the Allman Brothers and Little Richard made famous alongside Macon's music heritage.","Atrium Health Navicent (formerly Medical Center of Central Georgia) is the primary hospital, supplemented by Coliseum Medical Centers. Together they serve Middle Georgia—a region where Atlanta's medical infrastructure is technically accessible but practically out of reach for shift workers.","GLP-1 medications serve the Robins maintenance workforce, Mercer University community, and Middle Georgia—bridging the 90-minute gap to Atlanta's specialist capacity."]} citations={["North Central Health District. (2025). <em>Community Health Assessment</em>.","Mercer University School of Medicine. (2024). <em>Military-Civilian Healthcare Access in Middle Georgia</em>."]} />
      <InsuranceBreakdown title="Robins AFB and Middle Georgia" text="Macon-Warner Robins' economy centers on the air logistics complex." employers={[{name:"Robins AFB / WR-ALC (FEHB/TRICARE)",detail:"25,000+ workers. Federal/military specialist referrals 12-16 weeks."},{name:"Atrium Health Navicent",detail:"Regional system serves Middle Georgia with limited specialist depth."},{name:"Mercer University / GEICO (Regional)",detail:"Education and insurance add plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Macon" localCompetitors={[{name:"North Macon / WR Concierge",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"Zebulon Rd MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Navicent Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-75 & the Atlanta Gap" transitText="Macon sits on I-75 and I-16. Atlanta is 90 min north. Savannah is 3 hours east." hospitalText="<strong>Atrium Health Navicent</strong> and <strong>Coliseum Medical</strong> serve Middle Georgia." />
      <InteractiveFAQ faqs={[{q:"I work at Robins. Is this separate from my FEHB?",a:"Yes. Completely independent of your federal employee benefits."},{q:"Do you deliver to Warner Robins and Perry?",a:"Yes. All Bibb, Houston, and Peach County addresses."}]} />
      <StateLegalFramework stateName="Georgia" boardName="Georgia Composite Medical Board" text="Telehealth FX operates in compliance with the <strong>Georgia Composite Medical Board</strong>." />
      <DeliveryGridMap cityName="Macon" mapQuery="Macon, GA" coordinates="32.8407° N, 83.6324° W" counties="Bibb County, Houston County, Peach County" neighborhoods={['North Macon','Warner Robins','Perry','Byron','Centerville','Gray','Forsyth']} />
      <FinalCTA stateName="Georgia" />
    </div>
  );
}
