"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationJackson() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Mississippi" cityName="Jackson" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Jackson</span>" subheadline="Jackson is the capital of the state with the highest adult obesity rate in America—40.8%. UMMC is the state's only academic medical center, serving 3 million Mississippians from a single campus. The water crisis made national headlines, but the metabolic health crisis has been here for decades." dataPoint1="Mississippi leads the nation in adult obesity at 40.8%. Jackson, as the capital, houses both the state health apparatus and the only academic medical center—neither of which can scale to meet the magnitude of the crisis." dataPoint2="Telehealth FX delivers clinical metabolic care to the state that needs it most—without the UMMC waitlist." />
      <PatientArchetype archetype="The Mississippi State Health Department Nutritionist" quote="I design nutritional intervention programs for the Mississippi State Department of Health. I train community health workers. I present data showing Mississippi is the most obese state in America. My state employee plan requires a 6-month behavioral program before GLP-1 authorization. I designed the behavioral program. I know it doesn't work at scale. And I still have to complete it." details="<strong>Patient Profile:</strong> Dr. Robinson, 44, Public Health Nutritionist at MS Dept of Health.<br/><br/><strong>The Challenge:</strong> She designs the very behavioral programs her insurance requires her to complete. She knows the efficacy data. The professional irony is devastating.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Fondren. MS-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="America's #1 Obesity State and Its Single Hospital" paragraphs={["Mississippi's 40.8% adult obesity rate is the highest in the nation. This is not a statistical anomaly—it is the product of structural poverty, food desert geography, cultural food traditions, and a healthcare system that has been chronically underfunded. Jackson, as the state capital, concentrates both the policy response and the clinical infrastructure.","UMMC (University of Mississippi Medical Center) is the state's only academic medical center and Level I trauma center. It serves as the specialist referral destination for 3 million Mississippians. The endocrinology department at UMMC has waits exceeding 20 weeks—a number that reflects the impossible math of one specialist center for an entire state.","The food culture is Deep South at its most tradition-bound: fried catfish, country-fried steak, pork chops, collard greens with fatback, sweet potato pie, and the biscuit tradition that defines Southern breakfast. The Fondren neighborhood has developed a food scene, but the dietary default for working Jackson remains high-calorie comfort.","GLP-1 medications represent a population-level intervention opportunity in Mississippi—scaling metabolic care beyond what UMMC can provide through traditional appointment-based practice."]} citations={["Mississippi State Department of Health. (2025). <em>Mississippi Obesity Report</em>.","UMMC School of Population Health. (2024). <em>Obesity Prevalence, Healthcare Access, and the Single-Campus Academic Medical Center Model</em>."]} />
      <InsuranceBreakdown title="#1 Obesity State, One Academic Medical Center" text="Jackson's economy centers on government, healthcare, and education." employers={[{name:"State of Mississippi",detail:"State plans require behavioral programs that the state's own health department acknowledges are insufficient."},{name:"UMMC (Sole Academic Center)",detail:"The state's only academic medical center faces impossible demand. 20+ week specialist waits."},{name:"Nissan Canton / Entergy",detail:"Manufacturing and utility plans add volume with the same limited specialist network."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Jackson" localCompetitors={[{name:"Fondren / Ridgeland Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"County Line Rd MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"UMMC Endocrinology",cost:"$80 Copay+Rx",consult:"20-26 Week Wait",access:"1 Campus for 3M"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="One Hospital for Three Million People" transitText="Jackson sprawls along I-55 and I-20. The metro is car-dependent with limited public transit." hospitalText="<strong>UMMC</strong> is the state's only academic medical center and Level I trauma center. <strong>Baptist</strong> and <strong>Merit Health</strong> supplement." />
      <InteractiveFAQ faqs={[{q:"I'm a state employee. Can I use this?",a:"Yes. Telehealth FX is private, self-pay, independent of state benefits."},{q:"Do you deliver to Ridgeland, Madison, and Brandon?",a:"Yes. All Hinds, Madison, and Rankin County addresses."}]} />
      <StateLegalFramework stateName="Mississippi" boardName="Mississippi State Board of Medical Licensure" text="Telehealth FX operates in compliance with the <strong>MS Board of Medical Licensure</strong> and Miss. Code § 73-25." />
      <DeliveryGridMap cityName="Jackson" mapQuery="Jackson, MS" coordinates="32.2988° N, 90.1848° W" counties="Hinds County, Madison County, Rankin County" neighborhoods={['Fondren','Belhaven','Ridgeland','Madison','Brandon','Clinton','Pearl','Flowood']} />
      <FinalCTA stateName="Mississippi" />
    </div>
  );
}
