"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationGrandRapids() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Michigan" cityName="Grand Rapids" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Grand Rapids</span>" subheadline="Grand Rapids is Beer City USA and the furniture capital of America. The craft brewery explosion has added a significant weekly caloric contribution to a city whose Dutch Reformed heritage already centered community life around large, shared meals." dataPoint1="Kent County's adult obesity rate exceeds 32%. Grand Rapids has more craft breweries per capita than almost any US city, and the Dutch-heritage food traditions (stroopwafels, comfort baking, church potlucks) create a metabolic environment unique to West Michigan." dataPoint2="Telehealth FX serves the Beer City workforce without competing for Spectrum Health's specialist appointments." />
      <PatientArchetype archetype="The Steelcase Office Furniture Designer" quote="I design ergonomic office furniture at Steelcase—my job is literally to make sitting healthier. The irony is not lost on me. I sit at a desk designing chairs for 9 hours, then go to a brewery after work because that's what everyone does in Grand Rapids. My Priority Health plan has a 12-week wait for endocrinology." details="<strong>Patient Profile:</strong> Emily, 35, Industrial Designer at Steelcase, Grand Rapids.<br/><br/><strong>The Challenge:</strong> Designs ergonomic seating for a living while experiencing the metabolic consequences of sedentary work. Grand Rapids' brewery culture adds 800+ weekly calories from craft beer alone.<br/><br/><strong>The Intervention:</strong> Completed intake from her home in East Hills. MI-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Beer City, Furniture Capital, Church Potluck" paragraphs={["Grand Rapids has been voted 'Beer City USA' multiple times. Founders Brewing, Bell's (Kalamazoo, but culturally GR), Brewery Vivant, and dozens of craft breweries define the social culture. A standard GR evening involves 2-3 pints of craft beer (600-900 calories) and shared appetizers. This is not weekend indulgence—it is midweek social default.","The furniture manufacturing heritage (Steelcase, Herman Miller/MillerKnoll, Haworth) created West Michigan's middle class. The Dutch Reformed cultural tradition that settled the region added large family meals, church potlucks, and a baking culture that produces calorie-dense comfort food as an expression of community.","Spectrum Health (now Corewell Health) is the dominant system, supplemented by Mercy Health. Together they serve West Michigan with specialist capacity that is adequate but stretched during peak demand periods. Endocrinology waits average 10-14 weeks.","GLP-1 medications serve Grand Rapids without requiring patients to skip the Founders taproom or decline the church potluck—restoring metabolic signaling within the cultural context of Beer City."]} citations={["Kent County Health Department. (2025). <em>Community Health Assessment</em>.","Michigan State University College of Human Medicine-Grand Rapids. (2024). <em>Craft Beverage Culture and Metabolic Health</em>."]} />
      <InsuranceBreakdown title="Furniture, Beer, and Dutch Heritage" text="Grand Rapids's employer mix spans furniture manufacturing, healthcare, and food production." employers={[{name:"Steelcase / MillerKnoll / Haworth",detail:"Furniture manufacturers offer corporate plans with standard PBM restrictions."},{name:"Corewell Health (Spectrum) / Mercy Health",detail:"West Michigan's health systems employ thousands with the same formulary barriers."},{name:"Meijer (HQ) / Amway (HQ)",detail:"Major retailers and direct-sales companies add corporate plan volume."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Grand Rapids" localCompetitors={[{name:"East Hills / Ada Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"28th St MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"Corewell Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass US-131 & Corewell Waitlists" transitText="Grand Rapids traffic concentrates on US-131 and I-96. The suburban sprawl into Grandville, Wyoming, and Ada adds commute time." hospitalText="<strong>Corewell Health</strong> and <strong>Mercy Health</strong> serve West Michigan. Specialist waits average 10-14 weeks." />
      <InteractiveFAQ faqs={[{q:"Do I have to stop drinking craft beer?",a:"GLP-1 medications don't require alcohol abstinence. Many patients report naturally reduced alcohol desire. Your prescribing physician will discuss this."},{q:"Do you deliver to Holland and Kalamazoo?",a:"Yes. All Kent, Ottawa, Allegan, and Kalamazoo County addresses."}]} />
      <StateLegalFramework stateName="Michigan" boardName="Michigan Board of Medicine" text="Telehealth FX operates in compliance with the <strong>Michigan Board of Medicine</strong> and MCL § 333.16284." />
      <DeliveryGridMap cityName="Grand Rapids" mapQuery="Grand Rapids, MI" coordinates="42.9634° N, 85.6681° W" counties="Kent County, Ottawa County, Allegan County" neighborhoods={['East Hills','Eastown','Ada','Grandville','Wyoming','Rockford','Holland','Kalamazoo']} />
      <FinalCTA stateName="Michigan" />
    </div>
  );
}
