"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationProvidence() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Rhode Island" cityName="Providence" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Providence</span>" subheadline="Providence is the capital of America's smallest state—and home to some of its biggest food. The city that houses the Culinary Institute of America's satellite programs, Federal Hill's legendary Italian restaurants, and New England's densest concentration of Portuguese bakeries creates a food environment where culinary excellence and metabolic challenge coexist." dataPoint1="Rhode Island's adult obesity rate exceeds 30%. Providence's food identity—Federal Hill Italian, Portuguese, and the New England seafood tradition—creates caloric density that the city's world-class culinary reputation amplifies." dataPoint2="Telehealth FX delivers metabolic care to a city where the food is exceptional and the specialist waits are not." />
      <PatientArchetype archetype="The CVS Health Corporate Analyst" quote="I work at CVS Health headquarters in Woonsocket—one of the largest pharmacy benefit managers in America. I analyze prescription utilization data, including GLP-1 spending patterns. I know exactly how much insurers restrict these medications because I see the PA denial data. My own CVS employee plan requires the same prior authorization process I analyze every day." details="<strong>Patient Profile:</strong> James, 36, Pharmacy Benefits Analyst at CVS Health.<br/><br/><strong>The Challenge:</strong> He analyzes GLP-1 utilization and denial data for one of America's largest PBMs. His own CVS employee plan requires the same PA process he documents. The irony is professional-grade.<br/><br/><strong>The Intervention:</strong> Completed intake from his apartment on the East Side. RI-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Federal Hill, Portuguese Bakeries, and the PBM Capital" paragraphs={["Providence's food culture punches far above its weight class. Federal Hill (Atwells Avenue) is one of America's great Italian restaurant corridors—the kind of neighborhood where a Tuesday dinner is 1,500 calories of pasta, bread, and wine. The Portuguese community in Fox Point and East Providence adds pastéis de nata, linguiça, and the rich, butter-heavy baking traditions of the Azorean diaspora.","The proximity to CVS Health headquarters (Woonsocket, 15 miles north) creates a unique irony: thousands of Providence-area workers design and administer the very PBM formulary restrictions that limit GLP-1 access nationwide. They understand the denial process because they built it.","Brown University and its affiliated hospitals (Rhode Island Hospital, The Miriam) provide strong academic medical care, but Rhode Island's small size means the entire state's specialist capacity is concentrated in one metro—and it's not enough for a population of 1.1 million.","GLP-1 medications serve Providence's food-passionate, insurance-industry-savvy population—bypassing the PBM barriers that many of them helped design."]} citations={["RI Department of Health. (2025). <em>Community Health Assessment</em>.","Brown University School of Public Health. (2024). <em>Food Culture, Pharmacy Benefits, and Metabolic Health in Rhode Island</em>."]} />
      <InsuranceBreakdown title="PBM Capital and the Food City Paradox" text="Providence's economy intersects insurance, healthcare, and culinary arts." employers={[{name:"CVS Health (Woonsocket HQ)",detail:"PBM employees face the same formulary restrictions they administer."},{name:"Brown / Lifespan / Care New England",detail:"Academic and healthcare systems apply standard specialist referral chains."},{name:"Hasbro / Textron / Naval Station Newport",detail:"Corporate and military employers add standard plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Providence" localCompetitors={[{name:"East Side / Barrington Concierge",cost:"$700-$1,100/mo",consult:"In-Person",access:"Branded Only"},{name:"Thayer St MedSpas",cost:"$400-$650/mo",consult:"Monthly",access:"Variable"},{name:"Lifespan Endocrinology",cost:"$125 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-95 & Lifespan Waitlists" transitText="Providence sits on I-95 between Boston (1hr) and New York (3hr). The city is compact but RI traffic on 95/195 is disproportionately congested." hospitalText="<strong>Rhode Island Hospital</strong> and <strong>The Miriam</strong> (Lifespan) serve the state alongside <strong>Care New England</strong>." />
      <InteractiveFAQ faqs={[{q:"I work at CVS. Is this a conflict?",a:"No. Telehealth FX is independent of your employer and your employer's PBM."},{q:"Do you deliver to Cranston, Warwick, and East Providence?",a:"Yes. All Rhode Island addresses."}]} />
      <StateLegalFramework stateName="Rhode Island" boardName="Rhode Island Board of Medical Licensure and Discipline" text="Telehealth FX operates in compliance with the <strong>RI Board of Medical Licensure</strong> and RIGL § 5-37." />
      <DeliveryGridMap cityName="Providence" mapQuery="Providence, RI" coordinates="41.8240° N, 71.4128° W" counties="Providence County, Kent County" neighborhoods={['East Side','Federal Hill','Cranston','Warwick','East Providence','Pawtucket','Woonsocket','Newport']} />
      <FinalCTA stateName="Rhode Island" />
    </div>
  );
}
