"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationBeaumont() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="Beaumont" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Beaumont</span>" subheadline="Beaumont anchors the Golden Triangle—America's oil refining capital. The ExxonMobil, Motiva, and Valero refineries process more crude oil than most countries. The shift workers who keep America's fuel flowing eat refinery cafeteria food for 12 hours, then drive home to Southeast Texas comfort." dataPoint1="Jefferson County's adult obesity rate exceeds 38%. The Golden Triangle (Beaumont-Port Arthur-Orange) has one of the highest concentrations of petrochemical facilities in the world and among the fewest specialists per capita." dataPoint2="Telehealth FX serves the refinery corridor without the 90-minute drive to Houston." />
      <PatientArchetype archetype="The Motiva Port Arthur Refinery Operator" quote="I run the control board at the Motiva refinery in Port Arthur—the largest refinery in North America. Twelve-hour rotating shifts: days one week, nights the next. The refinery cafeteria is burgers and fried catfish. After a night shift, I eat whatever's open at 7 AM, which is Whataburger. My Motiva plan has a 16-week wait for endocrinology in Beaumont. Houston is 90 minutes but I work 84 hours some weeks." details="<strong>Patient Profile:</strong> Travis, 37, Control Board Operator, Motiva Enterprises, Port Arthur.<br/><br/><strong>The Challenge:</strong> 12-hour rotating shifts at North America's largest refinery. Cafeteria food + 7 AM Whataburger post-night-shift. 16-week specialist wait. Houston 90 min but inaccessible during 84-hour work weeks.<br/><br/><strong>The Intervention:</strong> Completed intake during off-rotation from home in Nederland. TX-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="America's Refining Capital and Its Health Deficit" paragraphs={["The Golden Triangle processes roughly 2.5 million barrels of crude oil per day. Motiva (Port Arthur), ExxonMobil (Beaumont), Valero (Port Arthur), and Total (Port Arthur) operate some of the largest refineries on Earth. The workforce is overwhelmingly 12-hour rotating shifts—a schedule that destroys circadian rhythm, cortisol regulation, and metabolic stability.","The food culture is Southeast Texas: Cajun-influenced (boudin, crawfish, gumbo from the Louisiana border 20 miles east), BBQ, and the fried catfish/fried shrimp tradition that defines Golden Triangle dining. Sartin's Seafood is a Beaumont institution. The caloric density matches the physical labor that refinery work once required—but modern control board operations are sedentary.","Baptist Hospitals of Southeast Texas and Christus Southeast Texas are the primary systems. Together they serve the Golden Triangle with community-level care, but complex specialist needs often route to Houston (UTMB Galveston or the Texas Medical Center).","GLP-1 medications serve the refinery corridor—delivering metabolic care to the control board operators, pipefitters, and instrumentation technicians who keep America's fuel flowing."]} citations={["Jefferson County Health Department. (2025). <em>Community Health Assessment</em>.","Lamar University. (2024). <em>Petrochemical Workforce Health and Shift Work in the Golden Triangle</em>."]} />
      <InsuranceBreakdown title="The Refinery Corridor" text="Beaumont-Port Arthur's economy is overwhelmingly petrochemical." employers={[{name:"Motiva / ExxonMobil / Valero",detail:"Refinery plans with standard PBM restrictions. 14-18 week specialist waits locally."},{name:"Baptist / Christus SE Texas",detail:"Regional systems serve the Triangle with limited specialist depth."},{name:"Lamar University / Entergy",detail:"Education and utility plans add volume."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Beaumont" localCompetitors={[{name:"West End / Lumberton Concierge",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"Dowlen Rd MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"Baptist Endocrinology",cost:"$100 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-10 & the Houston Drive" transitText="Beaumont sits on I-10. Houston is 90 min west. Lake Charles LA is 60 min east. The Golden Triangle is functionally isolated." hospitalText="<strong>Baptist SE Texas</strong> and <strong>Christus SE Texas</strong> serve the Triangle." />
      <InteractiveFAQ faqs={[{q:"I work rotating 12s at the refinery. When?",a:"Anytime. Fully asynchronous—complete between shifts."},{q:"Do you deliver to Port Arthur, Orange, and Nederland?",a:"Yes. All Jefferson, Orange, and Hardin County addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong>." />
      <DeliveryGridMap cityName="Beaumont" mapQuery="Beaumont, TX" coordinates="30.0802° N, 94.1266° W" counties="Jefferson County, Orange County, Hardin County" neighborhoods={['West End','Port Arthur','Orange','Nederland','Groves','Lumberton','Vidor','Bridge City']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
