"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationPeoria() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Illinois" cityName="Peoria" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Peoria</span>" subheadline="'Will it play in Peoria?' The phrase that made this city America's test market for everything from consumer products to political campaigns. Caterpillar built its global headquarters here. The question today: can a city that tests everything fix its own metabolic health crisis?" ctaText="Check Illinois Eligibility" />
      <PatientArchetype archetype="The Caterpillar Heavy Equipment Test Engineer" quote="I test mining trucks and excavators at the Caterpillar Proving Grounds—machines that weigh 400 tons. I sit in an instrumented cab collecting vibration and performance data for 10 hours. The irony is I test the machines that build the world but I can't build my own health. My Caterpillar plan requires Step Therapy that takes 6 months. The union benefits are good. Just not for this." details="<strong>Patient Profile:</strong> Greg, 45, Test Engineer at Caterpillar Inc, Peoria.<br/><br/><strong>The Challenge:</strong> Sedentary cab-based testing of heavy equipment. Caterpillar's corporate plan requires standard Step Therapy. Midwest comfort food default. OSF and UnityPoint specialist waits 10-14 weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Dunlap. IL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Will It Play in Peoria?" paragraphs={["Peoria's identity as America's test market is well-earned—its demographics historically mirrored the national average, making it the ideal proving ground for products, campaigns, and cultural trends. Caterpillar's global headquarters anchored the economy for over a century, though the company moved its executive offices to Irving, TX in 2017. The engineering, testing, and manufacturing operations remain.","The food culture is classic Central Illinois: horseshoe sandwiches (an open-faced sandwich with thick toast, meat, fries, and cheese sauce—a Springfield invention adopted across the region), tenderloin sandwiches, and the Midwest comfort food canon. Avanti's gondola (an Italian bread boat filled with meat and cheese) is Peoria's signature.","OSF HealthCare (Sisters of the Third Order of St. Francis) and UnityPoint Health serve the region. Both are strong community systems, but as the referral hub for Central Illinois, specialist capacity is stretched by a catchment area extending from Bloomington to Galesburg.","GLP-1 medications serve Caterpillar's remaining workforce, the healthcare community, and the broader Central Illinois population—delivering metabolic care that plays in Peoria."]} citations={["Peoria City/County Health Department. (2025). <em>Community Health Assessment</em>.","University of Illinois College of Medicine Peoria. (2024). <em>Healthcare Access in Central Illinois</em>."]} />
      <InsuranceBreakdown title="Caterpillar, Healthcare, and the Test Market" text="Peoria's economy centers on heavy manufacturing, healthcare, and education." employers={[{name:"Caterpillar Inc",detail:"Corporate and union plans both require Step Therapy for GLP-1 weight management."},{name:"OSF HealthCare / UnityPoint Health",detail:"Health systems serve as both employer and specialist source."},{name:"Bradley University / ICC",detail:"Education employers add standard plan volumes."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Peoria" localCompetitors={[{name:"Dunlap / Germantown Hills Concierge",cost:"$500-$800/mo",consult:"In-Person",access:"Branded Only"},{name:"University St MedSpas",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"OSF Endocrinology",cost:"$100 Copay+Rx",consult:"10-14 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-74 & OSF Waitlists" transitText="Peoria sits on I-74. Chicago is 2.5 hours NE. St. Louis is 2.5 hours SW. Springfield is 1.5 hours south." hospitalText="<strong>OSF Saint Francis</strong> and <strong>UnityPoint Methodist</strong> serve Central Illinois." />
      <InteractiveFAQ faqs={[{q:"I work at Caterpillar. Is this separate?",a:"Yes. Telehealth FX is independent of your CAT benefits."},{q:"Do you deliver to East Peoria, Morton, and Bloomington?",a:"Yes. All Peoria, Tazewell, and McLean County addresses."}]} />
      <StateLegalFramework stateName="Illinois" boardName="Illinois Division of Professional Regulation" text="Telehealth FX operates in compliance with <strong>IDFPR</strong> and 225 ILCS 60." />
      <DeliveryGridMap cityName="Peoria" mapQuery="Peoria, IL" coordinates="40.6936° N, 89.5890° W" counties="Peoria County, Tazewell County, Woodford County" neighborhoods={['Dunlap','Germantown Hills','East Peoria','Morton','Washington','Pekin','Metamora']} />
      <FinalCTA stateName="Illinois" />
    </div>
  );
}
