"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationBirmingham() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Alabama" cityName="Birmingham" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Birmingham</span>" subheadline="UAB is a top-20 hospital in America. Alabama has the second-highest adult obesity rate. Birmingham lives at the intersection of world-class medicine and a population health crisis that world-class medicine alone cannot solve." ctaText="Check Alabama Eligibility" />
      <PatientArchetype archetype="The UAB Hospital Lab Technician" quote="I run metabolic panels in the UAB clinical lab. I process A1C results, lipid panels, and insulin levels all day. I know exactly what my own numbers mean because I see thousands of patients' numbers that look just like mine. My UAB employee plan requires a wellness program that meets at 1 PM on Tuesdays. I'm in the lab at 1 PM on Tuesdays." details="<strong>Patient Profile:</strong> DeShawn, 38, Clinical Lab Technician at UAB Hospital.<br/><br/><strong>The Challenge:</strong> DeShawn processes the very lab results that diagnose metabolic disease. He understands the science from the testing side. His UAB employee plan wellness program conflicts with his lab shift schedule.<br/><br/><strong>The Intervention:</strong> Completed intake from his home in Homewood. An AL-licensed physician prescribed compounded Tirzepatide within 24 hours." />
      <ClinicalDeepDive title="World-Class Hospital, Population Health Crisis" paragraphs={["The UAB paradox defines Birmingham: the city has one of the best hospitals in America, but the state has the second-highest adult obesity rate (39.9%) in the nation. Alabama's metabolic health crisis is not a UAB problem—it is a systemic problem rooted in poverty, food access, cultural food traditions, and a chronic disease burden that no single hospital system can resolve.","Birmingham's food culture is deep Southern: barbecue (Saw's, Dreamland), fried chicken, biscuits, and the meat-and-three tradition that defines lunch for much of the working population. A standard meat-and-three plate—fried catfish, mac and cheese, collard greens cooked with pork, and cornbread—can exceed 1,500 calories.","The iron and steel heritage that built Birmingham (the 'Pittsburgh of the South') created a food tradition built for furnace workers burning 5,000 calories a day. The furnaces are closed. The food tradition remains.","GLP-1 medications scale metabolic intervention beyond what UAB's endocrinology department can provide through traditional appointment-based care—reaching the population that needs it most without the 10-16 week waitlist."]} citations={["Jefferson County Department of Health. (2025). <em>Community Health Assessment</em>.","UAB School of Public Health. (2024). <em>Academic Medical Center Capacity and Population Health in Alabama</em>."]} />
      <InsuranceBreakdown title="UAB Dominance and the Deep South Paradox" text="Birmingham's economy is anchored by UAB and healthcare, with the state's population health metrics among the worst in the nation." employers={[{name:"UAB / UAB Health System",detail:"Birmingham's largest employer. Plans require wellness programs that conflict with clinical shift schedules."},{name:"Regions Financial / Protective Life",detail:"Financial sector plans apply standard PBM restrictions."},{name:"Brookwood Baptist / Grandview",detail:"Other health systems face the same formulary and specialist constraints."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in Birmingham" localCompetitors={[{name:"Mountain Brook / Vestavia Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Lakeshore / Hoover MedSpas",cost:"$300-$600/mo",consult:"Monthly",access:"Variable"},{name:"UAB Endocrinology",cost:"$100 Copay+Rx",consult:"10-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-65/I-20 & UAB Waitlists" transitText="Birmingham sprawls along I-65 and I-20/I-59 with the Red Mountain ridge dividing the city." hospitalText="<strong>UAB Hospital</strong> (top-20 nationally) and <strong>Brookwood Baptist</strong> serve the metro. Specialist waits average 10-16 weeks." />
      <InteractiveFAQ faqs={[{q:"I work at UAB. Is this a conflict?",a:"No. Telehealth FX is independent. Your use is a private healthcare decision."},{q:"Do you deliver to Hoover, Vestavia, and Trussville?",a:"Yes. All Jefferson and Shelby County addresses."}]} />
      <StateLegalFramework stateName="Alabama" boardName="Alabama Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>Alabama Board of Medical Examiners</strong> and Ala. Code § 34-24." />
      <DeliveryGridMap cityName="Birmingham" mapQuery="Birmingham, AL" coordinates="33.5186° N, 86.8104° W" counties="Jefferson County, Shelby County" neighborhoods={['Homewood','Mountain Brook','Vestavia Hills','Hoover','Trussville','Pelham','Bessemer','Alabaster']} />
      <FinalCTA stateName="Alabama" />
    </div>
  );
}
