"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationLakeCharles() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Louisiana" cityName="Lake Charles" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Lake Charles</span>" subheadline="Lake Charles is the LNG capital of America—the Cheniere Sabine Pass and Cameron LNG terminals make Southwest Louisiana the gateway for US natural gas exports. The petrochemical corridor adds Sasol, Citgo, and Phillips 66 refineries. The workforce runs 24/7. The healthcare system doesn't." dataPoint1="Calcasieu Parish's adult obesity rate exceeds 36%. Lake Charles combines petrochemical shift work, Cajun food culture, and casino industry dining—a triple metabolic challenge in a region where the nearest academic medical center is 2+ hours away." dataPoint2="Telehealth FX serves the LNG corridor without the I-10 drive to Houston or Baton Rouge." />
      <PatientArchetype archetype="The Cheniere Sabine Pass LNG Terminal Operator" quote="I operate the liquefaction trains at Sabine Pass—we export more natural gas than any facility in the Western Hemisphere. Twelve-hour shifts monitoring cryogenic systems at -260°F. The irony is the control room is 72 degrees and I sit in a chair for 12 hours. The plant cafeteria is boudin, cracklins, and rice dressing. My Cheniere plan has a 16-week specialist wait at LCMHS. Houston is 2.5 hours. I work 84-hour weeks." details="<strong>Patient Profile:</strong> Ryan, 35, LNG Operations Technician, Cheniere Sabine Pass.<br/><br/><strong>The Challenge:</strong> 12-hour sedentary control room shifts. Cajun plant cafeteria food. 16-week specialist wait. Houston 2.5 hours west. 84-hour work weeks.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Sulphur. LA-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="America's LNG Gateway and the Cajun Calorie Pipeline" paragraphs={["Lake Charles sits at the center of the largest concentration of LNG export capacity in the Western Hemisphere. Cheniere's Sabine Pass terminal, Cameron LNG, and the proposed Driftwood LNG project represent tens of billions of investment. The petrochemical corridor—Sasol (the $12.9B ethane cracker), Citgo, Phillips 66—adds refining capacity.","The food culture is Cajun Louisiana at its most authentic: boudin (rice and pork sausage), cracklins (fried pork skin), crawfish étouffée, and the rice dressing that defines Southwest Louisiana comfort food. Steamboat Bill's and Seafood Palace are Lake Charles institutions. This food is culturally sacred and calorically devastating.","LCMHS (Lake Charles Memorial Health System) and Christus Ochsner St. Patrick serve the region. The nearest academic center is Houston (2.5 hours west on I-10) or Baton Rouge (2.5 hours east). Lake Charles' specialist capacity is overwhelmed by the combined LNG, petrochemical, and casino workforce.","GLP-1 medications serve the LNG operators, refinery workers, and casino employees—delivering metabolic care to the community that exports America's energy surplus."]} citations={["Calcasieu Parish Health Unit. (2025). <em>Community Health Assessment</em>.","McNeese State University. (2024). <em>Petrochemical Workforce Health in Southwest Louisiana</em>."]} />
      <InsuranceBreakdown title="LNG, Cajun Food, and the I-10 Corridor" text="Lake Charles' economy is overwhelmingly energy and gaming." employers={[{name:"Cheniere / Cameron LNG",detail:"LNG operators have corporate plans with limited local specialist networks."},{name:"Sasol / Citgo / Phillips 66",detail:"Refinery plans with standard PBM restrictions."},{name:"L'Auberge / Golden Nugget (Casinos)",detail:"24/7 hospitality plans with minimal specialist coverage."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Lake Charles" localCompetitors={[{name:"South Lake Charles / Sulphur Concierge",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"Ryan St MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"LCMHS Endocrinology",cost:"$100 Copay+Rx",consult:"14-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-10: 2.5 Hours Either Direction" transitText="Lake Charles sits on I-10. Houston is 2.5 hours west. Baton Rouge is 2.5 hours east. Beaumont is 60 min west." hospitalText="<strong>LCMHS</strong> and <strong>Christus St. Patrick</strong> serve SW Louisiana." />
      <InteractiveFAQ faqs={[{q:"I work rotating 12s at the LNG terminal. When?",a:"Anytime. Fully asynchronous—complete between shifts."},{q:"Do you deliver to Sulphur, Moss Bluff, and DeQuincy?",a:"Yes. All Calcasieu and Cameron Parish addresses."}]} />
      <StateLegalFramework stateName="Louisiana" boardName="Louisiana State Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>LSBME</strong>." />
      <DeliveryGridMap cityName="Lake Charles" mapQuery="Lake Charles, LA" coordinates="30.2266° N, 93.2174° W" counties="Calcasieu Parish, Cameron Parish" neighborhoods={['South Lake Charles','Sulphur','Moss Bluff','Westlake','DeQuincy','Iowa','Vinton']} />
      <FinalCTA stateName="Louisiana" />
    </div>
  );
}
