"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationMcAllen() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="McAllen" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>McAllen</span>" subheadline="McAllen anchors the Mid Rio Grande Valley—one of the poorest and most medically underserved regions in the United States. Hidalgo County's adult diabetes rate exceeds 30%. The Valley has among the fewest specialists per capita in America. San Antonio is 4 hours north. Houston is 6." dataPoint1="Hidalgo County's adult obesity rate exceeds 43%—the highest in Texas. McAllen has been identified by CMS as one of the highest-spending healthcare markets in America, yet access to specialist care remains critically insufficient." dataPoint2="Telehealth FX serves the Valley without the 4-hour drive to San Antonio or the 6-hour drive to Houston." />
      <PatientArchetype archetype="The McAllen ISD School Counselor" quote="I counsel students at a Title I school—95% free-and-reduced lunch. I see childhood obesity in every classroom. I try to connect families to resources that don't exist down here. My TRS ActiveCare plan has a 20-week wait for endocrinology in the Valley. There's one endocrinologist for 800,000 people. I help families navigate a system I can't navigate myself." details="<strong>Patient Profile:</strong> Maria, 38, School Counselor, McAllen ISD.<br/><br/><strong>The Challenge:</strong> Sees childhood obesity daily in Title I schools. TRS plan faces 20-week specialist wait. The Valley has one endocrinologist per 800,000 residents.<br/><br/><strong>The Intervention:</strong> Completed intake from home in North McAllen. TX-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="One Endocrinologist for 800,000 People" paragraphs={["The Rio Grande Valley's specialist shortage is not a gap—it is a chasm. Hidalgo County's physician-to-population ratio is among the worst in the nation. Endocrinology specialists are virtually nonexistent: the McAllen-Edinburg-Mission metro of 870,000 people has a specialist capacity designed for a city one-tenth that size.","The food culture is authentic Tex-Mex at its most traditional: breakfast tacos (barbacoa, carne guisada, huevos a la mexicana), enchiladas, tamales, and the pan dulce bakery tradition. The caloric density is amplified by food desert dynamics in the colonias—unincorporated communities where fresh grocery access is severely limited.","South Texas Health System and DHR Health are the primary hospitals. UT Health RGV's medical school is building local capacity, but the decades-long specialist deficit cannot be resolved in years.","GLP-1 medications represent the most impactful intervention in our network—serving the most underserved metro in America with clinical metabolic care delivered directly to the Valley."]} citations={["Hidalgo County Health and Human Services. (2025). <em>Community Health Assessment</em>.","UT Health RGV School of Medicine. (2024). <em>Specialist Access and Health Outcomes in the Rio Grande Valley</em>."]} />
      <InsuranceBreakdown title="The Valley's Access Crisis" text="McAllen's economy blends border trade, agriculture, and healthcare." employers={[{name:"McAllen ISD / PSJA ISD (TRS)",detail:"Teacher plans face 20+ week specialist waits in the Valley."},{name:"South Texas Health System / DHR Health",detail:"The Valley's hospitals cannot scale specialist capacity fast enough."},{name:"CBP / Border Patrol",detail:"Federal employees face the same specialist desert."}]} />
      <CostComparisonTable title="What Weight Loss Costs in McAllen" localCompetitors={[{name:"North McAllen / Sharyland Concierge",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"10th St MedSpas",cost:"$200-$400/mo",consult:"Monthly",access:"Variable"},{name:"DHR Endocrinology",cost:"$80 Copay+Rx",consult:"20-26 Week Wait",access:"1 Provider per 800K"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="4 Hours to San Antonio, 6 to Houston" transitText="McAllen sits on US-83/I-2. San Antonio is 4 hours NW. Houston is 6 hours NE. The Valley is functionally isolated." hospitalText="<strong>South Texas Health</strong> and <strong>DHR Health</strong> serve the mid-Valley." />
      <InteractiveFAQ faqs={[{q:"I work for CBP. Is this confidential?",a:"Yes. Completely independent of your federal employer."},{q:"Do you deliver to Edinburg, Mission, and Pharr?",a:"Yes. All Hidalgo County addresses."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX operates in compliance with the <strong>Texas Medical Board</strong>." />
      <DeliveryGridMap cityName="McAllen" mapQuery="McAllen, TX" coordinates="26.2034° N, 98.2300° W" counties="Hidalgo County" neighborhoods={['North McAllen','Edinburg','Mission','Pharr','Weslaco','Harlingen','San Juan','Alamo']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
