"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationYuma() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Arizona" cityName="Yuma" headline="Clinical GLP-1 Weight Loss in <span style='color: #2ECC71'>Yuma</span>" subheadline="Yuma is the sunniest city on Earth—averaging 90% of daylight hours in sunshine. MCAS Yuma trains Marine Corps aviation. Yuma Proving Ground tests every piece of Army equipment in extreme heat. But 115°F summers make outdoor exercise dangerous for 5 months, and the nearest specialist is 3 hours away in Phoenix or Tucson." dataPoint1="Yuma County's adult obesity rate exceeds 35%. The city is functionally isolated—Phoenix is 3 hours NE, San Diego is 3 hours NW, and Tucson is 3.5 hours east. The agricultural economy (Yuma grows 90% of US winter lettuce) adds a seasonal workforce." dataPoint2="Telehealth FX serves the Marine aviation community, Army proving ground workers, and agricultural workforce without the 3-hour desert drive." />
      <PatientArchetype archetype="The Yuma Proving Ground Weapons Tester" quote="I test weapons systems at Yuma Proving Ground—the Army's premier hot-weather test facility. I'm outside in 115°F heat watching artillery impact zones. The irony is that this heat makes normal outdoor exercise medically dangerous from May through October. My FEHB plan has an 18-week specialist referral. Phoenix is 3 hours. There's nothing between here and there." details="<strong>Patient Profile:</strong> Steve, 41, Weapons Test Engineer, US Army Yuma Proving Ground.<br/><br/><strong>The Challenge:</strong> 115°F outdoor weapons testing. Heat makes exercise dangerous 5 months/year. FEHB specialist wait 18 weeks. Phoenix/Tucson both 3+ hours away.<br/><br/><strong>The Intervention:</strong> Completed intake from home in Foothills area. AZ-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Sunniest City and Its Hottest Problem" paragraphs={["Yuma holds the Guinness record for sunniest city on Earth—averaging 4,015 hours of sunshine annually. But that sunshine comes with temperatures exceeding 110°F for months. The heat is not uncomfortable—it is medically dangerous. Heat stroke prevention guidance from MCAS Yuma and Yuma Proving Ground restricts outdoor physical activity during peak hours from May through September.","The agricultural economy is significant: Yuma County produces 90% of the nation's winter leafy vegetables. The field workers, packing house employees, and irrigation managers face heat exposure alongside the military community. The seasonal agricultural population swells Yuma's healthcare demand November through March.","Yuma Regional Medical Center is the sole hospital. The nearest alternative is a 3-hour drive in any direction—Phoenix (NE), Tucson (E), or San Diego (NW). For specialist care, Yuma residents face either the local waitlist or a day-long desert drive.","GLP-1 medications serve Yuma's extreme-heat community—Marines, weapons testers, and agricultural workers—delivering metabolic care without the 3-hour drive across the Sonoran Desert."]} citations={["Yuma County Health Department. (2025). <em>Community Health Assessment</em>.","Northern Arizona University-Yuma. (2024). <em>Extreme Heat, Military Workforce, and Healthcare Access in the Lower Colorado River Valley</em>."]} />
      <InsuranceBreakdown title="Marines, Proving Ground, and Lettuce" text="Yuma's economy spans military, agriculture, and border trade." employers={[{name:"MCAS Yuma / YPG (TRICARE/FEHB)",detail:"Marine aviation + Army testing. Specialist referrals 16-20 weeks."},{name:"Yuma Regional Medical Center",detail:"Sole hospital for the Yuma metro. Limited specialist depth."},{name:"Agriculture / Dole / Tanimura & Antle",detail:"Seasonal agricultural plans with minimal specialist networks."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Yuma" localCompetitors={[{name:"Foothills / Somerton Concierge",cost:"$400-$700/mo",consult:"In-Person",access:"Branded Only"},{name:"32nd St MedSpas",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"YRMC Endocrinology",cost:"$100 Copay+Rx",consult:"14-20 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="3 Hours from Anywhere" transitText="Yuma sits on I-8. Phoenix is 3 hours NE. San Diego is 3 hours NW. Tucson is 3.5 hours east. El Centro is 60 min west." hospitalText="<strong>Yuma Regional Medical Center</strong> is the sole hospital." />
      <InteractiveFAQ faqs={[{q:"I test weapons at YPG. Is this confidential?",a:"Yes. Completely independent of your federal employer and FEHB."},{q:"Do you deliver to San Luis, Somerton, and Wellton?",a:"Yes. All Yuma County addresses."}]} />
      <StateLegalFramework stateName="Arizona" boardName="Arizona Medical Board" text="Telehealth FX operates in compliance with the <strong>Arizona Medical Board</strong>." />
      <DeliveryGridMap cityName="Yuma" mapQuery="Yuma, AZ" coordinates="32.6927° N, 114.6277° W" counties="Yuma County" neighborhoods={['Foothills','Somerton','San Luis','Wellton','Fortuna Foothills','Gadsden','Yuma Proving Ground']} />
      <FinalCTA stateName="Arizona" />
    </div>
  );
}
