"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationDothan() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Alabama" cityName="Dothan" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Dothan</span>" subheadline="Dothan is the Peanut Capital of the World—and home to Fort Novosel (formerly Fort Rucker), where every Army aviator earns their wings. The helicopter pilots and crew chiefs who fly America's Apaches, Black Hawks, and Chinooks depend on a healthcare system in Alabama's rural Wiregrass region." ctaText="Check Alabama Eligibility" />
      <PatientArchetype archetype="The Fort Novosel Apache Flight Instructor" quote="I teach Army pilots to fly the AH-64 Apache—the most lethal rotary-wing platform in the world. I sit in a simulator or cockpit for 8 hours, then eat at the O-Club or drive to Dothan for peanut-everything and fried catfish. My TRICARE specialist referral from Lyster Army Health Clinic is 22 weeks. Montgomery is 90 min north. I teach people to fly gunships. I can't get an appointment." details="<strong>Patient Profile:</strong> CW3 Banks, 36, Apache Flight Instructor Pilot, Fort Novosel.<br/><br/><strong>The Challenge:</strong> Cockpit/simulator sedentary hours. O-Club + Dothan comfort food. Lyster AHC specialist wait 22 weeks. Montgomery 90 min. No alternative.<br/><br/><strong>The Intervention:</strong> Completed intake from off-post in Daleville. AL-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="Where Every Army Aviator Gets Their Wings" paragraphs={["Fort Novosel (renamed in 2023 from Fort Rucker) is the US Army Aviation Center of Excellence—every Army helicopter pilot, from the UH-60 Black Hawk to the AH-64 Apache to the CH-47 Chinook, trains here. The installation adds 15,000+ soldiers, civilians, and families to the Wiregrass region.","Dothan's food culture is Deep South and peanut-centric: boiled peanuts at every gas station, fried peanuts, peanut brittle, plus the standard Alabama fried catfish, BBQ, and meat-and-three canon. Hunt's Seafood and the Wiregrass country restaurants define the food environment.","Southeast Health (formerly Southeast Alabama Medical Center) is the sole major hospital. The Wiregrass region is rural Alabama—the nearest alternative is Montgomery (90 min) or Pensacola (2 hours). Lyster Army Health Clinic serves the military with community-clinic specialist capacity.","GLP-1 medications serve the Army aviation community, Dothan's peanut agriculture workforce, and the Wiregrass—delivering metabolic care to the community that trains America's helicopter pilots."]} citations={["Houston County Health Department. (2025). <em>Community Health Assessment</em>.","Troy University-Dothan. (2024). <em>Military Healthcare Access in the Alabama Wiregrass</em>."]} />
      <InsuranceBreakdown title="Army Aviation and the Peanut Capital" text="Dothan's economy centers on military aviation, agriculture, and healthcare." employers={[{name:"Fort Novosel / USAACE (TRICARE)",detail:"15,000+ aviators and families. Lyster AHC specialist waits 20-24 weeks."},{name:"Southeast Health",detail:"Sole major hospital for the Wiregrass region."},{name:"Peanut Agriculture / Wayne Farms",detail:"Agricultural and poultry processing plans."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Dothan" localCompetitors={[{name:"North Dothan / Headland Concierge",cost:"$400-$600/mo",consult:"In-Person",access:"Branded Only"},{name:"Ross Clark Circle MedSpas",cost:"$200-$400/mo",consult:"Monthly",access:"Variable"},{name:"Southeast Health Endocrinology",cost:"$80 Copay+Rx",consult:"18-24 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="The Wiregrass: 90 Min from Anything" transitText="Dothan sits on US-231 and US-84. Montgomery is 90 min NW. Pensacola is 2 hours S. Panama City is 90 min SE." hospitalText="<strong>Southeast Health</strong> is the sole major hospital. <strong>Lyster AHC</strong> serves Fort Novosel." />
      <InteractiveFAQ faqs={[{q:"Will GLP-1 affect my flight physical?",a:"Consult your flight surgeon. Telehealth FX is independent of military medical records."},{q:"Do you deliver to Daleville, Enterprise, and Ozark?",a:"Yes. All Houston, Dale, and Coffee County addresses."}]} />
      <StateLegalFramework stateName="Alabama" boardName="Alabama Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>Alabama Board of Medical Examiners</strong>." />
      <DeliveryGridMap cityName="Dothan" mapQuery="Dothan, AL" coordinates="31.2232° N, 85.3905° W" counties="Houston County, Dale County, Coffee County" neighborhoods={['North Dothan','Daleville','Enterprise','Ozark','Headland','Midland City','Fort Novosel']} />
      <FinalCTA stateName="Alabama" />
    </div>
  );
}
