"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationBatonRouge() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Louisiana" cityName="Baton Rouge" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Baton Rouge</span>" subheadline="Baton Rouge is Louisiana's capital and the petrochemical corridor's anchor city. The refineries along the Mississippi River run 24/7, and the state government workforce fills the Capitol complex. Both populations face the same specialist shortage in a state with the third-highest obesity rate in America." ctaText="Check Louisiana Eligibility" />
      <PatientArchetype archetype="The ExxonMobil Baton Rouge Refinery Operator" quote="I run a distillation unit at the ExxonMobil refinery—one of the largest in the country. Twelve-hour rotating shifts. The canteen food is industrial cafeteria grade. Louisiana's food culture is incredible, but at 2 AM on a night shift, I'm eating vending machine chips and gas station boudin. My Blue Cross plan has one endocrinologist in network within 30 miles—and she's booked 5 months out." details="<strong>Patient Profile:</strong> Darryl, 42, Process Operator at ExxonMobil Baton Rouge Refinery.<br/><br/><strong>The Challenge:</strong> 12-hour rotating shifts at one of America's largest refineries. The refinery canteen serves industrial-grade food. Night shift eating patterns drive severe insulin resistance. Louisiana's specialist shortage means 5+ month waits.<br/><br/><strong>The Intervention:</strong> Completed intake from his home in Gonzales after a night shift. LA-licensed physician prescribed compounded Tirzepatide within 20 hours." />
      <ClinicalDeepDive title="The Petrochemical Corridor and the Capitol Paradox" paragraphs={["Baton Rouge anchors Louisiana's petrochemical corridor—a stretch of refineries and chemical plants along the Mississippi River from New Orleans to Baton Rouge known locally as 'Cancer Alley.' ExxonMobil's Baton Rouge refinery is among the largest in the US, and Dow, BASF, and dozens of other chemical companies line the river. The shift-work workforce mirrors Corpus Christi and Tulsa—12-hour rotating schedules that destroy circadian rhythm and metabolic consistency.","The state government workforce adds a second metabolic profile: sedentary Capitol complex desk workers navigating Louisiana's extraordinary food culture. Baton Rouge's food scene—crawfish, boudin, jambalaya, cracklins, and the drive-through daiquiri shops that are uniquely Louisiana—creates caloric density that rivals New Orleans.","Louisiana's obesity rate (40.1%) is the third-highest in the nation. The specialist shortage is acute statewide, and Baton Rouge—despite having Our Lady of the Lake and Baton Rouge General—cannot provide the metabolic specialist capacity that a state capital with major refinery operations requires.","GLP-1 medications serve both Baton Rouge populations—the refinery shift workers and the Capitol desk workers—without requiring either to navigate the specialist shortage."]} citations={["East Baton Rouge Parish Health Unit. (2025). <em>Community Health Assessment</em>.","LSU Health Sciences Center. (2024). <em>Obesity, Petrochemical Shift Work, and Healthcare Access in the Capital Region</em>."]} />
      <InsuranceBreakdown title="Refineries, State Government, and LSU" text="Baton Rouge's employer landscape spans petrochemical, government, and education." employers={[{name:"ExxonMobil / Dow / BASF (Refineries)",detail:"Refinery plans apply standard PBM restrictions in a region with critical specialist shortages."},{name:"State of Louisiana (Capitol Workforce)",detail:"State employee plans require Step Therapy that takes 6+ months in a state with limited endocrinology capacity."},{name:"Our Lady of the Lake / Baton Rouge General",detail:"Regional health systems face overwhelming demand."}]} />
      <CostComparisonTable title="What Weight Loss Actually Costs in Baton Rouge" localCompetitors={[{name:"Bocage / Highland Concierge",cost:"$600-$1,000/mo",consult:"In-Person",access:"Branded Only"},{name:"Perkins Rd MedSpas",cost:"$350-$600/mo",consult:"Monthly",access:"Variable"},{name:"OLOL Endocrinology",cost:"$100 Copay+Rx",consult:"16-22 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass the I-10/I-12 Merge & OLOL Waitlists" transitText="Baton Rouge's I-10/I-12 interchange and the Mississippi River Bridge create daily gridlock. Getting from Denham Springs or Gonzales to a specialist appointment in the city takes 45-60 minutes." hospitalText="<strong>Our Lady of the Lake</strong> and <strong>Baton Rouge General</strong> serve the region. Specialist waits average 16-22 weeks." />
      <InteractiveFAQ faqs={[{q:"I work rotating shifts at the refinery. When do I do the intake?",a:"Anytime. Fully asynchronous—no appointment."},{q:"Do you deliver to Denham Springs and Gonzales?",a:"Yes. All East Baton Rouge, Livingston, and Ascension Parish addresses."}]} />
      <StateLegalFramework stateName="Louisiana" boardName="Louisiana State Board of Medical Examiners" text="Telehealth FX operates in compliance with the <strong>LSBME</strong> and Louisiana telehealth statutes." />
      <DeliveryGridMap cityName="Baton Rouge" mapQuery="Baton Rouge, LA" coordinates="30.4515° N, 91.1871° W" counties="East Baton Rouge Parish, Livingston Parish, Ascension Parish" neighborhoods={['Bocage','Highland','Southdowns','Denham Springs','Gonzales','Prairieville','Central','Zachary']} />
      <FinalCTA stateName="Louisiana" />
    </div>
  );
}
