"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationAugusta() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Georgia" cityName="Augusta" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Augusta</span>" subheadline="Augusta hosts The Masters every April—the most exclusive sporting event in the world. The city that serves pimento cheese sandwiches for $1.50 at Augusta National faces an adult obesity rate exceeding 36% outside those hallowed gates. Fort Eisenhower (formerly Fort Gordon) adds 30,000 military personnel to the healthcare demand." ctaText="Check Georgia Eligibility" />
      <PatientArchetype archetype="The Fort Eisenhower Cyber Command Analyst" quote="I work in Army Cyber Command at Fort Eisenhower. My job is classified signals intelligence in a windowless SCIF. I sit at screens for 10 hours, eat DFAC food or vending machine snacks, and drive back to my apartment in Evans. TRICARE's specialist referral at the base clinic is 16 weeks. I protect the nation's digital infrastructure but I can't get a basic doctor's appointment." details="<strong>Patient Profile:</strong> SPC Morgan, 27, Cyber Intelligence Analyst at Army Cyber Command, Fort Eisenhower.<br/><br/><strong>The Challenge:</strong> SCIF-bound classified work, DFAC diet, TRICARE specialist bottleneck. Fort Eisenhower's Cyber Command workforce is highly technical and entirely sedentary.<br/><br/><strong>The Intervention:</strong> Completed intake from apartment in Evans. GA-licensed physician prescribed compounded Semaglutide within 20 hours." />
      <ClinicalDeepDive title="The Masters and the Military" paragraphs={["Augusta's identity is split: the world knows it for The Masters at Augusta National, where perfection is curated down to the azalea pruning schedule. The local reality is a mid-size Southern city anchored by Fort Eisenhower (Army Cyber Command), the Savannah River Site (nuclear), and Augusta University Health.","Fort Eisenhower's transformation into the Army's Cyber Center of Excellence has brought thousands of technical military and civilian DoD workers. The Cyber Command SCIF workforce mirrors Huntsville, Colorado Springs, and Tucson: sedentary, windowless, cafeteria-dependent.","The food culture is Georgia comfort: BBQ, fried chicken, peach cobbler, and the soul food tradition of the CSRA (Central Savannah River Area). Augusta's restaurant scene is modest but calorie-dense.","Augusta University Health is the region's academic medical center, serving not just Augusta but the broader CSRA region extending into South Carolina. Specialist capacity is strained by the combined military and civilian population."]} citations={["Augusta-Richmond County Health Department. (2025). <em>Community Health Assessment</em>.","Augusta University Medical College of Georgia. (2024). <em>Military Population Growth and Healthcare Access in the CSRA</em>."]} />
      <InsuranceBreakdown title="Cyber Command, Nuclear, and the CSRA" text="Augusta's economy centers on military, nuclear, and healthcare." employers={[{name:"Fort Eisenhower / Army Cyber Command (TRICARE)",detail:"Military and DoD civilian workforce faces 16+ week specialist waits."},{name:"Savannah River Site (DOE)",detail:"Nuclear facility workers have FEHB or contractor plans with standard restrictions."},{name:"Augusta University Health",detail:"The region's academic medical center serves military and civilian demand."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Augusta" localCompetitors={[{name:"Evans / Martinez Concierge",cost:"$500-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"Washington Rd MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"AU Health Endocrinology",cost:"$100 Copay+Rx",consult:"12-18 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass Bobby Jones & AU Waitlists" transitText="Augusta sprawls along I-20 and Washington Road (the road to Augusta National). Getting from Fort Eisenhower to a specialist at AU Health requires crossing the city." hospitalText="<strong>Augusta University Health</strong> and <strong>Doctors Hospital</strong> serve the CSRA. Specialist waits average 12-18 weeks." />
      <InteractiveFAQ faqs={[{q:"Will this affect my security clearance?",a:"No. GLP-1 medications are not controlled substances."},{q:"Do you deliver to Evans, Martinez, and Aiken (SC)?",a:"Yes. All Richmond, Columbia, and Aiken (SC) County addresses."}]} />
      <StateLegalFramework stateName="Georgia" boardName="Georgia Composite Medical Board" text="Telehealth FX operates in compliance with the <strong>Georgia Composite Medical Board</strong> and OCGA § 43-34." />
      <DeliveryGridMap cityName="Augusta" mapQuery="Augusta, GA" coordinates="33.4735° N, 82.0105° W" counties="Richmond County, Columbia County, Aiken County (SC)" neighborhoods={['Evans','Martinez','North Augusta (SC)','Grovetown','Hephzibah','Aiken (SC)','Fort Eisenhower']} />
      <FinalCTA stateName="Georgia" />
    </div>
  );
}
