"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './location-modules.jsx';
export function LocationSiouxFalls() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="South Dakota" cityName="Sioux Falls" headline="Clinical GLP-1 Weight Loss in <br/><span style='color: #2ECC71'>Sioux Falls</span>" subheadline="Sioux Falls is the largest city in South Dakota and the economic engine of the Northern Plains. Sanford Health and Avera anchor both the economy and the healthcare system—but the same organizations that employ the city cannot provide enough specialist appointments for a rapidly growing population in one of America's coldest metros." ctaText="Check South Dakota Eligibility" />
      <PatientArchetype archetype="The Smithfield Foods Pork Processing Supervisor" quote="I supervise the kill floor at the Smithfield plant—one of the largest pork processing facilities in the world. My shifts are 10 hours in near-freezing temperatures. The cafeteria serves what you'd expect from a meatpacking plant. My Sanford plan has a 14-week wait for endocrinology. Sioux Falls processes more pork per day than most states process in a week, but I can't get a doctor's appointment." details="<strong>Patient Profile:</strong> Miguel, 38, Production Supervisor at Smithfield Foods, Sioux Falls.<br/><br/><strong>The Challenge:</strong> 10-hour shifts in a refrigerated pork processing facility. Near-freezing temps, physical exhaustion, industrial cafeteria. Sanford specialist waits stretch to 14 weeks as Sioux Falls outgrows its healthcare.<br/><br/><strong>The Intervention:</strong> Completed intake from apartment on the east side. SD-licensed physician prescribed compounded Semaglutide within 24 hours." />
      <ClinicalDeepDive title="The Northern Plains' Fastest-Growing City" paragraphs={["Sioux Falls has been one of the fastest-growing cities in the Midwest for a decade, driven by financial services (Citibank's credit card operations, Wells Fargo), healthcare (Sanford, Avera), and the meatpacking industry (Smithfield). The growth has strained a healthcare system that already serves as the referral center for all of South Dakota and parts of Minnesota, Iowa, and Nebraska.","The winters are brutal—averaging 42 inches of snow and temperatures that regularly hit -20°F. The outdoor activity window is limited to May through September, and the SAD/carbohydrate craving cycle is severe at this latitude. Comfort food traditions lean Scandinavian and German: hotdish (casserole), chislic (cubed fried meat unique to SD), lefse, and the Midwest staples of brats and cheese.","Sanford Health and Avera Health are the two dominant systems—competing for patients, physicians, and market share in a city where both are also the largest employers. Despite this competition, specialist capacity hasn't kept pace with population growth.","GLP-1 medications serve Sioux Falls' diverse workforce—meatpacking workers, financial services employees, and healthcare staff—without competing for Sanford or Avera's overbooked specialist slots."]} citations={["Sioux Falls Health Department. (2025). <em>Community Health Assessment</em>.","USD Sanford School of Medicine. (2024). <em>Population Growth and Healthcare Capacity in the Sioux Falls Metropolitan Area</em>."]} />
      <InsuranceBreakdown title="Meatpacking, Banking, and the Two-System Duopoly" text="Sioux Falls' economy spans meatpacking, financial services, and healthcare." employers={[{name:"Smithfield Foods / POET Ethanol",detail:"Industrial employers offer plans with standard PBM restrictions. Meatpacking shift schedules conflict with daytime programs."},{name:"Citibank / Wells Fargo / MetaBank",detail:"Financial sector plans apply standard specialty-tier GLP-1 restrictions."},{name:"Sanford Health / Avera Health",detail:"The two health systems compete but both face the same specialist capacity constraints."}]} />
      <CostComparisonTable title="What Weight Loss Costs in Sioux Falls" localCompetitors={[{name:"Southeast SF Concierge",cost:"$600-$900/mo",consult:"In-Person",access:"Branded Only"},{name:"41st St MedSpas",cost:"$300-$550/mo",consult:"Monthly",access:"Variable"},{name:"Sanford Endocrinology",cost:"$100 Copay+Rx",consult:"12-16 Week Wait",access:"Prior Auth"}]} telehealthPrice="From $146 / mo" />
      <LocalTransitPain title="Bypass I-90/I-29 & Sanford Waitlists" transitText="Sioux Falls sits at I-90 and I-29. The nearest alternative city for healthcare is Minneapolis—4 hours north." hospitalText="<strong>Sanford USD Medical Center</strong> and <strong>Avera McKennan</strong> serve the Northern Plains. Specialist waits average 12-16 weeks." />
      <InteractiveFAQ faqs={[{q:"I work at the Smithfield plant. When do I do the intake?",a:"Anytime. Fully asynchronous—no appointment."},{q:"Do you deliver to Brandon and Harrisburg?",a:"Yes. All Minnehaha and Lincoln County addresses."}]} />
      <StateLegalFramework stateName="South Dakota" boardName="South Dakota Board of Medical and Osteopathic Examiners" text="Telehealth FX operates in compliance with the <strong>SD Board of Medical and Osteopathic Examiners</strong> and SDCL § 36-4." />
      <DeliveryGridMap cityName="Sioux Falls" mapQuery="Sioux Falls, SD" coordinates="43.5460° N, 96.7313° W" counties="Minnehaha County, Lincoln County" neighborhoods={['Southeast','Tea','Brandon','Harrisburg','Dell Rapids','Canton','Hartford']} />
      <FinalCTA stateName="South Dakota" />
    </div>
  );
}
