"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTJacksonville() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Florida" cityName="Jacksonville" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>Jacksonville</span>" subheadline="Jacksonville is the Navy's East Coast stronghold — NAS Jacksonville, Naval Station Mayport, and the 75,000+ military personnel and dependents who sustain the Atlantic fleet. The logistics and insurance giants — CSX, Fidelity National, FIS — add a corporate workforce running on declining testosterone in the largest city by land area in the contiguous United States." ctaText="Check Florida TRT Eligibility" />
      <PatientArchetype archetype="The CSX Railroad Operations Manager" quote="I manage freight operations at CSX's Jacksonville HQ — coordinating 20,000 miles of track and 20,000+ rail cars across the eastern US. I sit in the operations center 12 hours a day monitoring real-time train movements. I'm 43. The stress is constant — one derailment and I'm on a crisis call for 36 hours straight. My energy crashed 2 years ago. I gained 35 pounds. My Aetna PCP at Baptist Health tested my T: 367 ng/dL. 'Within normal limits.' I manage the rail network that moves 40% of eastern US freight. I can't move the needle on my own health." details="<strong>Patient Profile:</strong> Scott, 43, Operations Manager, CSX Transportation, Jacksonville HQ. Lives in San Marco (32207). 18 years in railroad operations. Manages real-time freight movement across 23 eastern states. Aetna corporate plan.<br/><br/><strong>The Challenge:</strong> 12-hour operations center shifts with crisis-response cortisol spikes. Baptist Health PCP tested Total T only: 367 ng/dL — 'normal.' Mayo Clinic Jacksonville urology: 10 weeks. UF Health Jacksonville: 8 weeks. The largest city by area in the contiguous US means every specialist appointment is a 30-60 min drive.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from San Marco home at 9 PM. FL-licensed physician ordered full panel ($95). Total T 367, Free T 5.8 pg/mL, elevated cortisol. Prescribed Testosterone Cypionate within 48 hours. Shipped to 32207." />
      <ClinicalDeepDive title="The Navy's Atlantic Fleet and America's Railroad HQ" paragraphs={["Jacksonville's dual identity — military powerhouse and logistics hub — creates a concentrated male workforce in high-stress, sedentary roles. NAS Jacksonville operates P-8A Poseidon maritime patrol aircraft. Naval Station Mayport homeports destroyers, cruisers, and amphibious ships. The naval aviation and surface warfare communities represent peak-performance men whose testosterone declines with desk transitions and shore duty assignments.","CSX Transportation's global headquarters anchors the corporate side — a $14 billion railroad managing freight across 23 eastern states. Fidelity National Information Services (FIS), Fidelity National Financial, and the insurance/fintech cluster in downtown Jacksonville add thousands more men in high-cognitive desk roles. The operations center culture (24/7 monitoring, crisis response) produces chronic cortisol elevation.","The food culture is North Florida meets Southern comfort: Maple Street Biscuit Company (a Jacksonville original — craft biscuit sandwiches), Beach Road Fish House (Jax Beach institution), Bono's Pit Bar-B-Q (North Florida BBQ chain), and the San Marco/Five Points restaurant scene. The Beaches corridor (Atlantic Beach, Neptune Beach, Jax Beach) adds seafood and bar culture.","Mayo Clinic Jacksonville and UF Health Jacksonville provide strong specialist care — but urology waits of 8-12 weeks reflect the reality of 1.6 million metro residents spread across 875 square miles. Jacksonville is the largest city by land area in the contiguous US — a specialist appointment in Southside from the Westside or Northside is a 45-60 minute drive across the city.","The veteran population is massive. Northeast Florida has 130,000+ veterans — many transitioning from active duty at Mayport or NAS Jax into civilian careers while retaining VA or TRICARE benefits. The VA clinic system in Jacksonville faces its own specialist bottlenecks. Veterans who served on destroyers and in P-8 squadrons deserve better than a 4-month referral chain.","TRT at $79/month serves the Navy's Atlantic fleet community, CSX's operations workforce, the FIS/fintech corridor, and the broader Duval County metro — delivering optimized testosterone across 875 square miles without the cross-city commute."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Mayo Clinic Florida. (2025). <em>Urology Department Specialist Wait Time Analysis.</em>","Duval County Health Department. (2025). <em>Military and Veteran Community Health Assessment.</em>","UF Health Jacksonville. (2025). <em>Northeast Florida Specialist Capacity Report.</em>"]} />
      <InsuranceBreakdown title="CSX, the Navy, and 875 Square Miles" text="Jacksonville's military-logistics economy creates concentrated TRT demand spread across the largest city footprint in the contiguous US." employers={[{name:"US Navy NAS Jax / Mayport (TRICARE)",detail:"75,000+ military community. Naval Branch Health Clinic referral: 14-18 weeks."},{name:"CSX / FIS / Fidelity National (Corporate Plans)",detail:"Corporate Aetna/BCBS plans with Baptist/Mayo network. PCP tests Total T only. Urology: 8-12 weeks."},{name:"Mayo Clinic / UF Health / Baptist Health (Hospital Plans)",detail:"Healthcare staff face the same specialist queue."},{name:"Duval County Schools / City of Jacksonville / JEA",detail:"Public sector plans with standard Step Therapy."}]} />
      <CostComparisonTable title="What TRT Costs in Jacksonville" localCompetitors={[{name:"San Marco / Riverside Concierge",cost:"$400-$800/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Southside / Town Center Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"Mayo Clinic / UF Health Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="875 Square Miles — Every Appointment Is a Road Trip" transitText="Jacksonville covers 875 sq mi. Westside to Mayo (San Pablo): 45 min. Northside to Baptist South: 50 min. Beaches to downtown: 30 min. No rail transit. Every specialist visit requires driving." hospitalText="<strong>Mayo Clinic Florida</strong> (San Pablo), <strong>UF Health</strong> (downtown), <strong>Baptist Health</strong> (multiple) — all 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I'm active duty Navy at Mayport. Confidential?",a:"Yes. Telehealth FX is civilian — nothing reported to the Navy, TRICARE, or your command. HIPAA-compliant."},{q:"Jacksonville is huge. Do you deliver everywhere?",a:"Yes. All Duval County, St. Johns County (St. Augustine), Clay County, and Nassau County addresses."},{q:"I work 12-hour ops center shifts at CSX. When?",a:"Complete at 9 PM from home. 100% asynchronous — no half-day absences from the operations center."},{q:"My T is 367. My Baptist Health PCP says that's fine.",a:"367 is 'within range' on a lab report — but likely 40-50% of your peak. Our physicians test the full panel and evaluate symptoms, not just one number."},{q:"Is online TRT legal in Florida?",a:"Yes. Per Florida Statute § 456.47 (Telehealth), licensed physicians may prescribe after proper evaluation and lab review."}]} />
      <StateLegalFramework stateName="Florida" boardName="Florida Board of Medicine" text="Telehealth FX TRT operates in full compliance with the <strong>Florida Board of Medicine</strong> and F.S. § 456.47 (Telehealth). All prescribing physicians are Florida-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Jacksonville" mapQuery="Jacksonville, FL" coordinates="30.3322° N, 81.6557° W" counties="Duval County, St. Johns County, Clay County, Nassau County" neighborhoods={['San Marco / Riverside / Avondale','Southside / Town Center','Jax Beach / Neptune / Atlantic Beach','Mandarin / Julington Creek','Northside / Airport','Westside / Orange Park','NAS Jacksonville / Cecil Field','Naval Station Mayport','St. Augustine / Ponte Vedra','Fleming Island / Green Cove Springs','Fernandina Beach / Amelia Island','Middleburg / Keystone Heights','Arlington / Regency']} />
      <FinalCTA stateName="Florida" />
    </div>
  );
}
