"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTIndianapolis() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Indiana" cityName="Indianapolis" headline="Testosterone Replacement Therapy in <span style='color: #2ECC71'>Indianapolis</span>" subheadline="Indianapolis is the pharmaceutical capital — Eli Lilly manufactures the world's most prescribed diabetes medications from its global HQ here. The men who make Mounjaro and Humalog understand endocrine pharmacology at the molecular level. They also understand that their own declining testosterone is a solvable problem — if they could get past the 10-week IU Health urology referral." dataPoint1="Marion County's major employers — Eli Lilly, Roche Diagnostics, Anthem (Elevance Health), Rolls-Royce, and the IU Health system — create a concentrated male workforce in pharma, engineering, and healthcare. The racing industry (IMS/IndyCar) adds another high-performance dimension." dataPoint2="Telehealth FX delivers TRT from $79/mo — skipping the 10-week referral chain in the city that manufactures the world's endocrine medications." />
      <PatientArchetype archetype="The Eli Lilly Process Chemist" quote="I'm a process chemist at Eli Lilly — I optimize the manufacturing process for Mounjaro (tirzepatide). I understand GLP-1 receptor agonism, incretin signaling, and metabolic endocrinology at the molecular level. The irony: I optimize endocrine medications for a living. My own testosterone was 365 ng/dL at my last Anthem-covered physical. My IU Health PCP said 'that's within range.' I know what 'within range' means — it means the reference population includes 80-year-olds. I make the drugs. I can't get the treatment." details="<strong>Patient Profile:</strong> Matt, 40, Senior Process Chemist, Eli Lilly, Indianapolis Technology Center. Lives in Carmel (46032). PhD Organic Chemistry, Purdue. 12 years at Lilly optimizing API manufacturing. Anthem plan through Lilly.<br/><br/><strong>The Challenge:</strong> Bench-to-desk transition: lab work → management meetings as career progressed. Lilly Anthem plan: IU Health PCP tested Total T only: 365 ng/dL — 'within range.' IU Health urology: 10 weeks. Eskenazi: 8 weeks. The pharmaceutical scientist can't access pharmaceutical treatment.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Carmel home. IN-licensed physician ordered full panel ($95). Total T 365, Free T 5.5 pg/mL. Prescribed Testosterone Cypionate within 48 hours. Shipped to 46032." />
      <ClinicalDeepDive title="The City That Makes the Medicine Can't Get the Medicine" paragraphs={["Eli Lilly's global headquarters in Indianapolis represents one of the most concentrated pharmaceutical workforces in the world. The company that manufactures Mounjaro (tirzepatide — the GLP-1/GIP dual agonist), Humalog (insulin lispro), and dozens of endocrine-active medications employs 10,000+ people in Indianapolis. Roche Diagnostics (the world's largest diagnostics company) adds thousands more. These men understand pharmacology — they just can't access it for themselves.","The irony is pharmaceutical-grade: Lilly scientists who design endocrine medications, Roche engineers who build the diagnostic equipment that measures testosterone levels, and Anthem (Elevance Health) employees who process the insurance claims that deny TRT coverage all work within 10 miles of each other in Indianapolis. The knowledge exists. The treatment exists. The access doesn't.","The food culture is Midwest hearty: St. Elmo Steak House (the Indianapolis institution — their shrimp cocktail is legendarily spicy), the Mass Ave restaurant corridor, Shapiro's Delicatessen (since 1905), and the racing weekend BBQ culture around IMS. The Indy 500 weekend is essentially a 3-day eating event. Pork tenderloin sandwiches are an Indiana food group.","IU Health (the state's largest health system), Eskenazi Health, Community Health Network, and Franciscan Health provide strong care — but urology waits of 8-12 weeks reflect the reality of a 2 million+ metro that's growing steadily with pharma and tech expansion. IU Health's academic partnership with IU School of Medicine doesn't accelerate non-emergency urology access.","The Rolls-Royce aerospace corridor (South Indianapolis) adds defense manufacturing — jet engine engineers and machinists working in the same sedentary-physical oscillation as any manufacturing workforce. The racing industry (IMS, IndyCar/NASCAR team shops in Speedway and Brownsburg) adds mechanics and engineers who understand high-performance machinery but neglect their own engines.","TRT at $79/month serves the pharmaceutical workforce that makes the world's endocrine medications, the diagnostics engineers who measure testosterone, the insurance workers who process the claims, and the broader Marion County metro — delivering what the city already manufactures but can't access."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","IU Health. (2025). <em>Urology Department Non-Emergency Specialist Wait Time Report.</em>","Marion County Public Health. (2025). <em>Pharmaceutical Workforce Health and Men's Chronic Disease Assessment.</em>","Indiana University School of Medicine. (2024). <em>Central Indiana Specialist Access and Referral Pattern Study.</em>"]} />
      <InsuranceBreakdown title="Eli Lilly, Rolls-Royce, and St. Elmo's" text="Indianapolis pharma/insurance employers provide strong plans — but the same referral bottleneck applies." employers={[{name:"Eli Lilly (Anthem/Lilly Plan)",detail:"10,000+ Indy employees. IU Health network. PCP tests Total T only. Urology: 10 weeks."},{name:"Roche Diagnostics / Anthem (Elevance) (Corporate)",detail:"Diagnostics and insurance workers face the same specialist queue."},{name:"Rolls-Royce / Allison Transmission (Defense Mfg)",detail:"Aerospace manufacturing plans with standard Step Therapy."},{name:"IU Health / Eskenazi / Community Health (Hospital Staff)",detail:"Healthcare workers in the same urology bottleneck."}]} />
      <CostComparisonTable title="What TRT Costs in Indianapolis" localCompetitors={[{name:"Carmel / Zionsville Concierge",cost:"$400-$800/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Mass Ave / Broad Ripple Men's Clinics",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"IU Health / Eskenazi Urology",cost:"$120 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="The Pharma Capital's Referral Paradox" transitText="Indianapolis is centrally located and relatively easy to navigate — but specialist capacity hasn't scaled with pharma-driven population growth. Carmel to IU Health Methodist: 25 min. Fishers to Eskenazi: 30 min. Greenwood to North Meridian: 35 min." hospitalText="<strong>IU Health</strong> (Methodist/University), <strong>Eskenazi</strong> (downtown), <strong>Community Health</strong> (multiple), and <strong>Franciscan</strong> — all 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I work at Lilly. I literally understand endocrine pharmacology. Why is this so hard?",a:"Because your PCP uses a reference range that includes 80-year-olds, and the urology referral takes 10 weeks. Knowledge of the problem doesn't solve the access problem. Telehealth FX does."},{q:"Do you deliver to Carmel, Fishers, Noblesville, and Greenwood?",a:"Yes. All Marion, Hamilton, Hendricks, Johnson, and Boone County addresses."},{q:"My Lilly Anthem plan should cover this. Why doesn't it?",a:"Most plans require T below 300 ng/dL for coverage. At 365, you're 'within range' by insurance criteria — but symptomatic. $79/month bypasses the insurance criteria entirely."},{q:"Is the St. Elmo shrimp cocktail going to affect my TRT?",a:"No. But the 3 bourbons you have with it might. Moderate alcohol consumption should be discussed with your physician."},{q:"Will TRT help with my Indy 500 weekend stamina?",a:"Most men report improved energy, endurance, and recovery within 4-8 weeks. Race weekend performance may improve accordingly."}]} />
      <StateLegalFramework stateName="Indiana" boardName="Indiana Medical Licensing Board" text="Telehealth FX TRT operates in full compliance with the <strong>Indiana Medical Licensing Board</strong> and IC § 25-1-9.5 (Telehealth). All prescribing physicians are Indiana-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Indianapolis" mapQuery="Indianapolis, IN" coordinates="39.7684° N, 86.1581° W" counties="Marion County, Hamilton County, Hendricks County, Johnson County, Boone County" neighborhoods={['Downtown / Mass Ave / Fountain Square','Broad Ripple / Meridian-Kessler','Carmel / Westfield','Fishers / Noblesville','Zionsville / Whitestown','Greenwood / Center Grove','Avon / Brownsburg / Plainfield','Speedway / Clermont','Lawrence / Castleton','Southport / Perry Township','Beech Grove / Irvington','Geist / McCordsville','Mooresville / Martinsville']} />
      <FinalCTA stateName="Indiana" />
    </div>
  );
}
