"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTPhoenix() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Arizona" cityName="Phoenix" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>Phoenix</span>" subheadline="Phoenix is the semiconductor capital — TSMC, Intel Chandler, and NXP are building the future of American chipmaking. The fab engineers who work in cleanrooms 12 hours a day under artificial light are experiencing testosterone decline accelerated by shift work, circadian disruption, and 115°F summers that confine 5 million people indoors for 4 months." ctaText="Check Arizona TRT Eligibility" />
      <PatientArchetype archetype="The TSMC Fab Process Engineer" quote="I'm a process engineer at TSMC's new fab in North Phoenix — the most advanced semiconductor manufacturing facility in the Western Hemisphere. I work 12-hour shifts in a cleanroom wearing a bunny suit under artificial fluorescent light. No sunlight. No windows. Rotating shifts destroy my sleep schedule. I'm 38. I feel 58. My energy is gone. My libido disappeared after the night-shift rotation started. My Banner Health PCP tested my T: 371 ng/dL. He said it was 'within range.' I engineer 3-nanometer chips — transistors smaller than a virus. I can't get a doctor to take my symptoms seriously." details="<strong>Patient Profile:</strong> James, 38, Process Engineer, TSMC Arizona (North Phoenix). Lives in Scottsdale (85254). Transferred from TSMC Tainan. Works rotating 12-hour shifts in a cleanroom (DuPont schedule). MS Electrical Engineering, NCTU. 14 years in semiconductor manufacturing.<br/><br/><strong>The Challenge:</strong> Cleanroom work = zero sunlight, artificial light, bunny suit, standing/sedentary mix. DuPont rotating shifts destroy circadian rhythm → suppresses melatonin → suppresses LH → suppresses testosterone. Banner PCP tested Total T only: 371 ng/dL — 'normal.' Mayo Clinic Scottsdale urology: 10 weeks. Phoenix summers (115°F) eliminate outdoor activity May-September.<br/><br/><strong>The Intervention:</strong> Completed intake from Scottsdale apartment during off-rotation day. AZ-licensed physician ordered full panel ($95). Total T 371, Free T 5.4 pg/mL (critically low), vitamin D 18 ng/mL (deficient). Prescribed Testosterone Cypionate within 48 hours. Shipped to 85254." />
      <ClinicalDeepDive title="Cleanrooms, Circadian Disruption, and 115°F" paragraphs={["Phoenix is experiencing a semiconductor renaissance. TSMC's $40 billion investment, Intel's $20 billion Chandler expansion, and NXP Semiconductors' Tempe and Chandler operations are creating tens of thousands of high-skill engineering jobs. These men work in cleanrooms — hermetically sealed environments with artificial light, controlled temperature, and zero natural sunlight exposure. The circadian disruption from rotating shifts compounds the testosterone decline.","The circadian-testosterone mechanism is specific: melatonin production requires darkness-light cycling. Cleanroom fluorescent lighting disrupts melatonin. Rotating shifts prevent consistent sleep patterns. Melatonin disruption → reduced GnRH pulsatility → reduced LH → reduced Leydig cell testosterone production. A fab engineer on DuPont rotation may lose testosterone at 3-4x the normal age-related rate.","The heat confinement is Phoenix-specific. From May through September, temperatures regularly exceed 110°F, reaching 115-120°F during peak events. The Valley of the Sun becomes an outdoor oven. Exercise shifts indoors. Social life shifts indoors. The already-indoor fab workforce now spends 100% of their time under artificial light. Vitamin D deficiency (common despite 300+ sunny days) further compounds testosterone decline through the VDR-Leydig cell pathway.","Mayo Clinic Scottsdale, Banner Health, HonorHealth, and Dignity Health represent strong healthcare systems — but urology waits of 8-12 weeks reflect the reality of a metro that grew from 3.2 million (2010) to 5+ million (2025) faster than specialist capacity expanded. The semiconductor boom is adding thousands more patients to an already-strained system.","Phoenix's men's health clinic market has grown rapidly — cash-pay clinics in Scottsdale and Tempe charging $250-600/month have proliferated to serve the tech workforce. Many are legitimate. Some are not. The price differential between these clinics and Telehealth FX ($79/month) reflects overhead, not quality of care.","TRT at $79/month serves Phoenix's semiconductor workforce, the defense contractors (Raytheon, General Dynamics), the healthcare systems' own employees, and the 5+ million metro residents — delivering optimized testosterone to men trapped in cleanrooms and 115°F heat."]} citations={["Leproult, R. & Van Cauter, E. (2011). <em>Effect of 1 Week of Sleep Restriction on Testosterone Levels in Young Healthy Men.</em> JAMA.","Wehr, E., et al. (2010). <em>Association of Vitamin D Status with Serum Androgen Levels in Men.</em> Clinical Endocrinology.","Mayo Clinic Arizona. (2025). <em>Men's Health Urology Wait Time Analysis.</em>","Maricopa County Department of Public Health. (2025). <em>Heat-Related Health and Men's Chronic Disease Report.</em>"]} />
      <InsuranceBreakdown title="TSMC, Intel, and the Cleanroom Problem" text="Phoenix semiconductor employers provide strong plans — but PCPs don't test comprehensive hormone panels and urology waits run 8-12 weeks." employers={[{name:"TSMC Arizona (Corporate Plan)",detail:"Transferred engineers + local hires. Banner Health network. PCP tests Total T only. Urology: 10+ weeks."},{name:"Intel Chandler / NXP (Corporate BCBS)",detail:"Fab engineers on DuPont rotation. Same circadian disruption, same incomplete testing."},{name:"Raytheon / General Dynamics (Defense BCBS)",detail:"Defense contractor plans with standard Step Therapy referral requirements."},{name:"Banner Health / HonorHealth / Mayo Scottsdale (Hospital Plans)",detail:"Healthcare staff face the same specialist bottleneck."}]} />
      <CostComparisonTable title="What TRT Costs in Phoenix" localCompetitors={[{name:"Scottsdale Concierge Men's Health",cost:"$400-$800/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Tempe / Chandler Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"Mayo Scottsdale / Banner Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="5 Million People, 115°F, 8-12 Week Waits" transitText="Phoenix sprawls across the Valley of the Sun. Scottsdale to a Banner specialist in Mesa: 45 min. North Phoenix (TSMC) to Mayo Scottsdale: 30 min. Chandler (Intel) to central Phoenix urology: 40 min. Every appointment is a heat-exposed commute." hospitalText="<strong>Mayo Clinic Scottsdale</strong>, <strong>Banner Health</strong> (multiple), <strong>HonorHealth</strong>, and <strong>Dignity Health</strong> — all 8-12 week urology waits for non-emergency TRT evaluation." />
      <InteractiveFAQ faqs={[{q:"I work DuPont rotating shifts in a cleanroom. Is my schedule destroying my testosterone?",a:"Likely contributing. Circadian disruption from rotating shifts suppresses melatonin → LH → testosterone production. Our comprehensive labs ($95) will establish your baseline."},{q:"My vitamin D is low despite living in Phoenix. Is that related?",a:"Yes. Vitamin D receptors on Leydig cells influence testosterone production. Fab engineers who never see sunlight commonly have vitamin D deficiency that compounds T decline."},{q:"Do you deliver to Scottsdale, Chandler, and Tempe?",a:"Yes. All Maricopa County and Pinal County addresses — Scottsdale, Chandler, Tempe, Mesa, Gilbert, Glendale, Peoria, Surprise, and beyond."},{q:"I transferred from TSMC Taiwan. Is online TRT legal in Arizona?",a:"Yes. Telehealth TRT prescribing is fully legal in Arizona per A.R.S. § 36-3602 when conducted by an AZ-licensed physician after proper evaluation and labs."},{q:"It's 115°F. Will medication survive shipping?",a:"Yes. All medications ship in insulated cold-pack containers designed to maintain temperature integrity even in Phoenix summer heat."}]} />
      <StateLegalFramework stateName="Arizona" boardName="Arizona Medical Board" text="Telehealth FX TRT operates in full compliance with the <strong>Arizona Medical Board</strong> and A.R.S. § 36-3602 (Telehealth). All prescribing physicians are Arizona-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Phoenix" mapQuery="Phoenix, AZ" coordinates="33.4484° N, 112.0740° W" counties="Maricopa County, Pinal County" neighborhoods={['Scottsdale','Chandler / Gilbert','Tempe / Mesa','North Phoenix / Deer Valley','Glendale / Peoria','Surprise / Sun City','Paradise Valley','Cave Creek / Carefree','Goodyear / Avondale / Buckeye','Fountain Hills','Queen Creek / San Tan Valley','Anthem / New River','Ahwatukee / Laveen']} />
      <FinalCTA stateName="Arizona" />
    </div>
  );
}
