"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTNashville() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Tennessee" cityName="Nashville" headline="Testosterone Replacement Therapy in <span style='color: #2ECC71'>Nashville</span>" subheadline="Nashville is the healthcare capital of America — HCA Healthcare, Community Health Systems, and Envision Healthcare are headquartered here. The men who run the nation's largest hospital chains understand healthcare economics at the enterprise level. They also understand that their own testosterone is declining while their PCPs call it 'normal' using the same outdated reference ranges their own companies' hospitals use." dataPoint1="Nashville's healthcare industry employs 300,000+ people in Middle Tennessee — the largest concentration of healthcare corporate leadership in America. The irony: the men who manage 2,000+ hospitals nationwide face the same 8-12 week urology wait at Vanderbilt that their patients face everywhere else." dataPoint2="Telehealth FX delivers TRT from $79/mo — bypassing the Vanderbilt referral chain in the city that runs American healthcare." />
      <PatientArchetype archetype="The HCA Healthcare Regional VP" quote="I'm a regional VP at HCA Healthcare — I oversee operations for 28 hospitals across the Southeast. I fly to hospitals Monday through Thursday. I sit in boardrooms, review quality metrics, and manage $4 billion in annual revenue. I'm 47. I understand hospital operations better than anyone. I also understand that my T of 339 ng/dL is not 'normal' — but my TriStar PCP (an HCA hospital, ironically) says it is. I manage 28 hospitals. I can't manage a urology referral in my own company's system. Vanderbilt urology: 12 weeks." details="<strong>Patient Profile:</strong> Robert, 47, Regional VP, HCA Healthcare, Nashville HQ. Lives in Brentwood (37027). Oversees 28 hospitals. $4B annual revenue responsibility. Travels Mon-Thu weekly. MBA from Owen School (Vanderbilt). Former Vanderbilt football.<br/><br/><strong>The Challenge:</strong> Constant travel Mon-Thu. HCA TriStar PCP tested Total T only: 339 ng/dL — 'normal for your age.' Vanderbilt urology: 12 weeks. HCA's own TriStar system: 8 weeks. The healthcare executive can't navigate his own industry's referral system.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from a hotel in Atlanta between hospital visits. TN-licensed physician ordered full panel ($95). Total T 339, Free T 4.8 pg/mL. Prescribed Testosterone Cypionate within 48 hours. Shipped to 37027." />
      <ClinicalDeepDive title="The Healthcare Capital Can't Treat Its Own" paragraphs={["Nashville is to healthcare what New York is to finance: the industry capital. HCA Healthcare ($60+ billion revenue, 2,000+ facilities), Community Health Systems, Envision Healthcare, Acadia Healthcare, Surgery Partners, and dozens of healthcare services companies are headquartered here. The men who run American healthcare — CEOs, COOs, CFOs, regional VPs — live in Brentwood, Franklin, and Green Hills and face the same specialist access barriers as their patients nationwide.","The irony is institutional: an HCA VP whose hospitals employ thousands of urologists across 20+ states faces a 12-week wait at Vanderbilt (the academic center) or an 8-week wait at HCA's own TriStar hospitals (the commercial system his company operates). The healthcare executive who optimizes hospital throughput and specialist utilization cannot optimize his own access.","The food culture is Nashville's signature: hot chicken (Prince's — the original, Hattie B's, Bolton's), meat-and-threes (Arnold's Country Kitchen, Monell's), and the Lower Broadway honky-tonk bar scene that defines Nashville's social culture. The healthcare industry's client entertainment circuit adds steakhouse culture (Kayne Prime, Jeff Ruby's). Nashville's food is calorically dense and culturally sacred.","Vanderbilt University Medical Center is a top-20 academic medical center — world-class endocrinology and urology. But non-emergency urology waits of 10-14 weeks reflect a metro that grew from 1.5 million to 2+ million in a decade. The 'it city' migration (tech workers, healthcare relocations, entertainment industry growth) overwhelmed specialist capacity.","The music industry adds a unique dimension. Nashville's recording studios, label offices, and touring infrastructure employ thousands of men in high-stress, irregular-schedule roles. Session musicians, producers, and touring crew work night schedules that disrupt circadian rhythm. The music industry's substance culture (alcohol, late nights) compounds testosterone suppression.","TRT at $79/month serves HCA's corporate leadership, the healthcare industry workforce, Vanderbilt's own staff, and the broader Middle Tennessee community — delivering optimized testosterone to the men who run American healthcare but can't access it for themselves."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Vanderbilt University Medical Center. (2025). <em>Urology Department Non-Emergency Wait Time Report.</em>","Nashville Health Care Council. (2025). <em>Healthcare Industry Workforce Demographics and Men's Health Assessment.</em>","Metro Nashville Public Health. (2025). <em>Davidson County Men's Health and Chronic Disease Report.</em>"]} />
      <InsuranceBreakdown title="HCA, Hot Chicken, and the Healthcare Irony" text="Nashville's healthcare industry provides premium plans — but the specialist bottleneck affects even the executives who run the system." employers={[{name:"HCA Healthcare (Corporate Cigna/BCBS)",detail:"HQ workforce. TriStar network (their own hospitals). Urology: 8-12 weeks."},{name:"CHS / Envision / Acadia (Healthcare Corporate)",detail:"Healthcare services companies with same Vanderbilt/TriStar specialist queue."},{name:"Vanderbilt University / VUMC (Hospital/Academic)",detail:"Academic medical center staff face the same urology bottleneck."},{name:"Bridgestone / Nissan / Dollar General (Corporate)",detail:"Non-healthcare corporate plans with standard referral chains."}]} />
      <CostComparisonTable title="What TRT Costs in Nashville" localCompetitors={[{name:"Green Hills / Brentwood Concierge",cost:"$500-$900/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Gulch / 12South Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"Vanderbilt / TriStar Urology",cost:"$120 Copay + Branded",consult:"8-14 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="The Healthcare Capital's Referral Irony" transitText="Nashville sprawls across Davidson and into Williamson, Rutherford, and Sumner counties. Brentwood to Vanderbilt: 25 min on I-65. Franklin to downtown: 30 min. Mt. Juliet to West End: 35 min." hospitalText="<strong>Vanderbilt</strong> (West End), <strong>TriStar/HCA</strong> (Centennial/Summit), <strong>Saint Thomas/Ascension</strong> — all 8-14 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I run hospitals for a living. Why is this so hard?",a:"Because the referral system you optimize at the enterprise level applies to you as a patient. Telehealth FX bypasses the system entirely. 48 hours, not 12 weeks."},{q:"I travel Mon-Thu. Can I do intake from a hotel?",a:"Yes. Our platform is designed for traveling professionals. Complete from any location on your phone."},{q:"Do you deliver to Brentwood, Franklin, and Mt. Juliet?",a:"Yes. All Davidson, Williamson, Rutherford, Sumner, and Wilson County addresses."},{q:"My T is 339. That's close to the <300 threshold. Should I just wait until it drops more?",a:"No. Waiting for further decline means accepting months of symptoms. 339 with low Free T and symptoms is clinically actionable now."},{q:"Prince's Hot Chicken is non-negotiable.",a:"Agreed. TRT optimizes metabolism — most men report improved body composition without dietary prohibition. Enjoy Prince's."}]} />
      <StateLegalFramework stateName="Tennessee" boardName="Tennessee Board of Medical Examiners" text="Telehealth FX TRT operates in full compliance with the <strong>Tennessee Board of Medical Examiners</strong> and TCA § 63-6-209 (Telehealth). All prescribing physicians are Tennessee-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Nashville" mapQuery="Nashville, TN" coordinates="36.1627° N, 86.7816° W" counties="Davidson County, Williamson County, Rutherford County, Sumner County, Wilson County" neighborhoods={['Downtown / Gulch / SoBro','12South / Green Hills / Belle Meade','East Nashville / Five Points','Germantown / Salemtown','Brentwood / Franklin / Cool Springs','Murfreesboro / Smyrna / La Vergne','Hendersonville / Gallatin','Mt. Juliet / Lebanon','Nolensville / Spring Hill / Thompson Station','Hermitage / Donelson','Bellevue / West Nashville','Goodlettsville / Madison','Clarksville (Fort Campbell commuters)']} />
      <FinalCTA stateName="Tennessee" />
    </div>
  );
}
