"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTDallas() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Texas" cityName="Dallas" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>Dallas</span>" subheadline="Dallas is the corporate relocation capital — AT&T, Texas Instruments, CBRE, Kimberly-Clark, and hundreds of Fortune 500 operations have moved here. The men who manage these corporate machines work 60-hour weeks in Uptown high-rises and Legacy West campuses, eat steakhouse dinners 3 nights a week, and wonder why they feel like they're aging twice as fast as their calendar says." ctaText="Check Texas TRT Eligibility" />
      <PatientArchetype archetype="The AT&T Network Architecture VP" quote="I'm a VP of network architecture at AT&T's Dallas HQ. I manage the 5G infrastructure rollout across the Southwest. I sit in meetings from 7 AM to 6 PM, then work from my laptop until 10. I'm 44. I relocated from New Jersey 3 years ago. Since moving to Dallas, I've gained 40 pounds. The steakhouse culture here is relentless — Pappas Bros, Nick & Sam's, Bob's Steak & Chop House. Client dinners are a job requirement. My libido crashed. My energy is gone by noon. My T was 356 at my Baylor Scott & White annual. 'Totally normal.' I architect the network that connects 100 million Americans. I can't connect with my own doctor." details="<strong>Patient Profile:</strong> Mike, 44, VP Network Architecture, AT&T, Dallas HQ. Lives in Uptown (75201). Relocated from NJ 3 years ago. Manages $2B+ 5G infrastructure budget. Works 70-hour weeks. Former Rutgers football (offensive line).<br/><br/><strong>The Challenge:</strong> 70-hour desk weeks. Dallas steakhouse/client dinner culture 3-4 nights/week. Baylor PCP tested Total T only: 356 ng/dL — 'normal.' UT Southwestern urology: 10 weeks. Baylor urology: 8 weeks. Can't take half-days from the AT&T campus for medical appointments.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Uptown apartment at 10 PM after laptop work. TX-licensed physician ordered full panel ($95). Total T 356, Free T 5.3 pg/mL, elevated estradiol (aromatization from visceral fat). Prescribed Testosterone Cypionate within 48 hours. Shipped to 75201." />
      <ClinicalDeepDive title="Corporate Relocations and the Steakhouse Spiral" paragraphs={["Dallas-Fort Worth has attracted more corporate relocations than any US metro in the past decade. AT&T, CBRE, Charles Schwab, Caterpillar, McKesson, and hundreds more have moved HQs or major operations to North Texas. Each relocation brings thousands of high-earning, high-performing men — VPs, directors, managing directors — who immediately enter Dallas's corporate entertainment ecosystem.","The steakhouse culture is the mechanism. Dallas has more high-end steakhouses per capita than any US city: Pappas Bros, Nick & Sam's, Bob's Steak & Chop House, Al Biernat's, Knife, Town Hearth. Client entertainment in Dallas means a $200 steakhouse dinner with cocktails 3-4 nights per week. This is not optional — it's how Dallas does business. The caloric surplus produces visceral fat. Visceral fat contains aromatase. Aromatase converts testosterone to estradiol. The steakhouse dinners are biochemically converting testosterone to estrogen.","The Uptown/Legacy West/Plano corridor is the epicenter. The men who work at Toyota's new Plano HQ, Charles Schwab's Westlake campus, and the hundreds of tech companies along the Dallas North Tollway live in a bubble of high achievement and declining hormones. The gym memberships (Equinox, Lifetime) go unused as 70-hour weeks consume every hour.","UT Southwestern and Baylor Scott & White represent top-tier urology — but specialist waits of 8-12 weeks reflect the reality of 7.6 million DFW residents competing for the same specialists. A VP who relocated from New York or Chicago expects better access in Texas. He doesn't get it.","The heat factor: Dallas summers (June-September) regularly exceed 100°F. Outdoor activity drops. The already-indoor corporate workforce becomes entirely indoor. Air-conditioned offices → air-conditioned cars → air-conditioned steakhouses → air-conditioned apartments. The vitamin D-testosterone connection deteriorates.","TRT at $79/month serves the corporate relocation workforce, the AT&T/TI/CBRE campus communities, UT Southwestern's own staff, and the broader DFW metro — delivering optimized testosterone to men who relocated to Texas for a better life and got a steakhouse-fueled hormone crash instead."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Cohen, P.G. (1999). <em>The Hypogonadal-Obesity Cycle: Role of Aromatase in Modulating the Testosterone-Estradiol Shunt.</em> Medical Hypotheses.","UT Southwestern. (2025). <em>Urology Department Non-Emergency Wait Time Report.</em>","Dallas County HHS. (2025). <em>Men's Health and Corporate Workforce Chronic Disease Report.</em>"]} />
      <InsuranceBreakdown title="AT&T, Steakhouses, and the Aromatase Cycle" text="Dallas's corporate plans are strong — but PCP testing is incomplete and urology waits run 8-12 weeks." employers={[{name:"AT&T / Texas Instruments / CBRE (Corporate Plans)",detail:"Baylor/UT Southwestern network. PCPs test Total T only. Urology: 8-12 weeks."},{name:"Toyota / Charles Schwab / McKesson (Relocated HQs)",detail:"Corporate plans with standard referral chains. Legacy West/Plano PCPs: 3-week wait."},{name:"UT Southwestern / Baylor / Parkland (Hospital Plans)",detail:"Academic medical center staff face the same bottleneck."},{name:"Dallas ISD / City of Dallas / DART",detail:"Public sector plans with standard Step Therapy."}]} />
      <CostComparisonTable title="What TRT Costs in Dallas" localCompetitors={[{name:"Uptown / Highland Park Concierge",cost:"$500-$1,000/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Plano / Frisco Men's Clinics",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"UT Southwestern / Baylor Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="7.6 Million People and the Tollway Commute" transitText="DFW sprawls 100+ miles. Plano to UT Southwestern (Harry Hines): 45 min on the Tollway. Frisco to Baylor BUMC: 50 min on US-75. Fort Worth to Dallas Medical District: 45 min on I-30. Every specialist appointment is a half-day commitment." hospitalText="<strong>UT Southwestern</strong> (Medical District), <strong>Baylor</strong> (multiple), <strong>Texas Health</strong> (suburban), and <strong>Parkland</strong> — all 8-12 week non-emergency urology waits." />
      <InteractiveFAQ faqs={[{q:"I relocated to Dallas 2 years ago and gained 40 pounds. Is that related to my T?",a:"Likely bidirectional. Weight gain → increased aromatase (converts T to estrogen) → lower T → more weight gain. It's a biochemical cycle. TRT + body composition improvement breaks the cycle."},{q:"Client steakhouse dinners are mandatory. Will TRT work?",a:"Yes. TRT optimizes metabolism and body composition independent of dietary perfection. Most men report improved energy for exercise and better dietary discipline as hormone levels normalize."},{q:"Do you deliver to Uptown, Plano, Frisco, and Fort Worth?",a:"Yes. All DFW metro addresses — Dallas, Collin, Denton, Tarrant, and Rockwall counties."},{q:"I'm a senior executive. Is this discreet?",a:"Completely. Discreet packaging, discreet billing. Nothing visible to your employer, insurance, or anyone else."},{q:"Is my 356 T level really a problem?",a:"At 44, your age-25 baseline was likely 700-900+. At 356, you're functioning at ~40-50% of peak. Our physicians evaluate symptoms + comprehensive labs, not just the number."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX TRT operates in full compliance with the <strong>Texas Medical Board</strong> (TMB) and Texas Occupations Code Title 3, Subtitle B. All prescribing physicians are Texas-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Dallas" mapQuery="Dallas, TX" coordinates="32.7767° N, 96.7970° W" counties="Dallas County, Collin County, Denton County, Tarrant County, Rockwall County" neighborhoods={['Uptown / Oak Lawn / Knox-Henderson','Highland Park / University Park','Plano / Richardson','Frisco / Prosper / McKinney','Allen / Fairview / Lucas','Fort Worth / Southlake / Keller','Arlington / Grand Prairie','Irving / Las Colinas','Denton / Lewisville / Flower Mound','Garland / Rowlett / Rockwall','Addison / Carrollton / Farmers Branch','Mesquite / Sunnyvale','Cedar Hill / DeSoto / Duncanville']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
