"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTDenver() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Colorado" cityName="Denver" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>Denver</span>" subheadline="Denver is the outdoor capital that works indoors. The men who moved here 'for the lifestyle' — skiing, 14ers, mountain biking — work 60-hour weeks at Lockheed Martin, Ball Aerospace, and the DTC tech corridor, eat at Guard and Grace, and haven't seen a trailhead in months. The altitude doesn't fix testosterone. The sunshine doesn't fix cortisol. The outdoor gear collects dust." ctaText="Check Colorado TRT Eligibility" />
      <PatientArchetype archetype="The Lockheed Martin Space Systems Engineer" quote="I'm a systems engineer at Lockheed Martin Space in Littleton — I design satellite communication systems for the Space Force. I sit in a classified SCIF 10 hours a day. I moved from DC for 'the Colorado lifestyle.' I've skied twice in 3 years. I'm 42. My energy is gone. I gained 30 pounds since leaving active duty. My Kaiser PCP tested my T: 381. 'Normal range.' I design the satellites that connect the military worldwide. I can't connect with a specialist in under 10 weeks." details="<strong>Patient Profile:</strong> James, 42, Sr. Systems Engineer, Lockheed Martin Space, Littleton. Lives in Highlands Ranch (80129). Designs satellite comms for USSF. Former Air Force officer (Space Command). MS Aerospace Engineering. Moved from DC 5 years ago for 'the lifestyle.'<br/><br/><strong>The Challenge:</strong> 10-hour SCIF days (no sunlight, no phone, classified environment). Kaiser closed system: PCP tested Total T only: 381 ng/dL — 'normal.' Kaiser urology internal referral: 10 weeks. UCHealth urology: 8 weeks. The lifestyle he moved here for is inaccessible during 60-hour work weeks.<br/><br>The Intervention:</strong> Completed Telehealth FX TRT intake from Highlands Ranch home at 9 PM. CO-licensed physician ordered full panel ($95). Total T 381, Free T 6.0 pg/mL. Prescribed Testosterone Cypionate within 48 hours. Shipped to 80129." />
      <ClinicalDeepDive title="The Outdoor Capital That Works Indoors" paragraphs={["Denver's growth story is defined by the 'lifestyle migration' — hundreds of thousands of professionals who relocated from coastal cities for Colorado's outdoor recreation, 300 sunny days, and quality of life. What they found: the same 60-hour work weeks, the same desk jobs, and the same testosterone decline — now with 5,280 feet of altitude and a ski pass they don't use.","The aerospace-defense corridor along C-470 (Lockheed Martin Space in Littleton, Raytheon in Aurora, Ball Aerospace in Boulder, United Launch Alliance in Centennial) employs tens of thousands of engineers in classified facilities. SCIFs have no windows, no sunlight, and no break from cognitive stress. The security-cleared workforce can't even bring phones into their work areas — much less take half-days for medical appointments.","The food culture is Colorado elevated: Guard and Grace (LoDo steakhouse institution), Mercantile (Union Station), the RiNo brewery/restaurant corridor (Ratio Beerworks, Bierstadt Lagerhaus), and the farm-to-table scene that defines Denver dining. The craft beer dimension is critical — Colorado has 425+ breweries. The 'après-ski' culture extends year-round: post-work beers are a social requirement. Alcohol directly suppresses testosterone.","UCHealth, Denver Health, SCL Health (Intermountain), and Kaiser Permanente provide strong care — but urology waits of 8-12 weeks reflect the reality of a metro that grew from 2.5 million to 3+ million in a decade. Kaiser's closed system adds its own internal delays. The specialist supply was built for a smaller Denver — the lifestyle migrants overwhelmed it.","The altitude factor is medically interesting but not directly testosterone-relevant: altitude increases erythropoietin and red blood cell production (which TRT also does — requiring careful monitoring of hematocrit). The 300 sunny days should help vitamin D — but SCIF workers, office workers, and brewery patrons don't get outdoor UV exposure despite living at 5,280 feet in America's sunniest metro.","TRT at $79/month serves the aerospace-defense corridor, the DTC tech workforce, the healthcare systems' own staff, and the broader Front Range — delivering optimized testosterone to men who moved to Colorado for the mountains but live at a desk."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","UCHealth. (2025). <em>Urology Department Non-Emergency Wait Time Report.</em>","Colorado Department of Public Health. (2025). <em>Front Range Men's Health and Lifestyle Migration Health Impact Study.</em>","Denver Metro Chamber. (2024). <em>Aerospace-Defense Corridor Growth and Healthcare Infrastructure Analysis.</em>"]} />
      <InsuranceBreakdown title="Lockheed Martin, Craft Beer, and 300 Unused Sunny Days" text="Denver's aerospace-tech plans are strong — but Kaiser's closed loop and UCHealth's growing waits limit access." employers={[{name:"Lockheed Martin / Raytheon / Ball Aerospace (Defense BCBS)",detail:"Aerospace corridor. Kaiser or UCHealth network. SCIF schedules prevent half-day appointments."},{name:"DaVita / Arrow Electronics / Western Union (DTC Corporate)",detail:"DTC tech corridor plans with standard specialist referral."},{name:"Kaiser Permanente Colorado (Closed System)",detail:"Kaiser internal urology: 10 weeks. No out-of-network without self-pay."},{name:"UCHealth / Denver Health / SCL (Hospital Staff)",detail:"Healthcare workers face the same urology queue."}]} />
      <CostComparisonTable title="What TRT Costs in Denver" localCompetitors={[{name:"Cherry Creek / Wash Park Concierge",cost:"$500-$900/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"LoDo / RiNo Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"UCHealth / Kaiser Urology",cost:"$120 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="5,280 Feet, 300 Sunny Days, 10-Week Waits" transitText="The Front Range stretches from Fort Collins to Colorado Springs. Highlands Ranch to UCHealth Anschutz: 35 min. Boulder to downtown Denver: 45 min. Castle Rock to LoDo: 40 min on I-25." hospitalText="<strong>UCHealth</strong> (Anschutz/multiple), <strong>Kaiser</strong> (Franklin/multiple), <strong>Denver Health</strong> (downtown), <strong>SCL/Intermountain</strong> — all 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I work in a SCIF. I can't take calls during the day. How does this work?",a:"100% asynchronous. Complete intake at 9 PM from home. No phone calls during work hours. No half-day absences from classified work."},{q:"I'm at altitude. Does that affect TRT?",a:"Altitude increases red blood cell production. TRT also increases red blood cells. Your physician will monitor hematocrit carefully — standard protocol."},{q:"I moved here for skiing. I haven't skied in 2 years. Will TRT help?",a:"Most men report restored energy and motivation within 2-4 weeks. Getting back on the mountain is a common outcome."},{q:"Do you deliver to Highlands Ranch, Boulder, and the Springs?",a:"Yes. All Denver metro, Boulder County, El Paso County (Colorado Springs), and Douglas County addresses."},{q:"Kaiser won't let me see an outside urologist. Options?",a:"Telehealth FX is completely independent of Kaiser. No referral, no internal system, no gatekeeping."}]} />
      <StateLegalFramework stateName="Colorado" boardName="Colorado Medical Board" text="Telehealth FX TRT operates in full compliance with the <strong>Colorado Medical Board</strong> and CRS § 12-240-107 (Telehealth). All prescribing physicians are Colorado-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Denver" mapQuery="Denver, CO" coordinates="39.7392° N, 104.9903° W" counties="Denver County, Arapahoe County, Douglas County, Jefferson County, Adams County, Boulder County" neighborhoods={['LoDo / RiNo / Five Points','Cherry Creek / Wash Park','Highlands / Sloan Lake','Capitol Hill / City Park','Highlands Ranch / Lone Tree','Littleton / Lakewood / Golden','Aurora / Centennial','Boulder / Louisville / Lafayette','Parker / Castle Rock','Westminster / Broomfield / Arvada','Fort Collins / Loveland','Colorado Springs / Monument','Thornton / Northglenn / Brighton']} />
      <FinalCTA stateName="Colorado" />
    </div>
  );
}
