"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTHouston() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="Houston" headline="Testosterone Replacement Therapy in <span style='color: #2ECC71'>Houston</span>" subheadline="Houston is the energy capital of the world and home to the Texas Medical Center — the largest medical complex on earth. The men who manage $50 billion drilling programs at ExxonMobil and design Mars missions at NASA JSC share a paradox: world-class healthcare surrounds them, but specialist access still takes months." dataPoint1="Harris County has 4.7 million residents. The Texas Medical Center sees 10 million patient encounters annually — yet urology waits at MD Anderson, Methodist, and Memorial Hermann still run 8-14 weeks for non-oncologic cases like TRT evaluation." dataPoint2="Telehealth FX delivers TRT from $79/mo — no Beltway 8 traffic, no TMC parking garage, no 3-month urology wait." />
      <PatientArchetype archetype="The ExxonMobil Upstream Drilling Engineer" quote="I'm a senior drilling engineer at ExxonMobil's upstream division in Spring. I design well programs for the Permian Basin and Guyana — $50 million per well. I sit in planning meetings 10 hours a day, then fly to rig sites for 2-week rotations. I'm 41. I used to compete in CrossFit at Katy. Now I can barely finish a workout without wanting to sleep. My libido crashed after my second kid. My T was 395 at my annual physical — my Kelsey-Seybold PCP said 'that's normal, try exercising more.' I exercise. It's not working. Methodist urology: 10 weeks. I design wells that cost more than most buildings. I can't get a hormone panel read correctly." details="<strong>Patient Profile:</strong> Ryan, 41, Senior Drilling Engineer, ExxonMobil Upstream, Spring TX. Lives in Katy (77494). Designs $50M+ well programs. Works 50-60 hour weeks in Spring office + 2-week rig site rotations quarterly. Former collegiate swimmer at Texas A&M.<br/><br/><strong>The Challenge:</strong> Sedentary office planning + rig site stress cycles. Kelsey-Seybold PCP tested Total T only: 395 ng/dL — 'normal.' Methodist urology: 10 weeks. MD Anderson (oncology-focused): not appropriate for TRT. TMC traffic from Katy: 45-90 minutes each way on I-10.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Katy home. TX-licensed physician ordered comprehensive panel ($95). Total T 395, Free T 6.1 pg/mL, elevated estradiol. Prescribed Testosterone Cypionate within 48 hours. Shipped to 77494." />
      <ClinicalDeepDive title="The Energy Capital and the Medical Center Paradox" paragraphs={["Houston's energy sector employs hundreds of thousands of men in high-stress, sedentary-dominant roles: ExxonMobil, Chevron, ConocoPhillips, Schlumberger, Halliburton, Baker Hughes. The upstream planning offices in Spring, The Woodlands, and the Energy Corridor (I-10 West) house engineers, geologists, and project managers who sit in planning sessions for 10+ hours designing multi-billion-dollar drilling campaigns. The stress is enormous. The physical activity is minimal.","NASA Johnson Space Center adds another dimension — the flight controllers, mission planners, and astronaut training staff in Clear Lake work high-cognitive, high-stress, sedentary roles. The men who plan Mars missions experience the same testosterone decline as the men who plan oil wells.","The food culture is Houston at its most expansive: Tex-Mex (Ninfa's on Navigation — the birthplace of fajitas, El Tiempo, Pappasito's), BBQ (Truth BBQ, Killen's, Pinkerton's), Viet-Cajun crawfish (Crawfish & Noodles), and the steakhouse culture (Pappas Bros, Vic & Anthony's) that dominates energy-sector client entertainment.","The Texas Medical Center paradox: Houston houses the largest medical complex on earth — 60+ institutions, including MD Anderson, Methodist, Memorial Hermann, Baylor St. Luke's, and Texas Children's. Yet non-oncologic urology waits (TRT evaluation) still run 8-14 weeks because the TMC prioritizes surgical and oncologic cases. A man with a T of 395 who 'just' feels terrible is low-priority in a system designed for cancer and cardiac emergencies.","Houston's sprawl compounds the access problem. A drilling engineer in Katy (west) driving to a urology appointment at Methodist TMC (south-central) faces 45-90 minutes on I-10/610 each way during business hours. A NASA engineer in Clear Lake faces the same on I-45. The half-day commitment for a single appointment — in a city with the best medical infrastructure in the world — is the Houston paradox.","TRT at $79/month serves Houston's energy workforce, NASA's mission planners, the TMC's own staff, and the broader Harris County metro — delivering optimized testosterone without the Beltway 8 commute."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Houston Methodist. (2025). <em>Urology Department Non-Oncologic Wait Time Analysis.</em>","Harris County Public Health. (2025). <em>Men's Health and Chronic Disease Prevalence in Greater Houston.</em>","Texas Medical Center. (2025). <em>Annual Report: Patient Volume and Specialist Capacity.</em>"]} />
      <InsuranceBreakdown title="ExxonMobil, NASA, and the TMC Paradox" text="Houston employers provide strong plans — but the TMC prioritizes surgical/oncologic cases over TRT evaluation." employers={[{name:"ExxonMobil / Chevron / ConocoPhillips (Energy BCBS/Aetna)",detail:"Corporate plans with Kelsey-Seybold network. PCP tests Total T only. Urology referral: 8-12 weeks."},{name:"NASA JSC / Lockheed Martin (FEHB/Corporate)",detail:"Federal and contractor plans with standard referral chains. Clear Lake PCPs: 3-week wait before specialist referral begins."},{name:"Methodist / Memorial Hermann / MD Anderson (Hospital Plans)",detail:"TMC employees face the same specialist bottleneck. Non-oncologic urology: low priority."},{name:"Houston ISD / City of Houston / Harris County",detail:"Public sector plans with standard PBM Step Therapy."}]} />
      <CostComparisonTable title="What TRT Costs in Houston" localCompetitors={[{name:"River Oaks / Memorial Concierge Men's Health",cost:"$500-$1,000/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Galleria / Westheimer Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"Methodist / Memorial Hermann Urology",cost:"$150 Copay + Branded",consult:"8-14 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="The TMC Is 45 Minutes From Everywhere" transitText="Houston sprawls across 670 sq mi. Katy to TMC: 45-90 min on I-10. Clear Lake to TMC: 45-75 min on I-45. The Woodlands to TMC: 45-90 min on I-45. A single urology appointment is a half-day commitment." hospitalText="<strong>Methodist</strong>, <strong>Memorial Hermann</strong>, <strong>MD Anderson</strong>, and <strong>Baylor St. Luke's</strong> — all TMC, all 8-14 week non-oncologic urology waits." />
      <InteractiveFAQ faqs={[{q:"I rotate between the office and rig sites. Can I manage TRT on rotation?",a:"Yes. Discuss rig rotation schedules with your physician. Testosterone Cypionate injections are typically weekly or biweekly — manageable around 2-week rotations."},{q:"Houston has the TMC. Why can't I just go there?",a:"You can — in 8-14 weeks. The TMC prioritizes surgical and oncologic cases. A man with a T of 395 who 'just' feels terrible is low-priority. Telehealth FX: 48 hours."},{q:"Do you deliver to Katy, The Woodlands, Sugar Land, and Clear Lake?",a:"Yes. All Harris, Fort Bend, Montgomery, Galveston, and Brazoria County addresses."},{q:"My Kelsey-Seybold PCP tested my T and said it's normal. Should I get a second opinion?",a:"If your PCP tested only Total T, you got an incomplete picture. Our comprehensive panel ($95) includes Free T, SHBG, estradiol, PSA, CBC, FSH, and LH."},{q:"I make good money. Why is this only $79?",a:"Telehealth eliminates office overhead, front-desk staff, and commercial real estate. You're paying for medicine, not a River Oaks waiting room."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX TRT operates in full compliance with the <strong>Texas Medical Board</strong> (TMB) and Texas Occupations Code Title 3, Subtitle B. All prescribing physicians are Texas-licensed. Testosterone Cypionate is a Schedule III controlled substance prescribed under DEA and Texas DPS regulations." />
      <DeliveryGridMap cityName="Houston" mapQuery="Houston, TX" coordinates="29.7604° N, 95.3698° W" counties="Harris County, Fort Bend County, Montgomery County, Galveston County, Brazoria County" neighborhoods={['Downtown / Montrose / Heights','Katy / Energy Corridor','The Woodlands / Spring','Sugar Land / Missouri City','Clear Lake / League City / NASA','Pearland / Friendswood','Cypress / Tomball','Kingwood / Humble','Bellaire / West University','Memorial / Bunker Hill','Pasadena / Deer Park','Conroe / Willis','Galveston / Texas City']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
