"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTColumbus() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Ohio" cityName="Columbus" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>Columbus</span>" subheadline="Columbus is the test market of America — the city where brands launch products because its demographics mirror the nation. Nationwide Insurance, JPMorgan Chase, Battelle Memorial Institute, and Honda of America anchor an economy where men work corporate jobs, eat at Schmidt's Sausage Haus, and face the same testosterone decline as the rest of the country — but with Ohio State's medical center right there and still a 10-week urology wait." ctaText="Check Ohio TRT Eligibility" />
      <PatientArchetype archetype="The Nationwide Insurance Actuarial VP" quote="I'm a VP of actuarial services at Nationwide — I model risk for a $250 billion insurance company. I calculate probabilities for a living. The probability that my testosterone level of 373 ng/dL is 'optimal' for a 41-year-old former Ohio State linebacker? Approximately zero. But my OhioHealth PCP cited the reference range and said 'normal.' I model mortality tables. I know what metabolic decline looks like on a curve. OSU Wexner urology: 10 weeks." details="<strong>Patient Profile:</strong> Dan, 41, VP Actuarial, Nationwide Insurance, Columbus HQ. Lives in Upper Arlington (43221). Models $250B in insurance risk. Former OSU football (linebacker, walk-on). 16 years at Nationwide.<br/><br/><strong>The Challenge:</strong> 10-hour desk days modeling risk. OhioHealth PCP tested Total T only: 373 ng/dL — 'normal.' OSU Wexner urology: 10 weeks. Mt. Carmel: 8 weeks. The actuary who models probability knows 373 is not optimal — but his doctor disagrees.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Upper Arlington home at 9 PM. OH-licensed physician ordered full panel ($95). Total T 373, Free T 5.9 pg/mL. Prescribed Testosterone Cypionate within 48 hours. Shipped to 43221." />
      <ClinicalDeepDive title="America's Test Market and the Actuarial Truth" paragraphs={["Columbus is the most statistically average major city in America — which is why every consumer brand from Wendy's to White Castle to Bath & Body Works is headquartered here or uses it as a test market. The demographic mirror means Columbus's male workforce reflects the national testosterone crisis perfectly: 25-30% of men aged 40-54 with suboptimal testosterone, most undiagnosed.","The corporate center is concentrated: Nationwide Insurance (One Nationwide Plaza), JPMorgan Chase (largest employer in Columbus with 20,000+ employees), Battelle Memorial Institute (world's largest private R&D lab), L Brands/Bath & Body Works, and Cardinal Health. These desk-intensive corporate environments produce the same sedentary-stress testosterone suppression as every other major metro.","The food culture is Midwest comfort: Schmidt's Sausage Haus (German Village institution — bratwurst, sauerkraut, cream puffs the size of softballs), Thurman's Burgers (a burger so large it was featured on Man v. Food), North Market food hall, and the Short North restaurant scene. Ohio State's campus adds college-town food culture. The combination of Midwest portions and corporate sedentarism is metabolically predictable.","Ohio State University Wexner Medical Center is a top-30 academic medical center — but urology waits of 8-12 weeks reflect Columbus's rapid growth (2 million+ metro, up from 1.8M in 2015). OhioHealth and Mt. Carmel add community hospital capacity. The specialist supply hasn't kept pace with population growth and corporate relocations.","The Honda corridor (Marysville/East Liberty assembly plants, 30 miles NW) adds a manufacturing workforce — men on rotating 10-hour shifts building Accords and CR-Vs under the same circadian-disruption testosterone suppression as any factory shift worker. The blue-collar automotive workforce faces the same hormonal decline as the white-collar insurance actuaries.","TRT at $79/month serves Nationwide's risk modelers, JPMorgan's finance workforce, Battelle's researchers, Honda's assembly workers, and the broader Franklin County metro — delivering optimized testosterone to America's statistically average city."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","OSU Wexner Medical Center. (2025). <em>Urology Department Non-Emergency Wait Time Report.</em>","Franklin County Public Health. (2025). <em>Men's Health and Corporate Workforce Chronic Disease Assessment.</em>","Columbus Chamber of Commerce. (2024). <em>Test Market Demographics and Workforce Health Profile.</em>"]} />
      <InsuranceBreakdown title="Nationwide, JPMorgan, and Schmidt's Cream Puffs" text="Columbus's corporate plans are solid — but the PCP-to-urology chain takes 8-12 weeks." employers={[{name:"Nationwide Insurance (Corporate BCBS)",detail:"HQ workforce. OhioHealth network. PCP tests Total T only. Urology: 10 weeks."},{name:"JPMorgan Chase Columbus (Corporate Plan)",detail:"20,000+ employees. Same OSU/OhioHealth bottleneck."},{name:"Battelle / Cardinal Health / L Brands",detail:"Corporate plans with standard specialist referral chains."},{name:"OSU Wexner / OhioHealth / Mt. Carmel (Hospital Staff)",detail:"Healthcare workers face the same urology wait."}]} />
      <CostComparisonTable title="What TRT Costs in Columbus" localCompetitors={[{name:"Upper Arlington / Bexley Concierge",cost:"$400-$800/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Short North / Polaris Men's Clinics",cost:"$250-$450/mo",consult:"Monthly",access:"Variable"},{name:"OSU Wexner / OhioHealth Urology",cost:"$120 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="2 Million People, Growing Faster Than Specialists" transitText="Columbus sprawls across Franklin County and into Delaware, Licking, and Fairfield counties. Dublin to OSU Wexner (Olentangy): 25 min. Westerville to downtown: 30 min. Grove City to Polaris: 45 min." hospitalText="<strong>OSU Wexner Medical Center</strong> (University District), <strong>OhioHealth</strong> (Riverside/Grant), <strong>Mt. Carmel</strong> (multiple) — all 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I'm an actuary. I know 373 ng/dL isn't optimal. Why doesn't my doctor?",a:"Most PCPs use lab reference ranges (264-916 ng/dL) derived from populations including elderly men. Our physicians evaluate your level relative to age-matched optimal ranges and your symptoms."},{q:"Do you deliver to Upper Arlington, Dublin, Westerville, and Marysville?",a:"Yes. All Franklin, Delaware, Licking, Fairfield, and Union County addresses."},{q:"I work at Honda Marysville on rotating shifts. Is shift work affecting my T?",a:"Likely yes. Rotating shifts disrupt circadian rhythm → melatonin → LH → testosterone production. Comprehensive labs will establish your baseline."},{q:"Columbus is 'average.' Is the testosterone problem average too?",a:"Exactly. 25-30% of men 40-54 have suboptimal T. Columbus mirrors national data — making it a representative case of an under-diagnosed crisis."},{q:"Schmidt's cream puffs are the size of my head. Problem?",a:"TRT optimizes metabolism regardless. Most men report improved body composition even without dietary perfection. Enjoy the cream puffs in moderation."}]} />
      <StateLegalFramework stateName="Ohio" boardName="State Medical Board of Ohio" text="Telehealth FX TRT operates in full compliance with the <strong>State Medical Board of Ohio</strong> and ORC § 4731.296 (Telehealth). All prescribing physicians are Ohio-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Columbus" mapQuery="Columbus, OH" coordinates="39.9612° N, 82.9988° W" counties="Franklin County, Delaware County, Licking County, Fairfield County" neighborhoods={['Short North / Victorian Village','Upper Arlington / Grandview','German Village / Brewery District','Dublin / Powell','Westerville / Gahanna','Grove City / Galloway','Hilliard / Rome-Hilliard','New Albany / Johnstown','Pickerington / Reynoldsburg','Worthington / Clintonville','Polaris / Lewis Center','Lancaster / Canal Winchester','Marysville / Plain City (Honda)']} />
      <FinalCTA stateName="Ohio" />
    </div>
  );
}
