"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTChicago() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Illinois" cityName="Chicago" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>Chicago</span>" subheadline="Chicago is the trading floor, the manufacturing floor, and the operating room. The men who manage CME futures at 5 AM, engineer Boeing's next aircraft, and staff Northwestern Memorial's ORs are running on cortisol and declining testosterone. The city that works hard has a workforce that's hormonally depleted." ctaText="Check Illinois TRT Eligibility" />
      <PatientArchetype archetype="The CME Group Futures Trading Floor Manager" quote="I manage the agricultural futures desk at CME Group. Markets open at 5 AM Central — I'm on the floor by 4:30. The adrenaline carries me until 2 PM, then I crash. I used to power through. At 46, I can't. My focus is gone by early afternoon. I've gained 35 pounds since making MD. My testosterone was 362 — my PCP at Northwestern said 'totally normal for your age.' Normal for what? I manage $500 million in daily volume. My wife says I'm a different person. I don't disagree." details="<strong>Patient Profile:</strong> Mark, 46, Managing Director, CME Group. Lives in Lincoln Park (60614). Manages agricultural futures trading operations. 4:30 AM start time. 22 years in commodity trading. Former Big Ten wrestler at Northwestern.<br/><br/><strong>The Challenge:</strong> 4:30 AM cortisol spike → afternoon crash cycle for 22 years. Northwestern Medicine PCP tested Total T only: 362 ng/dL — 'normal.' No Free T, SHBG, or estradiol. Northwestern urology referral: 10 weeks. Rush urology: 8 weeks. Trading floor can't absorb a half-day absence for medical appointments.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Lincoln Park home at 9 PM after family dinner. IL-licensed physician ordered comprehensive panel. Total T 362, Free T 5.9 pg/mL, elevated SHBG. Prescribed Testosterone Cypionate within 48 hours. Shipped to 60614." />
      <ClinicalDeepDive title="The Trading Floor, the Factory Floor, and the OR" paragraphs={["Chicago's economic engine runs on three high-testosterone-demand industries: finance (CME Group, Citadel, Jump Trading, BMO Harris — the world's largest derivatives exchange and a cluster of quantitative trading firms), manufacturing/aerospace (Boeing's global HQ until 2022, Caterpillar, Abbott Laboratories, Baxter), and healthcare (Northwestern Memorial, Rush University Medical Center, UChicago Medicine, Advocate Aurora).","The cortisol pattern in Chicago is distinctive. Trading floor hours start at 4-5 AM Central (futures markets). Manufacturing shifts rotate across 24 hours. Hospital shifts run 12-16 hours. All three produce chronic cortisol elevation that directly suppresses the hypothalamic-pituitary-gonadal axis. The men who drive Chicago's economy are biochemically programmed to produce less testosterone the harder they work.","The food culture is calorically aggressive: deep-dish pizza (Lou Malnati's, Giordano's, Pequod's), Italian beef (Portillo's, Al's #1), Chicago-style hot dogs (Gene & Jude's, Superdawg), and the steakhouse culture (Gibson's, RPM Steak) that dominates client entertainment. Winter comfort eating from November through March adds another dimension — 5 months of cold-weather caloric surplus that compounds metabolic dysfunction.","Northwestern Medicine, Rush University Medical Center, and UChicago Medicine represent world-class endocrinology and urology. But specialist waits of 8-12 weeks reflect the reality of 9.5 million metro residents competing for the same specialists. The insurance referral chain (PCP → specialist → labs → follow-up → treatment) adds 4-6 months to the timeline.","The 'Midwest stoicism' factor matters. Chicago men are culturally less likely to discuss symptoms of low testosterone — fatigue, low libido, brain fog, mood changes — than their coastal counterparts. The trading floor doesn't reward vulnerability. The factory floor doesn't accommodate weakness. Many Chicago men attribute low-T symptoms to 'just getting older' or 'just working hard' and never seek evaluation.","TRT at $79/month serves Chicago's trading community, manufacturing workforce, healthcare professionals, and the broader Chicagoland metro — delivering optimized testosterone to men who power the nation's third-largest economy."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Cumming, D.C., et al. (1983). <em>Acute Suppression of Circulating Testosterone by Cortisol in Men.</em> JCEM.","Northwestern Medicine. (2025). <em>Urology Department Specialist Wait Time Analysis.</em>","Cook County Department of Public Health. (2025). <em>Men's Health and Chronic Disease in Chicagoland.</em>"]} />
      <InsuranceBreakdown title="CME, Boeing, and the Midwest Stoicism Problem" text="Chicago's employer plans are comprehensive — but every one funnels through the same 8-12 week urology referral chain." employers={[{name:"CME Group / Citadel / Jump Trading (Finance Plans)",detail:"Platinum plans with 8-10 week urology waits. Trading floor schedules prohibit half-day medical appointments."},{name:"Boeing / Caterpillar / Abbott (Corporate BCBS)",detail:"Manufacturing/aerospace plans with standard Step Therapy. PCP referral required before urology."},{name:"Northwestern / Rush / UChicago (Hospital Employee Plans)",detail:"Healthcare workers face the same specialist bottleneck they operate in."},{name:"CPS / City of Chicago / Cook County (Public Sector)",detail:"Public sector plans with standard PBM Step Therapy requirements."}]} />
      <CostComparisonTable title="What TRT Costs in Chicago" localCompetitors={[{name:"Gold Coast / Lincoln Park Concierge",cost:"$500-$1,000/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"River North Men's Clinics",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Northwestern / Rush Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription Model"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="9.5 Million People, 8-12 Week Waits" transitText="Chicago's transit system (CTA, Metra) and highway network (90/94, 290, 55) connect the metro — but a urology appointment at Northwestern from the suburbs is a half-day commitment." hospitalText="<strong>Northwestern Memorial</strong> (Streeterville), <strong>Rush</strong> (West Side), <strong>UChicago Medicine</strong> (Hyde Park), and <strong>Advocate Aurora</strong> (suburbs) — all 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"Markets open at 5 AM. When can I do this?",a:"Complete at 9 PM after markets close. 100% asynchronous — no half-day absences from the trading floor."},{q:"My T is 362 and my PCP says it's fine. What do your doctors do differently?",a:"We test the full panel: Total T, Free T, SHBG, estradiol, PSA, CBC, FSH, LH ($95). Your PCP likely tested Total T only. 362 with low Free T and high SHBG is clinical hypogonadism."},{q:"Do you deliver to Lincoln Park, the suburbs, and NW Indiana?",a:"Yes. All Cook County, DuPage, Lake, Will, and Kane County addresses. Plus NW Indiana (Hammond, Gary, Valparaiso) for IN-licensed patients."},{q:"Will TRT affect my trading performance?",a:"Most men report improved focus, energy, and cognitive clarity within 2-4 weeks. Testosterone receptors are densely concentrated in the brain."},{q:"Is this the same as those Instagram TRT ads?",a:"No. $79/mo. Licensed IL physicians. Comprehensive lab review. No aggressive upselling or $500/month subscriptions."}]} />
      <StateLegalFramework stateName="Illinois" boardName="Illinois Department of Financial and Professional Regulation" text="Telehealth FX TRT operates in full compliance with the <strong>Illinois DFPR</strong> and 225 ILCS 60 (Medical Practice Act). All prescribing physicians are Illinois-licensed with active, unrestricted licenses. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Chicago" mapQuery="Chicago, IL" coordinates="41.8781° N, 87.6298° W" counties="Cook County, DuPage County, Lake County, Will County, Kane County" neighborhoods={['Loop / Streeterville / River North','Lincoln Park / Lakeview','Wicker Park / Bucktown','Hyde Park / South Loop','Naperville / Aurora','Schaumburg / Arlington Heights','Evanston / Skokie','Oak Park / Elmhurst','Orland Park / Tinley Park','Downers Grove / Hinsdale','Waukegan / Lake Forest','Joliet / Plainfield','Oak Brook / Lombard']} />
      <FinalCTA stateName="Illinois" />
    </div>
  );
}
