"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTMiami() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Florida" cityName="Miami" headline="Testosterone Replacement Therapy in <span style='color: #2ECC71'>Miami</span>" subheadline="Miami is the gateway to Latin America and the new Wall Street South — hedge funds, crypto firms, and tech companies have relocated from New York, creating a finance-tech ecosystem where men work global hours, eat at Carbone at midnight, and maintain a social scene that demands peak physical appearance while their testosterone quietly declines behind the bottle service." dataPoint1="Miami-Dade's financial migration has brought 60,000+ finance and tech workers since 2020. These men work New York hours in Miami's heat and humidity, adding metabolic stress to cortisol stress. Jackson Memorial and University of Miami urology waits run 10-14 weeks." dataPoint2="Telehealth FX delivers TRT from $79/mo — no Brickell traffic, no I-95 crawl, no 3-month UM urology wait." />
      <PatientArchetype archetype="The Citadel Miami Quantitative Analyst" quote="I moved from Citadel's Chicago office to Citadel Miami 2 years ago. I'm a senior quant — I build the trading algorithms that execute $30 billion in daily volume. I'm 38. In Chicago, I at least walked to work. In Miami, I drive everywhere. I sit in a Brickell office 14 hours a day. The Miami social scene demands you look like a fitness model — I look like I ate one. My T was 392 at my Baptist Health annual. My PCP said 'you're 38, it's fine.' I model financial risk for a living. I can see my own risk curve, and it's declining." details="<strong>Patient Profile:</strong> David, 38, Senior Quantitative Analyst, Citadel Miami (Brickell). Lives in Edgewater (33137). Builds systematic trading algorithms. PhD Applied Mathematics, MIT. Relocated from Chicago 2 years ago. Former MIT club rowing.<br/><br/><strong>The Challenge:</strong> 14-hour desk days in Brickell. Miami social pressure (appearance-driven culture) + sedentary work = cognitive dissonance. Baptist Health PCP tested Total T only: 392 ng/dL — 'fine for 38.' UM/Jackson urology: 12 weeks. Miami's heat and humidity discourage outdoor activity May-October.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Edgewater apartment at midnight after a late trading session. FL-licensed physician ordered full panel ($95). Total T 392, Free T 6.5 pg/mL. Prescribed Testosterone Cypionate within 48 hours. Shipped to 33137." />
      <ClinicalDeepDive title="Wall Street South and the Appearance Economy" paragraphs={["Miami's financial migration is the defining economic event of 2020s South Florida. Citadel relocated its global HQ from Chicago. Point72, D1 Capital, Millennium, and dozens of hedge funds opened Miami offices. The crypto corridor (FTX's ghost, but Circle, Blockchain.com, and dozens of surviving firms) added tech-finance crossover. These men work New York hours (markets open at 9:30 EST — early by Miami standards but still 14-hour desk days) in a city that demands physical appearance at nightlife-level standards.","The 'appearance economy' is Miami-specific. Unlike New York, where a banking VP can be overweight and nobody notices, Miami's social culture is body-conscious at the extreme. South Beach, Wynwood rooftop bars, Brickell nightlife, and the boat culture all select for lean, muscular aesthetics. The gap between the appearance standard and the reality of a 38-year-old quant who sits 14 hours a day creates psychological stress that compounds the cortisol-testosterone suppression.","The food culture spans the spectrum: Cuban coffee and croquetas at Versailles (Calle Ocho institution), arepas at Salty Arepa, stone crab season at Joe's (South Beach), and the relocated New York restaurants (Carbone, Major Food Group empire) that dominate Brickell/Design District client entertainment. Late-night eating (Miami dines at 10 PM-midnight) disrupts circadian rhythm and glucose metabolism.","The heat confinement parallels Phoenix: from May through October, Miami's 90°F+ temperatures with 80%+ humidity make outdoor exercise punishing. The men who moved from New York 'for the weather' discover that Miami's weather is only pleasant November through April. Six months of heat confinement means gym-only exercise — and many men skip even that during 14-hour work days.","University of Miami Health/Jackson Memorial and Baptist Health represent strong healthcare systems — but urology waits of 10-14 weeks reflect the reality of 6 million+ metro residents plus the influx of 60,000+ finance/tech workers. The specialist supply was built for pre-migration Miami — not for Wall Street South.","TRT at $79/month serves the Brickell finance corridor, the Wynwood tech scene, the Latin American business community, and the broader Miami-Dade metro — delivering optimized testosterone to men who live in the appearance economy but are biochemically declining behind the designer clothes."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","UM Health/Jackson Memorial. (2025). <em>Urology Department Non-Emergency Wait Time Report.</em>","Miami-Dade County Health Department. (2025). <em>Men's Health, Financial Migration, and Chronic Disease Report.</em>","Greater Miami Chamber. (2024). <em>Financial Migration Workforce Health and Infrastructure Impact Study.</em>"]} />
      <InsuranceBreakdown title="Citadel, Carbone, and the Appearance Gap" text="Miami's finance plans are platinum — but the specialist supply hasn't scaled with the Wall Street South migration." employers={[{name:"Citadel / Point72 / Millennium (Hedge Fund Plans)",detail:"Premium plans with Baptist/UM network. PCP tests Total T only. Urology: 10-14 weeks."},{name:"Tech / Crypto Miami (Corporate Plans)",detail:"Startup plans with same limited specialist network."},{name:"Royal Caribbean / Carnival (Corporate Plans)",detail:"Cruise industry HQ workforce. Standard referral chain."},{name:"UM Health / Baptist Health / Jackson (Hospital Staff)",detail:"Healthcare workers face the same urology queue."}]} />
      <CostComparisonTable title="What TRT Costs in Miami" localCompetitors={[{name:"South Beach / Coral Gables Concierge",cost:"$600-$1,200/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Brickell / Design District Men's Clinics",cost:"$300-$600/mo",consult:"Monthly",access:"Variable"},{name:"UM Health / Baptist Urology",cost:"$150 Copay + Branded",consult:"10-14 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="6 Million People, I-95, and 90°F Humidity" transitText="South Florida sprawls from Palm Beach to Homestead. Brickell to UM/Jackson: 15 min. Doral to South Beach: 30 min. Fort Lauderdale to Coral Gables: 45 min on I-95. Every appointment outside your immediate area is a sweat-soaked commute." hospitalText="<strong>UM Health/Jackson Memorial</strong> (Medical District), <strong>Baptist Health</strong> (multiple), <strong>Cleveland Clinic Florida</strong> (Weston) — all 10-14 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I relocated from New York. Why are Miami specialist waits just as bad?",a:"60,000+ finance/tech workers moved to Miami since 2020. The specialist supply was built for pre-migration Miami. Demand overwhelmed capacity."},{q:"My social scene demands I look good. Will TRT help?",a:"Yes. Testosterone directly affects body composition — increased lean mass, decreased visceral fat. Most men see visible results in 8-12 weeks."},{q:"I work until midnight. When can I do this?",a:"Complete at midnight from your apartment. We designed this for Miami hours."},{q:"Do you deliver to Brickell, South Beach, Coral Gables, and Fort Lauderdale?",a:"Yes. All Miami-Dade, Broward, and Palm Beach County addresses."},{q:"My T is 392 at 38. Am I being dramatic?",a:"No. At 38, your age-25 baseline was likely 700-900+. 392 is ~45-55% of peak. If you're symptomatic, it's clinically actionable."}]} />
      <StateLegalFramework stateName="Florida" boardName="Florida Board of Medicine" text="Telehealth FX TRT operates in full compliance with the <strong>Florida Board of Medicine</strong> and F.S. § 456.47 (Telehealth). All prescribing physicians are Florida-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Miami" mapQuery="Miami, FL" coordinates="25.7617° N, 80.1918° W" counties="Miami-Dade County, Broward County, Palm Beach County" neighborhoods={['Brickell / Downtown / Edgewater','South Beach / Miami Beach','Coral Gables / Coconut Grove','Doral / Sweetwater / Kendall','Wynwood / Design District / Midtown','Aventura / Sunny Isles / Bal Harbour','Fort Lauderdale / Las Olas','Weston / Pembroke Pines / Miramar','Boca Raton / Delray Beach','West Palm Beach / Jupiter','Homestead / Cutler Bay','Key Biscayne / Fisher Island','Hialeah / Miami Lakes / Opa-locka']} />
      <FinalCTA stateName="Florida" />
    </div>
  );
}
