"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTAustin() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Texas" cityName="Austin" headline="Testosterone Replacement Therapy in <span style='color: #2ECC71'>Austin</span>" subheadline="Austin is the tech capital of Texas — Tesla's Gigafactory, Apple's $1B campus, Meta, Google, Oracle, Dell, and Samsung's $17B fab. The founders, engineers, and executives who moved here for 'the lifestyle' are working 70-hour weeks under fluorescent lights, eating Torchy's at midnight, and wondering why they feel worse at 38 than they did at 28." dataPoint1="Travis County's population grew 25% in a decade (2015-2025). Austin added 300,000+ residents — mostly high-earning tech workers aged 28-45. The healthcare infrastructure didn't scale proportionally. UT Dell Medical opened in 2017 but can't absorb the demand alone." dataPoint2="Telehealth FX delivers TRT from $79/mo — no I-35 traffic, no 10-week UT Dell urology wait, no half-day commitment." />
      <PatientArchetype archetype="The Tesla Gigafactory Production Director" quote="I'm a production director at Tesla's Gigafactory Texas — the largest manufacturing facility in the world by footprint. I manage the Model Y production line. I'm on the factory floor or in planning meetings 14 hours a day. I moved from Fremont 2 years ago. I'm 37. I feel 50. The Austin food scene is incredible and I'm eating all of it — Franklin BBQ, Uchi, Torchy's at midnight after a production run. My T came back at 389 — my Dell Seton PCP said 'you're fine, you're 37.' I produce 5,000 cars a week. I can't produce the energy to work out anymore." details="<strong>Patient Profile:</strong> Alex, 37, Production Director, Tesla Gigafactory Texas. Lives in East Austin near Mueller (78723). Relocated from Tesla Fremont. Manages Model Y line producing 5,000+ vehicles/week. Works 60-70 hours/week. MS Mechanical Engineering, Stanford.<br/><br/><strong>The Challenge:</strong> 14-hour factory/planning days. Austin food scene overshoot (Franklin BBQ, Uchi, Torchy's late-night). Dell Seton PCP tested Total T only: 389 ng/dL — 'fine for 37.' UT Dell Medical urology: 10 weeks. Baylor Scott & White Austin: 8 weeks. Tesla production can't absorb half-day medical absences.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Mueller apartment at 11 PM after production review. TX-licensed physician ordered full panel ($95). Total T 389, Free T 6.4 pg/mL, estradiol elevated. Prescribed Testosterone Cypionate within 48 hours. Shipped to 78723." />
      <ClinicalDeepDive title="The Tech Capital's Hormone Crisis" paragraphs={["Austin's tech boom is the defining demographic event of 21st-century Texas. Tesla, Apple, Meta, Google, Oracle, Dell, Samsung, AMD, NXP, and hundreds of startups have relocated or expanded operations. The population influx — predominantly men aged 28-45 in high-stress, sedentary tech roles — has created a testosterone optimization demand that Austin's healthcare system was never sized for.","The startup culture compounds the problem. Austin's 'hustle culture' glorifies 80-hour weeks, midnight coding sessions, and the 'I'll sleep when I'm dead' ethos. Cortisol production during sustained startup stress directly suppresses the HPG axis. The founders and early employees building the next unicorn are biochemically suppressing their own testosterone production.","The food culture is Austin's paradox: simultaneously health-conscious (Juiceland, Picnik, True Food Kitchen) and calorically devastating (Franklin BBQ — 14-hour smoked brisket worth driving from Houston for, Uchi — world-class Japanese, Torchy's Tacos at midnight, SXSW week food comas). The 'Keep Austin Weird' ethos extends to nutrition — there are no rules, and the food scene is a competitive sport.","UT Dell Medical Center opened in 2017 — Austin's first academic medical center. Before Dell Medical, Austin was the largest US city without an academic hospital. Dell Medical has dramatically improved care — but one academic center cannot serve a metro that added 300,000+ residents in a decade. Urology waits of 8-12 weeks reflect capacity that hasn't caught up with population.","Samsung's $17B Taylor TX fab and Tesla's Gigafactory add manufacturing shift-work populations — men who work rotating 12-hour shifts under artificial light, experiencing the same circadian-testosterone disruption as Phoenix's TSMC engineers. The blue-collar tech manufacturing workforce faces the same hormonal decline as the white-collar software engineers, through different but equally destructive mechanisms.","TRT at $79/month serves Tesla's production workforce, the Apple/Meta/Google campuses, Dell's Round Rock community, Samsung's Taylor fab, and the broader Travis County metro — delivering optimized testosterone to the fastest-growing tech workforce in America."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Leproult, R. & Van Cauter, E. (2011). <em>Effect of 1 Week of Sleep Restriction on Testosterone Levels in Young Healthy Men.</em> JAMA.","UT Dell Medical Center. (2025). <em>Urology Department Specialist Wait Time and Population Growth Analysis.</em>","Travis County Health Department. (2025). <em>Tech Workforce Health and Population Growth Impact Report.</em>"]} />
      <InsuranceBreakdown title="Tesla, Apple, and Franklin BBQ" text="Austin's tech employers provide platinum plans — but the local specialist supply can't absorb 300,000 new residents." employers={[{name:"Tesla Gigafactory (Corporate BCBS)",detail:"Manufacturing + engineering staff. Dell Seton/BSW network. Urology: 8-12 weeks."},{name:"Apple / Meta / Google Austin (Corporate Plans)",detail:"Premium tech plans with same limited Austin specialist network."},{name:"Dell Technologies / Oracle (Corporate Plans)",detail:"Round Rock/Austin campus. Same urology bottleneck."},{name:"Samsung Taylor / NXP (Semiconductor Plans)",detail:"Fab shift workers with standard PBM referral requirements."}]} />
      <CostComparisonTable title="What TRT Costs in Austin" localCompetitors={[{name:"West Lake Hills / Tarrytown Concierge",cost:"$500-$900/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"South Lamar / South Congress Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"UT Dell Medical / BSW Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="I-35 Traffic and a 10-Year Healthcare Deficit" transitText="Austin's I-35 corridor is among the most congested in Texas. Round Rock to UT Dell Medical (Red River): 35-60 min. Cedar Park to South Austin BSW: 45-75 min. Tesla Giga (SE Travis County) to anywhere medical: 30-45 min." hospitalText="<strong>UT Dell Medical</strong> (Red River), <strong>Baylor Scott & White</strong> (multiple), <strong>St. David's</strong> (multiple), and <strong>Ascension Seton</strong> — all 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I'm 37. Am I too young for TRT?",a:"No. Testosterone decline begins around 30 at 1-2% per year. At 37, you may have lost 15-20% of your peak levels. If you're symptomatic, age is not a disqualifier."},{q:"I moved from the Bay Area. Why is Austin's healthcare so backed up?",a:"Austin added 300,000+ residents in a decade. UT Dell Medical (its first academic hospital) opened in 2017. Specialist capacity hasn't caught up with population growth."},{q:"Do you deliver to Mueller, Round Rock, Cedar Park, and Dripping Springs?",a:"Yes. All Travis, Williamson, Hays, and Bastrop County addresses."},{q:"I work at the Gigafactory. Will my employer know?",a:"No. Telehealth FX is independent of Tesla and your employer insurance. HIPAA-compliant."},{q:"I eat Franklin BBQ weekly. Is that a problem?",a:"TRT optimizes metabolism regardless of dietary perfection. Most men report improved body composition even without eliminating their favorite foods."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX TRT operates in full compliance with the <strong>Texas Medical Board</strong> (TMB) and Texas Occupations Code Title 3, Subtitle B. All prescribing physicians are Texas-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Austin" mapQuery="Austin, TX" coordinates="30.2672° N, 97.7431° W" counties="Travis County, Williamson County, Hays County, Bastrop County" neighborhoods={['Downtown / Rainey / East Austin','Mueller / Windsor Park','South Congress / South Lamar','West Lake Hills / Tarrytown','Round Rock / Pflugerville','Cedar Park / Leander','Georgetown / Hutto','Kyle / Buda / San Marcos','Dripping Springs / Bee Cave','Lakeway / Lago Vista','Taylor (Samsung Fab)','Bastrop / Elgin','Manor / Del Valle (Tesla Giga)']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
