"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTSanDiego() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="California" cityName="San Diego" headline="Testosterone Replacement Therapy in <span style='color: #2ECC71'>San Diego</span>" subheadline="San Diego is the Navy's West Coast home — Naval Base San Diego, Naval Air Station North Island, Marine Corps Base Camp Pendleton, and the SEAL teams at Coronado. The defense contractors in Sorrento Valley and the biotech firms in Torrey Pines add a tech-military ecosystem where high-performing men push their bodies and minds until the hormones give out." dataPoint1="San Diego County's military population exceeds 100,000 active duty personnel — the largest concentration of military in the world. Add 240,000+ veterans and 50,000+ defense contractor employees, and the demand for men's health services vastly exceeds the specialist supply." dataPoint2="Telehealth FX delivers TRT from $79/mo — no base medical referral chain, no I-5 commute to UCSD Hillcrest." />
      <PatientArchetype archetype="The General Atomics MQ-9 Reaper Systems Engineer" quote="I'm a systems engineer at General Atomics — I design flight control software for the MQ-9 Reaper drone. I sit at a workstation in Poway 10-12 hours a day. I'm 40. I moved here from Northrop Grumman in El Segundo — same desk, different view. I used to surf Blacks Beach at dawn. Now I can barely get through my morning standup without yawning. My Kaiser PCP tested my T: 374. 'Normal.' I design autonomous flight systems for combat drones. My body runs on autopilot and it's crashing." details="<strong>Patient Profile:</strong> Kevin, 40, Senior Systems Engineer, General Atomics Aeronautical Systems, Poway. Lives in Carmel Valley (92130). Designs MQ-9 Reaper flight control systems. 15 years in defense aerospace. MS Aerospace Engineering, USC. Former competitive surfer.<br/><br/><strong>The Challenge:</strong> 10-12 hour desk days designing drone systems. Kaiser PCP tested Total T only: 374 ng/dL — 'normal.' Kaiser urology referral: internal system, 8-10 weeks. UCSD Hillcrest urology: 12 weeks. Scripps: 10 weeks. Commute from Poway/Carmel Valley to Hillcrest during business hours: 45-60 min on I-5/I-805.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Carmel Valley home at 9 PM. CA-licensed physician ordered full panel ($95). Total T 374, Free T 5.7 pg/mL, vitamin D 22 (suboptimal despite SD sunshine). Prescribed Testosterone Cypionate within 48 hours. Shipped to 92130." />
      <ClinicalDeepDive title="The Navy's West Coast and Silicon Beach Defense" paragraphs={["San Diego's military presence is unmatched: Naval Base San Diego (largest naval base on the West Coast), NAS North Island (carrier aviation), MCAS Miramar (Marine aviation — the original Top Gun), Camp Pendleton (1st Marine Division), and Naval Special Warfare (SEAL Teams 1, 3, 5, 7 at Coronado). The men who serve in these units represent the highest physical performance tier in the US military — and they face testosterone decline accelerated by deployment stress, physical training injuries, and the transition to staff/desk roles.","The defense contractor ecosystem in Sorrento Valley, Poway, and Rancho Bernardo — General Atomics, Northrop Grumman, BAE Systems, SAIC, Leidos — adds 50,000+ engineers and program managers in sedentary, high-cognitive roles. These men transitioned from operational military careers (many are veterans) to desk-based engineering careers. The activity level drops. The testosterone drops. The symptoms emerge.","San Diego's outdoor culture creates a paradox: the weather is perfect for physical activity year-round (70°F, 266 sunny days). But the men working 10-12 hour days in classified SCIFs and engineering bays don't have time to surf or hike. The Blacks Beach and Torrey Pines trails are theoretically 15 minutes away — and practically inaccessible during a 60-hour work week.","The biotech corridor (Torrey Pines / La Jolla — Illumina, Pfizer, Neurocrine, Halozyme) adds another high-education male workforce experiencing the same decline. Scientists who understand endocrine biology at the molecular level face the same outdated reference ranges and PCP dismissiveness as everyone else.","UCSD Health, Scripps Health, and Sharp HealthCare provide strong specialist care — but urology waits of 8-12 weeks, combined with the I-5/I-805 commute reality (Poway to Hillcrest: 45 min; Oceanside to La Jolla: 40 min), make a single appointment a half-day commitment. Kaiser's closed system adds its own internal delays.","TRT at $79/month serves San Diego's 100,000+ active duty personnel, 240,000+ veterans, 50,000+ defense contractor engineers, the biotech research workforce, and the broader metro — delivering optimized testosterone to the men who defend the Pacific and engineer the future."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Naval Medical Center San Diego. (2025). <em>Active Duty Men's Health and Specialist Referral Analysis.</em>","San Diego County HHSA. (2025). <em>Men's Health and Military Community Chronic Disease Report.</em>","UCSD Health. (2025). <em>Urology Department Non-Surgical Wait Time Analysis.</em>"]} />
      <InsuranceBreakdown title="Navy SEALs, General Atomics, and Kaiser's Closed Loop" text="San Diego's military-defense-biotech economy creates massive TRT demand against limited specialist supply." employers={[{name:"US Navy / USMC Active Duty (TRICARE)",detail:"100,000+ active duty. Naval Medical Center SD urology: 12-18 week referral chain."},{name:"General Atomics / Northrop / BAE (Defense BCBS)",detail:"Defense contractor plans with standard PCP → urology referral. 8-12 weeks."},{name:"Kaiser Permanente SD (Closed System)",detail:"Kaiser's internal referral: 8-10 weeks. No out-of-network options without self-pay."},{name:"Illumina / Pfizer / Neurocrine (Biotech Plans)",detail:"Biotech plans with Scripps/UCSD network. Standard referral chain."}]} />
      <CostComparisonTable title="What TRT Costs in San Diego" localCompetitors={[{name:"La Jolla / Del Mar Concierge Men's Health",cost:"$500-$1,000/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Sorrento Valley / UTC Men's Clinics",cost:"$300-$600/mo",consult:"Monthly",access:"Variable"},{name:"UCSD / Scripps / Sharp Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="Perfect Weather, Imperfect Access" transitText="San Diego's geography stretches 60+ miles from Oceanside to the border. Poway to UCSD Hillcrest: 45 min on I-15/163. Carlsbad to Scripps La Jolla: 30 min. Camp Pendleton to anywhere: 45-90 min depending on gate traffic." hospitalText="<strong>UCSD Health</strong> (Hillcrest/La Jolla), <strong>Scripps</strong> (multiple), <strong>Sharp</strong> (multiple), and <strong>Naval Medical Center SD</strong> — all 8-12+ week urology waits." />
      <InteractiveFAQ faqs={[{q:"I'm active duty Navy. Will this affect my career?",a:"Telehealth FX is a civilian provider. Nothing is reported to the Navy, TRICARE, or your command. HIPAA-compliant."},{q:"I have a security clearance. Is this confidential?",a:"Completely. Telehealth FX does not report to DoD, OPM, or any security clearance adjudication authority."},{q:"Do you deliver to Camp Pendleton, Coronado, and Poway?",a:"Yes. All San Diego County addresses including military installations (zip code delivery), North County, and South Bay."},{q:"Kaiser won't refer me to an outside urologist. Options?",a:"Telehealth FX is completely independent of Kaiser's closed system. No referral needed."},{q:"I used to surf at dawn. Will TRT help me get back out there?",a:"Most men report restored energy, motivation, and exercise capacity within 2-4 weeks. Getting back in the water is a common outcome."}]} />
      <StateLegalFramework stateName="California" boardName="Medical Board of California" text="Telehealth FX TRT operates in full compliance with the <strong>Medical Board of California</strong> and Cal. Bus. & Prof. Code § 2290.5. All prescribing physicians are California-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="San Diego" mapQuery="San Diego, CA" coordinates="32.7157° N, 117.1611° W" counties="San Diego County" neighborhoods={['La Jolla / UTC / Torrey Pines','Coronado / Imperial Beach','Poway / Rancho Bernardo','Carmel Valley / Del Mar','Carlsbad / Encinitas / Oceanside','Camp Pendleton / Fallbrook','Hillcrest / North Park / Mission Hills','Pacific Beach / Mission Beach','Chula Vista / Eastlake','El Cajon / Santee / Lakeside','Escondido / San Marcos','Point Loma / Ocean Beach','Scripps Ranch / Mira Mesa']} />
      <FinalCTA stateName="California" />
    </div>
  );
}
