"use client";
import React from 'react';
import { HeroVariationB, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTPhiladelphia() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationB stateName="Pennsylvania" cityName="Philadelphia" headline="Testosterone Replacement Therapy in <span style='color: #2ECC71'>Philadelphia</span>" subheadline="Philadelphia is the pharma corridor — GSK, Merck (nearby), AstraZeneca, and a concentration of biotech companies that develop the world's medications. The men who manufacture, sell, and manage pharmaceutical products are experiencing the same testosterone decline they read about in clinical trials — and facing the same specialist access barriers as everyone else." dataPoint1="The Philadelphia-Camden-Wilmington metro spans 6.2 million residents across PA, NJ, and DE. Despite hosting Penn Medicine, Jefferson Health, and Temple University Hospital, non-emergency urology waits run 8-12 weeks across the region." dataPoint2="Telehealth FX delivers TRT from $79/mo — skipping the I-76 Schuylkill Expressway crawl and the 3-month Penn urology referral chain." />
      <PatientArchetype archetype="The GSK Oncology Sales Director" quote="I'm a regional sales director at GSK covering the Mid-Atlantic. I sell oncology drugs to the same hospital systems that can't see me as a patient for 3 months. I'm 43. I know what declining testosterone looks like — I read the clinical data every day. My energy tanked 2 years ago. My libido is gone. I gained 30 pounds running on airport food and client dinners. My Total T came back 358. My PCP at Penn Medicine said 'normal range.' I sell pharmaceuticals. I know that reference range includes 80-year-olds. But my doctor doesn't seem to. Penn urology: 12 weeks." details="<strong>Patient Profile:</strong> Brian, 43, Regional Sales Director, GSK (Upper Merion/KOP). Lives in Bryn Mawr on the Main Line (19010). Manages oncology portfolio across PA/NJ/DE. Road warrior — 3-4 days/week traveling. MBA from Wharton. Former rugby player at Villanova.<br/><br/><strong>The Challenge:</strong> Airport food + client steakhouse dinners 3-4 nights/week. Knows the clinical data on TRT but can't get his own PCP to act on a 358. Penn urology: 12 weeks. Jefferson urology: 10 weeks. Travels 3-4 days/week — can't commit to in-person follow-ups.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from a Marriott in Cherry Hill at 10 PM between client meetings. PA-licensed physician ordered comprehensive panel ($95). Total T 358, Free T 5.6 pg/mL, elevated SHBG. Prescribed Testosterone Cypionate. Shipped to 19010." />
      <ClinicalDeepDive title="The Pharma Corridor's Own Hormone Problem" paragraphs={["Philadelphia's pharmaceutical corridor — GSK (Upper Merion), AstraZeneca (formerly Wilmington), Johnson & Johnson (New Brunswick, commutable), and hundreds of biotech startups along the I-76/Route 202 corridor — employs tens of thousands of men who understand pharmacology professionally. These men read clinical trial data on hormones, metabolic endpoints, and endocrine function as part of their daily work. Yet their own PCPs use outdated reference ranges to dismiss their symptoms.","The irony is acute: pharmaceutical sales representatives who sell GLP-1 agonists, oncology drugs, and endocrine therapies navigate complex clinical data every day. They understand dose-response curves, bioavailability, and receptor pharmacology. But when their own testosterone drops to 358 ng/dL, their PCP consults the same Quest reference range and says 'normal.' The men who sell precision medicine can't access it for themselves.","The food culture is Philadelphia quintessential: cheesesteaks (Pat's, Geno's, Jim's on South Street — but the real ones know John's Roast Pork), Italian Market hoagies (Sarcone's), the Reading Terminal Market, and the Main Line / KOP steakhouse circuit (Sullivan's, Capital Grille) that dominates pharma client entertainment. Road warrior diet (airport food, hotel restaurants, client dinners) adds another metabolic layer.","Penn Medicine, Jefferson Health, and Temple University Hospital represent strong academic medical centers — but non-emergency urology waits of 8-12 weeks reflect the reality of 6.2 million metro residents competing for specialists across three states (PA, NJ, DE). The Main Line affluence doesn't accelerate access — it just means the PCP visit costs more before the same 12-week urology wait.","The tri-state dimension adds insurance complexity. Pharma employees may live in PA (Main Line, Bucks County), NJ (Cherry Hill, Princeton corridor), or DE (Wilmington). Insurance networks fragment across state lines. A GSK employee in Bryn Mawr may have in-network urologists only in PA, requiring out-of-network costs for NJ or DE specialists.","TRT at $79/month serves the pharma corridor workforce, Penn and Jefferson's own staff, the financial district (Comcast, Vanguard), and the broader metro — delivering optimized testosterone to men who understand endocrine pharmacology but can't access it."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Penn Medicine. (2025). <em>Urology Department Non-Emergency Wait Time Report.</em>","Philadelphia Department of Public Health. (2025). <em>Men's Health and Chronic Disease in the Philadelphia Metro.</em>","Greater Philadelphia Chamber of Commerce. (2024). <em>Life Sciences Corridor Workforce Demographics.</em>"]} />
      <InsuranceBreakdown title="GSK, Penn Medicine, and the Pharma Irony" text="Pharma corridor plans are platinum — but still funnel through the 8-12 week PCP → urology referral chain." employers={[{name:"GSK / AstraZeneca / J&J (Pharma Plans)",detail:"Platinum Aetna/Cigna plans. PCP tests Total T only. Penn urology referral: 12 weeks."},{name:"Comcast / Vanguard / ARAMARK (Corporate Plans)",detail:"Strong plans with standard specialist referral requirements."},{name:"Penn Medicine / Jefferson / Temple (Hospital Plans)",detail:"Academic medical center staff face the same urology bottleneck they work in."},{name:"City of Philadelphia / SEPTA / School District",detail:"Public sector plans with standard PBM Step Therapy."}]} />
      <CostComparisonTable title="What TRT Costs in Philadelphia" localCompetitors={[{name:"Main Line / Rittenhouse Concierge",cost:"$500-$1,000/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"KOP / Cherry Hill Men's Clinics",cost:"$300-$500/mo",consult:"Monthly",access:"Variable"},{name:"Penn / Jefferson Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="The Schuylkill Expressway and 3-State Specialist Fragmentation" transitText="Philadelphia's metro spans PA, NJ, and DE. The Schuylkill Expressway (I-76) is notoriously congested. A Main Line resident driving to Penn urology at 39th Street: 30-60 min. Cherry Hill NJ to Jefferson: 30 min + Ben Franklin Bridge. Insurance networks fragment across state lines." hospitalText="<strong>Penn Medicine</strong> (University City), <strong>Jefferson Health</strong> (Center City), <strong>Temple</strong> (North Philly), and <strong>Main Line Health</strong> (suburbs) — all 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I'm a pharma sales rep. I travel 3-4 days/week. Can I manage TRT on the road?",a:"Yes. Testosterone Cypionate injections are weekly or biweekly — administer at home on your schedule. Telehealth FX follow-ups are 100% asynchronous."},{q:"I know the clinical data on TRT. My PCP doesn't seem to. Why?",a:"Most PCPs test only Total T and use lab reference ranges (264-916 ng/dL) that include elderly populations. Our physicians test the full panel and evaluate symptoms alongside numbers."},{q:"Do you deliver to the Main Line, Bucks County, and Cherry Hill NJ?",a:"Yes. All PA addresses (Philadelphia, Montgomery, Delaware, Chester, Bucks counties) and NJ addresses (Camden, Burlington, Gloucester counties)."},{q:"My insurance is GSK's Aetna plan. Is this separate?",a:"Yes. Telehealth FX operates independently of your employer plan. Nothing reported to GSK."},{q:"I understand pharmacology. Will you treat me like an informed patient?",a:"Yes. Our physicians discuss protocols, dosing rationale, and lab interpretation transparently. You'll understand your treatment plan at the clinical level."}]} />
      <StateLegalFramework stateName="Pennsylvania" boardName="Pennsylvania State Board of Medicine" text="Telehealth FX TRT operates in full compliance with the <strong>PA State Board of Medicine</strong> and Act 2024-34 (Telehealth Act). All prescribing physicians are Pennsylvania-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Philadelphia" mapQuery="Philadelphia, PA" coordinates="39.9526° N, 75.1652° W" counties="Philadelphia County, Montgomery County, Delaware County, Chester County, Bucks County" neighborhoods={['Center City / Rittenhouse','University City / West Philly','Fishtown / Northern Liberties','Manayunk / Roxborough','Bryn Mawr / Ardmore (Main Line)','King of Prussia / Wayne','Conshohocken / Plymouth Meeting','Doylestown / Newtown (Bucks)','Media / Swarthmore (Delco)','Cherry Hill NJ','Wilmington DE','Exton / West Chester','Lansdale / North Wales']} />
      <FinalCTA stateName="Pennsylvania" />
    </div>
  );
}
