"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTCharlotte() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="North Carolina" cityName="Charlotte" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>Charlotte</span>" subheadline="Charlotte is America's second-largest banking center — Bank of America, Wells Fargo, and Truist are headquartered here. The men who manage trillions in assets work 60-hour weeks in Uptown towers, eat at Sullivan's Steakhouse on Tryon Street, and experience testosterone decline that their concierge PCPs dismiss as 'normal aging.' The Queen City's banking culture selects for performance and punishes weakness — including the weakness of seeking medical help." ctaText="Check North Carolina TRT Eligibility" />
      <PatientArchetype archetype="The Bank of America SVP of Risk" quote="I'm an SVP in enterprise risk at Bank of America — I manage regulatory capital models across the consumer banking division. I sit in meetings from 7 AM to 6 PM in the BofA tower, then work from my SouthPark home until midnight during Fed stress test season. I'm 45. I played lacrosse at Duke. Now I can't finish a round of golf at Quail Hollow without exhaustion. My T was 348 — my Atrium PCP said 'normal for your age.' I model systemic risk for a $3 trillion bank. My own systemic risk is unmanaged." details="<strong>Patient Profile:</strong> Tom, 45, SVP Enterprise Risk, Bank of America, Charlotte HQ. Lives in SouthPark (28211). Models regulatory capital for $3T in assets. Works 70+ hours during Fed stress test cycles. Duke lacrosse, MBA from Fuqua.<br/><br/><strong>The Challenge:</strong> 70-hour desk weeks during stress test season. Sullivan's and Del Frisco's client dinners. Atrium Health PCP tested Total T only: 348 ng/dL — 'normal for 45.' Atrium urology: 10 weeks. Novant urology: 8 weeks. Banking culture doesn't accommodate half-day medical appointments.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from SouthPark home at 11 PM during stress test season. NC-licensed physician ordered full panel ($95). Total T 348, Free T 5.1 pg/mL, elevated SHBG. Prescribed Testosterone Cypionate within 48 hours. Shipped to 28211." />
      <ClinicalDeepDive title="The Banking Capital's Hormonal Balance Sheet" paragraphs={["Charlotte is the nation's second-largest banking center by assets under management — behind only New York. Bank of America ($3.2 trillion), Wells Fargo's East Coast operations, Truist Financial (formed from the BB&T/SunTrust merger), and Ally Financial create a concentrated financial workforce in Uptown Charlotte. These men manage trillions in assets while their own hormonal assets depreciate at 1-2% per year.","The banking culture parallel is direct: testosterone is a depreciating asset on a biological balance sheet. Without intervention, total testosterone declines 1-2% annually after age 30. By 45, a man has lost 15-30% of his peak production. The banking SVP who would never tolerate a 20% depreciation in his portfolio accepts the same depreciation in his testosterone without question — because his PCP calls it 'normal.'","The food culture is Charlotte banking meets Southern hospitality: Sullivan's Steakhouse (Uptown power lunch and client dinner institution), Del Frisco's (SouthPark), Steak 48 (South End), and the South End/NoDa brewery scene (Wooden Robot, Olde Mecklenburg). Charlotte's dining culture revolves around client entertainment — steakhouses and bourbon are professional requirements, not personal choices.","Atrium Health (now Advocate Health) and Novant Health dominate Charlotte's hospital landscape — both strong health systems. But urology waits of 8-12 weeks reflect the reality of a metro that's grown from 1.8 million to 2.7 million in 15 years. The banking relocations that made Charlotte the #2 financial center brought 900,000 new residents without proportional specialist capacity growth.","The NASCAR dimension adds another workforce: Charlotte Motor Speedway, the team shops in Mooresville and Concord, and the engineering/fabrication workforce building 200-mph stock cars. These mechanics and engineers understand engine performance optimization — applying the same logic to their own biological engines is the conceptual bridge.","TRT at $79/month serves Charlotte's banking executives, the Truist/Wells Fargo/Ally workforce, the NASCAR engineering community, and the broader Mecklenburg County metro — delivering optimized testosterone to the men who manage America's banking system from the Queen City."]} citations={["Travison, T.G., et al. (2007). <em>A Population-Level Decline in Serum Testosterone Levels in American Men.</em> JCEM.","Atrium Health. (2025). <em>Urology Department Non-Emergency Wait Time Analysis.</em>","Mecklenburg County Health Department. (2025). <em>Men's Health and Financial Sector Workforce Chronic Disease Report.</em>","Charlotte Regional Business Alliance. (2024). <em>Banking Corridor Growth and Healthcare Infrastructure Gap Analysis.</em>"]} />
      <InsuranceBreakdown title="BofA, Truist, and the $3 Trillion Balance Sheet" text="Charlotte's banking plans are platinum — but the same 8-12 week urology referral applies." employers={[{name:"Bank of America (Corporate BCBS)",detail:"HQ workforce. Atrium Health network. PCP tests Total T only. Urology: 10 weeks."},{name:"Wells Fargo / Truist / Ally (Banking Plans)",detail:"East Coast banking operations. Same Atrium/Novant specialist bottleneck."},{name:"Lowe's / Honeywell / Duke Energy (Corporate)",detail:"Corporate relocations to Charlotte area. Standard PCP referral chain."},{name:"Atrium Health / Novant Health (Hospital Staff)",detail:"Healthcare workers face the same urology queue."}]} />
      <CostComparisonTable title="What TRT Costs in Charlotte" localCompetitors={[{name:"SouthPark / Myers Park Concierge",cost:"$500-$900/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"South End / Uptown Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"Atrium / Novant Urology",cost:"$120 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"},{name:"Online TRT Competitors",cost:"$150-$300/mo",consult:"Virtual",access:"Subscription"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="The Fastest-Growing Banking City, Same Urology Waits" transitText="Charlotte spans Mecklenburg County and into Union, Cabarrus, and Iredell counties. Lake Norman to Uptown: 35 min. Ballantyne to NoDa: 30 min. Mooresville to Atrium Main: 40 min on I-77." hospitalText="<strong>Atrium Health</strong> (Main/Mercy/Pineville), <strong>Novant</strong> (Presbyterian/Huntersville) — both 8-12 week urology waits." />
      <InteractiveFAQ faqs={[{q:"I'm in banking. Discretion is critical.",a:"Completely discreet. Telehealth FX does not report to Bank of America, your insurance, or anyone. HIPAA-compliant. Plain packaging."},{q:"My T is 348. The reference range says 264-916. Am I really low?",a:"At 45, your age-25 baseline was likely 700-900+. 348 is ~40% of peak. Our physicians evaluate symptoms + comprehensive labs, not just the reference range."},{q:"Do you deliver to SouthPark, Lake Norman, and Ballantyne?",a:"Yes. All Mecklenburg, Union, Cabarrus, Iredell, and Gaston County addresses."},{q:"Stress test season is 70-hour weeks. When can I do this?",a:"Complete at 11 PM from home. Asynchronous — no appointments to schedule around regulatory deadlines."},{q:"Is online TRT legal in North Carolina?",a:"Yes. Per NCGS § 90-21.19A, licensed physicians may prescribe via telehealth after proper evaluation and lab review."}]} />
      <StateLegalFramework stateName="North Carolina" boardName="North Carolina Medical Board" text="Telehealth FX TRT operates in full compliance with the <strong>North Carolina Medical Board</strong> and NCGS § 90-21.19A (Telehealth). All prescribing physicians are NC-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="Charlotte" mapQuery="Charlotte, NC" coordinates="35.2271° N, 80.8431° W" counties="Mecklenburg County, Union County, Cabarrus County, Iredell County, Gaston County" neighborhoods={['Uptown / South End / NoDa','SouthPark / Myers Park / Dilworth','Ballantyne / Pineville','Lake Norman / Cornelius / Davidson','Huntersville / Northlake','Matthews / Mint Hill / Indian Trail','Mooresville / Statesville','Concord / Kannapolis','Fort Mill SC / Rock Hill SC','Gastonia / Belmont','Waxhaw / Marvin','University City / Harrisburg','Monroe / Wingate']} />
      <FinalCTA stateName="North Carolina" />
    </div>
  );
}
