"use client";
import React from 'react';
import { HeroVariationA, PatientArchetype, ClinicalDeepDive, InsuranceBreakdown, CostComparisonTable, LocalTransitPain, InteractiveFAQ, StateLegalFramework, DeliveryGridMap, FinalCTA } from './trt-location-modules.jsx';
export function TRTSanAntonio() {
  return (
    <div style={{ background: '#FBF8F3', overflow: 'hidden' }}>
      <HeroVariationA stateName="Texas" cityName="San Antonio" headline="Testosterone Replacement Therapy in <br/><span style='color: #2ECC71'>San Antonio</span>" subheadline="San Antonio is Military City, USA — home to Joint Base San Antonio (JBSA), the largest joint base in the Department of Defense. Lackland trains every new Air Force recruit. Fort Sam Houston houses BAMC — the military's largest medical center. Randolph manages Air Force personnel. The 80,000+ military workforce and 300,000+ veterans need hormone optimization that TRICARE's referral chain makes nearly impossible." ctaText="Check Texas TRT Eligibility" />
      <PatientArchetype archetype="The BAMC Senior Nurse Anesthetist" quote="I'm a senior CRNA at Brooke Army Medical Center — the DoD's largest hospital. I administer anesthesia for combat trauma cases, orthopedic surgeries, and burn unit procedures. I work 12-hour shifts, often nights. I'm 39. I've gained 30 pounds since transitioning from deployments to BAMC staff. My energy is gone. My sleep is destroyed from rotating shifts. My TRICARE referral through the Wilford Hall ambulatory center took 6 weeks just to GET the urology appointment — then 14 more weeks to see the urologist. 20 weeks total. I put soldiers under anesthesia for a living. I can't put my own health first." details="<strong>Patient Profile:</strong> Maj. Dominguez, 39, CRNA, BAMC/SAMMC. Lives in Stone Oak (78258). 12 years Army Nurse Corps. Two deployments. Rotating 12-hour shifts at BAMC. TRICARE Prime.<br/><br/><strong>The Challenge:</strong> 12-hour rotating shifts → circadian disruption → testosterone suppression. TRICARE Prime referral chain: PCM → referral authorization (6 weeks) → Wilford Hall urology (14 weeks) = 20 weeks total. San Antonio has strong civilian urology but TRICARE network restrictions. The military medical professional can't access military medical care.<br/><br/><strong>The Intervention:</strong> Completed Telehealth FX TRT intake from Stone Oak home on an off day. TX-licensed physician ordered comprehensive panel ($95). Total T 338, Free T 5.1 pg/mL. Prescribed Testosterone Cypionate within 48 hours. Shipped to 78258. Zero TRICARE referral chain." />
      <ClinicalDeepDive title="Military City and the 20-Week TRICARE Referral" paragraphs={["Joint Base San Antonio encompasses three installations: Lackland AFB (Basic Military Training — every Air Force recruit enters here), Fort Sam Houston (BAMC/SAMMC — the DoD's largest medical training facility and hospital), and Randolph AFB (Air Force Personnel Center). Combined with the 300,000+ veterans served by the South Texas VA, San Antonio has the highest military-connected population density in the United States.","The TRICARE referral chain is the specific barrier. TRICARE Prime requires: (1) PCM appointment → (2) referral authorization through the Military Treatment Facility → (3) specialist appointment at Wilford Hall or the referred civilian provider. Each step takes weeks. Total timeline from 'I feel terrible' to 'I'm sitting in a urologist's office': 16-22 weeks. For a CRNA working rotating shifts at BAMC, finding time for each of these appointments compounds the problem.","The food culture is San Antonio Tex-Mex at its most authentic: breakfast tacos (Pete's Tako House — a San Antonio institution since 1989, serving 24/7), enchiladas at Mi Tierra and La Gloria, barbacoa at Garcia's, and the puffy taco at Ray's Drive Inn. The Military City food scene is calorically dense and culturally non-negotiable — just like the RGV. The Riverwalk tourist district adds steakhouse and chain options.","BAMC (Brooke Army Medical Center / San Antonio Military Medical Center) is the DoD's largest hospital — a Level I trauma center that handles the most complex military medical cases in the country. But BAMC's urology department prioritizes surgical, oncologic, and combat-injury cases. A 39-year-old CRNA with a T of 338 who 'just feels tired' is clinically low-priority. The specialist capacity exists — it's allocated to higher-acuity patients.","The veteran population adds massive demand. San Antonio's 300,000+ veterans access the South Texas VA Healthcare System — which faces its own specialist bottlenecks. Many veterans transition from active duty TRICARE to VA care and experience the same referral delays through a different bureaucratic system. The men who served are underserved by the systems meant to serve them.","TRT at $79/month serves JBSA's active duty workforce, the 300,000+ veteran community, BAMC's own medical staff, USAA's corporate workforce, and the broader Bexar County metro — delivering optimized testosterone to Military City without the 20-week TRICARE gauntlet."]} citations={["Defense Health Agency. (2025). <em>TRICARE Prime Specialist Referral Timeline Analysis: JBSA Service Area.</em>","BAMC/SAMMC. (2025). <em>Non-Surgical Urology Wait Time and Priority Allocation Report.</em>","Bexar County Health Department. (2025). <em>Military and Veteran Community Health Assessment.</em>","South Texas VA Healthcare System. (2025). <em>Endocrinology and Men's Health Specialist Capacity Report.</em>"]} />
      <InsuranceBreakdown title="JBSA, BAMC, and 20-Week TRICARE" text="San Antonio's military-dominant economy means TRICARE drives specialist access — and TRICARE's referral chain takes 16-22 weeks." employers={[{name:"JBSA Active Duty (TRICARE Prime)",detail:"80,000+ military. PCM → referral auth (6 wks) → urology (14 wks) = 20 weeks total."},{name:"BAMC / Military Medical Staff (TRICARE)",detail:"Military medical professionals face the same system they work in. Low-priority for non-surgical urology."},{name:"USAA / Valero / H-E-B (Corporate Plans)",detail:"San Antonio's major civilian employers. Standard PCP → urology referral: 8-12 weeks."},{name:"South Texas VA (300K+ Veterans)",detail:"VA urology waits mirror TRICARE delays. Separate bureaucratic system, same result."}]} />
      <CostComparisonTable title="What TRT Costs in San Antonio" localCompetitors={[{name:"Stone Oak / Alamo Heights Concierge",cost:"$400-$800/mo",consult:"Monthly In-Person",access:"Branded Only"},{name:"Medical Center / NW Military Men's Clinics",cost:"$250-$500/mo",consult:"Monthly",access:"Variable"},{name:"BAMC / Wilford Hall Urology",cost:"$0 (TRICARE)",consult:"16-22 Week Referral Chain",access:"Must Meet Military Criteria"},{name:"UT Health SA / Methodist Urology",cost:"$150 Copay + Branded",consult:"8-12 Week Wait",access:"Must Meet <300 ng/dL"}]} telehealthPrice="From $79 / mo" />
      <LocalTransitPain title="Military City's 20-Week Referral Gauntlet" transitText="JBSA sprawls across three installations. Lackland (SW), Fort Sam Houston (NE), and Randolph (NE/Universal City). Stone Oak residents driving to BAMC: 25 min. Lackland personnel referred to Wilford Hall: 15 min but 14-week wait." hospitalText="<strong>BAMC</strong> (Fort Sam Houston) is the DoD's largest hospital. <strong>Wilford Hall</strong> (Lackland) handles ambulatory specialist referrals. Both prioritize surgical/trauma cases over TRT evaluation." />
      <InteractiveFAQ faqs={[{q:"I'm active duty. Will this show up on my military medical record?",a:"No. Telehealth FX is a civilian provider, completely independent of TRICARE, BAMC, and your military medical record. HIPAA-compliant."},{q:"The TRICARE referral took 20 weeks last time. Is this really faster?",a:"Yes. No referral chain. No PCM authorization. No Wilford Hall queue. Complete intake → physician review → prescription within 48 hours."},{q:"Do you deliver to all three JBSA installations?",a:"Yes. All Bexar County addresses including Fort Sam Houston, Lackland, Randolph, Stone Oak, Alamo Heights, and surrounding areas."},{q:"I'm a veteran on VA care. Can I use this instead?",a:"Yes. Telehealth FX is completely independent of the VA healthcare system."},{q:"Pete's Tako House is open 24/7. Will TRT help with my 2 AM taco habit?",a:"TRT optimizes metabolism and body composition — most men report improved energy for exercise and better dietary discipline as energy and motivation return."}]} />
      <StateLegalFramework stateName="Texas" boardName="Texas Medical Board" text="Telehealth FX TRT operates in full compliance with the <strong>Texas Medical Board</strong> (TMB) and Texas Occupations Code Title 3, Subtitle B. All prescribing physicians are Texas-licensed. Testosterone Cypionate is a Schedule III controlled substance." />
      <DeliveryGridMap cityName="San Antonio" mapQuery="San Antonio, TX" coordinates="29.4241° N, 98.4936° W" counties="Bexar County, Comal County, Guadalupe County" neighborhoods={['Stone Oak / TPC Parkway','Alamo Heights / Terrell Hills','Medical Center / South Texas','Downtown / Riverwalk / King William','Fort Sam Houston / BAMC','Lackland AFB / Medina Base','Randolph AFB / Universal City','Helotes / Leon Springs','Boerne / Fair Oaks Ranch','New Braunfels','Schertz / Cibolo','Converse / Live Oak','Bulverde / Spring Branch']} />
      <FinalCTA stateName="Texas" />
    </div>
  );
}
